In [4]:
#the import packages
import requests
import pandas as pd
from pandas import json_normalize
import requests
import os
from pathlib import Path
from datetime import datetime, timezone,timedelta

import json
import numpy as np

import seaborn as sns
import matplotlib.pyplot as plt

In [5]:
def loadDataFromFile(file_name):
    script_dir = Path().resolve().parent

    data_folder = script_dir / 'dataAnalysis and machine learning'/'data'
    print(data_folder)
    data_folder.mkdir(exist_ok=True)
    
    file_path = data_folder / (file_name + ".json")
    
    if file_path.exists():
        df = pd.read_json(file_path)
        print(f"Loaded {len(df)} records from {file_path}")
        return df
    else:
        print(f"File {file_path} does not exist.")
        return None

In [6]:
userInputDataRaw = loadDataFromFile("User:Calibration no source pollutant")
timeSeriesData = loadDataFromFile("Data:Calibration no source pollutant")

C:\Users\Andreas\Documents\PlatformIO\Projects\Diploma Project\dataAnalysis and machine learning\data
Loaded 63 records from C:\Users\Andreas\Documents\PlatformIO\Projects\Diploma Project\dataAnalysis and machine learning\data\User:Calibration no source pollutant.json
C:\Users\Andreas\Documents\PlatformIO\Projects\Diploma Project\dataAnalysis and machine learning\data
Loaded 135893 records from C:\Users\Andreas\Documents\PlatformIO\Projects\Diploma Project\dataAnalysis and machine learning\data\Data:Calibration no source pollutant.json

In [13]:
userInputDataRaw

,_id,experimentState,timestamp,userInputCategory,are-doors-opened,are-people-inside,are-windows-opened,front-wall,item-used,notes,pollutant-type,quantity-used,room,side-right-wall,back-wall,side-left-wall,are-fans-on,no-source-located,epoch_ms,timestamp_local
0,{'$oid': '68a0b932a1fbc302e14444b5'},StartingExperiment,{'$date': 1755363634147},ExperimentState,None,None,None,NaN,None,None,None,None,None,NaN,NaN,NaN,NaN,None,1755363634147,2025-08-16 17:00:34.147
1,{'$oid': '68a0b9d5a1fbc302e144468f'},NoSourcePollutantInserted,{'$date': 1755363797903},ExperimentState,on,on,on,NaN,Φαρμακευτικό αλκοόλ 95%,,VOC,30 ml,Σοφίτα-Όλοι οι αισθητήρες μαζί,NaN,NaN,NaN,NaN,on,1755363797903,2025-08-16 17:03:17.903
2,{'$oid': '688801042b6a61abefaee294'},RemovingSourcePollutant,{'$date': 1755377884000},ExperimentState,None,None,None,NaN,None,None,None,None,None,NaN,NaN,NaN,NaN,None,1755377884000,2025-08-16 20:58:04.000
3,{'$oid': '68a1e16fcf51922818e73582'},StartingExperiment,{'$date': 1755439471205},ExperimentState,None,None,None,NaN,None,None,None,None,None,NaN,NaN,NaN,NaN,None,1755439471205,2025-08-17 14:04:31.205
4,{'$oid': '68a1e40420b06e7dc691f360'},NoSourcePollutantInserted,{'$date': 1755440132473},ExperimentState,on,on,on,NaN,Φαρμακευτικό αλκοόλ 95%,,VOC,30 ml,Σοφίτα-Όλοι οι αισθητήρες μαζί,NaN,NaN,NaN,NaN,on,1755440132473,2025-08-17 14:15:32.473
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,{'$oid': '68adfc02ac4a03c9fe12c5d2'},InsertingSourcePollutant,{'$date': 1756232706584},ExperimentState,on,None,None,0.7,Φαρμακευτικό αλκοόλ 95%,,VOC,30 ml,"Κρεβατοκάμαρα-Όλοι οι αισθητήρες μαζί Μ:0.80 ,...",0.9,NaN,NaN,NaN,None,1756232706584,2025-08-26 18:25:06.584
59,{'$oid': '68adfdf0ac4a03c9fe12cc82'},RemovingSourcePollutant,{'$date': 1756233200196},ExperimentState,None,None,None,NaN,None,None,None,None,None,NaN,NaN,NaN,NaN,None,1756233200196,2025-08-26 18:33:20.196
60,{'$oid': '68ae0039ac4a03c9fe12d41e'},StartingExperiment,{'$date': 1756233785024},ExperimentState,None,None,None,NaN,None,None,None,None,None,NaN,NaN,NaN,NaN,None,1756233785024,2025-08-26 18:43:05.024
61,{'$oid': '68ae0111ac4a03c9fe12d71e'},InsertingSourcePollutant,{'$date': 1756234001710},ExperimentState,on,None,None,0.6,Φαρμακευτικό αλκοόλ 95%,,VOC,30 ml,"Κρεβατοκάμαρα-Όλοι οι αισθητήρες μαζί Μ:0.80 ,...",NaN,NaN,0.6,NaN,None,1756234001710,2025-08-26 18:46:41.710
62,{'$oid': '68ae0335ac4a03c9fe12de66'},RemovingSourcePollutant,{'$date': 1756234549347},ExperimentState,None,None,None,NaN,None,None,None,None,None,NaN,NaN,NaN,NaN,None,1756234549347,2025-08-26 18:55:49.347

In [14]:
timeSeriesData

,timestamp,Id=0:BME680:breathVocEquivalent,Id=1:BME680:breathVocEquivalent,Id=2:BME680:breathVocEquivalent
0,2025-08-16 17:00:36,1.094831,NaN,NaN
1,2025-08-16 17:00:37,NaN,NaN,1.884669
2,2025-08-16 17:00:39,1.095380,NaN,NaN
3,2025-08-16 17:00:40,NaN,NaN,1.980727
4,2025-08-16 17:00:42,1.114183,NaN,NaN
...,...,...,...,...
135888,2025-08-26 18:55:45,NaN,NaN,947.767300
135889,2025-08-26 18:55:46,29.332350,NaN,NaN
135890,2025-08-26 18:55:48,NaN,81.10573,NaN
135891,2025-08-26 18:55:48,NaN,NaN,513.575400
135892,2025-08-26 18:55:49,23.198300,NaN,NaN

In [15]:
timeSeriesData["timestamp"]

0        2025-08-16 17:00:36
1        2025-08-16 17:00:37
2        2025-08-16 17:00:39
3        2025-08-16 17:00:40
4        2025-08-16 17:00:42
                 ...
135888   2025-08-26 18:55:45
135889   2025-08-26 18:55:46
135890   2025-08-26 18:55:48
135891   2025-08-26 18:55:48
135892   2025-08-26 18:55:49
Name: timestamp, Length: 135893, dtype: datetime64[ns]

In [16]:
userInputData = userInputDataRaw.drop(columns=["_id","timestamp","epoch_ms","userInputCategory","pollutant-type","quantity-used"])

In [17]:
userInputData["timestamp_local"] = pd.to_datetime(userInputData["timestamp_local"])  # ensure datetime
userInputData["timestamp_local"] = userInputData["timestamp_local"].dt.floor("s")

In [18]:
userInputData

,experimentState,are-doors-opened,are-people-inside,are-windows-opened,front-wall,item-used,notes,room,side-right-wall,back-wall,side-left-wall,are-fans-on,no-source-located,timestamp_local
0,StartingExperiment,None,None,None,NaN,None,None,None,NaN,NaN,NaN,NaN,None,2025-08-16 17:00:34
1,NoSourcePollutantInserted,on,on,on,NaN,Φαρμακευτικό αλκοόλ 95%,,Σοφίτα-Όλοι οι αισθητήρες μαζί,NaN,NaN,NaN,NaN,on,2025-08-16 17:03:17
2,RemovingSourcePollutant,None,None,None,NaN,None,None,None,NaN,NaN,NaN,NaN,None,2025-08-16 20:58:04
3,StartingExperiment,None,None,None,NaN,None,None,None,NaN,NaN,NaN,NaN,None,2025-08-17 14:04:31
4,NoSourcePollutantInserted,on,on,on,NaN,Φαρμακευτικό αλκοόλ 95%,,Σοφίτα-Όλοι οι αισθητήρες μαζί,NaN,NaN,NaN,NaN,on,2025-08-17 14:15:32
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,InsertingSourcePollutant,on,None,None,0.7,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα-Όλοι οι αισθητήρες μαζί Μ:0.80 ,...",0.9,NaN,NaN,NaN,None,2025-08-26 18:25:06
59,RemovingSourcePollutant,None,None,None,NaN,None,None,None,NaN,NaN,NaN,NaN,None,2025-08-26 18:33:20
60,StartingExperiment,None,None,None,NaN,None,None,None,NaN,NaN,NaN,NaN,None,2025-08-26 18:43:05
61,InsertingSourcePollutant,on,None,None,0.6,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα-Όλοι οι αισθητήρες μαζί Μ:0.80 ,...",NaN,NaN,0.6,NaN,None,2025-08-26 18:46:41
62,RemovingSourcePollutant,None,None,None,NaN,None,None,None,NaN,NaN,NaN,NaN,None,2025-08-26 18:55:49

In [19]:
userInputDataCompressed = userInputData[userInputData["experimentState"].isin(["NoSourcePollutantInserted","InsertingSourcePollutant"])].copy()

In [20]:
userInputDataCompressed

,experimentState,are-doors-opened,are-people-inside,are-windows-opened,front-wall,item-used,notes,room,side-right-wall,back-wall,side-left-wall,are-fans-on,no-source-located,timestamp_local
1,NoSourcePollutantInserted,on,on,on,NaN,Φαρμακευτικό αλκοόλ 95%,,Σοφίτα-Όλοι οι αισθητήρες μαζί,NaN,NaN,NaN,NaN,on,2025-08-16 17:03:17
4,NoSourcePollutantInserted,on,on,on,NaN,Φαρμακευτικό αλκοόλ 95%,,Σοφίτα-Όλοι οι αισθητήρες μαζί,NaN,NaN,NaN,NaN,on,2025-08-17 14:15:32
7,InsertingSourcePollutant,None,on,None,1.0,Φαρμακευτικό αλκοόλ 95%,,Σοφίτα-Όλοι οι αισθητήρες μαζί,NaN,NaN,0.5,NaN,None,2025-08-17 22:01:35
10,InsertingSourcePollutant,on,on,None,1.0,Φαρμακευτικό αλκοόλ 95%,,Σοφίτα-Όλοι οι αισθητήρες μαζί,NaN,NaN,0.5,NaN,None,2025-08-17 22:58:58
13,NoSourcePollutantInserted,on,None,None,NaN,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα-Όλοι οι αισθητήρες μαζί,NaN,NaN,NaN,NaN,on,2025-08-23 14:49:05
16,InsertingSourcePollutant,on,None,None,1.0,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα-Όλοι οι αισθητήρες μαζί,NaN,NaN,1.0,NaN,None,2025-08-23 16:42:40
19,NoSourcePollutantInserted,on,None,None,NaN,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα-Όλοι οι αισθητήρες μαζί Μ:0.80 ,...",NaN,NaN,NaN,NaN,on,2025-08-24 12:23:06
22,InsertingSourcePollutant,on,None,None,0.8,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα-Όλοι οι αισθητήρες μαζί Μ:0.80 ,...",NaN,NaN,1.4,NaN,None,2025-08-24 13:33:13
25,InsertingSourcePollutant,on,None,None,0.8,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα-Όλοι οι αισθητήρες μαζί Μ:0.80 ,...",NaN,NaN,1.4,NaN,None,2025-08-24 13:37:49
28,InsertingSourcePollutant,on,None,None,0.8,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα-Όλοι οι αισθητήρες μαζί Μ:0.80 ,...",NaN,NaN,1.4,NaN,None,2025-08-24 14:23:02
31,NoSourcePollutantInserted,on,None,None,NaN,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα-Όλοι οι αισθητήρες μαζί Μ:0.80 ,...",NaN,NaN,NaN,NaN,on,2025-08-24 21:07:33
34,InsertingSourcePollutant,on,None,None,0.8,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα-Όλοι οι αισθητήρες μαζί Μ:0.80 ,...",NaN,NaN,1.4,NaN,None,2025-08-24 21:42:54
37,InsertingSourcePollutant,on,None,None,0.8,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα-Όλοι οι αισθητήρες μαζί Μ:0.80 ,...",NaN,NaN,1.4,NaN,None,2025-08-24 22:05:49
40,InsertingSourcePollutant,on,None,None,NaN,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα-Όλοι οι αισθητήρες μαζί Μ:0.80 ,...",NaN,0.6,0.6,NaN,None,2025-08-24 22:33:43
43,NoSourcePollutantInserted,on,None,None,NaN,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα-Όλοι οι αισθητήρες μαζί Μ:0.80 ,...",NaN,NaN,NaN,NaN,on,2025-08-26 11:13:02
46,InsertingSourcePollutant,on,None,None,0.8,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα-Όλοι οι αισθητήρες μαζί Μ:0.80 ,...",NaN,NaN,1.4,NaN,None,2025-08-26 11:56:26
49,InsertingSourcePollutant,on,None,None,NaN,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα-Όλοι οι αισθητήρες μαζί Μ:0.80 ,...",NaN,0.6,0.6,NaN,None,2025-08-26 13:09:30
52,InsertingSourcePollutant,on,None,None,NaN,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα-Όλοι οι αισθητήρες μαζί Μ:0.80 ,...",1.0,0.8,NaN,NaN,None,2025-08-26 13:42:02
55,InsertingSourcePollutant,on,None,None,NaN,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα-Όλοι οι αισθητήρες μαζί Μ:0.80 ,...",NaN,1.8,1.0,NaN,None,2025-08-26 16:49:11
58,InsertingSourcePollutant,on,None,None,0.7,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα-Όλοι οι αισθητήρες μαζί Μ:0.80 ,...",0.9,NaN,NaN,NaN,None,2025-08-26 18:25:06
61,InsertingSourcePollutant,on,None,None,0.6,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα-Όλοι οι αισθητήρες μαζί Μ:0.80 ,...",NaN,NaN,0.6,NaN,None,2025-08-26 18:46:41

In [21]:
userInputDataCompressed.index

Index([1, 4, 7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55,
       58, 61],
      dtype='int64')

In [22]:
userInputData

,experimentState,are-doors-opened,are-people-inside,are-windows-opened,front-wall,item-used,notes,room,side-right-wall,back-wall,side-left-wall,are-fans-on,no-source-located,timestamp_local
0,StartingExperiment,None,None,None,NaN,None,None,None,NaN,NaN,NaN,NaN,None,2025-08-16 17:00:34
1,NoSourcePollutantInserted,on,on,on,NaN,Φαρμακευτικό αλκοόλ 95%,,Σοφίτα-Όλοι οι αισθητήρες μαζί,NaN,NaN,NaN,NaN,on,2025-08-16 17:03:17
2,RemovingSourcePollutant,None,None,None,NaN,None,None,None,NaN,NaN,NaN,NaN,None,2025-08-16 20:58:04
3,StartingExperiment,None,None,None,NaN,None,None,None,NaN,NaN,NaN,NaN,None,2025-08-17 14:04:31
4,NoSourcePollutantInserted,on,on,on,NaN,Φαρμακευτικό αλκοόλ 95%,,Σοφίτα-Όλοι οι αισθητήρες μαζί,NaN,NaN,NaN,NaN,on,2025-08-17 14:15:32
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,InsertingSourcePollutant,on,None,None,0.7,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα-Όλοι οι αισθητήρες μαζί Μ:0.80 ,...",0.9,NaN,NaN,NaN,None,2025-08-26 18:25:06
59,RemovingSourcePollutant,None,None,None,NaN,None,None,None,NaN,NaN,NaN,NaN,None,2025-08-26 18:33:20
60,StartingExperiment,None,None,None,NaN,None,None,None,NaN,NaN,NaN,NaN,None,2025-08-26 18:43:05
61,InsertingSourcePollutant,on,None,None,0.6,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα-Όλοι οι αισθητήρες μαζί Μ:0.80 ,...",NaN,NaN,0.6,NaN,None,2025-08-26 18:46:41
62,RemovingSourcePollutant,None,None,None,NaN,None,None,None,NaN,NaN,NaN,NaN,None,2025-08-26 18:55:49

In [23]:
userInputDataCompressed["timestamp_StartingExperiment"] = userInputData["timestamp_local"].shift(1).loc[userInputDataCompressed.index]

In [24]:
userInputDataCompressed["timestamp_EndingExperiment"]= userInputData["timestamp_local"].shift(-1).loc[userInputDataCompressed.index]

In [31]:
userInputDataCompressed.reset_index()

,index,experimentState,are-doors-opened,are-people-inside,are-windows-opened,front-wall,item-used,notes,room,side-right-wall,back-wall,side-left-wall,are-fans-on,no-source-located,timestamp_local,timestamp_StartingExperiment,timestamp_EndingExperiment
0,1,NoSourcePollutantInserted,on,on,on,NaN,Φαρμακευτικό αλκοόλ 95%,,Σοφίτα-Όλοι οι αισθητήρες μαζί,NaN,NaN,NaN,NaN,on,2025-08-16 17:03:17,2025-08-16 17:00:34,2025-08-16 20:58:04
1,4,NoSourcePollutantInserted,on,on,on,NaN,Φαρμακευτικό αλκοόλ 95%,,Σοφίτα-Όλοι οι αισθητήρες μαζί,NaN,NaN,NaN,NaN,on,2025-08-17 14:15:32,2025-08-17 14:04:31,2025-08-17 15:12:35
2,7,InsertingSourcePollutant,None,on,None,1.0,Φαρμακευτικό αλκοόλ 95%,,Σοφίτα-Όλοι οι αισθητήρες μαζί,NaN,NaN,0.5,NaN,None,2025-08-17 22:01:35,2025-08-17 21:59:03,2025-08-17 22:32:34
3,10,InsertingSourcePollutant,on,on,None,1.0,Φαρμακευτικό αλκοόλ 95%,,Σοφίτα-Όλοι οι αισθητήρες μαζί,NaN,NaN,0.5,NaN,None,2025-08-17 22:58:58,2025-08-17 22:53:48,2025-08-17 23:24:58
4,13,NoSourcePollutantInserted,on,None,None,NaN,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα-Όλοι οι αισθητήρες μαζί,NaN,NaN,NaN,NaN,on,2025-08-23 14:49:05,2025-08-23 14:47:04,2025-08-23 15:43:08
5,16,InsertingSourcePollutant,on,None,None,1.0,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα-Όλοι οι αισθητήρες μαζί,NaN,NaN,1.0,NaN,None,2025-08-23 16:42:40,2025-08-23 16:39:57,2025-08-23 17:25:43
6,19,NoSourcePollutantInserted,on,None,None,NaN,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα-Όλοι οι αισθητήρες μαζί Μ:0.80 ,...",NaN,NaN,NaN,NaN,on,2025-08-24 12:23:06,2025-08-24 12:16:25,2025-08-24 13:22:07
7,22,InsertingSourcePollutant,on,None,None,0.8,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα-Όλοι οι αισθητήρες μαζί Μ:0.80 ,...",NaN,NaN,1.4,NaN,None,2025-08-24 13:33:13,2025-08-24 13:23:53,2025-08-24 13:35:04
8,25,InsertingSourcePollutant,on,None,None,0.8,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα-Όλοι οι αισθητήρες μαζί Μ:0.80 ,...",NaN,NaN,1.4,NaN,None,2025-08-24 13:37:49,2025-08-24 13:35:06,2025-08-24 14:03:11
9,28,InsertingSourcePollutant,on,None,None,0.8,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα-Όλοι οι αισθητήρες μαζί Μ:0.80 ,...",NaN,NaN,1.4,NaN,None,2025-08-24 14:23:02,2025-08-24 14:18:44,2025-08-24 14:34:08
10,31,NoSourcePollutantInserted,on,None,None,NaN,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα-Όλοι οι αισθητήρες μαζί Μ:0.80 ,...",NaN,NaN,NaN,NaN,on,2025-08-24 21:07:33,2025-08-24 21:07:22,2025-08-24 21:38:20
11,34,InsertingSourcePollutant,on,None,None,0.8,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα-Όλοι οι αισθητήρες μαζί Μ:0.80 ,...",NaN,NaN,1.4,NaN,None,2025-08-24 21:42:54,2025-08-24 21:39:21,2025-08-24 21:58:17
12,37,InsertingSourcePollutant,on,None,None,0.8,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα-Όλοι οι αισθητήρες μαζί Μ:0.80 ,...",NaN,NaN,1.4,NaN,None,2025-08-24 22:05:49,2025-08-24 22:02:36,2025-08-24 22:19:05
13,40,InsertingSourcePollutant,on,None,None,NaN,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα-Όλοι οι αισθητήρες μαζί Μ:0.80 ,...",NaN,0.6,0.6,NaN,None,2025-08-24 22:33:43,2025-08-24 22:23:47,2025-08-24 22:44:05
14,43,NoSourcePollutantInserted,on,None,None,NaN,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα-Όλοι οι αισθητήρες μαζί Μ:0.80 ,...",NaN,NaN,NaN,NaN,on,2025-08-26 11:13:02,2025-08-26 11:12:35,2025-08-26 11:44:22
15,46,InsertingSourcePollutant,on,None,None,0.8,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα-Όλοι οι αισθητήρες μαζί Μ:0.80 ,...",NaN,NaN,1.4,NaN,None,2025-08-26 11:56:26,2025-08-26 11:53:03,2025-08-26 12:44:09
16,49,InsertingSourcePollutant,on,None,None,NaN,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα-Όλοι οι αισθητήρες μαζί Μ:0.80 ,...",NaN,0.6,0.6,NaN,None,2025-08-26 13:09:30,2025-08-26 13:02:26,2025-08-26 13:23:48
17,52,InsertingSourcePollutant,on,None,None,NaN,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα-Όλοι οι αισθητήρες μαζί Μ:0.80 ,...",1.0,0.8,NaN,NaN,None,2025-08-26 13:42:02,2025-08-26 13:36:44,2025-08-26 13:53:04
18,55,InsertingSourcePollutant,on,None,None,NaN,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα-Όλοι οι αισθητήρες μαζί Μ:0.80 ,...",NaN,1.8,1.0,NaN,None,2025-08-26 16:49:11,2025-08-26 16:29:39,2025-08-26 17:11:16
19,58,InsertingSourcePollutant,on,None,None,0.7,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα-Όλοι οι αισθητήρες μαζί Μ:0.80 ,...",0.9,NaN,NaN,NaN,None,2025-08-26 18:25:06,2025-08-26 17:56:27,2025-08-26 18:33:20
20,61,InsertingSourcePollutant,on,None,None,0.6,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα-Όλοι οι αισθητήρες μαζί Μ:0.80 ,...",NaN,NaN,0.6,NaN,None,2025-08-26 18:46:41,2025-08-26 18:43:05,2025-08-26 18:55:49

In [26]:
start =userInputDataCompressed["timestamp_local"].iloc[0]
end=userInputDataCompressed["timestamp_EndingExperiment"].iloc[0]
timestamp = pd.date_range(start=start, end=end, freq="s",name="timestamp")

justTimestamp = pd.DataFrame(timestamp)
justTimestamp["Id=0:BME680:breathVocEquivalent"]  = np.nan
justTimestamp["Id=1:BME680:breathVocEquivalent"]  = np.nan
justTimestamp["Id=2:BME680:breathVocEquivalent"]  = np.nan

justTimestamp

,timestamp,Id=0:BME680:breathVocEquivalent,Id=1:BME680:breathVocEquivalent,Id=2:BME680:breathVocEquivalent
0,2025-08-16 17:03:17,NaN,NaN,NaN
1,2025-08-16 17:03:18,NaN,NaN,NaN
2,2025-08-16 17:03:19,NaN,NaN,NaN
3,2025-08-16 17:03:20,NaN,NaN,NaN
4,2025-08-16 17:03:21,NaN,NaN,NaN
...,...,...,...,...
14083,2025-08-16 20:58:00,NaN,NaN,NaN
14084,2025-08-16 20:58:01,NaN,NaN,NaN
14085,2025-08-16 20:58:02,NaN,NaN,NaN
14086,2025-08-16 20:58:03,NaN,NaN,NaN
14087,2025-08-16 20:58:04,NaN,NaN,NaN

In [27]:
timeSeriesDataToGet = timeSeriesData[(timeSeriesData["timestamp"] >= start) & (timeSeriesData["timestamp"] <= end)]
timeSeriesDataToGet

,timestamp,Id=0:BME680:breathVocEquivalent,Id=1:BME680:breathVocEquivalent,Id=2:BME680:breathVocEquivalent
164,2025-08-16 17:03:18,NaN,1.244104,NaN
165,2025-08-16 17:03:18,1.121423,NaN,NaN
166,2025-08-16 17:03:19,NaN,NaN,1.115498
167,2025-08-16 17:03:21,1.136985,NaN,NaN
168,2025-08-16 17:03:21,NaN,1.326080,NaN
...,...,...,...,...
14262,2025-08-16 20:58:00,2.295254,NaN,NaN
14263,2025-08-16 20:58:01,NaN,NaN,1.949698
14264,2025-08-16 20:58:03,NaN,2.340227,NaN
14265,2025-08-16 20:58:03,2.365427,NaN,NaN
14266,2025-08-16 20:58:04,NaN,NaN,2.019487

In [28]:
experimentDF = justTimestamp.merge(right = timeSeriesDataToGet,how = "left", on ="timestamp")
experimentDF

,timestamp,Id=0:BME680:breathVocEquivalent_x,Id=1:BME680:breathVocEquivalent_x,Id=2:BME680:breathVocEquivalent_x,Id=0:BME680:breathVocEquivalent_y,Id=1:BME680:breathVocEquivalent_y,Id=2:BME680:breathVocEquivalent_y
0,2025-08-16 17:03:17,NaN,NaN,NaN,NaN,NaN,NaN
1,2025-08-16 17:03:18,NaN,NaN,NaN,NaN,1.244104,NaN
2,2025-08-16 17:03:18,NaN,NaN,NaN,1.121423,NaN,NaN
3,2025-08-16 17:03:19,NaN,NaN,NaN,NaN,NaN,1.115498
4,2025-08-16 17:03:20,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...
18794,2025-08-16 20:58:01,NaN,NaN,NaN,NaN,NaN,1.949698
18795,2025-08-16 20:58:02,NaN,NaN,NaN,NaN,NaN,NaN
18796,2025-08-16 20:58:03,NaN,NaN,NaN,NaN,2.340227,NaN
18797,2025-08-16 20:58:03,NaN,NaN,NaN,2.365427,NaN,NaN
18798,2025-08-16 20:58:04,NaN,NaN,NaN,NaN,NaN,2.019487

In [29]:
experimentDF.index.dtype

dtype('int64')

In [30]:

# Melt dataframe: keep 'timestamp' fixed, put other columns into "sensor" + "value"
plot_df = experimentDF.melt(
    id_vars=["timestamp"], 
    value_vars=[
        "Id=0:BME680:breathVocEquivalent",
        "Id=1:BME680:breathVocEquivalent",
        "Id=2:BME680:breathVocEquivalent"
    ],
    var_name="Sensor", 
    value_name="VOC"
)

plot_df

KeyError: "The following 'value_vars' are not present in the DataFrame: ['Id=0:BME680:breathVocEquivalent', 'Id=1:BME680:breathVocEquivalent', 'Id=2:BME680:breathVocEquivalent']"

In [ ]:
# Plot with seaborn
plt.figure(figsize=(18, 8))
sns.lineplot(data=plot_df, x="timestamp", y="VOC", hue="Sensor")
plt.xticks(rotation=45)
plt.title("VOC Equivalent Time Series")
plt.show()