## IMPORT LIBRARIES, SET CONFIGURATIONS AND LOAD DATA FROM FILES INTO DATAFRAMES

### IMPORT LIBRARIES

In [1]:
#the import packages
import requests
import pandas as pd
from pandas import json_normalize
import requests
import os
from pathlib import Path
from datetime import datetime, timezone,timedelta,time
from scipy import stats
import json
import numpy as np

import seaborn as sns
import matplotlib.pyplot as plt

### SET CONFIGURATION

In [2]:
pd.set_option("display.max_columns", None)

### GET USER INPUT AND TIME SERIES DATA

In [3]:
def loadDataFromFile(file_name):
    script_dir = Path().resolve().parent

    data_folder = script_dir / 'dataAnalysis and machine learning'/'data'
    print(data_folder)
    data_folder.mkdir(exist_ok=True)
    
    file_path = data_folder / (file_name + ".json")
    
    if file_path.exists():
        df = pd.read_json(file_path)
        print(f"Loaded {len(df)} records from {file_path}")
        return df
    else:
        print(f"File {file_path} does not exist.")
        return None

In [4]:
userInputDataRaw = loadDataFromFile("User:Previous experiments")
timeSeriesData = loadDataFromFile("Data:Previous experiments")

C:\Users\Andreas\Documents\PlatformIO\Projects\Diploma Project\dataAnalysis and machine learning\data
Loaded 777 records from C:\Users\Andreas\Documents\PlatformIO\Projects\Diploma Project\dataAnalysis and machine learning\data\User:Previous experiments.json
C:\Users\Andreas\Documents\PlatformIO\Projects\Diploma Project\dataAnalysis and machine learning\data
Loaded 855293 records from C:\Users\Andreas\Documents\PlatformIO\Projects\Diploma Project\dataAnalysis and machine learning\data\Data:Previous experiments.json

In [5]:
userInputDataRaw

,_id,experimentState,timestamp,userInputCategory,are-doors-opened,are-people-inside,are-windows-opened,front-wall,item-used,notes,pollutant-type,quantity-used,room,side-right-wall,back-wall,side-left-wall,are-fans-on,no-source-located,epoch_ms,timestamp_local
0,{'$oid': '6863fe54cdf92819382e6866'},StartingExperiment,{'$date': 1751383636513},ExperimentState,None,None,None,NaN,None,None,None,None,None,NaN,NaN,NaN,None,None,1751383636513,2025-07-01 15:27:16.513
1,{'$oid': '686408456a2505a88d9b0665'},InsertingSourcePollutant,{'$date': 1751386181232},ExperimentState,on,None,None,0.95,Φαρμακευτικό αλκοόλ 95%,,VOC,30 ml,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,0.95,None,None,1751386181232,2025-07-01 16:09:41.232
2,{'$oid': '686409746a2505a88d9b087a'},RemovingSourcePollutant,{'$date': 1751386484742},ExperimentState,None,None,None,NaN,None,None,None,None,None,NaN,NaN,NaN,None,None,1751386484742,2025-07-01 16:14:44.742
3,{'$oid': '6865537ae30f2ab561c621a8'},StartingExperiment,{'$date': 1751470970240},ExperimentState,None,None,None,NaN,None,None,None,None,None,NaN,NaN,NaN,None,None,1751470970240,2025-07-02 15:42:50.240
4,{'$oid': '68655761e30f2ab561c629a2'},InsertingSourcePollutant,{'$date': 1751471969827},ExperimentState,on,None,None,0.95,Φαρμακευτικό αλκοόλ 95%,,VOC,30 ml,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,0.95,None,None,1751471969827,2025-07-02 15:59:29.827
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
772,{'$oid': '68fbf1027c6adebb72ced61d'},InsertingSourcePollutant,{'$date': 1761341698285},ExperimentState,None,None,None,2.50,Φαρμακευτικό αλκοόλ 95%,,VOC,30 ml,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.30,None,None,1761341698285,2025-10-24 21:34:58.285
773,{'$oid': '68fbf2727c6adebb72ceda7d'},RemovingSourcePollutant,{'$date': 1761342066926},ExperimentState,None,None,None,NaN,None,None,None,None,None,NaN,NaN,NaN,None,None,1761342066926,2025-10-24 21:41:06.926
774,{'$oid': '68fbf5107c6adebb72cee28d'},StartingExperiment,{'$date': 1761342736556},ExperimentState,None,None,None,NaN,None,None,None,None,None,NaN,NaN,NaN,None,None,1761342736556,2025-10-24 21:52:16.556
775,{'$oid': '68fbf57d7c6adebb72cee3ed'},InsertingSourcePollutant,{'$date': 1761342845443},ExperimentState,None,None,None,3.50,Φαρμακευτικό αλκοόλ 95%,,VOC,30 ml,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.30,None,None,1761342845443,2025-10-24 21:54:05.443
776,{'$oid': '68fbf7357c6adebb72cee922'},RemovingSourcePollutant,{'$date': 1761343285817},ExperimentState,None,None,None,NaN,None,None,None,None,None,NaN,NaN,NaN,None,None,1761343285817,2025-10-24 22:01:25.817

In [6]:
userInputDataRaw["room"].unique()

array([None, 'Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55',
       'Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1',
       'Κρεβατοκάμαρα-Όλοι οι αισθητήρες μαζί Μ:0.80 , Α:0.90',
       'Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0.5  ,id:2 Π:0.4 Α:1.0',
       'Κρεβατοκάμαρα Όλοι οι αισθητήρες μαζί Π:1.80 , Δ:2.00'],
      dtype=object)

In [7]:
timeSeriesData

,timestamp,Id=0:BME680:breathVocEquivalent,Id=1:BME680:breathVocEquivalent,Id=2:BME680:breathVocEquivalent
0,2025-07-01 15:27:18,NaN,1.480697,NaN
1,2025-07-01 15:27:19,NaN,NaN,1.430472
2,2025-07-01 15:27:21,NaN,1.469428,NaN
3,2025-07-01 15:27:22,NaN,NaN,1.441322
4,2025-07-01 15:27:24,NaN,1.476243,NaN
...,...,...,...,...
855288,2025-10-24 22:01:22,2.987463,NaN,NaN
855289,2025-10-24 22:01:22,NaN,2.595613,NaN
855290,2025-10-24 22:01:24,NaN,NaN,7.399793
855291,2025-10-24 22:01:25,2.989213,NaN,NaN
855292,2025-10-24 22:01:25,NaN,2.602333,NaN

In [8]:
userInputData = userInputDataRaw.drop(columns=["_id","timestamp","epoch_ms","userInputCategory","pollutant-type","quantity-used"])

## PROCCESS THE TIME COLUMNS AND VOC COLUMNS

### GET THE TIMEDATA FOR EACH EXPERIMENT,COMPARE STARTING EXPERIMENT STATE ROWS AND REMOVING SOURCE POLLUTANT STATE ROWS INTO THE IN BETWEEN INSERTING SOURCE POLLUTANT ROWS

In [9]:
userInputData["timestamp_local"] = pd.to_datetime(userInputData["timestamp_local"])  # ensure datetime
userInputData["timestamp_local"] = userInputData["timestamp_local"].dt.floor("s")

In [10]:
userInputData

,experimentState,are-doors-opened,are-people-inside,are-windows-opened,front-wall,item-used,notes,room,side-right-wall,back-wall,side-left-wall,are-fans-on,no-source-located,timestamp_local
0,StartingExperiment,None,None,None,NaN,None,None,None,NaN,NaN,NaN,None,None,2025-07-01 15:27:16
1,InsertingSourcePollutant,on,None,None,0.95,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,0.95,None,None,2025-07-01 16:09:41
2,RemovingSourcePollutant,None,None,None,NaN,None,None,None,NaN,NaN,NaN,None,None,2025-07-01 16:14:44
3,StartingExperiment,None,None,None,NaN,None,None,None,NaN,NaN,NaN,None,None,2025-07-02 15:42:50
4,InsertingSourcePollutant,on,None,None,0.95,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,0.95,None,None,2025-07-02 15:59:29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
772,InsertingSourcePollutant,None,None,None,2.50,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.30,None,None,2025-10-24 21:34:58
773,RemovingSourcePollutant,None,None,None,NaN,None,None,None,NaN,NaN,NaN,None,None,2025-10-24 21:41:06
774,StartingExperiment,None,None,None,NaN,None,None,None,NaN,NaN,NaN,None,None,2025-10-24 21:52:16
775,InsertingSourcePollutant,None,None,None,3.50,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.30,None,None,2025-10-24 21:54:05
776,RemovingSourcePollutant,None,None,None,NaN,None,None,None,NaN,NaN,NaN,None,None,2025-10-24 22:01:25

In [11]:
userInputDataTemp = userInputData[userInputData["experimentState"].isin(["NoSourcePollutantInserted","InsertingSourcePollutant"])].copy()

userInputDataTemp["timestamp StartingExperiment"] = userInputData["timestamp_local"].shift(1).loc[userInputData.index]
userInputDataTemp["timestamp EndingExperiment"]= userInputData["timestamp_local"].shift(-1).loc[userInputData.index]
userInputData =userInputDataTemp
userInputData = userInputData.reset_index(drop = True)
userInputData = userInputData.rename(columns={"timestamp_local":"timestamp InsertingSource"})

In [12]:
userInputData.head(20)

,experimentState,are-doors-opened,are-people-inside,are-windows-opened,front-wall,item-used,notes,room,side-right-wall,back-wall,side-left-wall,are-fans-on,no-source-located,timestamp InsertingSource,timestamp StartingExperiment,timestamp EndingExperiment
0,InsertingSourcePollutant,on,None,None,0.95,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,0.95,None,None,2025-07-01 16:09:41,2025-07-01 15:27:16,2025-07-01 16:14:44
1,InsertingSourcePollutant,on,None,None,0.95,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,0.95,None,None,2025-07-02 15:59:29,2025-07-02 15:42:50,2025-07-02 16:04:52
2,InsertingSourcePollutant,on,None,None,0.40,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,0.95,None,None,2025-07-03 12:34:32,2025-07-03 12:30:25,2025-07-03 12:45:31
3,InsertingSourcePollutant,on,None,None,0.95,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.85,None,None,2025-07-03 15:53:07,2025-07-03 15:43:27,2025-07-03 15:59:11
4,InsertingSourcePollutant,on,None,None,1.40,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.35,None,None,2025-07-09 19:19:19,2025-07-09 19:01:42,2025-07-09 19:27:50
5,InsertingSourcePollutant,None,None,None,0.95,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.75,None,None,2025-07-12 22:57:57,2025-07-12 22:31:25,2025-07-12 23:02:13
6,InsertingSourcePollutant,on,None,None,1.40,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.75,None,None,2025-07-14 19:40:37,2025-07-14 17:50:04,2025-07-14 19:48:32
7,InsertingSourcePollutant,on,on,None,1.80,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.10,None,None,2025-07-19 15:04:09,2025-07-19 14:59:47,2025-07-19 15:08:10
8,InsertingSourcePollutant,on,on,None,1.80,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.10,None,None,2025-07-19 15:17:10,2025-07-19 15:14:13,2025-07-19 15:21:23
9,InsertingSourcePollutant,on,on,None,1.80,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.10,None,None,2025-07-19 15:30:49,2025-07-19 15:25:07,2025-07-19 15:44:28
10,InsertingSourcePollutant,on,on,None,1.80,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.10,None,None,2025-07-19 16:12:54,2025-07-19 16:04:22,2025-07-19 16:21:55
11,InsertingSourcePollutant,on,on,None,1.80,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.10,None,None,2025-07-19 16:46:45,2025-07-19 16:36:03,2025-07-19 16:54:19
12,InsertingSourcePollutant,on,on,None,1.80,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.10,None,None,2025-07-19 17:25:36,2025-07-19 17:05:51,2025-07-19 17:35:58
13,InsertingSourcePollutant,on,None,None,1.80,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.10,None,None,2025-07-20 13:46:03,2025-07-20 13:36:41,2025-07-20 14:48:43
14,InsertingSourcePollutant,on,on,None,1.80,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.10,None,None,2025-07-20 15:15:34,2025-07-20 15:04:15,2025-07-20 15:39:22
15,InsertingSourcePollutant,on,on,None,1.80,Φαρμακευτικό αλκοόλ 95%,ανεμιστήρας,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.10,None,None,2025-07-20 15:52:33,2025-07-20 15:47:36,2025-07-20 16:08:05
16,InsertingSourcePollutant,on,None,None,1.80,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.10,None,None,2025-07-20 16:34:39,2025-07-20 16:20:42,2025-07-20 16:43:55
17,InsertingSourcePollutant,on,on,None,1.80,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.10,None,None,2025-07-20 18:13:07,2025-07-20 18:04:08,2025-07-20 18:22:22
18,InsertingSourcePollutant,on,on,on,1.80,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.10,None,None,2025-07-20 18:31:41,2025-07-20 18:29:19,2025-07-20 18:40:12
19,InsertingSourcePollutant,on,on,None,1.80,Φαρμακευτικό αλκοόλ 95%,ανεμιστήρας,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.10,None,None,2025-07-20 18:47:26,2025-07-20 18:41:09,2025-07-20 19:00:09

In [13]:
dict_of_timeseries = {}
for index, row in userInputData.iterrows():
    #get datetime
    start = row["timestamp StartingExperiment"]
    turning_point = row["timestamp InsertingSource"]
    end = row["timestamp EndingExperiment"]
    #Grab data
    particular_experiment = timeSeriesData[(timeSeriesData["timestamp"] >= start) & (timeSeriesData["timestamp"] <= end)]
    particular_experiment = particular_experiment.sort_values(by = ["timestamp"],ignore_index = True)
    dict_of_timeseries[index] = particular_experiment

In [14]:
userInputData["date of experiment"] = userInputData["timestamp EndingExperiment"].apply(lambda x:x.date())

### PROCESS THE EXPERIMENTS OF EACH ELEMENT OF DICTIONARY,IN ORDER TO INTERPOLATE THE DATA INTO A PER SECOND FREQUENCY

In [15]:
for index, row in userInputData.iterrows():
    particular_experiment =  dict_of_timeseries[index]

    #make the dataframe from multiple columns to have the data for each sensor to just one column
    particular_experiment = particular_experiment.melt(
        id_vars=["timestamp"], 
        value_vars=[
            "Id=0:BME680:breathVocEquivalent",
            "Id=1:BME680:breathVocEquivalent",
            "Id=2:BME680:breathVocEquivalent"
        ],
        var_name="sensors", 
        value_name="VOC"
    )
    particular_experiment = particular_experiment.dropna(ignore_index = True)

    particular_experiment = particular_experiment.sort_values(by = ["timestamp"],ignore_index = True)
    dict_of_timeseries[index] = particular_experiment

In [16]:
example_df = dict_of_timeseries[10]
example_df.head(20)

             timestamp                          sensors       VOC
0  2025-07-19 16:04:22  Id=1:BME680:breathVocEquivalent  0.513479
1  2025-07-19 16:04:24  Id=2:BME680:breathVocEquivalent  0.508068
2  2025-07-19 16:04:25  Id=1:BME680:breathVocEquivalent  0.518917
3  2025-07-19 16:04:27  Id=2:BME680:breathVocEquivalent  0.504020
4  2025-07-19 16:04:28  Id=1:BME680:breathVocEquivalent  0.521494
5  2025-07-19 16:04:30  Id=2:BME680:breathVocEquivalent  0.509921
6  2025-07-19 16:04:31  Id=1:BME680:breathVocEquivalent  0.518891
7  2025-07-19 16:04:33  Id=2:BME680:breathVocEquivalent  0.507465
8  2025-07-19 16:04:34  Id=1:BME680:breathVocEquivalent  0.514929
9  2025-07-19 16:04:36  Id=2:BME680:breathVocEquivalent  0.509477
10 2025-07-19 16:04:37  Id=1:BME680:breathVocEquivalent  0.509976
11 2025-07-19 16:04:39  Id=2:BME680:breathVocEquivalent  0.510929
12 2025-07-19 16:04:40  Id=1:BME680:breathVocEquivalent  0.509532
13 2025-07-19 16:04:42  Id=2:BME680:breathVocEquivalent  0.508344
14 2025-07-19 16:04:43  Id=1:BME680:breathVocEquivalent  0.516288
15 2025-07-19 16:04:45  Id=2:BME680:breathVocEquivalent  0.515360
16 2025-07-19 16:04:46  Id=1:BME680:breathVocEquivalent  0.511147
17 2025-07-19 16:04:48  Id=2:BME680:breathVocEquivalent  0.512273
18 2025-07-19 16:04:49  Id=1:BME680:breathVocEquivalent  0.511506
19 2025-07-19 16:04:51  Id=2:BME680:breathVocEquivalent  0.510924

In [17]:
userInputData

,experimentState,are-doors-opened,are-people-inside,are-windows-opened,front-wall,item-used,notes,room,side-right-wall,back-wall,side-left-wall,are-fans-on,no-source-located,timestamp InsertingSource,timestamp StartingExperiment,timestamp EndingExperiment,date of experiment
0,InsertingSourcePollutant,on,None,None,0.95,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,0.95,None,None,2025-07-01 16:09:41,2025-07-01 15:27:16,2025-07-01 16:14:44,2025-07-01
1,InsertingSourcePollutant,on,None,None,0.95,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,0.95,None,None,2025-07-02 15:59:29,2025-07-02 15:42:50,2025-07-02 16:04:52,2025-07-02
2,InsertingSourcePollutant,on,None,None,0.40,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,0.95,None,None,2025-07-03 12:34:32,2025-07-03 12:30:25,2025-07-03 12:45:31,2025-07-03
3,InsertingSourcePollutant,on,None,None,0.95,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.85,None,None,2025-07-03 15:53:07,2025-07-03 15:43:27,2025-07-03 15:59:11,2025-07-03
4,InsertingSourcePollutant,on,None,None,1.40,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.35,None,None,2025-07-09 19:19:19,2025-07-09 19:01:42,2025-07-09 19:27:50,2025-07-09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
254,InsertingSourcePollutant,None,None,None,0.50,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",0.5,NaN,NaN,None,None,2025-10-24 20:32:03,2025-10-24 20:29:36,2025-10-24 20:37:33,2025-10-24
255,InsertingSourcePollutant,None,None,None,0.50,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.30,None,None,2025-10-24 21:05:46,2025-10-24 21:03:22,2025-10-24 21:11:21,2025-10-24
256,InsertingSourcePollutant,None,None,None,1.50,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.30,None,None,2025-10-24 21:18:43,2025-10-24 21:17:10,2025-10-24 21:24:48,2025-10-24
257,InsertingSourcePollutant,None,None,None,2.50,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.30,None,None,2025-10-24 21:34:58,2025-10-24 21:33:44,2025-10-24 21:41:06,2025-10-24
258,InsertingSourcePollutant,None,None,None,3.50,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.30,None,None,2025-10-24 21:54:05,2025-10-24 21:52:16,2025-10-24 22:01:25,2025-10-24

In [18]:
for index, row in userInputData.iterrows():
#Now, we only have timestamps based of whenever the sensor took the value, but we want to have times 
    # Get full range of seconds from start to end timestamp
    particular_experiment =  dict_of_timeseries[index]
    start = row["timestamp StartingExperiment"]
    turning_point = row["timestamp InsertingSource"]

    end = row["timestamp EndingExperiment"]
    full_time_range = pd.date_range(start, end, freq="s")
    
    all_sensors = particular_experiment["sensors"].unique()
    particular_experiment["timestamp"] = pd.to_datetime(particular_experiment["timestamp"])
    
    full_index = pd.MultiIndex.from_product([full_time_range, all_sensors], names=["timestamp", "sensors"])
    extended_particular_experiment= pd.DataFrame(index=full_index).reset_index()
    particular_experiment = extended_particular_experiment.merge(particular_experiment, on=["timestamp", "sensors"], how="left",suffixes=["",None])
    particular_experiment["after_insertion"] = particular_experiment["timestamp"] > turning_point
    particular_experiment["original_value"] = pd.notna(particular_experiment["VOC"])
    dict_of_timeseries[index] = particular_experiment

In [19]:
example_df = dict_of_timeseries[10]
example_df

,timestamp,sensors,VOC,after_insertion,original_value
0,2025-07-19 16:04:22,Id=1:BME680:breathVocEquivalent,0.513479,False,True
1,2025-07-19 16:04:22,Id=2:BME680:breathVocEquivalent,NaN,False,False
2,2025-07-19 16:04:23,Id=1:BME680:breathVocEquivalent,NaN,False,False
3,2025-07-19 16:04:23,Id=2:BME680:breathVocEquivalent,NaN,False,False
4,2025-07-19 16:04:24,Id=1:BME680:breathVocEquivalent,NaN,False,False
...,...,...,...,...,...
2104,2025-07-19 16:21:53,Id=2:BME680:breathVocEquivalent,NaN,True,False
2105,2025-07-19 16:21:54,Id=1:BME680:breathVocEquivalent,NaN,True,False
2106,2025-07-19 16:21:54,Id=2:BME680:breathVocEquivalent,5.601505,True,True
2107,2025-07-19 16:21:55,Id=1:BME680:breathVocEquivalent,2.590167,True,True
2108,2025-07-19 16:21:55,Id=2:BME680:breathVocEquivalent,NaN,True,False

In [20]:
for index, row in userInputData.iterrows():
    
        particular_experiment =  dict_of_timeseries[index]

        particular_experiment["VOC"] = (
            particular_experiment
            .groupby("sensors")["VOC"]
            .transform(lambda s: s.interpolate(method = "cubic"))
        )
        dict_of_timeseries[index] = particular_experiment

In [21]:
example_df = dict_of_timeseries[10]
example_df

,timestamp,sensors,VOC,after_insertion,original_value
0,2025-07-19 16:04:22,Id=1:BME680:breathVocEquivalent,0.513479,False,True
1,2025-07-19 16:04:22,Id=2:BME680:breathVocEquivalent,NaN,False,False
2,2025-07-19 16:04:23,Id=1:BME680:breathVocEquivalent,0.515345,False,False
3,2025-07-19 16:04:23,Id=2:BME680:breathVocEquivalent,NaN,False,False
4,2025-07-19 16:04:24,Id=1:BME680:breathVocEquivalent,0.517211,False,False
...,...,...,...,...,...
2104,2025-07-19 16:21:53,Id=2:BME680:breathVocEquivalent,5.629334,True,False
2105,2025-07-19 16:21:54,Id=1:BME680:breathVocEquivalent,2.601317,True,False
2106,2025-07-19 16:21:54,Id=2:BME680:breathVocEquivalent,5.601505,True,True
2107,2025-07-19 16:21:55,Id=1:BME680:breathVocEquivalent,2.590167,True,True
2108,2025-07-19 16:21:55,Id=2:BME680:breathVocEquivalent,NaN,True,False

### PROCESS THE TIMESERIES COLUMNS

#### FIND THE MIN AND MAX TIMESTAPS THAT ALL SENSORS SHARE

In [22]:
# Ensure the columns exist and have datetime dtype
userInputData["actual timestamp StartingExperiment"] = pd.NaT
userInputData["actual timestamp EndingExperiment"] = pd.NaT
userInputData = userInputData.astype({
    "actual timestamp StartingExperiment": "datetime64[ns]",
    "actual timestamp EndingExperiment": "datetime64[ns]"
})

for index, row in userInputData.iterrows():
    particular_experiment = dict_of_timeseries[index]

    first_timestamps = particular_experiment[particular_experiment["VOC"].notna()] \
        .groupby("sensors", as_index=False)["timestamp"].min()
    last_timestamps = particular_experiment[particular_experiment["VOC"].notna()] \
        .groupby("sensors", as_index=False)["timestamp"].max()

    start = first_timestamps["timestamp"].max()
    end = last_timestamps["timestamp"].min()

    userInputData.at[index, "actual timestamp StartingExperiment"] = start
    userInputData.at[index, "actual timestamp EndingExperiment"] = end

    particular_experiment = particular_experiment.loc[
        particular_experiment["timestamp"].between(start, end, inclusive="both")
    ].reset_index(drop=True)

    dict_of_timeseries[index] = particular_experiment

In [23]:
userInputData.head(20)

,experimentState,are-doors-opened,are-people-inside,are-windows-opened,front-wall,item-used,notes,room,side-right-wall,back-wall,side-left-wall,are-fans-on,no-source-located,timestamp InsertingSource,timestamp StartingExperiment,timestamp EndingExperiment,date of experiment,actual timestamp StartingExperiment,actual timestamp EndingExperiment
0,InsertingSourcePollutant,on,None,None,0.95,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,0.95,None,None,2025-07-01 16:09:41,2025-07-01 15:27:16,2025-07-01 16:14:44,2025-07-01,2025-07-01 15:27:19,2025-07-01 16:14:42
1,InsertingSourcePollutant,on,None,None,0.95,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,0.95,None,None,2025-07-02 15:59:29,2025-07-02 15:42:50,2025-07-02 16:04:52,2025-07-02,2025-07-02 15:42:50,2025-07-02 16:04:50
2,InsertingSourcePollutant,on,None,None,0.40,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,0.95,None,None,2025-07-03 12:34:32,2025-07-03 12:30:25,2025-07-03 12:45:31,2025-07-03,2025-07-03 12:30:25,2025-07-03 12:45:31
3,InsertingSourcePollutant,on,None,None,0.95,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.85,None,None,2025-07-03 15:53:07,2025-07-03 15:43:27,2025-07-03 15:59:11,2025-07-03,2025-07-03 15:51:40,2025-07-03 15:59:10
4,InsertingSourcePollutant,on,None,None,1.40,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.35,None,None,2025-07-09 19:19:19,2025-07-09 19:01:42,2025-07-09 19:27:50,2025-07-09,2025-07-09 19:01:44,2025-07-09 19:27:49
5,InsertingSourcePollutant,None,None,None,0.95,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.75,None,None,2025-07-12 22:57:57,2025-07-12 22:31:25,2025-07-12 23:02:13,2025-07-12,2025-07-12 22:34:03,2025-07-12 23:02:11
6,InsertingSourcePollutant,on,None,None,1.40,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.75,None,None,2025-07-14 19:40:37,2025-07-14 17:50:04,2025-07-14 19:48:32,2025-07-14,2025-07-14 18:30:00,2025-07-14 19:20:03
7,InsertingSourcePollutant,on,on,None,1.80,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.10,None,None,2025-07-19 15:04:09,2025-07-19 14:59:47,2025-07-19 15:08:10,2025-07-19,2025-07-19 14:59:49,2025-07-19 15:08:09
8,InsertingSourcePollutant,on,on,None,1.80,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.10,None,None,2025-07-19 15:17:10,2025-07-19 15:14:13,2025-07-19 15:21:23,2025-07-19,2025-07-19 15:14:15,2025-07-19 15:21:21
9,InsertingSourcePollutant,on,on,None,1.80,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.10,None,None,2025-07-19 15:30:49,2025-07-19 15:25:07,2025-07-19 15:44:28,2025-07-19,2025-07-19 15:25:09,2025-07-19 15:44:27
10,InsertingSourcePollutant,on,on,None,1.80,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.10,None,None,2025-07-19 16:12:54,2025-07-19 16:04:22,2025-07-19 16:21:55,2025-07-19,2025-07-19 16:04:24,2025-07-19 16:21:54
11,InsertingSourcePollutant,on,on,None,1.80,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.10,None,None,2025-07-19 16:46:45,2025-07-19 16:36:03,2025-07-19 16:54:19,2025-07-19,2025-07-19 16:36:04,2025-07-19 16:54:18
12,InsertingSourcePollutant,on,on,None,1.80,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.10,None,None,2025-07-19 17:25:36,2025-07-19 17:05:51,2025-07-19 17:35:58,2025-07-19,2025-07-19 17:05:52,2025-07-19 17:35:57
13,InsertingSourcePollutant,on,None,None,1.80,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.10,None,None,2025-07-20 13:46:03,2025-07-20 13:36:41,2025-07-20 14:48:43,2025-07-20,2025-07-20 13:36:42,2025-07-20 14:48:41
14,InsertingSourcePollutant,on,on,None,1.80,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.10,None,None,2025-07-20 15:15:34,2025-07-20 15:04:15,2025-07-20 15:39:22,2025-07-20,2025-07-20 15:04:17,2025-07-20 15:39:20
15,InsertingSourcePollutant,on,on,None,1.80,Φαρμακευτικό αλκοόλ 95%,ανεμιστήρας,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.10,None,None,2025-07-20 15:52:33,2025-07-20 15:47:36,2025-07-20 16:08:05,2025-07-20,2025-07-20 15:47:38,2025-07-20 16:08:03
16,InsertingSourcePollutant,on,None,None,1.80,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.10,None,None,2025-07-20 16:34:39,2025-07-20 16:20:42,2025-07-20 16:43:55,2025-07-20,2025-07-20 16:20:44,2025-07-20 16:43:54
17,InsertingSourcePollutant,on,on,None,1.80,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.10,None,None,2025-07-20 18:13:07,2025-07-20 18:04:08,2025-07-20 18:22:22,2025-07-20,2025-07-20 18:04:10,2025-07-20 18:22:20
18,InsertingSourcePollutant,on,on,on,1.80,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.10,None,None,2025-07-20 18:31:41,2025-07-20 18:29:19,2025-07-20 18:40:12,2025-07-20,2025-07-20 18:29:21,2025-07-20 18:40:11
19,InsertingSourcePollutant,on,on,None,1.80,Φαρμακευτικό αλκοόλ 95%,ανεμιστήρας,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.10,None,None,2025-07-20 18:47:26,2025-07-20 18:41:09,2025-07-20 19:00:09,2025-07-20,2025-07-20 18:41:11,2025-07-20 19:00:08

In [24]:
example_df = dict_of_timeseries[10]
example_df

,timestamp,sensors,VOC,after_insertion,original_value
0,2025-07-19 16:04:24,Id=1:BME680:breathVocEquivalent,0.517211,False,False
1,2025-07-19 16:04:24,Id=2:BME680:breathVocEquivalent,0.508068,False,True
2,2025-07-19 16:04:25,Id=1:BME680:breathVocEquivalent,0.518917,False,True
3,2025-07-19 16:04:25,Id=2:BME680:breathVocEquivalent,0.503896,False,False
4,2025-07-19 16:04:26,Id=1:BME680:breathVocEquivalent,0.520305,False,False
...,...,...,...,...,...
2098,2025-07-19 16:21:52,Id=2:BME680:breathVocEquivalent,5.635052,True,False
2099,2025-07-19 16:21:53,Id=1:BME680:breathVocEquivalent,2.609777,True,False
2100,2025-07-19 16:21:53,Id=2:BME680:breathVocEquivalent,5.629334,True,False
2101,2025-07-19 16:21:54,Id=1:BME680:breathVocEquivalent,2.601317,True,False
2102,2025-07-19 16:21:54,Id=2:BME680:breathVocEquivalent,5.601505,True,True

In [25]:
userInputData

,experimentState,are-doors-opened,are-people-inside,are-windows-opened,front-wall,item-used,notes,room,side-right-wall,back-wall,side-left-wall,are-fans-on,no-source-located,timestamp InsertingSource,timestamp StartingExperiment,timestamp EndingExperiment,date of experiment,actual timestamp StartingExperiment,actual timestamp EndingExperiment
0,InsertingSourcePollutant,on,None,None,0.95,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,0.95,None,None,2025-07-01 16:09:41,2025-07-01 15:27:16,2025-07-01 16:14:44,2025-07-01,2025-07-01 15:27:19,2025-07-01 16:14:42
1,InsertingSourcePollutant,on,None,None,0.95,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,0.95,None,None,2025-07-02 15:59:29,2025-07-02 15:42:50,2025-07-02 16:04:52,2025-07-02,2025-07-02 15:42:50,2025-07-02 16:04:50
2,InsertingSourcePollutant,on,None,None,0.40,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,0.95,None,None,2025-07-03 12:34:32,2025-07-03 12:30:25,2025-07-03 12:45:31,2025-07-03,2025-07-03 12:30:25,2025-07-03 12:45:31
3,InsertingSourcePollutant,on,None,None,0.95,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.85,None,None,2025-07-03 15:53:07,2025-07-03 15:43:27,2025-07-03 15:59:11,2025-07-03,2025-07-03 15:51:40,2025-07-03 15:59:10
4,InsertingSourcePollutant,on,None,None,1.40,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.35,None,None,2025-07-09 19:19:19,2025-07-09 19:01:42,2025-07-09 19:27:50,2025-07-09,2025-07-09 19:01:44,2025-07-09 19:27:49
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
254,InsertingSourcePollutant,None,None,None,0.50,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",0.5,NaN,NaN,None,None,2025-10-24 20:32:03,2025-10-24 20:29:36,2025-10-24 20:37:33,2025-10-24,2025-10-24 20:29:37,2025-10-24 20:37:31
255,InsertingSourcePollutant,None,None,None,0.50,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.30,None,None,2025-10-24 21:05:46,2025-10-24 21:03:22,2025-10-24 21:11:21,2025-10-24,2025-10-24 21:03:24,2025-10-24 21:11:19
256,InsertingSourcePollutant,None,None,None,1.50,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.30,None,None,2025-10-24 21:18:43,2025-10-24 21:17:10,2025-10-24 21:24:48,2025-10-24,2025-10-24 21:17:12,2025-10-24 21:24:46
257,InsertingSourcePollutant,None,None,None,2.50,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.30,None,None,2025-10-24 21:34:58,2025-10-24 21:33:44,2025-10-24 21:41:06,2025-10-24,2025-10-24 21:33:46,2025-10-24 21:41:04
258,InsertingSourcePollutant,None,None,None,3.50,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.30,None,None,2025-10-24 21:54:05,2025-10-24 21:52:16,2025-10-24 22:01:25,2025-10-24,2025-10-24 21:52:18,2025-10-24 22:01:24

In [26]:
for index, row in userInputData.iterrows():

    particular_experiment =  dict_of_timeseries[index]
    particular_experiment = particular_experiment.drop_duplicates()
    dict_of_timeseries[index] = particular_experiment

In [27]:
dict_of_timeseries[7]

,timestamp,sensors,VOC,after_insertion,original_value
0,2025-07-19 14:59:49,Id=2:BME680:breathVocEquivalent,0.680033,False,False
1,2025-07-19 14:59:49,Id=1:BME680:breathVocEquivalent,2.118851,False,True
2,2025-07-19 14:59:50,Id=2:BME680:breathVocEquivalent,0.679083,False,False
3,2025-07-19 14:59:50,Id=1:BME680:breathVocEquivalent,2.125827,False,False
4,2025-07-19 14:59:51,Id=2:BME680:breathVocEquivalent,0.681077,False,True
...,...,...,...,...,...
997,2025-07-19 15:08:07,Id=1:BME680:breathVocEquivalent,1.193376,True,True
998,2025-07-19 15:08:08,Id=2:BME680:breathVocEquivalent,1.186056,True,False
999,2025-07-19 15:08:08,Id=1:BME680:breathVocEquivalent,1.192881,True,False
1000,2025-07-19 15:08:09,Id=2:BME680:breathVocEquivalent,1.184700,True,True
1001,2025-07-19 15:08:09,Id=1:BME680:breathVocEquivalent,1.193156,True,False

#### CREATE TIMEDELTA TYPE COLUMNS FOR TIMESTAMP AND FLOAT COLUMN FOR SECONDS

In [28]:
userInputData["time taken total"] = pd.NaT

for index, row in userInputData.iterrows():

    particular_experiment =  dict_of_timeseries[index]
    sensors = particular_experiment["sensors"].unique()
    particular_experiment["datetime_timestamp"] = particular_experiment["timestamp"]
    particular_experiment = particular_experiment.drop(columns="timestamp")
    particular_experiment["timestamp"] = np.nan
    particular_experiment["timestamp"] = particular_experiment["timestamp"].astype("timedelta64[ns]")
    for sensor in sensors:
        
        mask = particular_experiment["sensors"]==sensor
        #masked_data = particular_experiment.loc[mask]
        
        start = particular_experiment.loc[mask]["datetime_timestamp"].min()
        end = particular_experiment.loc[mask]["datetime_timestamp"].max()
        
        duration = end - start
        
        timeline = pd.timedelta_range(start="0s", end=duration, freq="s")
        
        particular_experiment.loc[mask,"timestamp"] = timeline
        particular_experiment.loc[mask,"seconds"] = timeline.total_seconds()
        userInputData.at[index,"time taken total"] = duration    
    dict_of_timeseries[index] =   particular_experiment

C:\Users\Andreas\AppData\Local\Temp\ipykernel_11096\1631178349.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  particular_experiment["datetime_timestamp"] = particular_experiment["timestamp"]

In [29]:
userInputData

,experimentState,are-doors-opened,are-people-inside,are-windows-opened,front-wall,item-used,notes,room,side-right-wall,back-wall,side-left-wall,are-fans-on,no-source-located,timestamp InsertingSource,timestamp StartingExperiment,timestamp EndingExperiment,date of experiment,actual timestamp StartingExperiment,actual timestamp EndingExperiment,time taken total
0,InsertingSourcePollutant,on,None,None,0.95,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,0.95,None,None,2025-07-01 16:09:41,2025-07-01 15:27:16,2025-07-01 16:14:44,2025-07-01,2025-07-01 15:27:19,2025-07-01 16:14:42,0 days 00:47:23
1,InsertingSourcePollutant,on,None,None,0.95,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,0.95,None,None,2025-07-02 15:59:29,2025-07-02 15:42:50,2025-07-02 16:04:52,2025-07-02,2025-07-02 15:42:50,2025-07-02 16:04:50,0 days 00:22:00
2,InsertingSourcePollutant,on,None,None,0.40,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,0.95,None,None,2025-07-03 12:34:32,2025-07-03 12:30:25,2025-07-03 12:45:31,2025-07-03,2025-07-03 12:30:25,2025-07-03 12:45:31,0 days 00:15:06
3,InsertingSourcePollutant,on,None,None,0.95,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.85,None,None,2025-07-03 15:53:07,2025-07-03 15:43:27,2025-07-03 15:59:11,2025-07-03,2025-07-03 15:51:40,2025-07-03 15:59:10,0 days 00:07:30
4,InsertingSourcePollutant,on,None,None,1.40,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.35,None,None,2025-07-09 19:19:19,2025-07-09 19:01:42,2025-07-09 19:27:50,2025-07-09,2025-07-09 19:01:44,2025-07-09 19:27:49,0 days 00:26:05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
254,InsertingSourcePollutant,None,None,None,0.50,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",0.5,NaN,NaN,None,None,2025-10-24 20:32:03,2025-10-24 20:29:36,2025-10-24 20:37:33,2025-10-24,2025-10-24 20:29:37,2025-10-24 20:37:31,0 days 00:07:54
255,InsertingSourcePollutant,None,None,None,0.50,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.30,None,None,2025-10-24 21:05:46,2025-10-24 21:03:22,2025-10-24 21:11:21,2025-10-24,2025-10-24 21:03:24,2025-10-24 21:11:19,0 days 00:07:55
256,InsertingSourcePollutant,None,None,None,1.50,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.30,None,None,2025-10-24 21:18:43,2025-10-24 21:17:10,2025-10-24 21:24:48,2025-10-24,2025-10-24 21:17:12,2025-10-24 21:24:46,0 days 00:07:34
257,InsertingSourcePollutant,None,None,None,2.50,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.30,None,None,2025-10-24 21:34:58,2025-10-24 21:33:44,2025-10-24 21:41:06,2025-10-24,2025-10-24 21:33:46,2025-10-24 21:41:04,0 days 00:07:18
258,InsertingSourcePollutant,None,None,None,3.50,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.30,None,None,2025-10-24 21:54:05,2025-10-24 21:52:16,2025-10-24 22:01:25,2025-10-24,2025-10-24 21:52:18,2025-10-24 22:01:24,0 days 00:09:06

In [30]:
userInputData.columns

Index(['experimentState', 'are-doors-opened', 'are-people-inside',
       'are-windows-opened', 'front-wall', 'item-used', 'notes', 'room',
       'side-right-wall', 'back-wall', 'side-left-wall', 'are-fans-on',
       'no-source-located', 'timestamp InsertingSource',
       'timestamp StartingExperiment', 'timestamp EndingExperiment',
       'date of experiment', 'actual timestamp StartingExperiment',
       'actual timestamp EndingExperiment', 'time taken total'],
      dtype='object')

In [31]:
 dict_of_timeseries[10]

,sensors,VOC,after_insertion,original_value,datetime_timestamp,timestamp,seconds
0,Id=1:BME680:breathVocEquivalent,0.517211,False,False,2025-07-19 16:04:24,0 days 00:00:00,0.0
1,Id=2:BME680:breathVocEquivalent,0.508068,False,True,2025-07-19 16:04:24,0 days 00:00:00,0.0
2,Id=1:BME680:breathVocEquivalent,0.518917,False,True,2025-07-19 16:04:25,0 days 00:00:01,1.0
3,Id=2:BME680:breathVocEquivalent,0.503896,False,False,2025-07-19 16:04:25,0 days 00:00:01,1.0
4,Id=1:BME680:breathVocEquivalent,0.520305,False,False,2025-07-19 16:04:26,0 days 00:00:02,2.0
...,...,...,...,...,...,...,...
2098,Id=2:BME680:breathVocEquivalent,5.635052,True,False,2025-07-19 16:21:52,0 days 00:17:28,1048.0
2099,Id=1:BME680:breathVocEquivalent,2.609777,True,False,2025-07-19 16:21:53,0 days 00:17:29,1049.0
2100,Id=2:BME680:breathVocEquivalent,5.629334,True,False,2025-07-19 16:21:53,0 days 00:17:29,1049.0
2101,Id=1:BME680:breathVocEquivalent,2.601317,True,False,2025-07-19 16:21:54,0 days 00:17:30,1050.0
2102,Id=2:BME680:breathVocEquivalent,5.601505,True,True,2025-07-19 16:21:54,0 days 00:17:30,1050.0

In [32]:
userInputData.dtypes

experimentState                                object
are-doors-opened                               object
are-people-inside                              object
are-windows-opened                             object
front-wall                                    float64
item-used                                      object
notes                                          object
room                                           object
side-right-wall                               float64
back-wall                                     float64
side-left-wall                                float64
are-fans-on                                    object
no-source-located                              object
timestamp InsertingSource              datetime64[ns]
timestamp StartingExperiment           datetime64[ns]
timestamp EndingExperiment             datetime64[ns]
date of experiment                             object
actual timestamp StartingExperiment    datetime64[ns]
actual timestamp EndingExperiment      datetime64[ns]
time taken total                               object
dtype: object

In [33]:
userInputData["timestamp InsertingSource timedelta"] = np.nan
userInputData["timestamp InsertingSource seconds"] = np.nan

for index, row in userInputData.iterrows():

    particular_experiment =  dict_of_timeseries[index]
    sensors = particular_experiment["sensors"].unique()

    for sensor in sensors:
        
        mask = particular_experiment["sensors"]==sensor
        #print(masker)

        start = particular_experiment.loc[mask,:]["timestamp"].min()
       # print(start)
        end = particular_experiment.loc[mask,:]["timestamp"].max()
        #print(end)
       # print(sensor)
        
        mask = (particular_experiment["sensors"] == sensor) & (particular_experiment["after_insertion"] == True)
        filtered = particular_experiment.loc[mask]
        #print(first_index)
        if not filtered.empty:
            first_index = filtered.index[0]
            insertion_time = filtered.at[first_index, "timestamp"]
        
            userInputData.at[index, "timestamp InsertingSource timedelta"] = insertion_time
            userInputData.at[index, "timestamp InsertingSource seconds"] = insertion_time.total_seconds()
            userInputData.at[index, "time taken after insertion"] = (userInputData.at[index, "time taken total"] - insertion_time)
            userInputData.at[index, "time taken before insertion"] = (userInputData.at[index, "time taken total"] - userInputData.at[index, "time taken after insertion"])
            
userInputData["time taken before insertion (seconds)"]  = userInputData["time taken before insertion"].dt.total_seconds() 
userInputData["time taken after insertion (seconds)"]  = userInputData["time taken after insertion"].dt.total_seconds() 
userInputData["time taken total"] = pd.to_timedelta(userInputData["time taken total"], errors="coerce")
userInputData["time taken total (seconds)"] = userInputData["time taken total"].dt.total_seconds()

In [34]:
userInputData.head(20)

,experimentState,are-doors-opened,are-people-inside,are-windows-opened,front-wall,item-used,notes,room,side-right-wall,back-wall,side-left-wall,are-fans-on,no-source-located,timestamp InsertingSource,timestamp StartingExperiment,timestamp EndingExperiment,date of experiment,actual timestamp StartingExperiment,actual timestamp EndingExperiment,time taken total,timestamp InsertingSource timedelta,timestamp InsertingSource seconds,time taken after insertion,time taken before insertion,time taken before insertion (seconds),time taken after insertion (seconds),time taken total (seconds)
0,InsertingSourcePollutant,on,None,None,0.95,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,0.95,None,None,2025-07-01 16:09:41,2025-07-01 15:27:16,2025-07-01 16:14:44,2025-07-01,2025-07-01 15:27:19,2025-07-01 16:14:42,0 days 00:47:23,0 days 00:42:23,2543.0,0 days 00:05:00,0 days 00:42:23,2543.0,300.0,2843.0
1,InsertingSourcePollutant,on,None,None,0.95,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,0.95,None,None,2025-07-02 15:59:29,2025-07-02 15:42:50,2025-07-02 16:04:52,2025-07-02,2025-07-02 15:42:50,2025-07-02 16:04:50,0 days 00:22:00,0 days 00:16:40,1000.0,0 days 00:05:20,0 days 00:16:40,1000.0,320.0,1320.0
2,InsertingSourcePollutant,on,None,None,0.40,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,0.95,None,None,2025-07-03 12:34:32,2025-07-03 12:30:25,2025-07-03 12:45:31,2025-07-03,2025-07-03 12:30:25,2025-07-03 12:45:31,0 days 00:15:06,0 days 00:04:08,248.0,0 days 00:10:58,0 days 00:04:08,248.0,658.0,906.0
3,InsertingSourcePollutant,on,None,None,0.95,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.85,None,None,2025-07-03 15:53:07,2025-07-03 15:43:27,2025-07-03 15:59:11,2025-07-03,2025-07-03 15:51:40,2025-07-03 15:59:10,0 days 00:07:30,0 days 00:01:28,88.0,0 days 00:06:02,0 days 00:01:28,88.0,362.0,450.0
4,InsertingSourcePollutant,on,None,None,1.40,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.35,None,None,2025-07-09 19:19:19,2025-07-09 19:01:42,2025-07-09 19:27:50,2025-07-09,2025-07-09 19:01:44,2025-07-09 19:27:49,0 days 00:26:05,0 days 00:17:36,1056.0,0 days 00:08:29,0 days 00:17:36,1056.0,509.0,1565.0
5,InsertingSourcePollutant,None,None,None,0.95,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.75,None,None,2025-07-12 22:57:57,2025-07-12 22:31:25,2025-07-12 23:02:13,2025-07-12,2025-07-12 22:34:03,2025-07-12 23:02:11,0 days 00:28:08,0 days 00:23:55,1435.0,0 days 00:04:13,0 days 00:23:55,1435.0,253.0,1688.0
6,InsertingSourcePollutant,on,None,None,1.40,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.75,None,None,2025-07-14 19:40:37,2025-07-14 17:50:04,2025-07-14 19:48:32,2025-07-14,2025-07-14 18:30:00,2025-07-14 19:20:03,0 days 00:50:03,NaN,NaN,NaT,NaT,NaN,NaN,3003.0
7,InsertingSourcePollutant,on,on,None,1.80,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.10,None,None,2025-07-19 15:04:09,2025-07-19 14:59:47,2025-07-19 15:08:10,2025-07-19,2025-07-19 14:59:49,2025-07-19 15:08:09,0 days 00:08:20,0 days 00:04:21,261.0,0 days 00:03:59,0 days 00:04:21,261.0,239.0,500.0
8,InsertingSourcePollutant,on,on,None,1.80,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.10,None,None,2025-07-19 15:17:10,2025-07-19 15:14:13,2025-07-19 15:21:23,2025-07-19,2025-07-19 15:14:15,2025-07-19 15:21:21,0 days 00:07:06,0 days 00:02:56,176.0,0 days 00:04:10,0 days 00:02:56,176.0,250.0,426.0
9,InsertingSourcePollutant,on,on,None,1.80,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.10,None,None,2025-07-19 15:30:49,2025-07-19 15:25:07,2025-07-19 15:44:28,2025-07-19,2025-07-19 15:25:09,2025-07-19 15:44:27,0 days 00:19:18,0 days 00:05:41,341.0,0 days 00:13:37,0 days 00:05:41,341.0,817.0,1158.0
10,InsertingSourcePollutant,on,on,None,1.80,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.10,None,None,2025-07-19 16:12:54,2025-07-19 16:04:22,2025-07-19 16:21:55,2025-07-19,2025-07-19 16:04:24,2025-07-19 16:21:54,0 days 00:17:30,0 days 00:08:31,511.0,0 days 00:08:59,0 days 00:08:31,511.0,539.0,1050.0
11,InsertingSourcePollutant,on,on,None,1.80,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.10,None,None,2025-07-19 16:46:45,2025-07-19 16:36:03,2025-07-19 16:54:19,2025-07-19,2025-07-19 16:36:04,2025-07-19 16:54:18,0 days 00:18:14,0 days 00:10:42,642.0,0 days 00:07:32,0 days 00:10:42,642.0,452.0,1094.0
12,InsertingSourcePollutant,on,on,None,1.80,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.10,None,None,2025-07-19 17:25:36,2025-07-19 17:05:51,2025-07-19 17:35:58,2025-07-19,2025-07-19 17:05:52,2025-07-19 17:35:57,0 days 00:30:05,0 days 00:19:45,1185.0,0 days 00:10:20,0 days 00:19:45,1185.0,620.0,1805.0
13,InsertingSourcePollutant,on,None,None,1.80,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.10,None,None,2025-07-20 13:46:03,2025-07-20 13:36:41,2025-07-20 14:48:43,2025-07-20,2025-07-20 13:36:42,2025-07-20 14:48:41,0 days 01:11:59,0 days 00:09:22,562.0,0 days 01:02:37,0 days 00:09:22,562.0,3757.0,4319.0
14,InsertingSourcePollutant,on,on,None,1.80,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.10,None,None,2025-07-20 15:15:34,2025-07-20 15:04:15,2025-07-20 15:39:22,2025-07-20,2025-07-20 15:04:17,2025-07-20 15:39:20,0 days 00:35:03,0 days 00:11:18,678.0,0 days 00:23:45,0 days 00:11:18,678.0,1425.0,2103.0
15,InsertingSourcePollutant,on,on,None,1.80,Φαρμακευτικό αλκοόλ 95%,ανεμιστήρας,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.10,None,None,2025-07-20 15:52:33,2025-07-20 15:47:36,2025-07-20 16:08:05,2025-07-20,2025-07-20 15:47:38,2025-07-20 16:08:03,0 days 00:20:25,0 days 00:04:56,296.0,0 days 00:15:29,0 days 00:04:56,296.0,929.0,1225.0
16,InsertingSourcePollutant,on,None,None,1.80,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.10,None,None,2025-07-20 16:34:39,2025-07-20 16:20:42,2025-07-20 16:43:55,2025-07-20,2025-07-20 16:20:44,2025-07-20 16:43:54,0 days 00:23:10,0 days 00:13:56,836.0,0 days 00:09:14,0 days 00:13:56,836.0,554.0,1390.0
17,InsertingSourcePollutant,on,on,None,1.80,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.10,None,None,2025-07-20 18:13:07,2025-07-20 18:04:08,2025-07-20 18:22:22,2025-07-20,2025-07-20 18:04:10,2025-07-20 18:22:20,0 days 00:18:10,0 days 00:08:58,538.0,0 days 00:09:12,0 days 00:08:58,538.0,552.0,1090.0
18,InsertingSourcePollutant,on,on,on,1.80,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.10,None,None,2025-07-20 18:31:41,2025-07-20 18:29:19,2025-07-20 18:40:12,2025-07-20,2025-07-20 18:29:21,2025-07-20 18:40:11,0 days 00:10:50,0 days 00:02:21,141.0,0 days 00:08:29,0 days 00:02:21,141.0,509.0,650.0
19,InsertingSourcePollutant,on,on,None,1.80,Φαρμακευτικό αλκοόλ 95%,ανεμιστήρας,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.10,None,None,2025-07-20 18:47:26,2025-07-20 18:41:09,2025-07-20 19:00:09,2025-07-20,2025-07-20 18:41:11,2025-07-20 19:00:08,0 days 00:18:57,0 days 00:06:16,376.0,0 days 00:12:41,0 days 00:06:16,376.0,761.0,1137.0

#### DROP THE EXPERIMENTS WHICH THEY DON'T HAVE ANY ACTUAL VALUE

In [35]:
# Find indices where the column is NaN
to_drop_idx = userInputData[userInputData["timestamp InsertingSource timedelta"].isna()].index
print(to_drop_idx)
# Remove those entries from the dictionary
for key in to_drop_idx:
    dict_of_timeseries.pop(key, None)

# Drop them from the DataFrame
userInputData = userInputData.dropna(subset=["timestamp InsertingSource timedelta"])

Index([6, 49], dtype='int64')

In [36]:


#if set is empty, the deletion at dictionary was succesful
missing_from_dict = set(userInputData.index) - set(dict_of_timeseries.keys())
print("Keys missing from dictionary:", missing_from_dict)

Keys missing from dictionary: set()

## SEARCH THE DATA AND CREATE EXTRA COLUMNS

In [37]:
userInputData["room"].unique()

array(['Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55',
       'Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1',
       'Κρεβατοκάμαρα-Όλοι οι αισθητήρες μαζί Μ:0.80 , Α:0.90',
       'Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0.5  ,id:2 Π:0.4 Α:1.0',
       'Κρεβατοκάμαρα Όλοι οι αισθητήρες μαζί Π:1.80 , Δ:2.00'],
      dtype=object)

In [38]:

#open_door_mask = userInputData["are-doors-opened"] != "on"
exp_state_mask = (userInputData["experimentState"] =="InsertingSourcePollutant")
#mask = room_mask & open_door_mask & exp_state_mask
room_list = userInputData["room"].unique()
time_to_check = "time taken after insertion (seconds)"
for room in room_list:
    print(room)
    room_mask =  userInputData["room"]==room
    userInputDataCheck = userInputData.loc[exp_state_mask & room_mask]
    
    value = 240  # your threshold value
    percentage = (userInputDataCheck[time_to_check] >= value).mean() * 100
    print(f"{percentage:.2f}% of rows have time taken after insertion (seconds) > {value}")
    
    value = 300  # your threshold value
    percentage = (userInputDataCheck[time_to_check] >= value).mean() * 100
    print(f"{percentage:.2f}% of rows have time taken after insertion (seconds) > {value}")
    
    value = 360  # your threshold value
    percentage = (userInputDataCheck[time_to_check] >= value).mean() * 100
    print(f"{percentage:.2f}% of rows have time taken after insertion (seconds) > {value}")

Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55
100.00% of rows have time taken after insertion (seconds) > 240
83.33% of rows have time taken after insertion (seconds) > 300
50.00% of rows have time taken after insertion (seconds) > 360
Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1
76.79% of rows have time taken after insertion (seconds) > 240
66.07% of rows have time taken after insertion (seconds) > 300
58.93% of rows have time taken after insertion (seconds) > 360
Κρεβατοκάμαρα-Όλοι οι αισθητήρες μαζί Μ:0.80 , Α:0.90
91.67% of rows have time taken after insertion (seconds) > 240
91.67% of rows have time taken after insertion (seconds) > 300
91.67% of rows have time taken after insertion (seconds) > 360
Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0.5  ,id:2 Π:0.4 Α:1.0
100.00% of rows have time taken after insertion (seconds) > 240
100.00% of rows have time taken after insertion (seconds) > 300
65.38% of rows have time taken after insertion (seconds) > 360
Κρεβατοκάμαρα Όλοι οι αισθητήρες μαζί Π:1.80 , Δ:2.00
100.00% of rows have time taken after insertion (seconds) > 240
100.00% of rows have time taken after insertion (seconds) > 300
71.43% of rows have time taken after insertion (seconds) > 360

In [39]:

open_door_mask = userInputData["are-doors-opened"] != "on"
exp_state_mask = (userInputData["experimentState"] =="InsertingSourcePollutant")
#mask = room_mask & open_door_mask & exp_state_mask
room_list = userInputData["room"].unique()
time_to_check = "time taken before insertion (seconds)"
for room in room_list:
    print(room)
    room_mask =  userInputData["room"]==room
    userInputDataCheck = userInputData.loc[exp_state_mask & room_mask]
    
    value = 30  # your threshold value
    percentage = (userInputDataCheck[time_to_check] >= value).mean() * 100
    print(f"{percentage:.2f}% of rows have time taken after insertion (seconds) > {value}")
    
    value = 60  # your threshold value
    percentage = (userInputDataCheck[time_to_check] >= value).mean() * 100
    print(f"{percentage:.2f}% of rows have time taken after insertion (seconds) > {value}")
    
    value = 120  # your threshold value
    percentage = (userInputDataCheck[time_to_check] >= value).mean() * 100
    print(f"{percentage:.2f}% of rows have time taken after insertion (seconds) > {value}")

Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55
100.00% of rows have time taken after insertion (seconds) > 30
100.00% of rows have time taken after insertion (seconds) > 60
83.33% of rows have time taken after insertion (seconds) > 120
Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1
98.21% of rows have time taken after insertion (seconds) > 30
98.21% of rows have time taken after insertion (seconds) > 60
92.86% of rows have time taken after insertion (seconds) > 120
Κρεβατοκάμαρα-Όλοι οι αισθητήρες μαζί Μ:0.80 , Α:0.90
100.00% of rows have time taken after insertion (seconds) > 30
100.00% of rows have time taken after insertion (seconds) > 60
100.00% of rows have time taken after insertion (seconds) > 120
Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0.5  ,id:2 Π:0.4 Α:1.0
99.36% of rows have time taken after insertion (seconds) > 30
98.72% of rows have time taken after insertion (seconds) > 60
57.05% of rows have time taken after insertion (seconds) > 120
Κρεβατοκάμαρα Όλοι οι αισθητήρες μαζί Π:1.80 , Δ:2.00
100.00% of rows have time taken after insertion (seconds) > 30
85.71% of rows have time taken after insertion (seconds) > 60
42.86% of rows have time taken after insertion (seconds) > 120

In [40]:

open_door_mask = userInputData["are-doors-opened"] != "on"
exp_state_mask = userInputData["experimentState"] =="InsertingSourcePollutant"
#mask = room_mask & open_door_mask & exp_state_mask
time_to_check = "time taken before insertion (seconds)"
room = 'Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0.5  ,id:2 Π:0.4 Α:1.0'
room_mask =  userInputData["room"] == room
userInputDataCheck = userInputData.loc[(exp_state_mask) & (room_mask) & (open_door_mask)]
print(room)
value = 30  # your threshold value
percentage = (userInputDataCheck[time_to_check] >= value).mean() * 100
print(f"{percentage:.2f}% of rows have time taken after insertion (seconds) > {value}")

value = 60  # your threshold value
percentage = (userInputDataCheck[time_to_check] >= value).mean() * 100
print(f"{percentage:.2f}% of rows have time taken after insertion (seconds) > {value}")

value = 120  # your threshold value
percentage = (userInputDataCheck[time_to_check] >= value).mean() * 100
print(f"{percentage:.2f}% of rows have time taken after insertion (seconds) > {value}")

Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0.5  ,id:2 Π:0.4 Α:1.0
100.00% of rows have time taken after insertion (seconds) > 30
98.98% of rows have time taken after insertion (seconds) > 60
36.73% of rows have time taken after insertion (seconds) > 120

In [41]:
userInputData

,experimentState,are-doors-opened,are-people-inside,are-windows-opened,front-wall,item-used,notes,room,side-right-wall,back-wall,side-left-wall,are-fans-on,no-source-located,timestamp InsertingSource,timestamp StartingExperiment,timestamp EndingExperiment,date of experiment,actual timestamp StartingExperiment,actual timestamp EndingExperiment,time taken total,timestamp InsertingSource timedelta,timestamp InsertingSource seconds,time taken after insertion,time taken before insertion,time taken before insertion (seconds),time taken after insertion (seconds),time taken total (seconds)
0,InsertingSourcePollutant,on,None,None,0.95,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,0.95,None,None,2025-07-01 16:09:41,2025-07-01 15:27:16,2025-07-01 16:14:44,2025-07-01,2025-07-01 15:27:19,2025-07-01 16:14:42,0 days 00:47:23,0 days 00:42:23,2543.0,0 days 00:05:00,0 days 00:42:23,2543.0,300.0,2843.0
1,InsertingSourcePollutant,on,None,None,0.95,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,0.95,None,None,2025-07-02 15:59:29,2025-07-02 15:42:50,2025-07-02 16:04:52,2025-07-02,2025-07-02 15:42:50,2025-07-02 16:04:50,0 days 00:22:00,0 days 00:16:40,1000.0,0 days 00:05:20,0 days 00:16:40,1000.0,320.0,1320.0
2,InsertingSourcePollutant,on,None,None,0.40,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,0.95,None,None,2025-07-03 12:34:32,2025-07-03 12:30:25,2025-07-03 12:45:31,2025-07-03,2025-07-03 12:30:25,2025-07-03 12:45:31,0 days 00:15:06,0 days 00:04:08,248.0,0 days 00:10:58,0 days 00:04:08,248.0,658.0,906.0
3,InsertingSourcePollutant,on,None,None,0.95,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.85,None,None,2025-07-03 15:53:07,2025-07-03 15:43:27,2025-07-03 15:59:11,2025-07-03,2025-07-03 15:51:40,2025-07-03 15:59:10,0 days 00:07:30,0 days 00:01:28,88.0,0 days 00:06:02,0 days 00:01:28,88.0,362.0,450.0
4,InsertingSourcePollutant,on,None,None,1.40,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.35,None,None,2025-07-09 19:19:19,2025-07-09 19:01:42,2025-07-09 19:27:50,2025-07-09,2025-07-09 19:01:44,2025-07-09 19:27:49,0 days 00:26:05,0 days 00:17:36,1056.0,0 days 00:08:29,0 days 00:17:36,1056.0,509.0,1565.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
254,InsertingSourcePollutant,None,None,None,0.50,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",0.5,NaN,NaN,None,None,2025-10-24 20:32:03,2025-10-24 20:29:36,2025-10-24 20:37:33,2025-10-24,2025-10-24 20:29:37,2025-10-24 20:37:31,0 days 00:07:54,0 days 00:02:27,147.0,0 days 00:05:27,0 days 00:02:27,147.0,327.0,474.0
255,InsertingSourcePollutant,None,None,None,0.50,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.30,None,None,2025-10-24 21:05:46,2025-10-24 21:03:22,2025-10-24 21:11:21,2025-10-24,2025-10-24 21:03:24,2025-10-24 21:11:19,0 days 00:07:55,0 days 00:02:23,143.0,0 days 00:05:32,0 days 00:02:23,143.0,332.0,475.0
256,InsertingSourcePollutant,None,None,None,1.50,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.30,None,None,2025-10-24 21:18:43,2025-10-24 21:17:10,2025-10-24 21:24:48,2025-10-24,2025-10-24 21:17:12,2025-10-24 21:24:46,0 days 00:07:34,0 days 00:01:32,92.0,0 days 00:06:02,0 days 00:01:32,92.0,362.0,454.0
257,InsertingSourcePollutant,None,None,None,2.50,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.30,None,None,2025-10-24 21:34:58,2025-10-24 21:33:44,2025-10-24 21:41:06,2025-10-24,2025-10-24 21:33:46,2025-10-24 21:41:04,0 days 00:07:18,0 days 00:01:13,73.0,0 days 00:06:05,0 days 00:01:13,73.0,365.0,438.0
258,InsertingSourcePollutant,None,None,None,3.50,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.30,None,None,2025-10-24 21:54:05,2025-10-24 21:52:16,2025-10-24 22:01:25,2025-10-24,2025-10-24 21:52:18,2025-10-24 22:01:24,0 days 00:09:06,0 days 00:01:48,108.0,0 days 00:07:18,0 days 00:01:48,108.0,438.0,546.0

In [42]:
for index, row in userInputData.iterrows():
    
    particular_experiment =  dict_of_timeseries[index]
    particular_experiment["seconds passed from insertionSource"] = np.nan
    sensors = particular_experiment["sensors"].unique()
    
    for sensor in sensors:
        
        mask = particular_experiment["sensors"]==sensor
        particular_experiment.loc[mask,"seconds passed from insertionSource"] = particular_experiment.loc[mask,"seconds"] - row["timestamp InsertingSource seconds"]  
    dict_of_timeseries[index] =   particular_experiment

In [43]:
dict_of_timeseries[10]

,sensors,VOC,after_insertion,original_value,datetime_timestamp,timestamp,seconds,seconds passed from insertionSource
0,Id=1:BME680:breathVocEquivalent,0.517211,False,False,2025-07-19 16:04:24,0 days 00:00:00,0.0,-511.0
1,Id=2:BME680:breathVocEquivalent,0.508068,False,True,2025-07-19 16:04:24,0 days 00:00:00,0.0,-511.0
2,Id=1:BME680:breathVocEquivalent,0.518917,False,True,2025-07-19 16:04:25,0 days 00:00:01,1.0,-510.0
3,Id=2:BME680:breathVocEquivalent,0.503896,False,False,2025-07-19 16:04:25,0 days 00:00:01,1.0,-510.0
4,Id=1:BME680:breathVocEquivalent,0.520305,False,False,2025-07-19 16:04:26,0 days 00:00:02,2.0,-509.0
...,...,...,...,...,...,...,...,...
2098,Id=2:BME680:breathVocEquivalent,5.635052,True,False,2025-07-19 16:21:52,0 days 00:17:28,1048.0,537.0
2099,Id=1:BME680:breathVocEquivalent,2.609777,True,False,2025-07-19 16:21:53,0 days 00:17:29,1049.0,538.0
2100,Id=2:BME680:breathVocEquivalent,5.629334,True,False,2025-07-19 16:21:53,0 days 00:17:29,1049.0,538.0
2101,Id=1:BME680:breathVocEquivalent,2.601317,True,False,2025-07-19 16:21:54,0 days 00:17:30,1050.0,539.0
2102,Id=2:BME680:breathVocEquivalent,5.601505,True,True,2025-07-19 16:21:54,0 days 00:17:30,1050.0,539.0

In [44]:
print(dict_of_timeseries[157].max())
print(userInputData.loc[157])

sensors                                Id=2:BME680:breathVocEquivalent
VOC                                                           9.690211
after_insertion                                                   True
original_value                                                    True
datetime_timestamp                                 2025-10-13 22:34:15
timestamp                                              0 days 00:08:03
seconds                                                          483.0
seconds passed from insertionSource                              388.0
dtype: object
experimentState                                                   InsertingSourcePollutant
are-doors-opened                                                                      None
are-people-inside                                                                     None
are-windows-opened                                                                    None
front-wall                                                                             1.5
item-used                                                          Φαρμακευτικό αλκοόλ 95%
notes
room                                     Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...
side-right-wall                                                                        2.5
back-wall                                                                              NaN
side-left-wall                                                                         NaN
are-fans-on                                                                           None
no-source-located                                                                     None
timestamp InsertingSource                                              2025-10-13 22:27:46
timestamp StartingExperiment                                           2025-10-13 22:26:11
timestamp EndingExperiment                                             2025-10-13 22:34:17
date of experiment                                                              2025-10-13
actual timestamp StartingExperiment                                    2025-10-13 22:26:12
actual timestamp EndingExperiment                                      2025-10-13 22:34:15
time taken total                                                           0 days 00:08:03
timestamp InsertingSource timedelta                                        0 days 00:01:35
timestamp InsertingSource seconds                                                     95.0
time taken after insertion                                                 0 days 00:06:28
time taken before insertion                                                0 days 00:01:35
time taken before insertion (seconds)                                                 95.0
time taken after insertion (seconds)                                                 388.0
time taken total (seconds)                                                           483.0
Name: 157, dtype: object

In [45]:
#make a column from VOC with the min at zerofor index, row in userInputData.iterrows():
for index, row in userInputData.iterrows():

    particular_experiment =  dict_of_timeseries[index].copy()
    col_to_create = "VOC original"
    col_name = "VOC"
    particular_experiment[col_to_create] = particular_experiment[col_name].copy()
    sensors = particular_experiment["sensors"].unique()
    if col_name  not in particular_experiment.columns:
        particular_experiment[col_name] = np.nan
    for sensor in sensors:
        mask = particular_experiment["sensors"]==sensor
        particular_experiment.loc[mask,col_name] = particular_experiment.loc[mask,col_name] - particular_experiment.loc[mask,col_name].min()
    dict_of_timeseries[index]  =  particular_experiment

In [46]:

#use rolling window
for index, row in userInputData.iterrows():
    particular_experiment =  dict_of_timeseries[index].copy()
    sensors = particular_experiment["sensors"].unique()

    for sensor in sensors:
        mask = particular_experiment["sensors"]==sensor
        particular_experiment.loc[mask,"VOC rolling average"] = particular_experiment.loc[mask].rolling(30,center= True ,min_periods=1,on="seconds")["VOC"].mean()


        
 #   scaler = StandardScaler()
#    particular_experiment.loc[:,"VOC standard scaled"] = scaler.fit_transform(particular_experiment.loc[:,"VOC"].to_numpy().reshape(-1,1))
#    particular_experiment.loc[:,"VOC rolling average standard scaled"] = scaler.fit_transform(particular_experiment.loc[:,"VOC rolling average"].to_numpy().reshape(-1,1))


    dict_of_timeseries[index] = particular_experiment

In [47]:
#round VOC rolling average data at 3 decimals
for index, row in userInputData.iterrows():
    
    particular_experiment =  dict_of_timeseries[index].copy()
    particular_experiment["VOC"] = particular_experiment["VOC"].round(3)
    particular_experiment["VOC rolling average"] = particular_experiment["VOC rolling average"].round(4)
    dict_of_timeseries[index]  =  particular_experiment

In [48]:
#trim the time before insertion to be less than two minutes 
#trim the time after insertion to be less than ten minutes
max_before= 31
max_after = 300
columns_to_add = ["time taken total (seconds)-capped","time taken before insertion (seconds)-capped","time taken after insertion (seconds)-capped"]
for index, row in userInputData.iterrows():
    particular_experiment =  dict_of_timeseries[index]
    for col in columns_to_add:
        if col not in userInputData.columns:
            userInputData.loc[:,col] = np.nan  
      
    time_mask = (particular_experiment["seconds passed from insertionSource"] > ( - max_before)) & (particular_experiment["seconds passed from insertionSource"] < max_after)
    particular_experiment = particular_experiment.loc[time_mask,:].copy()
   
    
    particular_experiment["original seconds"] = particular_experiment["seconds"]
    sensors = particular_experiment["sensors"].unique()
    
    for sensor in sensors:
        mask = particular_experiment["sensors"] == sensor 
        min_sensor_time = particular_experiment.loc[mask,"seconds passed from insertionSource"].min()
        max_sensor_time = particular_experiment.loc[mask,"seconds passed from insertionSource"].max()
        particular_experiment.loc[mask,"seconds"] = np.arange(min_sensor_time,max_sensor_time + 1) 
    min_sensor_time = particular_experiment["seconds passed from insertionSource"].min()    
    max_sensor_time = particular_experiment["seconds passed from insertionSource"].max()    

    userInputData.at[index,"time taken before insertion (seconds)-capped"] = min_sensor_time
    userInputData.at[index,"time taken after insertion (seconds)-capped"] =max_sensor_time
    userInputData.at[index,"time taken total (seconds)-capped"] = min_sensor_time +  max_sensor_time +1

    dict_of_timeseries[index]  =  particular_experiment

C:\Users\Andreas\AppData\Local\Temp\ipykernel_11096\3887428984.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  userInputData.loc[:,col] = np.nan
C:\Users\Andreas\AppData\Local\Temp\ipykernel_11096\3887428984.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  userInputData.loc[:,col] = np.nan
C:\Users\Andreas\AppData\Local\Temp\ipykernel_11096\3887428984.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  userInputData.loc[:,col] = np.nan

In [49]:
dict_of_timeseries[11]

,sensors,VOC,after_insertion,original_value,datetime_timestamp,timestamp,seconds,seconds passed from insertionSource,VOC original,VOC rolling average,original seconds
1224,Id=2:BME680:breathVocEquivalent,0.712,False,False,2025-07-19 16:46:16,0 days 00:10:12,-30.0,-30.0,1.303809,0.7231,612.0
1225,Id=1:BME680:breathVocEquivalent,0.849,False,True,2025-07-19 16:46:16,0 days 00:10:12,-30.0,-30.0,1.364794,0.8514,612.0
1226,Id=2:BME680:breathVocEquivalent,0.707,False,False,2025-07-19 16:46:17,0 days 00:10:13,-29.0,-29.0,1.299041,0.7233,613.0
1227,Id=1:BME680:breathVocEquivalent,0.845,False,False,2025-07-19 16:46:17,0 days 00:10:13,-29.0,-29.0,1.360319,0.8539,613.0
1228,Id=2:BME680:breathVocEquivalent,0.706,False,True,2025-07-19 16:46:18,0 days 00:10:14,-28.0,-28.0,1.298030,0.7235,614.0
...,...,...,...,...,...,...,...,...,...,...,...
1879,Id=1:BME680:breathVocEquivalent,1.398,True,True,2025-07-19 16:51:43,0 days 00:15:39,297.0,297.0,1.913526,1.4126,939.0
1880,Id=2:BME680:breathVocEquivalent,2.529,True,False,2025-07-19 16:51:44,0 days 00:15:40,298.0,298.0,3.120862,2.5407,940.0
1881,Id=1:BME680:breathVocEquivalent,1.412,True,False,2025-07-19 16:51:44,0 days 00:15:40,298.0,298.0,1.927478,1.4185,940.0
1882,Id=2:BME680:breathVocEquivalent,2.557,True,True,2025-07-19 16:51:45,0 days 00:15:41,299.0,299.0,3.148859,2.5592,941.0
1883,Id=1:BME680:breathVocEquivalent,1.425,True,False,2025-07-19 16:51:45,0 days 00:15:41,299.0,299.0,1.941105,1.4246,941.0

In [50]:
print(dict_of_timeseries[157].max())
print(userInputData.loc[157])

sensors                                Id=2:BME680:breathVocEquivalent
VOC                                                              4.206
after_insertion                                                   True
original_value                                                    True
datetime_timestamp                                 2025-10-13 22:32:46
timestamp                                              0 days 00:06:34
seconds                                                          299.0
seconds passed from insertionSource                              299.0
VOC original                                                  5.655352
VOC rolling average                                             4.0522
original seconds                                                 394.0
dtype: object
experimentState                                                          InsertingSourcePollutant
are-doors-opened                                                                             None
are-people-inside                                                                            None
are-windows-opened                                                                           None
front-wall                                                                                    1.5
item-used                                                                 Φαρμακευτικό αλκοόλ 95%
notes
room                                            Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...
side-right-wall                                                                               2.5
back-wall                                                                                     NaN
side-left-wall                                                                                NaN
are-fans-on                                                                                  None
no-source-located                                                                            None
timestamp InsertingSource                                                     2025-10-13 22:27:46
timestamp StartingExperiment                                                  2025-10-13 22:26:11
timestamp EndingExperiment                                                    2025-10-13 22:34:17
date of experiment                                                                     2025-10-13
actual timestamp StartingExperiment                                           2025-10-13 22:26:12
actual timestamp EndingExperiment                                             2025-10-13 22:34:15
time taken total                                                                  0 days 00:08:03
timestamp InsertingSource timedelta                                               0 days 00:01:35
timestamp InsertingSource seconds                                                            95.0
time taken after insertion                                                        0 days 00:06:28
time taken before insertion                                                       0 days 00:01:35
time taken before insertion (seconds)                                                        95.0
time taken after insertion (seconds)                                                        388.0
time taken total (seconds)                                                                  483.0
time taken total (seconds)-capped                                                           270.0
time taken before insertion (seconds)-capped                                                -30.0
time taken after insertion (seconds)-capped                                                 299.0
Name: 157, dtype: object

In [51]:
dict_of_timeseries[12]

,sensors,VOC,after_insertion,original_value,datetime_timestamp,timestamp,seconds,seconds passed from insertionSource,VOC original,VOC rolling average,original seconds
2310,Id=2:BME680:breathVocEquivalent,1.085,False,False,2025-07-19 17:25:07,0 days 00:19:15,-30.0,-30.0,1.742906,1.0831,1155.0
2311,Id=1:BME680:breathVocEquivalent,1.466,False,True,2025-07-19 17:25:07,0 days 00:19:15,-30.0,-30.0,2.043592,1.4920,1155.0
2312,Id=2:BME680:breathVocEquivalent,1.092,False,False,2025-07-19 17:25:08,0 days 00:19:16,-29.0,-29.0,1.750194,1.0819,1156.0
2313,Id=1:BME680:breathVocEquivalent,1.470,False,False,2025-07-19 17:25:08,0 days 00:19:16,-29.0,-29.0,2.047873,1.4944,1156.0
2314,Id=2:BME680:breathVocEquivalent,1.096,False,True,2025-07-19 17:25:09,0 days 00:19:17,-28.0,-28.0,1.754015,1.0806,1157.0
...,...,...,...,...,...,...,...,...,...,...,...
2965,Id=1:BME680:breathVocEquivalent,1.913,True,False,2025-07-19 17:30:34,0 days 00:24:42,297.0,297.0,2.490831,1.9152,1482.0
2966,Id=2:BME680:breathVocEquivalent,1.980,True,False,2025-07-19 17:30:35,0 days 00:24:43,298.0,298.0,2.637750,2.0040,1483.0
2967,Id=1:BME680:breathVocEquivalent,1.919,True,False,2025-07-19 17:30:35,0 days 00:24:43,298.0,298.0,2.496685,1.9185,1483.0
2968,Id=2:BME680:breathVocEquivalent,1.991,True,False,2025-07-19 17:30:36,0 days 00:24:44,299.0,299.0,2.649344,2.0172,1484.0
2969,Id=1:BME680:breathVocEquivalent,1.925,True,True,2025-07-19 17:30:36,0 days 00:24:44,299.0,299.0,2.503186,1.9219,1484.0

In [52]:
userInputData.loc[:,["front-wall","side-right-wall","back-wall","side-left-wall"]] = userInputData.loc[:,["front-wall","side-right-wall","back-wall","side-left-wall"]].round(1)

In [53]:
userInputData

,experimentState,are-doors-opened,are-people-inside,are-windows-opened,front-wall,item-used,notes,room,side-right-wall,back-wall,side-left-wall,are-fans-on,no-source-located,timestamp InsertingSource,timestamp StartingExperiment,timestamp EndingExperiment,date of experiment,actual timestamp StartingExperiment,actual timestamp EndingExperiment,time taken total,timestamp InsertingSource timedelta,timestamp InsertingSource seconds,time taken after insertion,time taken before insertion,time taken before insertion (seconds),time taken after insertion (seconds),time taken total (seconds),time taken total (seconds)-capped,time taken before insertion (seconds)-capped,time taken after insertion (seconds)-capped
0,InsertingSourcePollutant,on,None,None,1.0,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.0,None,None,2025-07-01 16:09:41,2025-07-01 15:27:16,2025-07-01 16:14:44,2025-07-01,2025-07-01 15:27:19,2025-07-01 16:14:42,0 days 00:47:23,0 days 00:42:23,2543.0,0 days 00:05:00,0 days 00:42:23,2543.0,300.0,2843.0,270.0,-30.0,299.0
1,InsertingSourcePollutant,on,None,None,1.0,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.0,None,None,2025-07-02 15:59:29,2025-07-02 15:42:50,2025-07-02 16:04:52,2025-07-02,2025-07-02 15:42:50,2025-07-02 16:04:50,0 days 00:22:00,0 days 00:16:40,1000.0,0 days 00:05:20,0 days 00:16:40,1000.0,320.0,1320.0,270.0,-30.0,299.0
2,InsertingSourcePollutant,on,None,None,0.4,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.0,None,None,2025-07-03 12:34:32,2025-07-03 12:30:25,2025-07-03 12:45:31,2025-07-03,2025-07-03 12:30:25,2025-07-03 12:45:31,0 days 00:15:06,0 days 00:04:08,248.0,0 days 00:10:58,0 days 00:04:08,248.0,658.0,906.0,270.0,-30.0,299.0
3,InsertingSourcePollutant,on,None,None,1.0,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.8,None,None,2025-07-03 15:53:07,2025-07-03 15:43:27,2025-07-03 15:59:11,2025-07-03,2025-07-03 15:51:40,2025-07-03 15:59:10,0 days 00:07:30,0 days 00:01:28,88.0,0 days 00:06:02,0 days 00:01:28,88.0,362.0,450.0,270.0,-30.0,299.0
4,InsertingSourcePollutant,on,None,None,1.4,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.4,None,None,2025-07-09 19:19:19,2025-07-09 19:01:42,2025-07-09 19:27:50,2025-07-09,2025-07-09 19:01:44,2025-07-09 19:27:49,0 days 00:26:05,0 days 00:17:36,1056.0,0 days 00:08:29,0 days 00:17:36,1056.0,509.0,1565.0,270.0,-30.0,299.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
254,InsertingSourcePollutant,None,None,None,0.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",0.5,NaN,NaN,None,None,2025-10-24 20:32:03,2025-10-24 20:29:36,2025-10-24 20:37:33,2025-10-24,2025-10-24 20:29:37,2025-10-24 20:37:31,0 days 00:07:54,0 days 00:02:27,147.0,0 days 00:05:27,0 days 00:02:27,147.0,327.0,474.0,270.0,-30.0,299.0
255,InsertingSourcePollutant,None,None,None,0.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:05:46,2025-10-24 21:03:22,2025-10-24 21:11:21,2025-10-24,2025-10-24 21:03:24,2025-10-24 21:11:19,0 days 00:07:55,0 days 00:02:23,143.0,0 days 00:05:32,0 days 00:02:23,143.0,332.0,475.0,270.0,-30.0,299.0
256,InsertingSourcePollutant,None,None,None,1.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:18:43,2025-10-24 21:17:10,2025-10-24 21:24:48,2025-10-24,2025-10-24 21:17:12,2025-10-24 21:24:46,0 days 00:07:34,0 days 00:01:32,92.0,0 days 00:06:02,0 days 00:01:32,92.0,362.0,454.0,270.0,-30.0,299.0
257,InsertingSourcePollutant,None,None,None,2.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:34:58,2025-10-24 21:33:44,2025-10-24 21:41:06,2025-10-24,2025-10-24 21:33:46,2025-10-24 21:41:04,0 days 00:07:18,0 days 00:01:13,73.0,0 days 00:06:05,0 days 00:01:13,73.0,365.0,438.0,270.0,-30.0,299.0
258,InsertingSourcePollutant,None,None,None,3.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:54:05,2025-10-24 21:52:16,2025-10-24 22:01:25,2025-10-24,2025-10-24 21:52:18,2025-10-24 22:01:24,0 days 00:09:06,0 days 00:01:48,108.0,0 days 00:07:18,0 days 00:01:48,108.0,438.0,546.0,270.0,-30.0,299.0

#make for each experiment and sensor as min the value zero
for index, row in userInputData.iterrows():
    particular_experiment =  dict_of_timeseries[index].copy()
    sensors = particular_experiment["sensors"].unique()
    col_name = "VOC rolling average"
    if col_name  not in particular_experiment.columns:
        particular_experiment[col_name] = np.nan
    for sensor in sensors:
        mask = particular_experiment["sensors"]==sensor
        particular_experiment.loc[mask,col_name] = particular_experiment.loc[mask,"VOC rolling average"] - particular_experiment.loc[mask,"VOC rolling average"].min()
    dict_of_timeseries[index]  =  particular_experiment

In [54]:
dict_of_timeseries[157]

,sensors,VOC,after_insertion,original_value,datetime_timestamp,timestamp,seconds,seconds passed from insertionSource,VOC original,VOC rolling average,original seconds
195,Id=0:BME680:breathVocEquivalent,0.355,False,True,2025-10-13 22:27:17,0 days 00:01:05,-30.0,-30.0,1.804527,0.3536,65.0
196,Id=1:BME680:breathVocEquivalent,0.541,False,True,2025-10-13 22:27:17,0 days 00:01:05,-30.0,-30.0,2.451902,0.5263,65.0
197,Id=2:BME680:breathVocEquivalent,0.090,False,False,2025-10-13 22:27:17,0 days 00:01:05,-30.0,-30.0,1.284219,0.0887,65.0
198,Id=0:BME680:breathVocEquivalent,0.358,False,False,2025-10-13 22:27:18,0 days 00:01:06,-29.0,-29.0,1.807059,0.3540,66.0
199,Id=1:BME680:breathVocEquivalent,0.552,False,False,2025-10-13 22:27:18,0 days 00:01:06,-29.0,-29.0,2.462499,0.5226,66.0
...,...,...,...,...,...,...,...,...,...,...,...
1180,Id=1:BME680:breathVocEquivalent,2.628,True,False,2025-10-13 22:32:45,0 days 00:06:33,298.0,298.0,4.538666,2.5994,393.0
1181,Id=2:BME680:breathVocEquivalent,3.599,True,True,2025-10-13 22:32:45,0 days 00:06:33,298.0,298.0,4.793872,3.5720,393.0
1182,Id=0:BME680:breathVocEquivalent,4.159,True,False,2025-10-13 22:32:46,0 days 00:06:34,299.0,299.0,5.607971,4.0315,394.0
1183,Id=1:BME680:breathVocEquivalent,2.643,True,False,2025-10-13 22:32:46,0 days 00:06:34,299.0,299.0,4.553225,2.6075,394.0
1184,Id=2:BME680:breathVocEquivalent,3.671,True,False,2025-10-13 22:32:46,0 days 00:06:34,299.0,299.0,4.865380,3.6532,394.0

In [55]:
dict_of_timeseries[157]

,sensors,VOC,after_insertion,original_value,datetime_timestamp,timestamp,seconds,seconds passed from insertionSource,VOC original,VOC rolling average,original seconds
195,Id=0:BME680:breathVocEquivalent,0.355,False,True,2025-10-13 22:27:17,0 days 00:01:05,-30.0,-30.0,1.804527,0.3536,65.0
196,Id=1:BME680:breathVocEquivalent,0.541,False,True,2025-10-13 22:27:17,0 days 00:01:05,-30.0,-30.0,2.451902,0.5263,65.0
197,Id=2:BME680:breathVocEquivalent,0.090,False,False,2025-10-13 22:27:17,0 days 00:01:05,-30.0,-30.0,1.284219,0.0887,65.0
198,Id=0:BME680:breathVocEquivalent,0.358,False,False,2025-10-13 22:27:18,0 days 00:01:06,-29.0,-29.0,1.807059,0.3540,66.0
199,Id=1:BME680:breathVocEquivalent,0.552,False,False,2025-10-13 22:27:18,0 days 00:01:06,-29.0,-29.0,2.462499,0.5226,66.0
...,...,...,...,...,...,...,...,...,...,...,...
1180,Id=1:BME680:breathVocEquivalent,2.628,True,False,2025-10-13 22:32:45,0 days 00:06:33,298.0,298.0,4.538666,2.5994,393.0
1181,Id=2:BME680:breathVocEquivalent,3.599,True,True,2025-10-13 22:32:45,0 days 00:06:33,298.0,298.0,4.793872,3.5720,393.0
1182,Id=0:BME680:breathVocEquivalent,4.159,True,False,2025-10-13 22:32:46,0 days 00:06:34,299.0,299.0,5.607971,4.0315,394.0
1183,Id=1:BME680:breathVocEquivalent,2.643,True,False,2025-10-13 22:32:46,0 days 00:06:34,299.0,299.0,4.553225,2.6075,394.0
1184,Id=2:BME680:breathVocEquivalent,3.671,True,False,2025-10-13 22:32:46,0 days 00:06:34,299.0,299.0,4.865380,3.6532,394.0

In [56]:
#make the seconds to be index
for index, row in userInputData.iterrows():
    
    particular_experiment =  dict_of_timeseries[index].copy()
    
    dict_of_timeseries[index]  =  particular_experiment.set_index("seconds",drop = False)

In [57]:
dict_of_timeseries[190]

,sensors,VOC,after_insertion,original_value,datetime_timestamp,timestamp,seconds,seconds passed from insertionSource,VOC original,VOC rolling average,original seconds
seconds,,,,,,,,,,,
-30.0,Id=0:BME680:breathVocEquivalent,0.118,False,True,2025-10-17 12:26:40,0 days 00:00:50,-30.0,-30.0,1.729892,0.1266,50.0
-30.0,Id=2:BME680:breathVocEquivalent,0.080,False,True,2025-10-17 12:26:40,0 days 00:00:50,-30.0,-30.0,1.838254,0.0995,50.0
-30.0,Id=1:BME680:breathVocEquivalent,0.024,False,False,2025-10-17 12:26:40,0 days 00:00:50,-30.0,-30.0,1.687442,0.0421,50.0
-29.0,Id=0:BME680:breathVocEquivalent,0.121,False,False,2025-10-17 12:26:41,0 days 00:00:51,-29.0,-29.0,1.733096,0.1278,51.0
-29.0,Id=2:BME680:breathVocEquivalent,0.081,False,False,2025-10-17 12:26:41,0 days 00:00:51,-29.0,-29.0,1.839303,0.1018,51.0
...,...,...,...,...,...,...,...,...,...,...,...
298.0,Id=2:BME680:breathVocEquivalent,0.787,True,False,2025-10-17 12:32:08,0 days 00:06:18,298.0,298.0,2.545097,0.7804,378.0
298.0,Id=1:BME680:breathVocEquivalent,0.526,True,True,2025-10-17 12:32:08,0 days 00:06:18,298.0,298.0,2.189760,0.5219,378.0
299.0,Id=0:BME680:breathVocEquivalent,1.277,True,False,2025-10-17 12:32:09,0 days 00:06:19,299.0,299.0,2.888517,1.2496,379.0
299.0,Id=2:BME680:breathVocEquivalent,0.779,True,False,2025-10-17 12:32:09,0 days 00:06:19,299.0,299.0,2.537247,0.7806,379.0
299.0,Id=1:BME680:breathVocEquivalent,0.528,True,False,2025-10-17 12:32:09,0 days 00:06:19,299.0,299.0,2.191384,0.5233,379.0

In [58]:
#find max values and its position
for index, row in userInputData.iterrows():
    particular_experiment =  dict_of_timeseries[index].copy()
    sensors = particular_experiment["sensors"].unique()
    column_to_find_values = "VOC rolling average"
    for sensor in sensors:
        mask = particular_experiment["sensors"]==sensor
        
        col_name = f"{sensor} MAX value {column_to_find_values}"
        if col_name  not in userInputData.columns:
            userInputData.loc[:,col_name] = np.nan
        userInputData.at[index,col_name] = particular_experiment.loc[mask,column_to_find_values].max()
    
            
        col_name = f"{sensor} index of MAX value {column_to_find_values}"
        if col_name  not in userInputData.columns:
            userInputData.loc[:,col_name] = np.nan    
        userInputData.at[index,col_name] = particular_experiment.loc[mask,column_to_find_values].idxmax()

dict_of_timeseries[index]  =  particular_experiment

C:\Users\Andreas\AppData\Local\Temp\ipykernel_11096\1512944631.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  userInputData.loc[:,col_name] = np.nan
C:\Users\Andreas\AppData\Local\Temp\ipykernel_11096\1512944631.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  userInputData.loc[:,col_name] = np.nan
C:\Users\Andreas\AppData\Local\Temp\ipykernel_11096\1512944631.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  userInputData.loc[:,col_name] = np.nan
C:\Users\Andreas\AppData\Local\Temp\ipykernel_11096\1512944631.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  userInputData.loc[:,col_name] = np.nan
C:\Users\Andreas\AppData\Local\Temp\ipykernel_11096\1512944631.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  userInputData.loc[:,col_name] = np.nan
C:\Users\Andreas\AppData\Local\Temp\ipykernel_11096\1512944631.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  userInputData.loc[:,col_name] = np.nan

In [59]:
userInputData

,experimentState,are-doors-opened,are-people-inside,are-windows-opened,front-wall,item-used,notes,room,side-right-wall,back-wall,side-left-wall,are-fans-on,no-source-located,timestamp InsertingSource,timestamp StartingExperiment,timestamp EndingExperiment,date of experiment,actual timestamp StartingExperiment,actual timestamp EndingExperiment,time taken total,timestamp InsertingSource timedelta,timestamp InsertingSource seconds,time taken after insertion,time taken before insertion,time taken before insertion (seconds),time taken after insertion (seconds),time taken total (seconds),time taken total (seconds)-capped,time taken before insertion (seconds)-capped,time taken after insertion (seconds)-capped,Id=1:BME680:breathVocEquivalent MAX value VOC rolling average,Id=1:BME680:breathVocEquivalent index of MAX value VOC rolling average,Id=2:BME680:breathVocEquivalent MAX value VOC rolling average,Id=2:BME680:breathVocEquivalent index of MAX value VOC rolling average,Id=0:BME680:breathVocEquivalent MAX value VOC rolling average,Id=0:BME680:breathVocEquivalent index of MAX value VOC rolling average
0,InsertingSourcePollutant,on,None,None,1.0,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.0,None,None,2025-07-01 16:09:41,2025-07-01 15:27:16,2025-07-01 16:14:44,2025-07-01,2025-07-01 15:27:19,2025-07-01 16:14:42,0 days 00:47:23,0 days 00:42:23,2543.0,0 days 00:05:00,0 days 00:42:23,2543.0,300.0,2843.0,270.0,-30.0,299.0,4.3501,299.0,8.1928,243.0,NaN,NaN
1,InsertingSourcePollutant,on,None,None,1.0,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.0,None,None,2025-07-02 15:59:29,2025-07-02 15:42:50,2025-07-02 16:04:52,2025-07-02,2025-07-02 15:42:50,2025-07-02 16:04:50,0 days 00:22:00,0 days 00:16:40,1000.0,0 days 00:05:20,0 days 00:16:40,1000.0,320.0,1320.0,270.0,-30.0,299.0,1.1333,201.0,0.3304,80.0,NaN,NaN
2,InsertingSourcePollutant,on,None,None,0.4,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.0,None,None,2025-07-03 12:34:32,2025-07-03 12:30:25,2025-07-03 12:45:31,2025-07-03,2025-07-03 12:30:25,2025-07-03 12:45:31,0 days 00:15:06,0 days 00:04:08,248.0,0 days 00:10:58,0 days 00:04:08,248.0,658.0,906.0,270.0,-30.0,299.0,1.3923,235.0,2.2994,299.0,NaN,NaN
3,InsertingSourcePollutant,on,None,None,1.0,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.8,None,None,2025-07-03 15:53:07,2025-07-03 15:43:27,2025-07-03 15:59:11,2025-07-03,2025-07-03 15:51:40,2025-07-03 15:59:10,0 days 00:07:30,0 days 00:01:28,88.0,0 days 00:06:02,0 days 00:01:28,88.0,362.0,450.0,270.0,-30.0,299.0,0.3439,299.0,18.4943,299.0,NaN,NaN
4,InsertingSourcePollutant,on,None,None,1.4,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.4,None,None,2025-07-09 19:19:19,2025-07-09 19:01:42,2025-07-09 19:27:50,2025-07-09,2025-07-09 19:01:44,2025-07-09 19:27:49,0 days 00:26:05,0 days 00:17:36,1056.0,0 days 00:08:29,0 days 00:17:36,1056.0,509.0,1565.0,270.0,-30.0,299.0,0.6066,246.0,0.7315,299.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
254,InsertingSourcePollutant,None,None,None,0.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",0.5,NaN,NaN,None,None,2025-10-24 20:32:03,2025-10-24 20:29:36,2025-10-24 20:37:33,2025-10-24,2025-10-24 20:29:37,2025-10-24 20:37:31,0 days 00:07:54,0 days 00:02:27,147.0,0 days 00:05:27,0 days 00:02:27,147.0,327.0,474.0,270.0,-30.0,299.0,2.0134,131.0,4.9923,299.0,2.8096,286.0
255,InsertingSourcePollutant,None,None,None,0.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:05:46,2025-10-24 21:03:22,2025-10-24 21:11:21,2025-10-24,2025-10-24 21:03:24,2025-10-24 21:11:19,0 days 00:07:55,0 days 00:02:23,143.0,0 days 00:05:32,0 days 00:02:23,143.0,332.0,475.0,270.0,-30.0,299.0,1.5436,269.0,6.0745,299.0,2.4431,236.0
256,InsertingSourcePollutant,None,None,None,1.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:18:43,2025-10-24 21:17:10,2025-10-24 21:24:48,2025-10-24,2025-10-24 21:17:12,2025-10-24 21:24:46,0 days 00:07:34,0 days 00:01:32,92.0,0 days 00:06:02,0 days 00:01:32,92.0,362.0,454.0,270.0,-30.0,299.0,2.0029,299.0,13.3480,277.0,2.0105,141.0
257,InsertingSourcePollutant,None,None,None,2.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:34:58,2025-10-24 21:33:44,2025-10-24 21:41:06,2025-10-24,2025-10-24 21:33:46,2025-10-24 21:41:04,0 days 00:07:18,0 days 00:01:13,73.0,0 days 00:06:05,0 days 00:01:13,73.0,365.0,438.0,270.0,-30.0,299.0,1.8114,299.0,7.5793,261.0,1.2671,299.0
258,InsertingSourcePollutant,None,None,None,3.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:54:05,2025-10-24 21:52:16,2025-10-24 22:01:25,2025-10-24,2025-10-24 21:52:18,2025-10-24 22:01:24,0 days 00:09:06,0 days 00:01:48,108.0,0 days 00:07:18,0 days 00:01:48,108.0,438.0,546.0,270.0,-30.0,299.0,1.6312,213.0,3.3710,287.0,2.1139,299.0

In [60]:
print(dict_of_timeseries[157].max())
print(userInputData.loc[157])

sensors                                Id=2:BME680:breathVocEquivalent
VOC                                                              4.206
after_insertion                                                   True
original_value                                                    True
datetime_timestamp                                 2025-10-13 22:32:46
timestamp                                              0 days 00:06:34
seconds                                                          299.0
seconds passed from insertionSource                              299.0
VOC original                                                  5.655352
VOC rolling average                                             4.0522
original seconds                                                 394.0
dtype: object
experimentState                                                                                    InsertingSourcePollutant
are-doors-opened                                                                                                       None
are-people-inside                                                                                                      None
are-windows-opened                                                                                                     None
front-wall                                                                                                              1.5
item-used                                                                                           Φαρμακευτικό αλκοόλ 95%
notes
room                                                                      Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...
side-right-wall                                                                                                         2.5
back-wall                                                                                                               NaN
side-left-wall                                                                                                          NaN
are-fans-on                                                                                                            None
no-source-located                                                                                                      None
timestamp InsertingSource                                                                               2025-10-13 22:27:46
timestamp StartingExperiment                                                                            2025-10-13 22:26:11
timestamp EndingExperiment                                                                              2025-10-13 22:34:17
date of experiment                                                                                               2025-10-13
actual timestamp StartingExperiment                                                                     2025-10-13 22:26:12
actual timestamp EndingExperiment                                                                       2025-10-13 22:34:15
time taken total                                                                                            0 days 00:08:03
timestamp InsertingSource timedelta                                                                         0 days 00:01:35
timestamp InsertingSource seconds                                                                                      95.0
time taken after insertion                                                                                  0 days 00:06:28
time taken before insertion                                                                                 0 days 00:01:35
time taken before insertion (seconds)                                                                                  95.0
time taken after insertion (seconds)                                                                                  388.0
time taken total (seconds)                                                                                            483.0
time taken total (seconds)-capped                                                                                     270.0
time taken before insertion (seconds)-capped                                                                          -30.0
time taken after insertion (seconds)-capped                                                                           299.0
Id=1:BME680:breathVocEquivalent MAX value VOC rolling average                                                        2.6075
Id=1:BME680:breathVocEquivalent index of MAX value VOC rolling average                                                299.0
Id=2:BME680:breathVocEquivalent MAX value VOC rolling average                                                        3.6532
Id=2:BME680:breathVocEquivalent index of MAX value VOC rolling average                                                299.0
Id=0:BME680:breathVocEquivalent MAX value VOC rolling average                                                        4.0522
Id=0:BME680:breathVocEquivalent index of MAX value VOC rolling average                                                296.0
Name: 157, dtype: object

In [61]:
col_list = []

for sensor in sensors:
    col_name = f"{sensor} MAX value {column_to_find_values}"
    col_list.append(col_name)
colunn_to_create = "sensor with MAX value experiment"    
if colunn_to_create not in userInputData.columns:
    userInputData[colunn_to_create] = np.nan
colunn_to_create_second = "sensor with second MAX value experiment"
if colunn_to_create not in userInputData.columns:
    userInputData[colunn_to_create] = np.nan
for index, row in userInputData.iterrows():
    max_dict = row[col_list].to_dict()  
    # Sort correctly — key must be inside sorted()
    sorted_items = sorted(
    max_dict.items(),
    key=lambda x: (pd.notna(x[1]), x[1])
)
    # Handle missing/NaN gracefully
    if len(sorted_items) > 0 and pd.notna(sorted_items[2][1]):
        userInputData.at[index, colunn_to_create] = sorted_items[2][0]
    if len(sorted_items) > 1 and pd.notna(sorted_items[1][1]):
        userInputData.at[index, colunn_to_create_second] = sorted_items[1][0]

C:\Users\Andreas\AppData\Local\Temp\ipykernel_11096\2114904390.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  userInputData[colunn_to_create] = np.nan
C:\Users\Andreas\AppData\Local\Temp\ipykernel_11096\2114904390.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  userInputData.at[index, colunn_to_create_second] = sorted_items[1][0]

In [62]:
#FIND 90% quantile and 99% quantile not yet use at capping values
#find quantile per sensor 
def create_column_quantile(userInputData,sensor,quantile_number,column_to_find_values):
    colunn_to_create = f"{sensor} quantile {quantile_number * 100}% {column_to_find_values}"    
    if colunn_to_create not in userInputData.columns:
        userInputData[colunn_to_create] = np.nan
    return colunn_to_create

    
for index, row in userInputData.iterrows():
    particular_experiment =  dict_of_timeseries[index].copy()

    column_to_find_values = "VOC rolling average"
    sensors = particular_experiment["sensors"].unique()

    for sensor in sensors:
        mask = particular_experiment["sensors"]==sensor

        quantile_number = 0.9
        colunn_to_create = create_column_quantile(userInputData,sensor,quantile_number,column_to_find_values)
    
        userInputData.at[index, colunn_to_create] = particular_experiment.loc[mask,column_to_find_values].quantile(quantile_number)

        quantile_number = 0.99
        colunn_to_create = create_column_quantile(userInputData,sensor,quantile_number,column_to_find_values)
    
        userInputData.at[index, colunn_to_create] = particular_experiment.loc[mask,column_to_find_values].quantile(quantile_number)


        
    dict_of_timeseries[index]  =   particular_experiment

C:\Users\Andreas\AppData\Local\Temp\ipykernel_11096\1746646411.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  userInputData[colunn_to_create] = np.nan
C:\Users\Andreas\AppData\Local\Temp\ipykernel_11096\1746646411.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  userInputData[colunn_to_create] = np.nan
C:\Users\Andreas\AppData\Local\Temp\ipykernel_11096\1746646411.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  userInputData[colunn_to_create] = np.nan
C:\Users\Andreas\AppData\Local\Temp\ipykernel_11096\1746646411.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  userInputData[colunn_to_create] = np.nan
C:\Users\Andreas\AppData\Local\Temp\ipykernel_11096\1746646411.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  userInputData[colunn_to_create] = np.nan
C:\Users\Andreas\AppData\Local\Temp\ipykernel_11096\1746646411.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  userInputData[colunn_to_create] = np.nan

In [63]:
#FIND 90% quantile and 99% quantile not yet use at capping values
#find quantile per experiment
def create_column_quantile(userInputData,sensor,quantile_number,column_to_find_values):
    colunn_to_create = f"{sensor} quantile {quantile_number * 100}% {column_to_find_values}"    
    if colunn_to_create not in userInputData.columns:
        userInputData[colunn_to_create] = np.nan
    return colunn_to_create

    
for index, row in userInputData.iterrows():
    particular_experiment =  dict_of_timeseries[index].copy()

    column_to_find_values = "VOC rolling average"
    sensor = "whole experiment"


    quantile_number = 0.9
    colunn_to_create = create_column_quantile(userInputData,sensor,quantile_number,column_to_find_values)

    userInputData.at[index, colunn_to_create] = particular_experiment.loc[:,column_to_find_values].quantile(quantile_number)

    quantile_number = 0.99
    colunn_to_create = create_column_quantile(userInputData,sensor,quantile_number,column_to_find_values)

    userInputData.at[index, colunn_to_create] = particular_experiment.loc[:,column_to_find_values].quantile(quantile_number)


        
    dict_of_timeseries[index]  =   particular_experiment

C:\Users\Andreas\AppData\Local\Temp\ipykernel_11096\1476829008.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  userInputData[colunn_to_create] = np.nan
C:\Users\Andreas\AppData\Local\Temp\ipykernel_11096\1476829008.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  userInputData[colunn_to_create] = np.nan

In [64]:
userInputData

,experimentState,are-doors-opened,are-people-inside,are-windows-opened,front-wall,item-used,notes,room,side-right-wall,back-wall,side-left-wall,are-fans-on,no-source-located,timestamp InsertingSource,timestamp StartingExperiment,timestamp EndingExperiment,date of experiment,actual timestamp StartingExperiment,actual timestamp EndingExperiment,time taken total,timestamp InsertingSource timedelta,timestamp InsertingSource seconds,time taken after insertion,time taken before insertion,time taken before insertion (seconds),time taken after insertion (seconds),time taken total (seconds),time taken total (seconds)-capped,time taken before insertion (seconds)-capped,time taken after insertion (seconds)-capped,Id=1:BME680:breathVocEquivalent MAX value VOC rolling average,Id=1:BME680:breathVocEquivalent index of MAX value VOC rolling average,Id=2:BME680:breathVocEquivalent MAX value VOC rolling average,Id=2:BME680:breathVocEquivalent index of MAX value VOC rolling average,Id=0:BME680:breathVocEquivalent MAX value VOC rolling average,Id=0:BME680:breathVocEquivalent index of MAX value VOC rolling average,sensor with MAX value experiment,sensor with second MAX value experiment,Id=1:BME680:breathVocEquivalent quantile 90.0% VOC rolling average,Id=1:BME680:breathVocEquivalent quantile 99.0% VOC rolling average,Id=2:BME680:breathVocEquivalent quantile 90.0% VOC rolling average,Id=2:BME680:breathVocEquivalent quantile 99.0% VOC rolling average,Id=0:BME680:breathVocEquivalent quantile 90.0% VOC rolling average,Id=0:BME680:breathVocEquivalent quantile 99.0% VOC rolling average,whole experiment quantile 90.0% VOC rolling average,whole experiment quantile 99.0% VOC rolling average
0,InsertingSourcePollutant,on,None,None,1.0,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.0,None,None,2025-07-01 16:09:41,2025-07-01 15:27:16,2025-07-01 16:14:44,2025-07-01,2025-07-01 15:27:19,2025-07-01 16:14:42,0 days 00:47:23,0 days 00:42:23,2543.0,0 days 00:05:00,0 days 00:42:23,2543.0,300.0,2843.0,270.0,-30.0,299.0,4.3501,299.0,8.1928,243.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,4.10260,4.342653,8.13641,8.191397,NaN,NaN,8.03289,8.186653
1,InsertingSourcePollutant,on,None,None,1.0,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.0,None,None,2025-07-02 15:59:29,2025-07-02 15:42:50,2025-07-02 16:04:52,2025-07-02,2025-07-02 15:42:50,2025-07-02 16:04:50,0 days 00:22:00,0 days 00:16:40,1000.0,0 days 00:05:20,0 days 00:16:40,1000.0,320.0,1320.0,270.0,-30.0,299.0,1.1333,201.0,0.3304,80.0,NaN,NaN,Id=1:BME680:breathVocEquivalent MAX value VOC ...,Id=2:BME680:breathVocEquivalent MAX value VOC ...,0.96260,1.130830,0.30518,0.330042,NaN,NaN,0.74384,1.123456
2,InsertingSourcePollutant,on,None,None,0.4,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.0,None,None,2025-07-03 12:34:32,2025-07-03 12:30:25,2025-07-03 12:45:31,2025-07-03,2025-07-03 12:30:25,2025-07-03 12:45:31,0 days 00:15:06,0 days 00:04:08,248.0,0 days 00:10:58,0 days 00:04:08,248.0,658.0,906.0,270.0,-30.0,299.0,1.3923,235.0,2.2994,299.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,1.34093,1.390726,1.62716,2.182643,NaN,NaN,1.46438,2.073907
3,InsertingSourcePollutant,on,None,None,1.0,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.8,None,None,2025-07-03 15:53:07,2025-07-03 15:43:27,2025-07-03 15:59:11,2025-07-03,2025-07-03 15:51:40,2025-07-03 15:59:10,0 days 00:07:30,0 days 00:01:28,88.0,0 days 00:06:02,0 days 00:01:28,88.0,362.0,450.0,270.0,-30.0,299.0,0.3439,299.0,18.4943,299.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.26763,0.334346,16.09553,17.771554,NaN,NaN,6.84825,17.295804
4,InsertingSourcePollutant,on,None,None,1.4,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.4,None,None,2025-07-09 19:19:19,2025-07-09 19:01:42,2025-07-09 19:27:50,2025-07-09,2025-07-09 19:01:44,2025-07-09 19:27:49,0 days 00:26:05,0 days 00:17:36,1056.0,0 days 00:08:29,0 days 00:17:36,1056.0,509.0,1565.0,270.0,-30.0,299.0,0.6066,246.0,0.7315,299.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.58644,0.606300,0.70629,0.726681,NaN,NaN,0.62712,0.723846
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
254,InsertingSourcePollutant,None,None,None,0.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",0.5,NaN,NaN,None,None,2025-10-24 20:32:03,2025-10-24 20:29:36,2025-10-24 20:37:33,2025-10-24,2025-10-24 20:29:37,2025-10-24 20:37:31,0 days 00:07:54,0 days 00:02:27,147.0,0 days 00:05:27,0 days 00:02:27,147.0,327.0,474.0,270.0,-30.0,299.0,2.0134,131.0,4.9923,299.0,2.8096,286.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=0:BME680:breathVocEquivalent MAX value VOC ...,1.85013,2.010252,4.58879,4.944112,2.74257,2.806868,3.70824,4.844487
255,InsertingSourcePollutant,None,None,None,0.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:05:46,2025-10-24 21:03:22,2025-10-24 21:11:21,2025-10-24,2025-10-24 21:03:24,2025-10-24 21:11:19,0 days 00:07:55,0 days 00:02:23,143.0,0 days 00:05:32,0 days 00:02:23,143.0,332.0,475.0,270.0,-30.0,299.0,1.5436,269.0,6.0745,299.0,2.4431,236.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=0:BME680:breathVocEquivalent MAX value VOC ...,1.50536,1.541913,4.53166,5.938517,2.38429,2.439926,3.22484,5.639461
256,InsertingSourcePollutant,None,None,None,1.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:18:43,2025-10-24 21:17:10,2025-10-24 21:24:48,2025-10-24,2025-10-24 21:17:12,2025-10-24 21:24:46,0 days 00:07:34,0 days 00:01:32,92.0,0 days 00:06:02,0 days 00:01:32,92.0,362.0,454.0,270.0,-30.0,299.0,2.0029,299.0,13.3480,277.0,2.0105,141.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=0:BME680:breathVocEquivalent MAX value VOC ...,1.27778,1.931717,13.17579,13.337491,1.89556,2.009913,10.16265,13.288696
257,InsertingSourcePollutant,None,None,None,2.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:34:58,2025-10-24 21:33:44,2025-10-24 21:41:06,2025-10-24,2025-10-24 21:33:46,2025-10-24 21:41:04,0 days 00:07:18,0 days 00:01:13,73.0,0 days 00:06:05,0 days 00:01:13,73.0,365.0,438.0,270.0,-30.0,299.0,1.8114,299.0,7.5793,261.0,1.2671,299.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,1.71769,1.786738,7.36787,7.576884,1.24307,1.262000,6.72750,7.545522
258,InsertingSourcePollutant,None,None,None,3.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:54:05,2025-10-24 21:52:16,2025-10-24 22:01:25,2025-10-24,2025-10-24 21:52:18,2025-10-24 22:01:24,0 days 00:09:06,0 days 00:01:48,108.0,0 days 00:07:18,0 days 00:01:48,108.0,438.0,546.0,270.0,-30.0,299.0,1.6312,213.0,3.3710,287.0,2.1139,299.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=0:BME680:breathVocEquivalent MAX value VOC ...,1.57461,1.630197,3.24331,3.369713,1.76254,2.072233,2.77298,3.363343

In [65]:
userInputData.head(20)

,experimentState,are-doors-opened,are-people-inside,are-windows-opened,front-wall,item-used,notes,room,side-right-wall,back-wall,side-left-wall,are-fans-on,no-source-located,timestamp InsertingSource,timestamp StartingExperiment,timestamp EndingExperiment,date of experiment,actual timestamp StartingExperiment,actual timestamp EndingExperiment,time taken total,timestamp InsertingSource timedelta,timestamp InsertingSource seconds,time taken after insertion,time taken before insertion,time taken before insertion (seconds),time taken after insertion (seconds),time taken total (seconds),time taken total (seconds)-capped,time taken before insertion (seconds)-capped,time taken after insertion (seconds)-capped,Id=1:BME680:breathVocEquivalent MAX value VOC rolling average,Id=1:BME680:breathVocEquivalent index of MAX value VOC rolling average,Id=2:BME680:breathVocEquivalent MAX value VOC rolling average,Id=2:BME680:breathVocEquivalent index of MAX value VOC rolling average,Id=0:BME680:breathVocEquivalent MAX value VOC rolling average,Id=0:BME680:breathVocEquivalent index of MAX value VOC rolling average,sensor with MAX value experiment,sensor with second MAX value experiment,Id=1:BME680:breathVocEquivalent quantile 90.0% VOC rolling average,Id=1:BME680:breathVocEquivalent quantile 99.0% VOC rolling average,Id=2:BME680:breathVocEquivalent quantile 90.0% VOC rolling average,Id=2:BME680:breathVocEquivalent quantile 99.0% VOC rolling average,Id=0:BME680:breathVocEquivalent quantile 90.0% VOC rolling average,Id=0:BME680:breathVocEquivalent quantile 99.0% VOC rolling average,whole experiment quantile 90.0% VOC rolling average,whole experiment quantile 99.0% VOC rolling average
0,InsertingSourcePollutant,on,None,None,1.0,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.0,None,None,2025-07-01 16:09:41,2025-07-01 15:27:16,2025-07-01 16:14:44,2025-07-01,2025-07-01 15:27:19,2025-07-01 16:14:42,0 days 00:47:23,0 days 00:42:23,2543.0,0 days 00:05:00,0 days 00:42:23,2543.0,300.0,2843.0,270.0,-30.0,299.0,4.3501,299.0,8.1928,243.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,4.10260,4.342653,8.13641,8.191397,NaN,NaN,8.03289,8.186653
1,InsertingSourcePollutant,on,None,None,1.0,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.0,None,None,2025-07-02 15:59:29,2025-07-02 15:42:50,2025-07-02 16:04:52,2025-07-02,2025-07-02 15:42:50,2025-07-02 16:04:50,0 days 00:22:00,0 days 00:16:40,1000.0,0 days 00:05:20,0 days 00:16:40,1000.0,320.0,1320.0,270.0,-30.0,299.0,1.1333,201.0,0.3304,80.0,NaN,NaN,Id=1:BME680:breathVocEquivalent MAX value VOC ...,Id=2:BME680:breathVocEquivalent MAX value VOC ...,0.96260,1.130830,0.30518,0.330042,NaN,NaN,0.74384,1.123456
2,InsertingSourcePollutant,on,None,None,0.4,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.0,None,None,2025-07-03 12:34:32,2025-07-03 12:30:25,2025-07-03 12:45:31,2025-07-03,2025-07-03 12:30:25,2025-07-03 12:45:31,0 days 00:15:06,0 days 00:04:08,248.0,0 days 00:10:58,0 days 00:04:08,248.0,658.0,906.0,270.0,-30.0,299.0,1.3923,235.0,2.2994,299.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,1.34093,1.390726,1.62716,2.182643,NaN,NaN,1.46438,2.073907
3,InsertingSourcePollutant,on,None,None,1.0,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.8,None,None,2025-07-03 15:53:07,2025-07-03 15:43:27,2025-07-03 15:59:11,2025-07-03,2025-07-03 15:51:40,2025-07-03 15:59:10,0 days 00:07:30,0 days 00:01:28,88.0,0 days 00:06:02,0 days 00:01:28,88.0,362.0,450.0,270.0,-30.0,299.0,0.3439,299.0,18.4943,299.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.26763,0.334346,16.09553,17.771554,NaN,NaN,6.84825,17.295804
4,InsertingSourcePollutant,on,None,None,1.4,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.4,None,None,2025-07-09 19:19:19,2025-07-09 19:01:42,2025-07-09 19:27:50,2025-07-09,2025-07-09 19:01:44,2025-07-09 19:27:49,0 days 00:26:05,0 days 00:17:36,1056.0,0 days 00:08:29,0 days 00:17:36,1056.0,509.0,1565.0,270.0,-30.0,299.0,0.6066,246.0,0.7315,299.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.58644,0.606300,0.70629,0.726681,NaN,NaN,0.62712,0.723846
5,InsertingSourcePollutant,None,None,None,1.0,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.8,None,None,2025-07-12 22:57:57,2025-07-12 22:31:25,2025-07-12 23:02:13,2025-07-12,2025-07-12 22:34:03,2025-07-12 23:02:11,0 days 00:28:08,0 days 00:23:55,1435.0,0 days 00:04:13,0 days 00:23:55,1435.0,253.0,1688.0,224.0,-30.0,253.0,0.1809,-30.0,0.8368,253.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.13562,0.176638,0.71555,0.822997,NaN,NaN,0.65977,0.812321
7,InsertingSourcePollutant,on,on,None,1.8,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,None,None,2025-07-19 15:04:09,2025-07-19 14:59:47,2025-07-19 15:08:10,2025-07-19,2025-07-19 14:59:49,2025-07-19 15:08:09,0 days 00:08:20,0 days 00:04:21,261.0,0 days 00:03:59,0 days 00:04:21,261.0,239.0,500.0,210.0,-30.0,239.0,0.2081,-30.0,0.5084,172.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.16252,0.206555,0.50321,0.508331,NaN,NaN,0.48965,0.508061
8,InsertingSourcePollutant,on,on,None,1.8,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,None,None,2025-07-19 15:17:10,2025-07-19 15:14:13,2025-07-19 15:21:23,2025-07-19,2025-07-19 15:14:15,2025-07-19 15:21:21,0 days 00:07:06,0 days 00:02:56,176.0,0 days 00:04:10,0 days 00:02:56,176.0,250.0,426.0,221.0,-30.0,250.0,0.3916,250.0,1.0680,250.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.36040,0.390020,0.91140,1.058680,NaN,NaN,0.74541,1.046716
9,InsertingSourcePollutant,on,on,None,1.8,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,None,None,2025-07-19 15:30:49,2025-07-19 15:25:07,2025-07-19 15:44:28,2025-07-19,2025-07-19 15:25:09,2025-07-19 15:44:27,0 days 00:19:18,0 days 00:05:41,341.0,0 days 00:13:37,0 days 00:05:41,341.0,817.0,1158.0,270.0,-30.0,299.0,1.4493,299.0,1.0056,299.0,NaN,NaN,Id=1:BME680:breathVocEquivalent MAX value VOC ...,Id=2:BME680:breathVocEquivalent MAX value VOC ...,1.11083,1.416626,0.71620,0.989721,NaN,NaN,0.94604,1.379992
10,InsertingSourcePollutant,on,on,None,1.8,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,None,None,2025-07-19 16:12:54,2025-07-19 16:04:22,2025-07-19 16:21:55,2025-07-19,2025-07-19 16:04:24,2025-07-19 16:21:54,0 days 00:17:30,0 days 00:08:31,511.0,0 days 00:08:59,0 days 00:08:31,511.0,539.0,1050.0,270.0,-30.0,299.0,1.7484,299.0,2.9637,299.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,1.51517,1.732250,2.37971,2.913531,NaN,NaN,1.74426,2.858929
11,InsertingSourcePollutant,on,on,None,1.8,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,None,None,2025-07-19 16:46:45,2025-07-19 16:36:03,2025-07-19 16:54:19,2025-07-19,2025-07-19 16:36:04,2025-07-19 16:54:18,0 days 00:18:14,0 days 00:10:42,642.0,0 days 00:07:32,0 days 00:10:42,642.0,452.0,1094.0,270.0,-30.0,299.0,1.4246,299.0,2.5592,299.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,1.26407,1.405492,2.05864,2.503834,NaN,NaN,1.68727,2.451024
12,InsertingSourcePollutant,on,on,None,1.8,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,None,None,2025-07-19 17:25:36,2025-07-19 17:05:51,2025-07-19 17:35:58,2025-07-19,2025-07-19 17:05:52,2025-07-19 17:35:57,0 days 00:30:05,0 days 00:19:45,1185.0,0 days 00:10:20,0 days 00:19:45,1185.0,620.0,1805.0,270.0,-30.0,299.0,1.9219,299.0,2.0172,299.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,1.82505,1.911130,1.74210,1.975220,NaN,NaN,1.80769,1.938423
13,InsertingSourcePollutant,on,None,None,1.8,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,None,None,2025-07-20 13:46:03,2025-07-20 13:36:41,2025-07-20 14:48:43,2025-07-20,2025-07-20 13:36:42,2025-07-20 14:48:41,0 days 01:11:59,0 days 00:09:22,562.0,0 days 01:02:37,0 days 00:09:22,562.0,3757.0,4319.0,270.0,-30.0,299.0,0.1910,261.0,0.2598,160.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.18540,0.190900,0.24836,0.259642,NaN,NaN,0.23963,0.259123
14,InsertingSourcePollutant,on,on,None,1.8,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,None,None,2025-07-20 15:15:34,2025-07-20 15:04:15,2025-07-20 15:39:22,2025-07-20,2025-07-20 15:04:17,2025-07-20 15:39:20,0 days 00:35:03,0 days 00:11:18,678.0,0 days 00:23:45,0 days 00:11:18,678.0,1425.0,2103.0,270.0,-30.0,299.0,0.2931,175.0,0.8709,299.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.28710,0.292871,0.72066,0.850215,NaN,NaN,0.56797,0.829301
15,InsertingSourcePollutant,on,on,None,1.8,Φαρμακευτικό αλκοόλ 95%,ανεμιστήρας,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,None,None,2025-07-20 15:52:33,2025-07-20 15:47:36,2025-07-20 16:08:05,2025-07-20,2025-07-20 15:47:38,2025-07-20 16:08:03,0 days 00:20:25,0 days 00:04:56,296.0,0 days 00:15:29,0 days 00:04:56,296.0,929.0,1225.0,270.0,-30.0,299.0,1.1745,299.0,0.8673,299.0,NaN,NaN,Id=1:BME680:breathVocEquivalent MAX value VOC ...,Id=2:BME680:breathVocEquivalent MAX value VOC ...,1.02663,1.158366,0.74384,0.852895,NaN,NaN,0.85985,1.144658
16,InsertingSourcePollutant,on,None,None,1.8,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,None,None,2025-07-20 16:34:39,2025-07-20 16:20:42,2025-07-20 16:43:55,2025-07-20,2025-07-20 16:20:44,2025-07-20 16:43:54,0 days 00:23:10,0 days 00:13:56,836.0,0 days 00:09:14,0 days 00:13:56,836.0,554.0,1390.0,270.0,-30.0,299.0,0.2088,284.0,0.3477,299.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.18658,0.208113,0.22651,0.331650,NaN,NaN,0.20391,0.316304
17,InsertingSourcePollutant,on,on,None,1.8,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,None,None,2025-07-20 18:13:07,2025-07-20 18:04:08,2025-07-20 18:22:22,2025-07-20,2025-07-20 18:04:10,2025-07-20 18:22:20,0 days 00:18:10,0 days 00:08:58,538.0,0 days 00:09:12,0 days 00:08:58,538.0,552.0,1090.0,270.0,-30.0,299.0,0.5649,299.0,0.8142,233.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.54597,0.562797,0.81210,0.813800,NaN,NaN,0.79987,0.813700
18,InsertingSourcePollutant,on,on,on,1.8,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,None,None,2025-07-20 18:31:41,2025-07-20 18:29:19,2025-07-20 18:40:12,2025-07-20,2025-07-20 18:29:21,2025-07-20 18:40:11,0 days 00:10:50,0 days 00:02:21,141.0,0 days 00:08:29,0 days 00:02:21,141.0,509.0,650.0,270.0,-30.0,299.0,0.0323,286.0,0.0264,151.0,NaN,NaN,Id=1:BME680:breathVocEquivalent MAX value VOC ...,Id=2:BME680:breathVocEquivalent MAX value VOC ...,0.02656,0.032100,0.02451,0.026300,NaN,NaN,0.02491,0.031800
19,InsertingSourcePollutant,on,on,None,1.8,Φαρμακευτικό αλκοόλ 95%,ανεμιστήρας,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,None,None,2025-07-20 18:47:26,2025-07-20 18:41:09,2025-07-20 19:00:09,2025-07-20,2025-07-20 18:41:11,2025-07-20 19:00:08,0 days 00:18:57,0 days 00:06:16,376.0,0 days 00:12:41,0 days 00:06:16,376.0,761.0,1137.0,270.0,-30.0,299.0,0.8626,299.0,1.2647,299.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.72151,0.848053,1.05549,1.246331,NaN,NaN,0.87314,1.226460
20,InsertingSourcePollutant,on,on,None,1.8,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,None,None,2025-07-20 19:15:51,2025-07-20 19:13:35,2025-07-20 19:23:44,2025-07-20,2025-07-20 19:13:36,2025-07-20 19:23:42,0 days 00:10:06,0 days 00:02:16,136.0,0 days 00:07:50,0 days 00:02:16,136.0,470.0,606.0,270.0,-30.0,299.0,0.1315,299.0,0.5513,149.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.11160,0.129326,0.54472,0.550871,NaN,NaN,0.54041,0.550082

In [66]:
#cap by max value 
offset_to_increase_capped = 5
for index, row in userInputData.iterrows():
    
    particular_experiment =  dict_of_timeseries[index].copy()
    colunn_to_create = "VOC-capped"
    if colunn_to_create not in userInputData.columns:
        particular_experiment[colunn_to_create] = np.nan
        
    max_sensor = row["sensor with MAX value experiment"]

    max_sensor = max_sensor.split()[0]

    max_sensor_column_name = f"{max_sensor} MAX value VOC rolling average"
    max_value = row[max_sensor_column_name]
    
    second_max_sensor = row["sensor with second MAX value experiment"].split()[0]
    
    second_max_sensor_column_name = f"{second_max_sensor} MAX value VOC rolling average"
    second_max_value = row[second_max_sensor_column_name]  
    value_to_cap_into =  5  + second_max_value
   
        
    for sensor in sensors:
        mask = particular_experiment["sensors"]==sensor
        particular_experiment.loc[mask,colunn_to_create] = particular_experiment.loc[mask,"VOC"]

        if (sensor == max_sensor):
            full_mask = mask & (particular_experiment["VOC"]> value_to_cap_into)
            particular_experiment.loc[full_mask,colunn_to_create] = value_to_cap_into
        
    dict_of_timeseries[index]  =   particular_experiment

In [67]:
#cap by max value 
offset_to_increase_capped = 5
for index, row in userInputData.iterrows():
    
    particular_experiment =  dict_of_timeseries[index].copy()
    colunn_to_create = "VOC rolling average-capped"
    if colunn_to_create not in userInputData.columns:
        particular_experiment[colunn_to_create] = np.nan
        
    max_sensor = row["sensor with MAX value experiment"]

    max_sensor = max_sensor.split()[0]

    max_sensor_column_name = f"{max_sensor} MAX value VOC rolling average"
    max_value = row[max_sensor_column_name]
    
    second_max_sensor = row["sensor with second MAX value experiment"].split()[0]
    
    second_max_sensor_column_name = f"{second_max_sensor} MAX value VOC rolling average"
    second_max_value = row[second_max_sensor_column_name]  
    value_to_cap_into =  5  + second_max_value
   
        
    for sensor in sensors:
        mask = particular_experiment["sensors"]==sensor
        particular_experiment.loc[mask,colunn_to_create] = particular_experiment.loc[mask,"VOC rolling average"]

        if (sensor == max_sensor):
            full_mask = mask & (particular_experiment["VOC rolling average"]> value_to_cap_into)
            particular_experiment.loc[full_mask,colunn_to_create] = value_to_cap_into
        
    dict_of_timeseries[index]  =   particular_experiment

In [68]:
for index, row in userInputData.iterrows():
    particular_experiment =  dict_of_timeseries[index].copy()
    sensors = particular_experiment["sensors"].unique()

    for sensor in sensors:
        mask = particular_experiment["sensors"]==sensor
        column_to_create = "VOC gradient"
        if column_to_create not in particular_experiment.columns:
            particular_experiment.loc[:,column_to_create] = np.nan
        particular_experiment.loc[mask,column_to_create] = np.gradient(particular_experiment.loc[mask,"VOC rolling average"].to_numpy())
        
        
        mask = particular_experiment["sensors"]==sensor
        column_to_create = "VOC rolling average gradient"
        if column_to_create not in particular_experiment.columns:
            particular_experiment.loc[:,column_to_create] = np.nan
        particular_experiment.loc[mask,column_to_create] = np.gradient(particular_experiment.loc[mask,"VOC rolling average"].to_numpy())
        
        # column_to_create = "VOC rolling average-capped gradient"
        # if column_to_create not in particular_experiment.columns:
        #     particular_experiment.loc[:,column_to_create] = np.nan
        #particular_experiment.loc[mask,column_to_create] = np.gradient(particular_experiment.loc[mask,"VOC rolling average-capped"].to_numpy())

    dict_of_timeseries[index] = particular_experiment

In [69]:
userInputData

,experimentState,are-doors-opened,are-people-inside,are-windows-opened,front-wall,item-used,notes,room,side-right-wall,back-wall,side-left-wall,are-fans-on,no-source-located,timestamp InsertingSource,timestamp StartingExperiment,timestamp EndingExperiment,date of experiment,actual timestamp StartingExperiment,actual timestamp EndingExperiment,time taken total,timestamp InsertingSource timedelta,timestamp InsertingSource seconds,time taken after insertion,time taken before insertion,time taken before insertion (seconds),time taken after insertion (seconds),time taken total (seconds),time taken total (seconds)-capped,time taken before insertion (seconds)-capped,time taken after insertion (seconds)-capped,Id=1:BME680:breathVocEquivalent MAX value VOC rolling average,Id=1:BME680:breathVocEquivalent index of MAX value VOC rolling average,Id=2:BME680:breathVocEquivalent MAX value VOC rolling average,Id=2:BME680:breathVocEquivalent index of MAX value VOC rolling average,Id=0:BME680:breathVocEquivalent MAX value VOC rolling average,Id=0:BME680:breathVocEquivalent index of MAX value VOC rolling average,sensor with MAX value experiment,sensor with second MAX value experiment,Id=1:BME680:breathVocEquivalent quantile 90.0% VOC rolling average,Id=1:BME680:breathVocEquivalent quantile 99.0% VOC rolling average,Id=2:BME680:breathVocEquivalent quantile 90.0% VOC rolling average,Id=2:BME680:breathVocEquivalent quantile 99.0% VOC rolling average,Id=0:BME680:breathVocEquivalent quantile 90.0% VOC rolling average,Id=0:BME680:breathVocEquivalent quantile 99.0% VOC rolling average,whole experiment quantile 90.0% VOC rolling average,whole experiment quantile 99.0% VOC rolling average
0,InsertingSourcePollutant,on,None,None,1.0,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.0,None,None,2025-07-01 16:09:41,2025-07-01 15:27:16,2025-07-01 16:14:44,2025-07-01,2025-07-01 15:27:19,2025-07-01 16:14:42,0 days 00:47:23,0 days 00:42:23,2543.0,0 days 00:05:00,0 days 00:42:23,2543.0,300.0,2843.0,270.0,-30.0,299.0,4.3501,299.0,8.1928,243.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,4.10260,4.342653,8.13641,8.191397,NaN,NaN,8.03289,8.186653
1,InsertingSourcePollutant,on,None,None,1.0,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.0,None,None,2025-07-02 15:59:29,2025-07-02 15:42:50,2025-07-02 16:04:52,2025-07-02,2025-07-02 15:42:50,2025-07-02 16:04:50,0 days 00:22:00,0 days 00:16:40,1000.0,0 days 00:05:20,0 days 00:16:40,1000.0,320.0,1320.0,270.0,-30.0,299.0,1.1333,201.0,0.3304,80.0,NaN,NaN,Id=1:BME680:breathVocEquivalent MAX value VOC ...,Id=2:BME680:breathVocEquivalent MAX value VOC ...,0.96260,1.130830,0.30518,0.330042,NaN,NaN,0.74384,1.123456
2,InsertingSourcePollutant,on,None,None,0.4,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.0,None,None,2025-07-03 12:34:32,2025-07-03 12:30:25,2025-07-03 12:45:31,2025-07-03,2025-07-03 12:30:25,2025-07-03 12:45:31,0 days 00:15:06,0 days 00:04:08,248.0,0 days 00:10:58,0 days 00:04:08,248.0,658.0,906.0,270.0,-30.0,299.0,1.3923,235.0,2.2994,299.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,1.34093,1.390726,1.62716,2.182643,NaN,NaN,1.46438,2.073907
3,InsertingSourcePollutant,on,None,None,1.0,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.8,None,None,2025-07-03 15:53:07,2025-07-03 15:43:27,2025-07-03 15:59:11,2025-07-03,2025-07-03 15:51:40,2025-07-03 15:59:10,0 days 00:07:30,0 days 00:01:28,88.0,0 days 00:06:02,0 days 00:01:28,88.0,362.0,450.0,270.0,-30.0,299.0,0.3439,299.0,18.4943,299.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.26763,0.334346,16.09553,17.771554,NaN,NaN,6.84825,17.295804
4,InsertingSourcePollutant,on,None,None,1.4,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.4,None,None,2025-07-09 19:19:19,2025-07-09 19:01:42,2025-07-09 19:27:50,2025-07-09,2025-07-09 19:01:44,2025-07-09 19:27:49,0 days 00:26:05,0 days 00:17:36,1056.0,0 days 00:08:29,0 days 00:17:36,1056.0,509.0,1565.0,270.0,-30.0,299.0,0.6066,246.0,0.7315,299.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.58644,0.606300,0.70629,0.726681,NaN,NaN,0.62712,0.723846
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
254,InsertingSourcePollutant,None,None,None,0.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",0.5,NaN,NaN,None,None,2025-10-24 20:32:03,2025-10-24 20:29:36,2025-10-24 20:37:33,2025-10-24,2025-10-24 20:29:37,2025-10-24 20:37:31,0 days 00:07:54,0 days 00:02:27,147.0,0 days 00:05:27,0 days 00:02:27,147.0,327.0,474.0,270.0,-30.0,299.0,2.0134,131.0,4.9923,299.0,2.8096,286.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=0:BME680:breathVocEquivalent MAX value VOC ...,1.85013,2.010252,4.58879,4.944112,2.74257,2.806868,3.70824,4.844487
255,InsertingSourcePollutant,None,None,None,0.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:05:46,2025-10-24 21:03:22,2025-10-24 21:11:21,2025-10-24,2025-10-24 21:03:24,2025-10-24 21:11:19,0 days 00:07:55,0 days 00:02:23,143.0,0 days 00:05:32,0 days 00:02:23,143.0,332.0,475.0,270.0,-30.0,299.0,1.5436,269.0,6.0745,299.0,2.4431,236.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=0:BME680:breathVocEquivalent MAX value VOC ...,1.50536,1.541913,4.53166,5.938517,2.38429,2.439926,3.22484,5.639461
256,InsertingSourcePollutant,None,None,None,1.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:18:43,2025-10-24 21:17:10,2025-10-24 21:24:48,2025-10-24,2025-10-24 21:17:12,2025-10-24 21:24:46,0 days 00:07:34,0 days 00:01:32,92.0,0 days 00:06:02,0 days 00:01:32,92.0,362.0,454.0,270.0,-30.0,299.0,2.0029,299.0,13.3480,277.0,2.0105,141.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=0:BME680:breathVocEquivalent MAX value VOC ...,1.27778,1.931717,13.17579,13.337491,1.89556,2.009913,10.16265,13.288696
257,InsertingSourcePollutant,None,None,None,2.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:34:58,2025-10-24 21:33:44,2025-10-24 21:41:06,2025-10-24,2025-10-24 21:33:46,2025-10-24 21:41:04,0 days 00:07:18,0 days 00:01:13,73.0,0 days 00:06:05,0 days 00:01:13,73.0,365.0,438.0,270.0,-30.0,299.0,1.8114,299.0,7.5793,261.0,1.2671,299.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,1.71769,1.786738,7.36787,7.576884,1.24307,1.262000,6.72750,7.545522
258,InsertingSourcePollutant,None,None,None,3.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:54:05,2025-10-24 21:52:16,2025-10-24 22:01:25,2025-10-24,2025-10-24 21:52:18,2025-10-24 22:01:24,0 days 00:09:06,0 days 00:01:48,108.0,0 days 00:07:18,0 days 00:01:48,108.0,438.0,546.0,270.0,-30.0,299.0,1.6312,213.0,3.3710,287.0,2.1139,299.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=0:BME680:breathVocEquivalent MAX value VOC ...,1.57461,1.630197,3.24331,3.369713,1.76254,2.072233,2.77298,3.363343

In [70]:
#find the VOC values and gradient mean in calm periods,both in NoSourcePollutantInserted and before insertion source
for index, row in userInputData.iterrows():
    particular_experiment =  dict_of_timeseries[index].copy()
    sensors = particular_experiment["sensors"].unique()

    for sensor in sensors:
        mask = particular_experiment["sensors"]==sensor
        #if the experiment had a pollutant source, grab only the rows with negative seconds
        if userInputData.at[index,"experimentState"] == "InsertingSourcePollutant":
            mask = mask & (particular_experiment["seconds"]<0)
            
        column_to_use = "VOC"  
        column_to_insert = f"{sensor} {column_to_use} mean calm period"
        if column_to_insert not in userInputData.columns:
            userInputData[column_to_insert] = np.nan
        userInputData.at[index,column_to_insert] = particular_experiment.loc[mask,column_to_use].mean()
        
        column_to_use = "VOC gradient"  
        column_to_insert = f"{sensor} {column_to_use} mean calm period"
        if column_to_insert not in userInputData.columns:
            userInputData[column_to_insert] = np.nan
        userInputData.at[index,column_to_insert] = particular_experiment.loc[mask,column_to_use].mean()

C:\Users\Andreas\AppData\Local\Temp\ipykernel_11096\2493855348.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  userInputData[column_to_insert] = np.nan
C:\Users\Andreas\AppData\Local\Temp\ipykernel_11096\2493855348.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  userInputData[column_to_insert] = np.nan
C:\Users\Andreas\AppData\Local\Temp\ipykernel_11096\2493855348.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  userInputData[column_to_insert] = np.nan
C:\Users\Andreas\AppData\Local\Temp\ipykernel_11096\2493855348.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  userInputData[column_to_insert] = np.nan
C:\Users\Andreas\AppData\Local\Temp\ipykernel_11096\2493855348.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  userInputData[column_to_insert] = np.nan
C:\Users\Andreas\AppData\Local\Temp\ipykernel_11096\2493855348.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  userInputData[column_to_insert] = np.nan

In [71]:
#create standard scaler per experiment and per sensor, per VOC rolling average and VOC rolling average capped

In [72]:
#experiment
from sklearn.preprocessing import StandardScaler
def create_column_standard_scaler(particular_experiment,column_to_find_values):
    
    colunn_to_create = f"{column_to_find_values} standard scaler whole experiment"    
    if colunn_to_create not in particular_experiment.columns:
        particular_experiment[colunn_to_create] = np.nan
    return colunn_to_create
    
columns_to_find_values = ["VOC rolling average","VOC rolling average-capped"]

for column_to_find_values in columns_to_find_values:
    for index, row in userInputData.iterrows():
    
        particular_experiment =  dict_of_timeseries[index].copy()
        scaler = StandardScaler()
            
        colunn_to_create = create_column_standard_scaler(particular_experiment,column_to_find_values)
    
        particular_experiment.loc[:, colunn_to_create] = scaler.fit_transform((particular_experiment.loc[:,column_to_find_values].to_numpy().reshape(-1,1)))
    
        dict_of_timeseries[index]  =   particular_experiment

In [73]:
dict_of_timeseries[157]

,sensors,VOC,after_insertion,original_value,datetime_timestamp,timestamp,seconds,seconds passed from insertionSource,VOC original,VOC rolling average,original seconds,VOC-capped,VOC rolling average-capped,VOC gradient,VOC rolling average gradient,VOC rolling average standard scaler whole experiment,VOC rolling average-capped standard scaler whole experiment
seconds,,,,,,,,,,,,,,,,,
-30.0,Id=0:BME680:breathVocEquivalent,0.355,False,True,2025-10-13 22:27:17,0 days 00:01:05,-30.0,-30.0,1.804527,0.3536,65.0,0.355,0.3536,0.00040,0.00040,-0.922070,-0.922070
-30.0,Id=1:BME680:breathVocEquivalent,0.541,False,True,2025-10-13 22:27:17,0 days 00:01:05,-30.0,-30.0,2.451902,0.5263,65.0,0.541,0.5263,-0.00370,-0.00370,-0.740326,-0.740326
-30.0,Id=2:BME680:breathVocEquivalent,0.090,False,False,2025-10-13 22:27:17,0 days 00:01:05,-30.0,-30.0,1.284219,0.0887,65.0,0.090,0.0887,0.00080,0.00080,-1.200841,-1.200841
-29.0,Id=0:BME680:breathVocEquivalent,0.358,False,False,2025-10-13 22:27:18,0 days 00:01:06,-29.0,-29.0,1.807059,0.3540,66.0,0.358,0.3540,0.00055,0.00055,-0.921649,-0.921649
-29.0,Id=1:BME680:breathVocEquivalent,0.552,False,False,2025-10-13 22:27:18,0 days 00:01:06,-29.0,-29.0,2.462499,0.5226,66.0,0.552,0.5226,-0.00395,-0.00395,-0.744220,-0.744220
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298.0,Id=1:BME680:breathVocEquivalent,2.628,True,False,2025-10-13 22:32:45,0 days 00:06:33,298.0,298.0,4.538666,2.5994,393.0,2.628,2.5994,0.00820,0.00820,1.441331,1.441331
298.0,Id=2:BME680:breathVocEquivalent,3.599,True,True,2025-10-13 22:32:45,0 days 00:06:33,298.0,298.0,4.793872,3.5720,393.0,3.599,3.5720,0.08015,0.08015,2.464861,2.464861
299.0,Id=0:BME680:breathVocEquivalent,4.159,True,False,2025-10-13 22:32:46,0 days 00:06:34,299.0,299.0,5.607971,4.0315,394.0,4.159,4.0315,-0.00970,-0.00970,2.948423,2.948423
299.0,Id=1:BME680:breathVocEquivalent,2.643,True,False,2025-10-13 22:32:46,0 days 00:06:34,299.0,299.0,4.553225,2.6075,394.0,2.643,2.6075,0.00810,0.00810,1.449855,1.449855
299.0,Id=2:BME680:breathVocEquivalent,3.671,True,False,2025-10-13 22:32:46,0 days 00:06:34,299.0,299.0,4.865380,3.6532,394.0,3.671,3.6532,0.08120,0.08120,2.550313,2.550313

## CREATE THE RELEVANT INFORMATION FOR POSITION

### FIND X AND Y AXIS

In [74]:
room_length = 4.0
room_width = 3.25
userInputData["x axis"] = np.nan
userInputData["y axis"] = np.nan
#front is max,back is zero,right is max,left is zero
def find_x_axis(x,room_width):
    from_right = None
    from_left = None

    #return NaN either if numbers at the position columns are negative or above room width
    if (x["side-right-wall"]<0 and x["side-right-wall"]> room_width) or (x["side-left-wall"]< 0 and x["side-left-wall"]> room_width) or (pd.isna(x["side-right-wall"]) and pd.isna(x["side-left-wall"])):
        x["x axis"] = np.nan
        return x["x axis"] 
    if pd.notna(x["side-right-wall"]):
       from_right = -x["side-right-wall"]
    if pd.notna(x["side-left-wall"]):
       from_left = -room_width + x["side-left-wall"]
      
    if  from_right is not None and from_left is not None:
        if from_right == from_left:
            x["x axis"] = from_right
        else:
            x["x axis"] = np.nan
          

    elif pd.notna(x["side-left-wall"]):
    
        x["x axis"] = from_left

    elif pd.notna(x["side-right-wall"]):
        x["x axis"] = from_right
    return  x["x axis"]

def find_y_axis(x,room_length):
    from_front = None
    from_back = None

    #return NaN either if numbers at the position columns are negative or above room width
    if (x["front-wall"]<0 and x["front-wall"]> room_length) or (x["back-wall"]< 0 and x["back-wall"]> room_length) or (pd.isna(x["front-wall"]) and pd.isna(x["back-wall"])):
        x["y axis"] = np.nan
        return x["y axis"] 
    if pd.notna(x["front-wall"]):
       from_front = room_length - x["front-wall"]
    if pd.notna(x["back-wall"]):
       from_back = x["back-wall"]
    if from_front is not None and from_back is not None:
        if from_front == from_back:
            x["y axis"] = from_front
        else:
            x["y axis"] = np.nan
            
    elif pd.notna(x["back-wall"]):
    
        x["y axis"] = from_back

    elif pd.notna(x["front-wall"]):
        x["y axis"] = from_front

    return  x["y axis"]

userInputData["x axis"] = userInputData.apply(lambda x:find_x_axis(x,room_width),axis=1)
userInputData["y axis"] = userInputData.apply(lambda x:find_y_axis(x,room_length),axis=1)

C:\Users\Andreas\AppData\Local\Temp\ipykernel_11096\971905250.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  userInputData["x axis"] = np.nan
C:\Users\Andreas\AppData\Local\Temp\ipykernel_11096\971905250.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  userInputData["y axis"] = np.nan
C:\Users\Andreas\AppData\Local\Temp\ipykernel_11096\971905250.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  userInputData["x axis"] = userInputData.apply(lambda x:find_x_axis(x,room_width),axis=1)
C:\Users\Andreas\AppData\Local\Temp\ipykernel_11096\971905250.py:62: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  userInputData["y axis"] = userInputData.apply(lambda x:find_y_axis(x,room_length),axis=1)

In [75]:
userInputData.head(30)

,experimentState,are-doors-opened,are-people-inside,are-windows-opened,front-wall,item-used,notes,room,side-right-wall,back-wall,side-left-wall,are-fans-on,no-source-located,timestamp InsertingSource,timestamp StartingExperiment,timestamp EndingExperiment,date of experiment,actual timestamp StartingExperiment,actual timestamp EndingExperiment,time taken total,timestamp InsertingSource timedelta,timestamp InsertingSource seconds,time taken after insertion,time taken before insertion,time taken before insertion (seconds),time taken after insertion (seconds),time taken total (seconds),time taken total (seconds)-capped,time taken before insertion (seconds)-capped,time taken after insertion (seconds)-capped,Id=1:BME680:breathVocEquivalent MAX value VOC rolling average,Id=1:BME680:breathVocEquivalent index of MAX value VOC rolling average,Id=2:BME680:breathVocEquivalent MAX value VOC rolling average,Id=2:BME680:breathVocEquivalent index of MAX value VOC rolling average,Id=0:BME680:breathVocEquivalent MAX value VOC rolling average,Id=0:BME680:breathVocEquivalent index of MAX value VOC rolling average,sensor with MAX value experiment,sensor with second MAX value experiment,Id=1:BME680:breathVocEquivalent quantile 90.0% VOC rolling average,Id=1:BME680:breathVocEquivalent quantile 99.0% VOC rolling average,Id=2:BME680:breathVocEquivalent quantile 90.0% VOC rolling average,Id=2:BME680:breathVocEquivalent quantile 99.0% VOC rolling average,Id=0:BME680:breathVocEquivalent quantile 90.0% VOC rolling average,Id=0:BME680:breathVocEquivalent quantile 99.0% VOC rolling average,whole experiment quantile 90.0% VOC rolling average,whole experiment quantile 99.0% VOC rolling average,Id=1:BME680:breathVocEquivalent VOC mean calm period,Id=1:BME680:breathVocEquivalent VOC gradient mean calm period,Id=2:BME680:breathVocEquivalent VOC mean calm period,Id=2:BME680:breathVocEquivalent VOC gradient mean calm period,Id=0:BME680:breathVocEquivalent VOC mean calm period,Id=0:BME680:breathVocEquivalent VOC gradient mean calm period,x axis,y axis
0,InsertingSourcePollutant,on,None,None,1.0,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.0,None,None,2025-07-01 16:09:41,2025-07-01 15:27:16,2025-07-01 16:14:44,2025-07-01,2025-07-01 15:27:19,2025-07-01 16:14:42,0 days 00:47:23,0 days 00:42:23,2543.0,0 days 00:05:00,0 days 00:42:23,2543.0,300.0,2843.0,270.0,-30.0,299.0,4.3501,299.0,8.1928,243.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,4.10260,4.342653,8.13641,8.191397,NaN,NaN,8.03289,8.186653,1.338333,0.000302,5.003467,0.001410,NaN,NaN,-2.25,3.0
1,InsertingSourcePollutant,on,None,None,1.0,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.0,None,None,2025-07-02 15:59:29,2025-07-02 15:42:50,2025-07-02 16:04:52,2025-07-02,2025-07-02 15:42:50,2025-07-02 16:04:50,0 days 00:22:00,0 days 00:16:40,1000.0,0 days 00:05:20,0 days 00:16:40,1000.0,320.0,1320.0,270.0,-30.0,299.0,1.1333,201.0,0.3304,80.0,NaN,NaN,Id=1:BME680:breathVocEquivalent MAX value VOC ...,Id=2:BME680:breathVocEquivalent MAX value VOC ...,0.96260,1.130830,0.30518,0.330042,NaN,NaN,0.74384,1.123456,0.050000,-0.000188,0.149700,0.002748,NaN,NaN,-2.25,3.0
2,InsertingSourcePollutant,on,None,None,0.4,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.0,None,None,2025-07-03 12:34:32,2025-07-03 12:30:25,2025-07-03 12:45:31,2025-07-03,2025-07-03 12:30:25,2025-07-03 12:45:31,0 days 00:15:06,0 days 00:04:08,248.0,0 days 00:10:58,0 days 00:04:08,248.0,658.0,906.0,270.0,-30.0,299.0,1.3923,235.0,2.2994,299.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,1.34093,1.390726,1.62716,2.182643,NaN,NaN,1.46438,2.073907,0.133633,-0.003248,0.412300,-0.007478,NaN,NaN,-2.25,3.6
3,InsertingSourcePollutant,on,None,None,1.0,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.8,None,None,2025-07-03 15:53:07,2025-07-03 15:43:27,2025-07-03 15:59:11,2025-07-03,2025-07-03 15:51:40,2025-07-03 15:59:10,0 days 00:07:30,0 days 00:01:28,88.0,0 days 00:06:02,0 days 00:01:28,88.0,362.0,450.0,270.0,-30.0,299.0,0.3439,299.0,18.4943,299.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.26763,0.334346,16.09553,17.771554,NaN,NaN,6.84825,17.295804,0.027200,0.000002,0.505133,0.005152,NaN,NaN,-1.45,3.0
4,InsertingSourcePollutant,on,None,None,1.4,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.4,None,None,2025-07-09 19:19:19,2025-07-09 19:01:42,2025-07-09 19:27:50,2025-07-09,2025-07-09 19:01:44,2025-07-09 19:27:49,0 days 00:26:05,0 days 00:17:36,1056.0,0 days 00:08:29,0 days 00:17:36,1056.0,509.0,1565.0,270.0,-30.0,299.0,0.6066,246.0,0.7315,299.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.58644,0.606300,0.70629,0.726681,NaN,NaN,0.62712,0.723846,0.030767,-0.000302,0.343333,-0.000157,NaN,NaN,-1.85,2.6
5,InsertingSourcePollutant,None,None,None,1.0,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.8,None,None,2025-07-12 22:57:57,2025-07-12 22:31:25,2025-07-12 23:02:13,2025-07-12,2025-07-12 22:34:03,2025-07-12 23:02:11,0 days 00:28:08,0 days 00:23:55,1435.0,0 days 00:04:13,0 days 00:23:55,1435.0,253.0,1688.0,224.0,-30.0,253.0,0.1809,-30.0,0.8368,253.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.13562,0.176638,0.71555,0.822997,NaN,NaN,0.65977,0.812321,0.158933,-0.001602,0.068533,-0.000877,NaN,NaN,-1.45,3.0
7,InsertingSourcePollutant,on,on,None,1.8,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,None,None,2025-07-19 15:04:09,2025-07-19 14:59:47,2025-07-19 15:08:10,2025-07-19,2025-07-19 14:59:49,2025-07-19 15:08:09,0 days 00:08:20,0 days 00:04:21,261.0,0 days 00:03:59,0 days 00:04:21,261.0,239.0,500.0,210.0,-30.0,239.0,0.2081,-30.0,0.5084,172.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.16252,0.206555,0.50321,0.508331,NaN,NaN,0.48965,0.508061,0.185033,-0.001642,0.109533,-0.000750,NaN,NaN,-2.15,2.2
8,InsertingSourcePollutant,on,on,None,1.8,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,None,None,2025-07-19 15:17:10,2025-07-19 15:14:13,2025-07-19 15:21:23,2025-07-19,2025-07-19 15:14:15,2025-07-19 15:21:21,0 days 00:07:06,0 days 00:02:56,176.0,0 days 00:04:10,0 days 00:02:56,176.0,250.0,426.0,221.0,-30.0,250.0,0.3916,250.0,1.0680,250.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.36040,0.390020,0.91140,1.058680,NaN,NaN,0.74541,1.046716,0.100067,0.001715,0.077233,0.002275,NaN,NaN,-2.15,2.2
9,InsertingSourcePollutant,on,on,None,1.8,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,None,None,2025-07-19 15:30:49,2025-07-19 15:25:07,2025-07-19 15:44:28,2025-07-19,2025-07-19 15:25:09,2025-07-19 15:44:27,0 days 00:19:18,0 days 00:05:41,341.0,0 days 00:13:37,0 days 00:05:41,341.0,817.0,1158.0,270.0,-30.0,299.0,1.4493,299.0,1.0056,299.0,NaN,NaN,Id=1:BME680:breathVocEquivalent MAX value VOC ...,Id=2:BME680:breathVocEquivalent MAX value VOC ...,1.11083,1.416626,0.71620,0.989721,NaN,NaN,0.94604,1.379992,0.015833,-0.000120,0.047667,0.000025,NaN,NaN,-2.15,2.2
10,InsertingSourcePollutant,on,on,None,1.8,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,None,None,2025-07-19 16:12:54,2025-07-19 16:04:22,2025-07-19 16:21:55,2025-07-19,2025-07-19 16:04:24,2025-07-19 16:21:54,0 days 00:17:30,0 days 00:08:31,511.0,0 days 00:08:59,0 days 00:08:31,511.0,539.0,1050.0,270.0,-30.0,299.0,1.7484,299.0,2.9637,299.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,1.51517,1.732250,2.37971,2.913531,NaN,NaN,1.74426,2.858929,0.207600,0.000922,0.318800,0.001273,NaN,NaN,-2.15,2.2
11,InsertingSourcePollutant,on,on,None,1.8,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,None,None,2025-07-19 16:46:45,2025-07-19 16:36:03,2025-07-19 16:54:19,2025-07-19,2025-07-19 16:36:04,2025-07-19 16:54:18,0 days 00:18:14,0 days 00:10:42,642.0,0 days 00:07:32,0 days 00:10:42,642.0,452.0,1094.0,270.0,-30.0,299.0,1.4246,299.0,2.5592,299.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,1.26407,1.405492,2.05864,2.503834,NaN,NaN,1.68727,2.451024,0.870433,0.000522,0.726000,0.000768,NaN,NaN,-2.15,2.2
12,InsertingSourcePollutant,on,on,None,1.8,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,None,None,2025-07-19 17:25:36,2025-07-19 17:05:51,2025-07-19 17:35:58,2025-07-19,2025-07-19 17:05:52,2025-07-19 17:35:57,0 days 00:30:05,0 days 00:19:45,1185.0,0 days 00:10:20,0 days 00:19:45,1185.0,620.0,1805.0,270.0,-30.0,299.0,1.9219,299.0,2.0172,299.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,1.82505,1.911130,1.74210,1.975220,NaN,NaN,1.80769,1.938423,1.538733,0.002958,1.071967,-0.000553,NaN,NaN,-2.15,2.2
13,InsertingSourcePollutant,on,None,None,1.8,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,None,None,2025-07-20 13:46:03,2025-07-20 13:36:41,2025-07-20 14:48:43,2025-07-20,2025-07-20 13:36:42,2025-07-20 14:48:41,0 days 01:11:59,0 days 00:09:22,562.0,0 days 01:02:37,0 days 00:09:22,562.0,3757.0,4319.0,270.0,-30.0,299.0,0.1910,261.0,0.2598,160.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.18540,0.190900,0.24836,0.259642,NaN,NaN,0.23963,0.259123,0.088633,0.000232,0.104667,0.000335,NaN,NaN,-2.15,2.2
14,InsertingSourcePollutant,on,on,None,1.8,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,None,None,2025-07-20 15:15:34,2025-07-20 15:04:15,2025-07-20 15:39:22,2025-07-20,2025-07-20 15:04:17,2025-07-20 15:39:20,0 days 00:35:03,0 days 00:11:18,678.0,0 days 00:23:45,0 days 00:11:18,678.0,1425.0,2103.0,270.0,-30.0,299.0,0.2931,175.0,0.8709,299.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.28710,0.292871,0.72066,0.850215,NaN,NaN,0.56797,0.829301,0.159800,0.000032,0.363067,0.000227,NaN,NaN,-2.15,2.2
15,InsertingSourcePollutant,on,on,None,1.8,Φαρμακευτικό αλκοόλ 95%,ανεμιστήρας,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,None,None,2025-07-20 15:52:33,2025-07-20 15:47:36,2025-07-20 16:08:05,2025-07-20,2025-07-20 15:47:38,2025-07-20 16:08:03,0 days 00:20:25,0 days 00:04:56,296.0,0 days 00:15:29,0 days 00:04:56,296.0,929.0,1225.0,270.0,-30.0,299.0,1.1745,299.0,0.8673,299.0,NaN,NaN,Id=1:BME680:breathVocEquivalent MAX value VOC ...,Id=2:BME680:breathVocEquivalent MAX value VOC ...,1.02663,1.158366,0.74384,0.852895,NaN,NaN,0.85985,1.144658,0.215467,0.000350,0.062300,0.000492,NaN,NaN,-2.15,2.2
16,InsertingSourcePollutant,on,None,None,1.8,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,None,None,2025-07-20 16:34:39,2025-07-20 16:20:42,2025-07-20 16:43:55,2025-07-20,2025-07-20 16:20:44,2025-07-20 16:43:54,0 days 00:23:10,0 days 00:13:56,836.0,0 days 00:09:14,0 days 00:13:56,836.0,554.0,1390.0,270.0,-30.0,299.0,0.2088,284.0,0.3477,299.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.18658,0.208113,0.22651,0.331650,NaN,NaN,0.20391,0.316304,0.003133,0.000038,0.000000,0.000005,NaN,NaN,-2.15,2.2
17,InsertingSourcePollutant,on,on,None,1.8,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,None,None,2025-07-20 18:13:07,2025-07-20 18:04:08,2025-07-20 18:22:22,2025-07-20,2025-07-20 18:04:10,2025-07-20 18:22:20,0 days 00:18:10,0 days 00:08:58,538.0,0 days 00:09:12,0 days 00:08:58,538.0,552.0,1090.0,270.0,-30.0,299.0,0.5649,299.0,0.8142,233.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.54597,0.562797,0.81210,0.813800,NaN,NaN,0.79987,0.813700,0.079967,0.000308,0.141600,0.000510,NaN,NaN,-2.15,2.2
18,InsertingSourcePollutant,on,on,on,1.8,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,None,None,2025-07-20 18:31:41,2025-07-20 18:29:19,2025-07-20 18:40:12,2025-07-20,2025-07-20 18:29:21,2025-07-20 18:40:11,0 days 00:10:50,0 days 00:02:21,141.0,0 days 00:08:29,0 days 00:02:21,141.0,509.0,650.0,270.0,-30.0,299.0,0.0323,286.0,0.0264,151.0,NaN,NaN,Id=1:BME680:breathVocEquivalent MAX value VOC ...,Id=2:BME680:breathVocEquivalent MAX value VOC ...,0.02656,0.032100,0.02451,0.026300,NaN,NaN,0.02491,0.031800,0.011600,-0.000023,0.007067,0.000063,NaN,NaN,-2.15,2.2
19,InsertingSourcePollutant,on,on,None,1.8,Φαρμακευτικό αλκοόλ 95%,ανεμιστήρας,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,None,None,2025-07-20 18:47:26,2025-07-20 18:41:09,2025-07-20 19:00:09,2025-07-20,2025-07-20 18:41:11,2025-07-20 19:00:08,0 days 00:18:57,0 days 00:06:16,376.0,0 days 00:12:41,0 days 00:06:16,376.0,761.0,1137.0,270.0,-30.0,299.0,0.8626,299.0,1.2647,299.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.72151,0.848053,1.05549,1.246331,NaN,NaN,0.87314,1.226460,0.082033,0.000518,0.158367,0.000432,NaN,NaN,-2.15,2.2
20,InsertingSourcePollutant,on,on,None,1.8,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,None,None,2025-07-20 19:15:51,2025-07-20 19:13:35,2025-07-20 19:23:44,2025-07-20,2025-07-20 19:13:36,2025-07-20 19:23:42,0 days 00:10:06,0 days 00:02:16,136.0,0 days 00:07:50,0 days 00:02:16,136.0,470.0,606.0,270.0,-30.0,299.0,0.1315,299.0,0.5513,149.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.11160,0.129326,0.54472,0.550871,NaN,NaN,0.54041,0.550082,0.020533,0.000518,0.019367,0.000513,NaN,NaN,-2.15,2.2
21,InsertingSourcePollutant,on,None,None,1.8,Φαρμακευτικό αλκοόλ 95%,ανεμιστήρας,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,None,None,2025-07-20 19:37:50,2025-07-20 19:30:51,2025-07-20 19:46:28,2025-07-20,2025-07-20 19:30:53,2025-07-20 19:46:26,0 days 00:15:33,0 days 00:06:58,418.0,0 days 00:08:35,0 days 00:06:58,418.0,515.0,933.0,270.0,-30.0,299.0,0.4218,299.0,0.5627,299.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.30171,0.408111,0.42745,0.546795,NaN,NaN,0.37118,0.532004,0.044800,0.000948,0.040500,0.000327,NaN,NaN,-2.15,2.2
22,InsertingSourcePollutant,on,on,None,1.8,Φαρμακευτικό αλκοόλ 95%,ανεμιστήρας,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,None,None,2025-07-20 19:59:56,2025-07-20 19:55:47,2025-07-20 20:05:21,2025-07-20,2025-07-20 19:55:48,2025-07-20 20:05:20,0 days 00:09:32,0 days 00:04:09,249.0,0 days 00:05:23,0 days 00:04:09,249.0,323.0,572.0,270.0,-30.0,299.0,1.3922,299.0,1.4778,299.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,1.15224,1.372357,1.27872,1.453744,NaN,NaN,1.21924,1.436027,0.035167,-0.000307,0.016467,0.000013,NaN,NaN,-2.15,2.2
23,InsertingSourcePollutant,on,None,None,1.8,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,on,None,2025-07-20 20:29:17,2025-07-20 20:25:07,2025-07-20 20:34:24,2025-07-20,2025-07-20 20:25:42,2025-07-20 20:30:33,0 days 00:04:51,0 days 00:03:36,216.0,0 days 00:01:15,0 days 00:03:36,216.0,75.0,291.0,46.0,-30.0,75.0,0.0755,73.0,0.0580,75.0,NaN,NaN,Id=1:BME680:breathVocEquivalent MAX value VOC ...,Id=2:BME680:breathVocEquivalent MAX value VOC ...,0.07345,0.075395,0.04610,0.056125,NaN,NaN,0.06170,0.075267,0.033933,-0.000145,0.033900,-0.000098,NaN,NaN,-2.15,2.2
24,InsertingSourcePollutant,on,None,None,1.8,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,on,None,2025-07-20 20:48:43,2025-07-20 20:47:09,2025-07-20 20:55:25,2025-07-20,2025-07-20 20:47:11,2025-07-20 20:55:23,0 days 00:08:12,0 days 00:01:33,93.0,0 days 00:06:39,0 days 00:01:33,93.0,399.0,492.0,270.0,-30.0,299.0,0.6419,299.0,0.5688,299.0,NaN,NaN,Id=1:BME680:breathVocEquivalent MAX value VOC ...,Id=2:BME680:breathVocEquivalent MAX value VOC ...,0.50917,0.627024,0.48538,0.562262,NaN,NaN,0.49617,0.612127,0.037367,-0.001228,0.029167,-0.000553,NaN,NaN,-2.15,2.2
25,InsertingSourcePollutant,on,None,None,1.8,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,on,None,2025-07-20 21:11:42,2025-07-20 21:08:20,2025-07-20 21:19:43,2025-07-20,2025-07-20 21:08:21,2025-07-20 21:19:41,0 days 00:11:20,0 days 00:03:22,202.0,0 days 00:07:58,0 days 00:03:22,202.0,478.0,680.0,270.0,-30.0,299.0,0.7168,299.0,0.6031,299.0,NaN,NaN,Id=1:BME680:breathVocEquivalent MAX value VOC ...,Id=2:BME680:breathVocEquivalent MAX value VOC ...,0.57656,0.702695,0.49706,0.597120,NaN,NaN,0.54060,0.687745,0.027033,-0.000075,0.018500,-0.000040,NaN,NaN,-2.15,2.2
26,InsertingSourcePollutant,on,on,None,1.8,Φαρμακευτικό αλκοόλ 70%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,on,None,2025-07-21 14:32:35,2025-07-21 14:24:56,2025-07-21 14:46:41,2025-07-21,2025-07-21 14:24:58,2025-07-21 14:46:39,0 days 00:21:41,0 days 00:07:38,458.0,0 days 00:14:03,0 days 00:07:38,458.0,843.0,1301.0,270.0,-30.0,299.0,0.7052,299.0,1.8658,299.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.59321,0.694830,1.38082,1.814263,NaN,NaN,1.02079,1.760416,0.189100,0.000105,0.176367,0.000692,NaN,NaN,-2.15,2.2
27,InsertingSourcePollutant,on,None,None,1.8,Φαρμακευτικό αλκοόλ 70%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,None,None,2025-07-21 19:37:03,2025-07-21 19:33:55,2025-07-21 19:48:50,2025-07-21,2025-07-21 19:33:56,2025-07-21 19:48:49,0 days 00:14:53,0 days 00:03:08,188.0,0 days 00:11:45,0 days 00:03:08,188.0,705.0,893.0,270.0,-30.0,299.0,0.1165,299.0,0.4738,229.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.10480,0.115242,0.45588,0.473500,NaN,NaN,0.44990,0.472487,0.002900,0.000040,0.008033,-0.000245,NaN,NaN,-2.15,2.2
28,InsertingSourcePollutant,on,None,None,NaN,Φαρμακευτικό αλκοόλ 70%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,1.2,1.2,on,None,2025-07-21 20:02:43,2025-07-21 19:59:26,2025-07-21 20:08:57,2025-07-21,2025-07-21 19:59:28,2025-07-21 20:08:55,0 days 00:09:27,0 days 00:03:16,196.0,0 days 00:06:11,0 days 00:03:16,196.0,371.0,567.0,270.0,-30.0,299.0,1.1152,299.0,0.8222,299.0,NaN,NaN,Id=1:BME680:breathVocEquivalent MAX value VOC ...,Id=2:BME680:breathVocEquivalent MAX value VOC ...,0.85189,1.093083,0.69746,0.807998,NaN,NaN,0.80385,1.066267,0.011833,0.000072,0.012567,-0.000075,NaN,NaN,-2.05,1.2
29,InsertingSourcePollutant,on,None,None,NaN,Φαρμακευτικό αλκοόλ 70%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,1.2,1.2,None,None,2025-07-21 20:52:37,2025-07-21 20:49:38,2025-07-21 21:03:43,2025-07-21,2025-07-21 20:49:40,2025-07-21 21:03:41,0 days 00:14:01,0 days 00:02:58,178.0,0 days 00:11:03,0 days 00:02:58,178.0,663.0,841.0,270.0,-30.0,299.0,0.3570,299.0,0.3510,299.0,NaN,NaN,Id=1:BME680:breathVocEquivalent MAX value VOC ...,Id=2:BME680:breathVocEquivalent MAX value VOC ...,0.33671,0.352265,0.30589,0.347352,NaN,NaN,0.33522,0.349941,0.039100,0.000845,0.031933,0.000233,NaN,NaN,-2.05,1.2

In [76]:
userInputData.loc[:,["x axis","y axis"]] = userInputData.loc[:,["x axis","y axis"]].round(2)

In [77]:
userInputData.loc[:, ["x axis", "y axis"]].tail(30)

     x axis  y axis
229   -1.50     2.5
230   -2.50     2.5
231   -2.95     2.5
232   -0.50     0.5
233   -1.50     0.5
234   -2.50     0.5
235   -2.95     0.5
236   -0.50     3.5
237   -1.50     3.5
238   -2.50     3.5
239   -2.95     3.5
240     NaN     NaN
241   -2.75     2.2
242     NaN     NaN
243   -1.50     1.5
244   -1.50     0.5
245   -1.50     2.5
246   -1.50     3.5
247   -2.50     3.5
248   -2.50     2.5
249   -2.50     1.5
250   -2.50     0.5
251   -0.50     0.5
252   -0.50     1.5
253   -0.50     2.5
254   -0.50     3.5
255   -2.95     3.5
256   -2.95     2.5
257   -2.95     1.5
258   -2.95     0.5

In [78]:
userInputData.loc[:,"x-y axis"] = list(zip(userInputData.loc[:,"x axis"], userInputData.loc[:,"y axis"]))

C:\Users\Andreas\AppData\Local\Temp\ipykernel_11096\767001041.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  userInputData.loc[:,"x-y axis"] = list(zip(userInputData.loc[:,"x axis"], userInputData.loc[:,"y axis"]))

In [79]:
userInputData["x-y axis"]

0      (-2.25, 3.0)
1      (-2.25, 3.0)
2      (-2.25, 3.6)
3      (-1.45, 3.0)
4      (-1.85, 2.6)
           ...
254     (-0.5, 3.5)
255    (-2.95, 3.5)
256    (-2.95, 2.5)
257    (-2.95, 1.5)
258    (-2.95, 0.5)
Name: x-y axis, Length: 257, dtype: object

In [80]:
print(dict_of_timeseries[157].max())
print(userInputData.loc[157])

sensors                                                        Id=2:BME680:breathVocEquivalent
VOC                                                                                      4.206
after_insertion                                                                           True
original_value                                                                            True
datetime_timestamp                                                         2025-10-13 22:32:46
timestamp                                                                      0 days 00:06:34
seconds                                                                                  299.0
seconds passed from insertionSource                                                      299.0
VOC original                                                                          5.655352
VOC rolling average                                                                     4.0522
original seconds                                                                         394.0
VOC-capped                                                                               4.206
VOC rolling average-capped                                                              4.0522
VOC gradient                                                                            0.0812
VOC rolling average gradient                                                            0.0812
VOC rolling average standard scaler whole experiment                                  2.970206
VOC rolling average-capped standard scaler whole experiment                           2.970206
dtype: object
experimentState                                                                                    InsertingSourcePollutant
are-doors-opened                                                                                                       None
are-people-inside                                                                                                      None
are-windows-opened                                                                                                     None
front-wall                                                                                                              1.5
item-used                                                                                           Φαρμακευτικό αλκοόλ 95%
notes
room                                                                      Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...
side-right-wall                                                                                                         2.5
back-wall                                                                                                               NaN
side-left-wall                                                                                                          NaN
are-fans-on                                                                                                            None
no-source-located                                                                                                      None
timestamp InsertingSource                                                                               2025-10-13 22:27:46
timestamp StartingExperiment                                                                            2025-10-13 22:26:11
timestamp EndingExperiment                                                                              2025-10-13 22:34:17
date of experiment                                                                                               2025-10-13
actual timestamp StartingExperiment                                                                     2025-10-13 22:26:12
actual timestamp EndingExperiment                                                                       2025-10-13 22:34:15
time taken total                                                                                            0 days 00:08:03
timestamp InsertingSource timedelta                                                                         0 days 00:01:35
timestamp InsertingSource seconds                                                                                      95.0
time taken after insertion                                                                                  0 days 00:06:28
time taken before insertion                                                                                 0 days 00:01:35
time taken before insertion (seconds)                                                                                  95.0
time taken after insertion (seconds)                                                                                  388.0
time taken total (seconds)                                                                                            483.0
time taken total (seconds)-capped                                                                                     270.0
time taken before insertion (seconds)-capped                                                                          -30.0
time taken after insertion (seconds)-capped                                                                           299.0
Id=1:BME680:breathVocEquivalent MAX value VOC rolling average                                                        2.6075
Id=1:BME680:breathVocEquivalent index of MAX value VOC rolling average                                                299.0
Id=2:BME680:breathVocEquivalent MAX value VOC rolling average                                                        3.6532
Id=2:BME680:breathVocEquivalent index of MAX value VOC rolling average                                                299.0
Id=0:BME680:breathVocEquivalent MAX value VOC rolling average                                                        4.0522
Id=0:BME680:breathVocEquivalent index of MAX value VOC rolling average                                                296.0
sensor with MAX value experiment                                          Id=0:BME680:breathVocEquivalent MAX value VOC ...
sensor with second MAX value experiment                                   Id=2:BME680:breathVocEquivalent MAX value VOC ...
Id=1:BME680:breathVocEquivalent quantile 90.0% VOC rolling average                                                  2.41689
Id=1:BME680:breathVocEquivalent quantile 99.0% VOC rolling average                                                 2.578684
Id=2:BME680:breathVocEquivalent quantile 90.0% VOC rolling average                                                  2.07151
Id=2:BME680:breathVocEquivalent quantile 99.0% VOC rolling average                                                 3.395643
Id=0:BME680:breathVocEquivalent quantile 90.0% VOC rolling average                                                  3.25783
Id=0:BME680:breathVocEquivalent quantile 99.0% VOC rolling average                                                 4.047166
whole experiment quantile 90.0% VOC rolling average                                                                 2.43382
whole experiment quantile 99.0% VOC rolling average                                                                4.017512
Id=1:BME680:breathVocEquivalent VOC mean calm period                                                               0.465633
Id=1:BME680:breathVocEquivalent VOC gradient mean calm period                                                     -0.005427
Id=2:BME680:breathVocEquivalent VOC mean calm period                                                               0.097733
Id=2:BME680:breathVocEquivalent VOC gradient mean calm period                                                      0.000453
Id=0:BME680:breathVocEquivalent VOC mean calm period                                                               0.372967
Id=0:BME680:breathVocEquivalent VOC gradient mean calm period                                                      0.001753
x axis                                                                                                                 -2.5
y axis                                                                                                                  2.5
x-y axis                                                                                                        (-2.5, 2.5)
Name: 157, dtype: object

In [81]:
userInputData["room"].unique()

array(['Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55',
       'Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1',
       'Κρεβατοκάμαρα-Όλοι οι αισθητήρες μαζί Μ:0.80 , Α:0.90',
       'Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0.5  ,id:2 Π:0.4 Α:1.0',
       'Κρεβατοκάμαρα Όλοι οι αισθητήρες μαζί Π:1.80 , Δ:2.00'],
      dtype=object)

###  FIND POSITIONS OF SENSORS AND SOURCES,ALSO EUCLIDIAN DISTANCE

In [82]:
room_length = 4.0
room_width = 3.25
pos_id0 = 'position of Id=0:BME680:breathVocEquivalent'
pos_id1 = 'position of Id=1:BME680:breathVocEquivalent'
pos_id2 = 'position of Id=2:BME680:breathVocEquivalent'
pos_id_all = [pos_id0,pos_id1,pos_id2]
room_positions = {
    'Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55' : {
        pos_id1 +"-x axis" : room_width - 0.85 ,
        pos_id1 +"-y axis" : room_length - 0.95,
        pos_id2+"-x axis" :  room_width - 1.55 ,
        pos_id2+  "-y axis" : room_length - 0.95
              
    },
        
    'Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1' : {
        pos_id1+"-x axis" :  room_width - 1.2 ,
        pos_id1+"-y axis" :  0.6,
        pos_id2+"-x axis" :  room_width -1.1 ,
        pos_id2+"-y axis" : room_length - 0.8
   
    },      
        
    'Κρεβατοκάμαρα-Όλοι οι αισθητήρες μαζί Μ:0.80 , Α:0.90' : {
        
        pos_id0+"-x axis" : -room_width + 0.9, 
        pos_id0+"-y axis" : room_length - 0.8,
        
        pos_id1+"-x axis" : -room_width + 0.9,
        pos_id1+"-y axis" : room_length - 0.8,
        
        pos_id2+"-x axis" : -room_width + 0.9,
        pos_id2+"-y axis" : room_length - 0.8
     },
    'Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0.5  ,id:2 Π:0.4 Α:1.0' :{
        pos_id0+"-x axis" : -room_width  + 1.4, 
        pos_id0+"-y axis" : room_length - 0.5,
        
        pos_id1+"-x axis" :   -0.5,
        pos_id1+"-y axis" :   1.7,
        
        pos_id2+"-x axis" :  -room_width +1.0,
        pos_id2+"-y axis" :  0.4    
    }
}
room_positions

{'Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55': {'position of Id=1:BME680:breathVocEquivalent-x axis': 2.4,
  'position of Id=1:BME680:breathVocEquivalent-y axis': 3.05,
  'position of Id=2:BME680:breathVocEquivalent-x axis': 1.7,
  'position of Id=2:BME680:breathVocEquivalent-y axis': 3.05},
 'Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1': {'position of Id=1:BME680:breathVocEquivalent-x axis': 2.05,
  'position of Id=1:BME680:breathVocEquivalent-y axis': 0.6,
  'position of Id=2:BME680:breathVocEquivalent-x axis': 2.15,
  'position of Id=2:BME680:breathVocEquivalent-y axis': 3.2},
 'Κρεβατοκάμαρα-Όλοι οι αισθητήρες μαζί Μ:0.80 , Α:0.90': {'position of Id=0:BME680:breathVocEquivalent-x axis': -2.35,
  'position of Id=0:BME680:breathVocEquivalent-y axis': 3.2,
  'position of Id=1:BME680:breathVocEquivalent-x axis': -2.35,
  'position of Id=1:BME680:breathVocEquivalent-y axis': 3.2,
  'position of Id=2:BME680:breathVocEquivalent-x axis': -2.35,
  'position of Id=2:BME680:breathVocEquivalent-y axis': 3.2},
 'Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0.5  ,id:2 Π:0.4 Α:1.0': {'position of Id=0:BME680:breathVocEquivalent-x axis': -1.85,
  'position of Id=0:BME680:breathVocEquivalent-y axis': 3.5,
  'position of Id=1:BME680:breathVocEquivalent-x axis': -0.5,
  'position of Id=1:BME680:breathVocEquivalent-y axis': 1.7,
  'position of Id=2:BME680:breathVocEquivalent-x axis': -2.25,
  'position of Id=2:BME680:breathVocEquivalent-y axis': 0.4}}

In [83]:
pos_id0 = 'position of Id=0:BME680:breathVocEquivalent'
pos_id1 = 'position of Id=1:BME680:breathVocEquivalent'
pos_id2 = 'position of Id=2:BME680:breathVocEquivalent'
pos_id_all = [pos_id0,pos_id1,pos_id2]
for pos_id in pos_id_all:
    userInputData.loc[:,(pos_id+"-x axis")] = np.nan
    userInputData.loc[:,(pos_id+"-y axis")] = np.nan
    


for room,sensor_positions in room_positions.items():
    outer_mask = userInputData["room"] == room
    for sensor_position,value  in sensor_positions.items():
          
        userInputData.loc[outer_mask,sensor_position] = value

C:\Users\Andreas\AppData\Local\Temp\ipykernel_11096\1256993855.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  userInputData.loc[:,(pos_id+"-x axis")] = np.nan
C:\Users\Andreas\AppData\Local\Temp\ipykernel_11096\1256993855.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  userInputData.loc[:,(pos_id+"-y axis")] = np.nan
C:\Users\Andreas\AppData\Local\Temp\ipykernel_11096\1256993855.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  userInputData.loc[:,(pos_id+"-x axis")] = np.nan
C:\Users\Andreas\AppData\Local\Temp\ipykernel_11096\1256993855.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  userInputData.loc[:,(pos_id+"-y axis")] = np.nan
C:\Users\Andreas\AppData\Local\Temp\ipykernel_11096\1256993855.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  userInputData.loc[:,(pos_id+"-x axis")] = np.nan
C:\Users\Andreas\AppData\Local\Temp\ipykernel_11096\1256993855.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  userInputData.loc[:,(pos_id+"-y axis")] = np.nan

In [84]:
userInputData

,experimentState,are-doors-opened,are-people-inside,are-windows-opened,front-wall,item-used,notes,room,side-right-wall,back-wall,side-left-wall,are-fans-on,no-source-located,timestamp InsertingSource,timestamp StartingExperiment,timestamp EndingExperiment,date of experiment,actual timestamp StartingExperiment,actual timestamp EndingExperiment,time taken total,timestamp InsertingSource timedelta,timestamp InsertingSource seconds,time taken after insertion,time taken before insertion,time taken before insertion (seconds),time taken after insertion (seconds),time taken total (seconds),time taken total (seconds)-capped,time taken before insertion (seconds)-capped,time taken after insertion (seconds)-capped,Id=1:BME680:breathVocEquivalent MAX value VOC rolling average,Id=1:BME680:breathVocEquivalent index of MAX value VOC rolling average,Id=2:BME680:breathVocEquivalent MAX value VOC rolling average,Id=2:BME680:breathVocEquivalent index of MAX value VOC rolling average,Id=0:BME680:breathVocEquivalent MAX value VOC rolling average,Id=0:BME680:breathVocEquivalent index of MAX value VOC rolling average,sensor with MAX value experiment,sensor with second MAX value experiment,Id=1:BME680:breathVocEquivalent quantile 90.0% VOC rolling average,Id=1:BME680:breathVocEquivalent quantile 99.0% VOC rolling average,Id=2:BME680:breathVocEquivalent quantile 90.0% VOC rolling average,Id=2:BME680:breathVocEquivalent quantile 99.0% VOC rolling average,Id=0:BME680:breathVocEquivalent quantile 90.0% VOC rolling average,Id=0:BME680:breathVocEquivalent quantile 99.0% VOC rolling average,whole experiment quantile 90.0% VOC rolling average,whole experiment quantile 99.0% VOC rolling average,Id=1:BME680:breathVocEquivalent VOC mean calm period,Id=1:BME680:breathVocEquivalent VOC gradient mean calm period,Id=2:BME680:breathVocEquivalent VOC mean calm period,Id=2:BME680:breathVocEquivalent VOC gradient mean calm period,Id=0:BME680:breathVocEquivalent VOC mean calm period,Id=0:BME680:breathVocEquivalent VOC gradient mean calm period,x axis,y axis,x-y axis,position of Id=0:BME680:breathVocEquivalent-x axis,position of Id=0:BME680:breathVocEquivalent-y axis,position of Id=1:BME680:breathVocEquivalent-x axis,position of Id=1:BME680:breathVocEquivalent-y axis,position of Id=2:BME680:breathVocEquivalent-x axis,position of Id=2:BME680:breathVocEquivalent-y axis
0,InsertingSourcePollutant,on,None,None,1.0,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.0,None,None,2025-07-01 16:09:41,2025-07-01 15:27:16,2025-07-01 16:14:44,2025-07-01,2025-07-01 15:27:19,2025-07-01 16:14:42,0 days 00:47:23,0 days 00:42:23,2543.0,0 days 00:05:00,0 days 00:42:23,2543.0,300.0,2843.0,270.0,-30.0,299.0,4.3501,299.0,8.1928,243.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,4.10260,4.342653,8.13641,8.191397,NaN,NaN,8.03289,8.186653,1.338333,0.000302,5.003467,0.001410,NaN,NaN,-2.25,3.0,"(-2.25, 3.0)",NaN,NaN,2.4,3.05,1.70,3.05
1,InsertingSourcePollutant,on,None,None,1.0,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.0,None,None,2025-07-02 15:59:29,2025-07-02 15:42:50,2025-07-02 16:04:52,2025-07-02,2025-07-02 15:42:50,2025-07-02 16:04:50,0 days 00:22:00,0 days 00:16:40,1000.0,0 days 00:05:20,0 days 00:16:40,1000.0,320.0,1320.0,270.0,-30.0,299.0,1.1333,201.0,0.3304,80.0,NaN,NaN,Id=1:BME680:breathVocEquivalent MAX value VOC ...,Id=2:BME680:breathVocEquivalent MAX value VOC ...,0.96260,1.130830,0.30518,0.330042,NaN,NaN,0.74384,1.123456,0.050000,-0.000188,0.149700,0.002748,NaN,NaN,-2.25,3.0,"(-2.25, 3.0)",NaN,NaN,2.4,3.05,1.70,3.05
2,InsertingSourcePollutant,on,None,None,0.4,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.0,None,None,2025-07-03 12:34:32,2025-07-03 12:30:25,2025-07-03 12:45:31,2025-07-03,2025-07-03 12:30:25,2025-07-03 12:45:31,0 days 00:15:06,0 days 00:04:08,248.0,0 days 00:10:58,0 days 00:04:08,248.0,658.0,906.0,270.0,-30.0,299.0,1.3923,235.0,2.2994,299.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,1.34093,1.390726,1.62716,2.182643,NaN,NaN,1.46438,2.073907,0.133633,-0.003248,0.412300,-0.007478,NaN,NaN,-2.25,3.6,"(-2.25, 3.6)",NaN,NaN,2.4,3.05,1.70,3.05
3,InsertingSourcePollutant,on,None,None,1.0,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.8,None,None,2025-07-03 15:53:07,2025-07-03 15:43:27,2025-07-03 15:59:11,2025-07-03,2025-07-03 15:51:40,2025-07-03 15:59:10,0 days 00:07:30,0 days 00:01:28,88.0,0 days 00:06:02,0 days 00:01:28,88.0,362.0,450.0,270.0,-30.0,299.0,0.3439,299.0,18.4943,299.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.26763,0.334346,16.09553,17.771554,NaN,NaN,6.84825,17.295804,0.027200,0.000002,0.505133,0.005152,NaN,NaN,-1.45,3.0,"(-1.45, 3.0)",NaN,NaN,2.4,3.05,1.70,3.05
4,InsertingSourcePollutant,on,None,None,1.4,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.4,None,None,2025-07-09 19:19:19,2025-07-09 19:01:42,2025-07-09 19:27:50,2025-07-09,2025-07-09 19:01:44,2025-07-09 19:27:49,0 days 00:26:05,0 days 00:17:36,1056.0,0 days 00:08:29,0 days 00:17:36,1056.0,509.0,1565.0,270.0,-30.0,299.0,0.6066,246.0,0.7315,299.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.58644,0.606300,0.70629,0.726681,NaN,NaN,0.62712,0.723846,0.030767,-0.000302,0.343333,-0.000157,NaN,NaN,-1.85,2.6,"(-1.85, 2.6)",NaN,NaN,2.4,3.05,1.70,3.05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
254,InsertingSourcePollutant,None,None,None,0.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",0.5,NaN,NaN,None,None,2025-10-24 20:32:03,2025-10-24 20:29:36,2025-10-24 20:37:33,2025-10-24,2025-10-24 20:29:37,2025-10-24 20:37:31,0 days 00:07:54,0 days 00:02:27,147.0,0 days 00:05:27,0 days 00:02:27,147.0,327.0,474.0,270.0,-30.0,299.0,2.0134,131.0,4.9923,299.0,2.8096,286.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=0:BME680:breathVocEquivalent MAX value VOC ...,1.85013,2.010252,4.58879,4.944112,2.74257,2.806868,3.70824,4.844487,0.384700,-0.004535,0.790767,0.014290,1.095967,-0.005078,-0.50,3.5,"(-0.5, 3.5)",-1.85,3.5,-0.5,1.70,-2.25,0.40
255,InsertingSourcePollutant,None,None,None,0.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:05:46,2025-10-24 21:03:22,2025-10-24 21:11:21,2025-10-24,2025-10-24 21:03:24,2025-10-24 21:11:19,0 days 00:07:55,0 days 00:02:23,143.0,0 days 00:05:32,0 days 00:02:23,143.0,332.0,475.0,270.0,-30.0,299.0,1.5436,269.0,6.0745,299.0,2.4431,236.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=0:BME680:breathVocEquivalent MAX value VOC ...,1.50536,1.541913,4.53166,5.938517,2.38429,2.439926,3.22484,5.639461,0.830100,0.003192,0.938300,0.004927,0.278667,0.009215,-2.95,3.5,"(-2.95, 3.5)",-1.85,3.5,-0.5,1.70,-2.25,0.40
256,InsertingSourcePollutant,None,None,None,1.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:18:43,2025-10-24 21:17:10,2025-10-24 21:24:48,2025-10-24,2025-10-24 21:17:12,2025-10-24 21:24:46,0 days 00:07:34,0 days 00:01:32,92.0,0 days 00:06:02,0 days 00:01:32,92.0,362.0,454.0,270.0,-30.0,299.0,2.0029,299.0,13.3480,277.0,2.0105,141.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=0:BME680:breathVocEquivalent MAX value VOC ...,1.27778,1.931717,13.17579,13.337491,1.89556,2.009913,10.16265,13.288696,0.130833,0.003005,1.964067,0.021602,0.356100,0.002903,-2.95,2.5,"(-2.95, 2.5)",-1.85,3.5,-0.5,1.70,-2.25,0.40
257,InsertingSourcePollutant,None,None,None,2.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:34:58,2025-10-24 21:33:44,2025-10-24 21:41:06,2025-10-24,2025-10-24 21:33:46,2025-10-24 21:41:04,0 days 00:07:18,0 days 00:01:13,73.0,0 days 00:06:05,0 days 00:01:13,73.0,365.0,438.0,270.0,-30.0,299.0,1.8114,299.0,7.5793,261.0,1.2671,299.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,1.71769,1.786738,7.36787,7.576884,1.24307,1.262000,6.72750,7.545522,0.316533,0.002780,0.425500,0.012363,0.281700,0.004330,-2.95,1.5,"(-2.95, 1.5)",-1.85,3.5,-0.5,1.70,-2.25,0.40
258,InsertingSourcePollutant,None,None,None,3.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:54:05,2025-10-24 21:52:16,2025-10-24 22:01:25,2025-10-24,2025-10-24 21:52:18,2025-10-24 22:01:24,0 days 00:09:06,0 days 00:01:48,108.0,0 days 00:07:18,0 days 00:01:48,108.0,438.0,546.0,270.0,-30.0,299.0,1.6312,213.0,3.3710,287.0,2.1139,299.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=0:BME680:breathVocEquivalent MAX value VOC ...,1.57461,1.630197,3.24331,3.369713,1.76254,2.072233,2.77298,3.363343,0.104633,-0.002098,0.727733,0.008225,0.324233,0.004552,-2.95,0.5,"(-2.95, 0.5)",-1.85,3.5,-0.5,1.70,-2.25,0.40

In [85]:
pos_id_all

['position of Id=0:BME680:breathVocEquivalent',
 'position of Id=1:BME680:breathVocEquivalent',
 'position of Id=2:BME680:breathVocEquivalent']

In [86]:
pos_id0 = 'position of Id=0:BME680:breathVocEquivalent'
pos_id1 = 'position of Id=1:BME680:breathVocEquivalent'
pos_id2 = 'position of Id=2:BME680:breathVocEquivalent'
pos_id_all = [pos_id0,pos_id1,pos_id2]

for pos in pos_id_all:
    column_to_create = pos +" x-y axis"
    userInputData.loc[:,column_to_create] = list(zip(userInputData.loc[:,pos+"-x axis"], userInputData.loc[:,pos + "-y axis"]))

C:\Users\Andreas\AppData\Local\Temp\ipykernel_11096\641594831.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  userInputData.loc[:,column_to_create] = list(zip(userInputData.loc[:,pos+"-x axis"], userInputData.loc[:,pos + "-y axis"]))
C:\Users\Andreas\AppData\Local\Temp\ipykernel_11096\641594831.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  userInputData.loc[:,column_to_create] = list(zip(userInputData.loc[:,pos+"-x axis"], userInputData.loc[:,pos + "-y axis"]))
C:\Users\Andreas\AppData\Local\Temp\ipykernel_11096\641594831.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  userInputData.loc[:,column_to_create] = list(zip(userInputData.loc[:,pos+"-x axis"], userInputData.loc[:,pos + "-y axis"]))

In [87]:
x_axis_source = userInputData["x-y axis"].to_numpy()
x_axis_source

array([(-2.25, 3.0), (-2.25, 3.0), (-2.25, 3.6), (-1.45, 3.0),
       (-1.85, 2.6), (-1.45, 3.0), (-2.15, 2.2), (-2.15, 2.2),
       (-2.15, 2.2), (-2.15, 2.2), (-2.15, 2.2), (-2.15, 2.2),
       (-2.15, 2.2), (-2.15, 2.2), (-2.15, 2.2), (-2.15, 2.2),
       (-2.15, 2.2), (-2.15, 2.2), (-2.15, 2.2), (-2.15, 2.2),
       (-2.15, 2.2), (-2.15, 2.2), (-2.15, 2.2), (-2.15, 2.2),
       (-2.15, 2.2), (-2.15, 2.2), (-2.15, 2.2), (-2.05, 1.2),
       (-2.05, 1.2), (-2.05, 1.2), (-2.05, 1.2), (-2.05, 1.2),
       (-2.05, 1.2), (-2.05, 1.2), (-2.05, 1.2), (-2.95, 1.7),
       (-2.95, 1.7), (-2.95, 1.7), (-2.95, 1.7), (-0.6, 2.0), (-0.6, 2.0),
       (-0.6, 2.0), (-0.6, 2.0), (-0.6, 2.0), (-2.15, 2.2), (-2.05, 1.2),
       (-2.05, 1.2), (-2.05, 1.2), (-2.05, 1.2), (-2.05, 1.2),
       (-0.6, 2.0), (-0.6, 2.0), (-0.6, 2.0), (-0.6, 2.0), (-0.6, 2.0),
       (-2.95, 1.7), (-2.95, 1.7), (-2.95, 1.7), (-2.95, 1.7),
       (-2.95, 1.7), (-2.95, 1.7), (-2.95, 1.7), (nan, nan), (-1.85, 3.2),
       (-1.85, 3.2), (-1.85, 3.2), (nan, nan), (-1.85, 3.2), (-1.85, 3.2),
       (-2.65, 0.6), (nan, nan), (-1.85, 3.2), (-2.65, 0.6), (-1.0, 0.8),
       (-2.25, 1.8), (-0.9, 3.3), (-2.65, 3.4), (nan, nan), (-2.15, 2.0),
       (-1.35, 2.0), (-1.35, 1.5), (-1.35, 1.0), (-1.85, 1.0),
       (-1.85, 1.5), (nan, nan), (-0.5, 3.5), (-0.5, 2.5), (nan, nan),
       (-0.5, 3.5), (-0.5, 2.5), (-0.5, 1.5), (-0.5, 0.5), (-1.5, 0.5),
       (-1.5, 1.5), (-1.5, 2.5), (-1.5, 3.5), (-2.5, 3.5), (-2.5, 2.5),
       (-2.5, 0.5), (-2.95, 0.5), (-2.95, 1.5), (-2.95, 2.5), (nan, nan),
       (-2.95, 3.5), (-2.95, 2.5), (-2.95, 1.5), (-2.95, 0.5),
       (-2.5, 0.5), (-2.5, 1.5), (-2.5, 2.5), (-2.5, 3.5), (-1.5, 3.5),
       (-1.5, 2.5), (-1.5, 1.5), (-1.5, 0.5), (-0.5, 0.5), (-0.5, 1.5),
       (-0.5, 2.5), (-0.5, 3.5), (nan, nan), (-0.5, 3.5), (-0.5, 3.5),
       (-0.5, 2.5), (-0.5, 1.5), (-0.5, 0.5), (-1.5, 0.5), (nan, nan),
       (-0.5, 3.5), (-0.5, 2.5), (nan, nan), (-0.5, 1.5), (-0.5, 0.5),
       (-1.5, 0.5), (-1.5, 1.5), (-1.5, 2.5), (-1.5, 3.5), (-2.5, 3.5),
       (nan, nan), (-2.5, 2.5), (-2.5, 1.5), (-2.5, 0.5), (-2.95, 0.5),
       (-2.95, 1.5), (nan, nan), (-2.95, 2.5), (-2.95, 3.5), (-0.5, 3.5),
       (-0.5, 2.5), (-0.5, 1.5), (-0.5, 0.5), (-1.5, 0.5), (-1.5, 1.5),
       (-1.5, 2.5), (-1.5, 3.5), (-2.5, 3.5), (-2.5, 2.5), (-2.5, 1.5),
       (-2.5, 0.5), (-2.95, 0.5), (nan, nan), (-2.75, 1.8), (-2.95, 1.5),
       (-2.95, 2.5), (-2.95, 3.5), (nan, nan), (-2.75, 1.8), (-2.95, 1.5),
       (-2.5, 1.5), (-1.5, 1.5), (-0.5, 1.5), (-0.5, 0.5), (-1.5, 0.5),
       (-2.5, 0.5), (-2.95, 0.5), (-2.95, 2.5), (-2.5, 2.5), (-1.5, 2.5),
       (-0.5, 2.5), (-0.5, 3.5), (-1.5, 3.5), (-2.5, 3.5), (-2.95, 3.5),
       (-2.95, 3.5), (-2.5, 3.5), (-1.5, 3.5), (nan, nan), (-2.75, 1.8),
       (-2.75, 1.8), (-0.5, 3.5), (-0.5, 2.5), (-1.5, 2.5), (-2.5, 2.5),
       (-2.95, 2.5), (-2.95, 1.5), (-2.5, 1.5), (-1.5, 1.5), (-0.5, 1.5),
       (-0.5, 0.5), (-1.5, 0.5), (-2.5, 0.5), (-2.95, 0.5), (nan, nan),
       (-2.75, 1.8), (-0.5, 3.5), (-0.5, 2.5), (-0.5, 1.5), (-0.5, 0.5),
       (-1.5, 0.5), (-1.5, 1.5), (-1.5, 2.5), (-1.5, 3.5), (-2.5, 3.5),
       (-2.5, 2.5), (-2.5, 1.5), (-2.5, 0.5), (-2.95, 0.5), (-2.95, 1.5),
       (-2.95, 2.5), (-2.95, 3.5), (nan, nan), (nan, nan), (-2.75, 2.2),
       (-2.95, 1.5), (-2.5, 1.5), (-1.5, 1.5), (-0.5, 1.5), (-0.5, 2.5),
       (-1.5, 2.5), (-2.5, 2.5), (-2.95, 2.5), (-0.5, 0.5), (-1.5, 0.5),
       (-2.5, 0.5), (-2.95, 0.5), (-0.5, 3.5), (-1.5, 3.5), (-2.5, 3.5),
       (-2.95, 3.5), (nan, nan), (-2.75, 2.2), (nan, nan), (-1.5, 1.5),
       (-1.5, 0.5), (-1.5, 2.5), (-1.5, 3.5), (-2.5, 3.5), (-2.5, 2.5),
       (-2.5, 1.5), (-2.5, 0.5), (-0.5, 0.5), (-0.5, 1.5), (-0.5, 2.5),
       (-0.5, 3.5), (-2.95, 3.5), (-2.95, 2.5), (-2.95, 1.5),
       (-2.95, 0.5)], dtype=object)

In [88]:
userInputData

,experimentState,are-doors-opened,are-people-inside,are-windows-opened,front-wall,item-used,notes,room,side-right-wall,back-wall,side-left-wall,are-fans-on,no-source-located,timestamp InsertingSource,timestamp StartingExperiment,timestamp EndingExperiment,date of experiment,actual timestamp StartingExperiment,actual timestamp EndingExperiment,time taken total,timestamp InsertingSource timedelta,timestamp InsertingSource seconds,time taken after insertion,time taken before insertion,time taken before insertion (seconds),time taken after insertion (seconds),time taken total (seconds),time taken total (seconds)-capped,time taken before insertion (seconds)-capped,time taken after insertion (seconds)-capped,Id=1:BME680:breathVocEquivalent MAX value VOC rolling average,Id=1:BME680:breathVocEquivalent index of MAX value VOC rolling average,Id=2:BME680:breathVocEquivalent MAX value VOC rolling average,Id=2:BME680:breathVocEquivalent index of MAX value VOC rolling average,Id=0:BME680:breathVocEquivalent MAX value VOC rolling average,Id=0:BME680:breathVocEquivalent index of MAX value VOC rolling average,sensor with MAX value experiment,sensor with second MAX value experiment,Id=1:BME680:breathVocEquivalent quantile 90.0% VOC rolling average,Id=1:BME680:breathVocEquivalent quantile 99.0% VOC rolling average,Id=2:BME680:breathVocEquivalent quantile 90.0% VOC rolling average,Id=2:BME680:breathVocEquivalent quantile 99.0% VOC rolling average,Id=0:BME680:breathVocEquivalent quantile 90.0% VOC rolling average,Id=0:BME680:breathVocEquivalent quantile 99.0% VOC rolling average,whole experiment quantile 90.0% VOC rolling average,whole experiment quantile 99.0% VOC rolling average,Id=1:BME680:breathVocEquivalent VOC mean calm period,Id=1:BME680:breathVocEquivalent VOC gradient mean calm period,Id=2:BME680:breathVocEquivalent VOC mean calm period,Id=2:BME680:breathVocEquivalent VOC gradient mean calm period,Id=0:BME680:breathVocEquivalent VOC mean calm period,Id=0:BME680:breathVocEquivalent VOC gradient mean calm period,x axis,y axis,x-y axis,position of Id=0:BME680:breathVocEquivalent-x axis,position of Id=0:BME680:breathVocEquivalent-y axis,position of Id=1:BME680:breathVocEquivalent-x axis,position of Id=1:BME680:breathVocEquivalent-y axis,position of Id=2:BME680:breathVocEquivalent-x axis,position of Id=2:BME680:breathVocEquivalent-y axis,position of Id=0:BME680:breathVocEquivalent x-y axis,position of Id=1:BME680:breathVocEquivalent x-y axis,position of Id=2:BME680:breathVocEquivalent x-y axis
0,InsertingSourcePollutant,on,None,None,1.0,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.0,None,None,2025-07-01 16:09:41,2025-07-01 15:27:16,2025-07-01 16:14:44,2025-07-01,2025-07-01 15:27:19,2025-07-01 16:14:42,0 days 00:47:23,0 days 00:42:23,2543.0,0 days 00:05:00,0 days 00:42:23,2543.0,300.0,2843.0,270.0,-30.0,299.0,4.3501,299.0,8.1928,243.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,4.10260,4.342653,8.13641,8.191397,NaN,NaN,8.03289,8.186653,1.338333,0.000302,5.003467,0.001410,NaN,NaN,-2.25,3.0,"(-2.25, 3.0)",NaN,NaN,2.4,3.05,1.70,3.05,"(nan, nan)","(2.4, 3.05)","(1.7, 3.05)"
1,InsertingSourcePollutant,on,None,None,1.0,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.0,None,None,2025-07-02 15:59:29,2025-07-02 15:42:50,2025-07-02 16:04:52,2025-07-02,2025-07-02 15:42:50,2025-07-02 16:04:50,0 days 00:22:00,0 days 00:16:40,1000.0,0 days 00:05:20,0 days 00:16:40,1000.0,320.0,1320.0,270.0,-30.0,299.0,1.1333,201.0,0.3304,80.0,NaN,NaN,Id=1:BME680:breathVocEquivalent MAX value VOC ...,Id=2:BME680:breathVocEquivalent MAX value VOC ...,0.96260,1.130830,0.30518,0.330042,NaN,NaN,0.74384,1.123456,0.050000,-0.000188,0.149700,0.002748,NaN,NaN,-2.25,3.0,"(-2.25, 3.0)",NaN,NaN,2.4,3.05,1.70,3.05,"(nan, nan)","(2.4, 3.05)","(1.7, 3.05)"
2,InsertingSourcePollutant,on,None,None,0.4,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.0,None,None,2025-07-03 12:34:32,2025-07-03 12:30:25,2025-07-03 12:45:31,2025-07-03,2025-07-03 12:30:25,2025-07-03 12:45:31,0 days 00:15:06,0 days 00:04:08,248.0,0 days 00:10:58,0 days 00:04:08,248.0,658.0,906.0,270.0,-30.0,299.0,1.3923,235.0,2.2994,299.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,1.34093,1.390726,1.62716,2.182643,NaN,NaN,1.46438,2.073907,0.133633,-0.003248,0.412300,-0.007478,NaN,NaN,-2.25,3.6,"(-2.25, 3.6)",NaN,NaN,2.4,3.05,1.70,3.05,"(nan, nan)","(2.4, 3.05)","(1.7, 3.05)"
3,InsertingSourcePollutant,on,None,None,1.0,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.8,None,None,2025-07-03 15:53:07,2025-07-03 15:43:27,2025-07-03 15:59:11,2025-07-03,2025-07-03 15:51:40,2025-07-03 15:59:10,0 days 00:07:30,0 days 00:01:28,88.0,0 days 00:06:02,0 days 00:01:28,88.0,362.0,450.0,270.0,-30.0,299.0,0.3439,299.0,18.4943,299.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.26763,0.334346,16.09553,17.771554,NaN,NaN,6.84825,17.295804,0.027200,0.000002,0.505133,0.005152,NaN,NaN,-1.45,3.0,"(-1.45, 3.0)",NaN,NaN,2.4,3.05,1.70,3.05,"(nan, nan)","(2.4, 3.05)","(1.7, 3.05)"
4,InsertingSourcePollutant,on,None,None,1.4,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.4,None,None,2025-07-09 19:19:19,2025-07-09 19:01:42,2025-07-09 19:27:50,2025-07-09,2025-07-09 19:01:44,2025-07-09 19:27:49,0 days 00:26:05,0 days 00:17:36,1056.0,0 days 00:08:29,0 days 00:17:36,1056.0,509.0,1565.0,270.0,-30.0,299.0,0.6066,246.0,0.7315,299.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.58644,0.606300,0.70629,0.726681,NaN,NaN,0.62712,0.723846,0.030767,-0.000302,0.343333,-0.000157,NaN,NaN,-1.85,2.6,"(-1.85, 2.6)",NaN,NaN,2.4,3.05,1.70,3.05,"(nan, nan)","(2.4, 3.05)","(1.7, 3.05)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
254,InsertingSourcePollutant,None,None,None,0.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",0.5,NaN,NaN,None,None,2025-10-24 20:32:03,2025-10-24 20:29:36,2025-10-24 20:37:33,2025-10-24,2025-10-24 20:29:37,2025-10-24 20:37:31,0 days 00:07:54,0 days 00:02:27,147.0,0 days 00:05:27,0 days 00:02:27,147.0,327.0,474.0,270.0,-30.0,299.0,2.0134,131.0,4.9923,299.0,2.8096,286.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=0:BME680:breathVocEquivalent MAX value VOC ...,1.85013,2.010252,4.58879,4.944112,2.74257,2.806868,3.70824,4.844487,0.384700,-0.004535,0.790767,0.014290,1.095967,-0.005078,-0.50,3.5,"(-0.5, 3.5)",-1.85,3.5,-0.5,1.70,-2.25,0.40,"(-1.85, 3.5)","(-0.5, 1.7)","(-2.25, 0.4)"
255,InsertingSourcePollutant,None,None,None,0.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:05:46,2025-10-24 21:03:22,2025-10-24 21:11:21,2025-10-24,2025-10-24 21:03:24,2025-10-24 21:11:19,0 days 00:07:55,0 days 00:02:23,143.0,0 days 00:05:32,0 days 00:02:23,143.0,332.0,475.0,270.0,-30.0,299.0,1.5436,269.0,6.0745,299.0,2.4431,236.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=0:BME680:breathVocEquivalent MAX value VOC ...,1.50536,1.541913,4.53166,5.938517,2.38429,2.439926,3.22484,5.639461,0.830100,0.003192,0.938300,0.004927,0.278667,0.009215,-2.95,3.5,"(-2.95, 3.5)",-1.85,3.5,-0.5,1.70,-2.25,0.40,"(-1.85, 3.5)","(-0.5, 1.7)","(-2.25, 0.4)"
256,InsertingSourcePollutant,None,None,None,1.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:18:43,2025-10-24 21:17:10,2025-10-24 21:24:48,2025-10-24,2025-10-24 21:17:12,2025-10-24 21:24:46,0 days 00:07:34,0 days 00:01:32,92.0,0 days 00:06:02,0 days 00:01:32,92.0,362.0,454.0,270.0,-30.0,299.0,2.0029,299.0,13.3480,277.0,2.0105,141.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=0:BME680:breathVocEquivalent MAX value VOC ...,1.27778,1.931717,13.17579,13.337491,1.89556,2.009913,10.16265,13.288696,0.130833,0.003005,1.964067,0.021602,0.356100,0.002903,-2.95,2.5,"(-2.95, 2.5)",-1.85,3.5,-0.5,1.70,-2.25,0.40,"(-1.85, 3.5)","(-0.5, 1.7)","(-2.25, 0.4)"
257,InsertingSourcePollutant,None,None,None,2.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:34:58,2025-10-24 21:33:44,2025-10-24 21:41:06,2025-10-24,2025-10-24 21:33:46,2025-10-24 21:41:04,0 days 00:07:18,0 days 00:01:13,73.0,0 days 00:06:05,0 days 00:01:13,73.0,365.0,438.0,270.0,-30.0,299.0,1.8114,299.0,7.5793,261.0,1.2671,299.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,1.71769,1.786738,7.36787,7.576884,1.24307,1.262000,6.72750,7.545522,0.316533,0.002780,0.425500,0.012363,0.281700,0.004330,-2.95,1.5,"(-2.95, 1.5)",-1.85,3.5,-0.5,1.70,-2.25,0.40,"(-1.85, 3.5)","(-0.5, 1.7)","(-2.25, 0.4)"
258,InsertingSourcePollutant,None,None,None,3.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:54:05,2025-10-24 21:52:16,2025-10-24 22:01:25,2025-10-24,2025-10-24 21:52:18,2025-10-24 22:01:24,0 days 00:09:06,0 days 00:01:48,108.0,0 days 00:07:18,0 days 00:01:48,108.0,438.0,546.0,270.0,-30.0,299.0,1.6312,213.0,3.3710,287.0,2.1139,299.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=0:BME680:breathVocEquivalent MAX value VOC ...,1.57461,1.630197,3.24331,3.369713,1.76254,2.072233,2.77298,3.363343,0.104633,-0.002098,0.727733,0.008225,0.324233,0.004552,-2.95,0.5,"(-2.95, 0.5)",-1.85,3.5,-0.5,1.70,-2.25,0.40,"(-1.85, 3.5)","(-0.5, 1.7)","(-2.25, 0.4)"

In [93]:
#find euclidian distance between sensors position and source

y_axis_source = userInputData["y axis"].to_numpy()
source_position_name = "x-y axis"
source_position_column = np.array(userInputData[source_position_name].tolist())

for id_sensor_number in range(3):
    sensor_name = "Id="+str(id_sensor_number)+":BME680:breathVocEquivalent"
    sensor_position_name = "position of "+ sensor_name + " x-y axis"
    sensor_position_column = np.array(userInputData[sensor_position_name].tolist())
    distances = np.linalg.norm(
        source_position_column - sensor_position_column,
        axis=1
    )
    var_name = "Euclidian distance to "+sensor_name
    userInputData.loc[:,var_name] = distances
    #round the distance
    userInputData.loc[:,var_name] = userInputData.loc[:,var_name].round(2)

In [94]:

userInputData

,experimentState,are-doors-opened,are-people-inside,are-windows-opened,front-wall,item-used,notes,room,side-right-wall,back-wall,side-left-wall,are-fans-on,no-source-located,timestamp InsertingSource,timestamp StartingExperiment,timestamp EndingExperiment,date of experiment,actual timestamp StartingExperiment,actual timestamp EndingExperiment,time taken total,timestamp InsertingSource timedelta,timestamp InsertingSource seconds,time taken after insertion,time taken before insertion,time taken before insertion (seconds),time taken after insertion (seconds),time taken total (seconds),time taken total (seconds)-capped,time taken before insertion (seconds)-capped,time taken after insertion (seconds)-capped,Id=1:BME680:breathVocEquivalent MAX value VOC rolling average,Id=1:BME680:breathVocEquivalent index of MAX value VOC rolling average,Id=2:BME680:breathVocEquivalent MAX value VOC rolling average,Id=2:BME680:breathVocEquivalent index of MAX value VOC rolling average,Id=0:BME680:breathVocEquivalent MAX value VOC rolling average,Id=0:BME680:breathVocEquivalent index of MAX value VOC rolling average,sensor with MAX value experiment,sensor with second MAX value experiment,Id=1:BME680:breathVocEquivalent quantile 90.0% VOC rolling average,Id=1:BME680:breathVocEquivalent quantile 99.0% VOC rolling average,Id=2:BME680:breathVocEquivalent quantile 90.0% VOC rolling average,Id=2:BME680:breathVocEquivalent quantile 99.0% VOC rolling average,Id=0:BME680:breathVocEquivalent quantile 90.0% VOC rolling average,Id=0:BME680:breathVocEquivalent quantile 99.0% VOC rolling average,whole experiment quantile 90.0% VOC rolling average,whole experiment quantile 99.0% VOC rolling average,Id=1:BME680:breathVocEquivalent VOC mean calm period,Id=1:BME680:breathVocEquivalent VOC gradient mean calm period,Id=2:BME680:breathVocEquivalent VOC mean calm period,Id=2:BME680:breathVocEquivalent VOC gradient mean calm period,Id=0:BME680:breathVocEquivalent VOC mean calm period,Id=0:BME680:breathVocEquivalent VOC gradient mean calm period,x axis,y axis,x-y axis,position of Id=0:BME680:breathVocEquivalent-x axis,position of Id=0:BME680:breathVocEquivalent-y axis,position of Id=1:BME680:breathVocEquivalent-x axis,position of Id=1:BME680:breathVocEquivalent-y axis,position of Id=2:BME680:breathVocEquivalent-x axis,position of Id=2:BME680:breathVocEquivalent-y axis,position of Id=0:BME680:breathVocEquivalent x-y axis,position of Id=1:BME680:breathVocEquivalent x-y axis,position of Id=2:BME680:breathVocEquivalent x-y axis,Euclidian distance to Id=0:BME680:breathVocEquivalent,Euclidian distance to Id=1:BME680:breathVocEquivalent,Euclidian distance to Id=2:BME680:breathVocEquivalent
0,InsertingSourcePollutant,on,None,None,1.0,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.0,None,None,2025-07-01 16:09:41,2025-07-01 15:27:16,2025-07-01 16:14:44,2025-07-01,2025-07-01 15:27:19,2025-07-01 16:14:42,0 days 00:47:23,0 days 00:42:23,2543.0,0 days 00:05:00,0 days 00:42:23,2543.0,300.0,2843.0,270.0,-30.0,299.0,4.3501,299.0,8.1928,243.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,4.10260,4.342653,8.13641,8.191397,NaN,NaN,8.03289,8.186653,1.338333,0.000302,5.003467,0.001410,NaN,NaN,-2.25,3.0,"(-2.25, 3.0)",NaN,NaN,2.4,3.05,1.70,3.05,"(nan, nan)","(2.4, 3.05)","(1.7, 3.05)",NaN,4.65,3.95
1,InsertingSourcePollutant,on,None,None,1.0,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.0,None,None,2025-07-02 15:59:29,2025-07-02 15:42:50,2025-07-02 16:04:52,2025-07-02,2025-07-02 15:42:50,2025-07-02 16:04:50,0 days 00:22:00,0 days 00:16:40,1000.0,0 days 00:05:20,0 days 00:16:40,1000.0,320.0,1320.0,270.0,-30.0,299.0,1.1333,201.0,0.3304,80.0,NaN,NaN,Id=1:BME680:breathVocEquivalent MAX value VOC ...,Id=2:BME680:breathVocEquivalent MAX value VOC ...,0.96260,1.130830,0.30518,0.330042,NaN,NaN,0.74384,1.123456,0.050000,-0.000188,0.149700,0.002748,NaN,NaN,-2.25,3.0,"(-2.25, 3.0)",NaN,NaN,2.4,3.05,1.70,3.05,"(nan, nan)","(2.4, 3.05)","(1.7, 3.05)",NaN,4.65,3.95
2,InsertingSourcePollutant,on,None,None,0.4,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.0,None,None,2025-07-03 12:34:32,2025-07-03 12:30:25,2025-07-03 12:45:31,2025-07-03,2025-07-03 12:30:25,2025-07-03 12:45:31,0 days 00:15:06,0 days 00:04:08,248.0,0 days 00:10:58,0 days 00:04:08,248.0,658.0,906.0,270.0,-30.0,299.0,1.3923,235.0,2.2994,299.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,1.34093,1.390726,1.62716,2.182643,NaN,NaN,1.46438,2.073907,0.133633,-0.003248,0.412300,-0.007478,NaN,NaN,-2.25,3.6,"(-2.25, 3.6)",NaN,NaN,2.4,3.05,1.70,3.05,"(nan, nan)","(2.4, 3.05)","(1.7, 3.05)",NaN,4.68,3.99
3,InsertingSourcePollutant,on,None,None,1.0,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.8,None,None,2025-07-03 15:53:07,2025-07-03 15:43:27,2025-07-03 15:59:11,2025-07-03,2025-07-03 15:51:40,2025-07-03 15:59:10,0 days 00:07:30,0 days 00:01:28,88.0,0 days 00:06:02,0 days 00:01:28,88.0,362.0,450.0,270.0,-30.0,299.0,0.3439,299.0,18.4943,299.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.26763,0.334346,16.09553,17.771554,NaN,NaN,6.84825,17.295804,0.027200,0.000002,0.505133,0.005152,NaN,NaN,-1.45,3.0,"(-1.45, 3.0)",NaN,NaN,2.4,3.05,1.70,3.05,"(nan, nan)","(2.4, 3.05)","(1.7, 3.05)",NaN,3.85,3.15
4,InsertingSourcePollutant,on,None,None,1.4,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.4,None,None,2025-07-09 19:19:19,2025-07-09 19:01:42,2025-07-09 19:27:50,2025-07-09,2025-07-09 19:01:44,2025-07-09 19:27:49,0 days 00:26:05,0 days 00:17:36,1056.0,0 days 00:08:29,0 days 00:17:36,1056.0,509.0,1565.0,270.0,-30.0,299.0,0.6066,246.0,0.7315,299.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.58644,0.606300,0.70629,0.726681,NaN,NaN,0.62712,0.723846,0.030767,-0.000302,0.343333,-0.000157,NaN,NaN,-1.85,2.6,"(-1.85, 2.6)",NaN,NaN,2.4,3.05,1.70,3.05,"(nan, nan)","(2.4, 3.05)","(1.7, 3.05)",NaN,4.27,3.58
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
254,InsertingSourcePollutant,None,None,None,0.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",0.5,NaN,NaN,None,None,2025-10-24 20:32:03,2025-10-24 20:29:36,2025-10-24 20:37:33,2025-10-24,2025-10-24 20:29:37,2025-10-24 20:37:31,0 days 00:07:54,0 days 00:02:27,147.0,0 days 00:05:27,0 days 00:02:27,147.0,327.0,474.0,270.0,-30.0,299.0,2.0134,131.0,4.9923,299.0,2.8096,286.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=0:BME680:breathVocEquivalent MAX value VOC ...,1.85013,2.010252,4.58879,4.944112,2.74257,2.806868,3.70824,4.844487,0.384700,-0.004535,0.790767,0.014290,1.095967,-0.005078,-0.50,3.5,"(-0.5, 3.5)",-1.85,3.5,-0.5,1.70,-2.25,0.40,"(-1.85, 3.5)","(-0.5, 1.7)","(-2.25, 0.4)",1.35,1.80,3.56
255,InsertingSourcePollutant,None,None,None,0.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:05:46,2025-10-24 21:03:22,2025-10-24 21:11:21,2025-10-24,2025-10-24 21:03:24,2025-10-24 21:11:19,0 days 00:07:55,0 days 00:02:23,143.0,0 days 00:05:32,0 days 00:02:23,143.0,332.0,475.0,270.0,-30.0,299.0,1.5436,269.0,6.0745,299.0,2.4431,236.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=0:BME680:breathVocEquivalent MAX value VOC ...,1.50536,1.541913,4.53166,5.938517,2.38429,2.439926,3.22484,5.639461,0.830100,0.003192,0.938300,0.004927,0.278667,0.009215,-2.95,3.5,"(-2.95, 3.5)",-1.85,3.5,-0.5,1.70,-2.25,0.40,"(-1.85, 3.5)","(-0.5, 1.7)","(-2.25, 0.4)",1.10,3.04,3.18
256,InsertingSourcePollutant,None,None,None,1.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:18:43,2025-10-24 21:17:10,2025-10-24 21:24:48,2025-10-24,2025-10-24 21:17:12,2025-10-24 21:24:46,0 days 00:07:34,0 days 00:01:32,92.0,0 days 00:06:02,0 days 00:01:32,92.0,362.0,454.0,270.0,-30.0,299.0,2.0029,299.0,13.3480,277.0,2.0105,141.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=0:BME680:breathVocEquivalent MAX value VOC ...,1.27778,1.931717,13.17579,13.337491,1.89556,2.009913,10.16265,13.288696,0.130833,0.003005,1.964067,0.021602,0.356100,0.002903,-2.95,2.5,"(-2.95, 2.5)",-1.85,3.5,-0.5,1.70,-2.25,0.40,"(-1.85, 3.5)","(-0.5, 1.7)","(-2.25, 0.4)",1.49,2.58,2.21
257,InsertingSourcePollutant,None,None,None,2.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:34:58,2025-10-24 21:33:44,2025-10-24 21:41:06,2025-10-24,2025-10-24 21:33:46,2025-10-24 21:41:04,0 days 00:07:18,0 days 00:01:13,73.0,0 days 00:06:05,0 days 00:01:13,73.0,365.0,438.0,270.0,-30.0,299.0,1.8114,299.0,7.5793,261.0,1.2671,299.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,1.71769,1.786738,7.36787,7.576884,1.24307,1.262000,6.72750,7.545522,0.316533,0.002780,0.425500,0.012363,0.281700,0.004330,-2.95,1.5,"(-2.95, 1.5)",-1.85,3.5,-0.5,1.70,-2.25,0.40,"(-1.85, 3.5)","(-0.5, 1.7)","(-2.25, 0.4)",2.28,2.46,1.30
258,InsertingSourcePollutant,None,None,None,3.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:54:05,2025-10-24 21:52:16,2025-10-24 22:01:25,2025-10-24,2025-10-24 21:52:18,2025-10-24 22:01:24,0 days 00:09:06,0 days 00:01:48,108.0,0 days 00:07:18,0 days 00:01:48,108.0,438.0,546.0,270.0,-30.0,299.0,1.6312,213.0,3.3710,287.0,2.1139,299.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=0:BME680:breathVocEquivalent MAX value VOC ...,1.57461,1.630197,3.24331,3.369713,1.76254,2.072233,2.77298,3.363343,0.104633,-0.002098,0.727733,0.008225,0.324233,0.004552,-2.95,0.5,"(-2.95, 0.5)",-1.85,3.5,-0.5,1.70,-2.25,0.40,"(-1.85, 3.5)","(-0.5, 1.7)","(-2.25, 0.4)",3.20,2.73,0.71

In [95]:
print(dict_of_timeseries[157].max())
print(userInputData.loc[157])

sensors                                                        Id=2:BME680:breathVocEquivalent
VOC                                                                                      4.206
after_insertion                                                                           True
original_value                                                                            True
datetime_timestamp                                                         2025-10-13 22:32:46
timestamp                                                                      0 days 00:06:34
seconds                                                                                  299.0
seconds passed from insertionSource                                                      299.0
VOC original                                                                          5.655352
VOC rolling average                                                                     4.0522
original seconds                                                                         394.0
VOC-capped                                                                               4.206
VOC rolling average-capped                                                              4.0522
VOC gradient                                                                            0.0812
VOC rolling average gradient                                                            0.0812
VOC rolling average standard scaler whole experiment                                  2.970206
VOC rolling average-capped standard scaler whole experiment                           2.970206
dtype: object
experimentState                                          InsertingSourcePollutant
are-doors-opened                                                             None
are-people-inside                                                            None
are-windows-opened                                                           None
front-wall                                                                    1.5
                                                                   ...
position of Id=1:BME680:breathVocEquivalent x-y axis                  (-0.5, 1.7)
position of Id=2:BME680:breathVocEquivalent x-y axis                 (-2.25, 0.4)
Euclidian distance to Id=0:BME680:breathVocEquivalent                        1.19
Euclidian distance to Id=1:BME680:breathVocEquivalent                        2.15
Euclidian distance to Id=2:BME680:breathVocEquivalent                        2.11
Name: 157, Length: 67, dtype: object

### CREATE ROOM ARRAY THAT SHOWS FOR EACH POINT IN THE ARRAY THE CLOSEST GIVEN INSERTED POSITION

In [96]:
userInputData["room"].unique()

array(['Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55',
       'Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1',
       'Κρεβατοκάμαρα-Όλοι οι αισθητήρες μαζί Μ:0.80 , Α:0.90',
       'Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0.5  ,id:2 Π:0.4 Α:1.0',
       'Κρεβατοκάμαρα Όλοι οι αισθητήρες μαζί Π:1.80 , Δ:2.00'],
      dtype=object)

In [97]:
userInputData.columns

Index(['experimentState', 'are-doors-opened', 'are-people-inside',
       'are-windows-opened', 'front-wall', 'item-used', 'notes', 'room',
       'side-right-wall', 'back-wall', 'side-left-wall', 'are-fans-on',
       'no-source-located', 'timestamp InsertingSource',
       'timestamp StartingExperiment', 'timestamp EndingExperiment',
       'date of experiment', 'actual timestamp StartingExperiment',
       'actual timestamp EndingExperiment', 'time taken total',
       'timestamp InsertingSource timedelta',
       'timestamp InsertingSource seconds', 'time taken after insertion',
       'time taken before insertion', 'time taken before insertion (seconds)',
       'time taken after insertion (seconds)', 'time taken total (seconds)',
       'time taken total (seconds)-capped',
       'time taken before insertion (seconds)-capped',
       'time taken after insertion (seconds)-capped',
       'Id=1:BME680:breathVocEquivalent MAX value VOC rolling average',
       'Id=1:BME680:breathVocEquivalent index of MAX value VOC rolling average',
       'Id=2:BME680:breathVocEquivalent MAX value VOC rolling average',
       'Id=2:BME680:breathVocEquivalent index of MAX value VOC rolling average',
       'Id=0:BME680:breathVocEquivalent MAX value VOC rolling average',
       'Id=0:BME680:breathVocEquivalent index of MAX value VOC rolling average',
       'sensor with MAX value experiment',
       'sensor with second MAX value experiment',
       'Id=1:BME680:breathVocEquivalent quantile 90.0% VOC rolling average',
       'Id=1:BME680:breathVocEquivalent quantile 99.0% VOC rolling average',
       'Id=2:BME680:breathVocEquivalent quantile 90.0% VOC rolling average',
       'Id=2:BME680:breathVocEquivalent quantile 99.0% VOC rolling average',
       'Id=0:BME680:breathVocEquivalent quantile 90.0% VOC rolling average',
       'Id=0:BME680:breathVocEquivalent quantile 99.0% VOC rolling average',
       'whole experiment quantile 90.0% VOC rolling average',
       'whole experiment quantile 99.0% VOC rolling average',
       'Id=1:BME680:breathVocEquivalent VOC mean calm period',
       'Id=1:BME680:breathVocEquivalent VOC gradient mean calm period',
       'Id=2:BME680:breathVocEquivalent VOC mean calm period',
       'Id=2:BME680:breathVocEquivalent VOC gradient mean calm period',
       'Id=0:BME680:breathVocEquivalent VOC mean calm period',
       'Id=0:BME680:breathVocEquivalent VOC gradient mean calm period',
       'x axis', 'y axis', 'x-y axis',
       'position of Id=0:BME680:breathVocEquivalent-x axis',
       'position of Id=0:BME680:breathVocEquivalent-y axis',
       'position of Id=1:BME680:breathVocEquivalent-x axis',
       'position of Id=1:BME680:breathVocEquivalent-y axis',
       'position of Id=2:BME680:breathVocEquivalent-x axis',
       'position of Id=2:BME680:breathVocEquivalent-y axis',
       'position of Id=0:BME680:breathVocEquivalent x-y axis',
       'position of Id=1:BME680:breathVocEquivalent x-y axis',
       'position of Id=2:BME680:breathVocEquivalent x-y axis',
       'Euclidian distance to Id=0:BME680:breathVocEquivalent',
       'Euclidian distance to Id=1:BME680:breathVocEquivalent',
       'Euclidian distance to Id=2:BME680:breathVocEquivalent'],
      dtype='object')

In [98]:
room_mask = userInputData["room"] == 'Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0.5  ,id:2 Π:0.4 Α:1.0'
column_to_choose = 'x-y axis'
extra_conditions_mask = (
    userInputData['are-doors-opened'] != "on"
) & (
    ~userInputData[column_to_choose].apply(lambda t: any(pd.isna(x) for x in t))
)
mask = room_mask & extra_conditions_mask
print(userInputData.loc[mask,column_to_choose].unique())

[(-2.95, 2.5) (-2.95, 3.5) (-0.5, 3.5) (-0.5, 2.5) (-0.5, 1.5) (-0.5, 0.5)
 (-1.5, 0.5) (-1.5, 1.5) (-1.5, 2.5) (-1.5, 3.5) (-2.5, 3.5) (-2.5, 2.5)
 (-2.5, 1.5) (-2.5, 0.5) (-2.95, 0.5) (-2.95, 1.5)]

In [99]:


column_to_choose = 'x-y axis'

room_mask = userInputData["room"] == 'Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0.5  ,id:2 Π:0.4 Α:1.0'
extra_conditions_mask = (
    userInputData['are-doors-opened'] != "on"
) & (
    ~userInputData[column_to_choose].apply(lambda t: any(pd.isna(x) for x in t))
)
mask = room_mask & extra_conditions_mask


unique_sources_positions_df = pd.DataFrame({column_to_choose: userInputData.loc[mask,column_to_choose].unique()})

In [100]:
unique_sources_positions_df

        x-y axis
0   (-2.95, 2.5)
1   (-2.95, 3.5)
2    (-0.5, 3.5)
3    (-0.5, 2.5)
4    (-0.5, 1.5)
5    (-0.5, 0.5)
6    (-1.5, 0.5)
7    (-1.5, 1.5)
8    (-1.5, 2.5)
9    (-1.5, 3.5)
10   (-2.5, 3.5)
11   (-2.5, 2.5)
12   (-2.5, 1.5)
13   (-2.5, 0.5)
14  (-2.95, 0.5)
15  (-2.95, 1.5)

In [101]:


column_to_choose = 'x-y axis'

room_mask = userInputData["room"] == 'Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0.5  ,id:2 Π:0.4 Α:1.0'
extra_conditions_mask = (
    userInputData['are-doors-opened'] == "on"
) & (
    ~userInputData[column_to_choose].apply(lambda t: any(pd.isna(x) for x in t))
)
mask = room_mask & extra_conditions_mask


unique_sources_positions_df_open = pd.DataFrame({column_to_choose: userInputData.loc[mask,column_to_choose].unique()})

In [102]:
unique_sources_positions_df_open

        x-y axis
0   (-2.15, 2.0)
1   (-1.35, 2.0)
2   (-1.35, 1.5)
3   (-1.35, 1.0)
4   (-1.85, 1.0)
5   (-1.85, 1.5)
6    (-0.5, 3.5)
7    (-0.5, 2.5)
8    (-0.5, 1.5)
9    (-0.5, 0.5)
10   (-1.5, 0.5)
11   (-1.5, 1.5)
12   (-1.5, 2.5)
13   (-1.5, 3.5)
14   (-2.5, 3.5)
15   (-2.5, 2.5)
16   (-2.5, 0.5)
17  (-2.95, 0.5)
18  (-2.95, 1.5)
19  (-2.95, 2.5)
20  (-2.95, 3.5)
21   (-2.5, 1.5)

In [103]:
room_mask = userInputData["room"] == 'Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0.5  ,id:2 Π:0.4 Α:1.0'

print(f"the samples of open door room is {userInputData.loc[room_mask & (userInputData['are-doors-opened'] == 'on')].shape }")
print(f"the samples of open close room is {userInputData.loc[room_mask & (userInputData['are-doors-opened'] != 'on')].shape }")

the samples of open door room is (66, 67)
the samples of open close room is (102, 67)

In [104]:
import numpy as np

room_length = 4.0
room_width = 3.25

room_length_dimensions = int(room_length * 100)
room_width_dimensions = int(room_width * 100)

# create an array filled with NaN
room_area = np.full((room_width_dimensions, room_length_dimensions), np.nan)

print(room_area)

[[nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 ...
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]]

In [105]:
room_area

array([[nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       ...,
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan]])

## SAVE THE DATA

In [106]:
userInputData

,experimentState,are-doors-opened,are-people-inside,are-windows-opened,front-wall,item-used,notes,room,side-right-wall,back-wall,side-left-wall,are-fans-on,no-source-located,timestamp InsertingSource,timestamp StartingExperiment,timestamp EndingExperiment,date of experiment,actual timestamp StartingExperiment,actual timestamp EndingExperiment,time taken total,timestamp InsertingSource timedelta,timestamp InsertingSource seconds,time taken after insertion,time taken before insertion,time taken before insertion (seconds),time taken after insertion (seconds),time taken total (seconds),time taken total (seconds)-capped,time taken before insertion (seconds)-capped,time taken after insertion (seconds)-capped,Id=1:BME680:breathVocEquivalent MAX value VOC rolling average,Id=1:BME680:breathVocEquivalent index of MAX value VOC rolling average,Id=2:BME680:breathVocEquivalent MAX value VOC rolling average,Id=2:BME680:breathVocEquivalent index of MAX value VOC rolling average,Id=0:BME680:breathVocEquivalent MAX value VOC rolling average,Id=0:BME680:breathVocEquivalent index of MAX value VOC rolling average,sensor with MAX value experiment,sensor with second MAX value experiment,Id=1:BME680:breathVocEquivalent quantile 90.0% VOC rolling average,Id=1:BME680:breathVocEquivalent quantile 99.0% VOC rolling average,Id=2:BME680:breathVocEquivalent quantile 90.0% VOC rolling average,Id=2:BME680:breathVocEquivalent quantile 99.0% VOC rolling average,Id=0:BME680:breathVocEquivalent quantile 90.0% VOC rolling average,Id=0:BME680:breathVocEquivalent quantile 99.0% VOC rolling average,whole experiment quantile 90.0% VOC rolling average,whole experiment quantile 99.0% VOC rolling average,Id=1:BME680:breathVocEquivalent VOC mean calm period,Id=1:BME680:breathVocEquivalent VOC gradient mean calm period,Id=2:BME680:breathVocEquivalent VOC mean calm period,Id=2:BME680:breathVocEquivalent VOC gradient mean calm period,Id=0:BME680:breathVocEquivalent VOC mean calm period,Id=0:BME680:breathVocEquivalent VOC gradient mean calm period,x axis,y axis,x-y axis,position of Id=0:BME680:breathVocEquivalent-x axis,position of Id=0:BME680:breathVocEquivalent-y axis,position of Id=1:BME680:breathVocEquivalent-x axis,position of Id=1:BME680:breathVocEquivalent-y axis,position of Id=2:BME680:breathVocEquivalent-x axis,position of Id=2:BME680:breathVocEquivalent-y axis,position of Id=0:BME680:breathVocEquivalent x-y axis,position of Id=1:BME680:breathVocEquivalent x-y axis,position of Id=2:BME680:breathVocEquivalent x-y axis,Euclidian distance to Id=0:BME680:breathVocEquivalent,Euclidian distance to Id=1:BME680:breathVocEquivalent,Euclidian distance to Id=2:BME680:breathVocEquivalent
0,InsertingSourcePollutant,on,None,None,1.0,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.0,None,None,2025-07-01 16:09:41,2025-07-01 15:27:16,2025-07-01 16:14:44,2025-07-01,2025-07-01 15:27:19,2025-07-01 16:14:42,0 days 00:47:23,0 days 00:42:23,2543.0,0 days 00:05:00,0 days 00:42:23,2543.0,300.0,2843.0,270.0,-30.0,299.0,4.3501,299.0,8.1928,243.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,4.10260,4.342653,8.13641,8.191397,NaN,NaN,8.03289,8.186653,1.338333,0.000302,5.003467,0.001410,NaN,NaN,-2.25,3.0,"(-2.25, 3.0)",NaN,NaN,2.4,3.05,1.70,3.05,"(nan, nan)","(2.4, 3.05)","(1.7, 3.05)",NaN,4.65,3.95
1,InsertingSourcePollutant,on,None,None,1.0,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.0,None,None,2025-07-02 15:59:29,2025-07-02 15:42:50,2025-07-02 16:04:52,2025-07-02,2025-07-02 15:42:50,2025-07-02 16:04:50,0 days 00:22:00,0 days 00:16:40,1000.0,0 days 00:05:20,0 days 00:16:40,1000.0,320.0,1320.0,270.0,-30.0,299.0,1.1333,201.0,0.3304,80.0,NaN,NaN,Id=1:BME680:breathVocEquivalent MAX value VOC ...,Id=2:BME680:breathVocEquivalent MAX value VOC ...,0.96260,1.130830,0.30518,0.330042,NaN,NaN,0.74384,1.123456,0.050000,-0.000188,0.149700,0.002748,NaN,NaN,-2.25,3.0,"(-2.25, 3.0)",NaN,NaN,2.4,3.05,1.70,3.05,"(nan, nan)","(2.4, 3.05)","(1.7, 3.05)",NaN,4.65,3.95
2,InsertingSourcePollutant,on,None,None,0.4,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.0,None,None,2025-07-03 12:34:32,2025-07-03 12:30:25,2025-07-03 12:45:31,2025-07-03,2025-07-03 12:30:25,2025-07-03 12:45:31,0 days 00:15:06,0 days 00:04:08,248.0,0 days 00:10:58,0 days 00:04:08,248.0,658.0,906.0,270.0,-30.0,299.0,1.3923,235.0,2.2994,299.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,1.34093,1.390726,1.62716,2.182643,NaN,NaN,1.46438,2.073907,0.133633,-0.003248,0.412300,-0.007478,NaN,NaN,-2.25,3.6,"(-2.25, 3.6)",NaN,NaN,2.4,3.05,1.70,3.05,"(nan, nan)","(2.4, 3.05)","(1.7, 3.05)",NaN,4.68,3.99
3,InsertingSourcePollutant,on,None,None,1.0,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.8,None,None,2025-07-03 15:53:07,2025-07-03 15:43:27,2025-07-03 15:59:11,2025-07-03,2025-07-03 15:51:40,2025-07-03 15:59:10,0 days 00:07:30,0 days 00:01:28,88.0,0 days 00:06:02,0 days 00:01:28,88.0,362.0,450.0,270.0,-30.0,299.0,0.3439,299.0,18.4943,299.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.26763,0.334346,16.09553,17.771554,NaN,NaN,6.84825,17.295804,0.027200,0.000002,0.505133,0.005152,NaN,NaN,-1.45,3.0,"(-1.45, 3.0)",NaN,NaN,2.4,3.05,1.70,3.05,"(nan, nan)","(2.4, 3.05)","(1.7, 3.05)",NaN,3.85,3.15
4,InsertingSourcePollutant,on,None,None,1.4,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.4,None,None,2025-07-09 19:19:19,2025-07-09 19:01:42,2025-07-09 19:27:50,2025-07-09,2025-07-09 19:01:44,2025-07-09 19:27:49,0 days 00:26:05,0 days 00:17:36,1056.0,0 days 00:08:29,0 days 00:17:36,1056.0,509.0,1565.0,270.0,-30.0,299.0,0.6066,246.0,0.7315,299.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.58644,0.606300,0.70629,0.726681,NaN,NaN,0.62712,0.723846,0.030767,-0.000302,0.343333,-0.000157,NaN,NaN,-1.85,2.6,"(-1.85, 2.6)",NaN,NaN,2.4,3.05,1.70,3.05,"(nan, nan)","(2.4, 3.05)","(1.7, 3.05)",NaN,4.27,3.58
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
254,InsertingSourcePollutant,None,None,None,0.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",0.5,NaN,NaN,None,None,2025-10-24 20:32:03,2025-10-24 20:29:36,2025-10-24 20:37:33,2025-10-24,2025-10-24 20:29:37,2025-10-24 20:37:31,0 days 00:07:54,0 days 00:02:27,147.0,0 days 00:05:27,0 days 00:02:27,147.0,327.0,474.0,270.0,-30.0,299.0,2.0134,131.0,4.9923,299.0,2.8096,286.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=0:BME680:breathVocEquivalent MAX value VOC ...,1.85013,2.010252,4.58879,4.944112,2.74257,2.806868,3.70824,4.844487,0.384700,-0.004535,0.790767,0.014290,1.095967,-0.005078,-0.50,3.5,"(-0.5, 3.5)",-1.85,3.5,-0.5,1.70,-2.25,0.40,"(-1.85, 3.5)","(-0.5, 1.7)","(-2.25, 0.4)",1.35,1.80,3.56
255,InsertingSourcePollutant,None,None,None,0.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:05:46,2025-10-24 21:03:22,2025-10-24 21:11:21,2025-10-24,2025-10-24 21:03:24,2025-10-24 21:11:19,0 days 00:07:55,0 days 00:02:23,143.0,0 days 00:05:32,0 days 00:02:23,143.0,332.0,475.0,270.0,-30.0,299.0,1.5436,269.0,6.0745,299.0,2.4431,236.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=0:BME680:breathVocEquivalent MAX value VOC ...,1.50536,1.541913,4.53166,5.938517,2.38429,2.439926,3.22484,5.639461,0.830100,0.003192,0.938300,0.004927,0.278667,0.009215,-2.95,3.5,"(-2.95, 3.5)",-1.85,3.5,-0.5,1.70,-2.25,0.40,"(-1.85, 3.5)","(-0.5, 1.7)","(-2.25, 0.4)",1.10,3.04,3.18
256,InsertingSourcePollutant,None,None,None,1.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:18:43,2025-10-24 21:17:10,2025-10-24 21:24:48,2025-10-24,2025-10-24 21:17:12,2025-10-24 21:24:46,0 days 00:07:34,0 days 00:01:32,92.0,0 days 00:06:02,0 days 00:01:32,92.0,362.0,454.0,270.0,-30.0,299.0,2.0029,299.0,13.3480,277.0,2.0105,141.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=0:BME680:breathVocEquivalent MAX value VOC ...,1.27778,1.931717,13.17579,13.337491,1.89556,2.009913,10.16265,13.288696,0.130833,0.003005,1.964067,0.021602,0.356100,0.002903,-2.95,2.5,"(-2.95, 2.5)",-1.85,3.5,-0.5,1.70,-2.25,0.40,"(-1.85, 3.5)","(-0.5, 1.7)","(-2.25, 0.4)",1.49,2.58,2.21
257,InsertingSourcePollutant,None,None,None,2.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:34:58,2025-10-24 21:33:44,2025-10-24 21:41:06,2025-10-24,2025-10-24 21:33:46,2025-10-24 21:41:04,0 days 00:07:18,0 days 00:01:13,73.0,0 days 00:06:05,0 days 00:01:13,73.0,365.0,438.0,270.0,-30.0,299.0,1.8114,299.0,7.5793,261.0,1.2671,299.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,1.71769,1.786738,7.36787,7.576884,1.24307,1.262000,6.72750,7.545522,0.316533,0.002780,0.425500,0.012363,0.281700,0.004330,-2.95,1.5,"(-2.95, 1.5)",-1.85,3.5,-0.5,1.70,-2.25,0.40,"(-1.85, 3.5)","(-0.5, 1.7)","(-2.25, 0.4)",2.28,2.46,1.30
258,InsertingSourcePollutant,None,None,None,3.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:54:05,2025-10-24 21:52:16,2025-10-24 22:01:25,2025-10-24,2025-10-24 21:52:18,2025-10-24 22:01:24,0 days 00:09:06,0 days 00:01:48,108.0,0 days 00:07:18,0 days 00:01:48,108.0,438.0,546.0,270.0,-30.0,299.0,1.6312,213.0,3.3710,287.0,2.1139,299.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=0:BME680:breathVocEquivalent MAX value VOC ...,1.57461,1.630197,3.24331,3.369713,1.76254,2.072233,2.77298,3.363343,0.104633,-0.002098,0.727733,0.008225,0.324233,0.004552,-2.95,0.5,"(-2.95, 0.5)",-1.85,3.5,-0.5,1.70,-2.25,0.40,"(-1.85, 3.5)","(-0.5, 1.7)","(-2.25, 0.4)",3.20,2.73,0.71

In [107]:
dict_of_timeseries[12]

,sensors,VOC,after_insertion,original_value,datetime_timestamp,timestamp,seconds,seconds passed from insertionSource,VOC original,VOC rolling average,original seconds,VOC-capped,VOC rolling average-capped,VOC gradient,VOC rolling average gradient,VOC rolling average standard scaler whole experiment,VOC rolling average-capped standard scaler whole experiment
seconds,,,,,,,,,,,,,,,,,
-30.0,Id=2:BME680:breathVocEquivalent,1.085,False,False,2025-07-19 17:25:07,0 days 00:19:15,-30.0,-30.0,1.742906,1.0831,1155.0,1.085,1.0831,-0.00120,-0.00120,-1.705457,-1.705457
-30.0,Id=1:BME680:breathVocEquivalent,1.466,False,True,2025-07-19 17:25:07,0 days 00:19:15,-30.0,-30.0,2.043592,1.4920,1155.0,1.466,1.4920,0.00240,0.00240,-0.096036,-0.096036
-29.0,Id=2:BME680:breathVocEquivalent,1.092,False,False,2025-07-19 17:25:08,0 days 00:19:16,-29.0,-29.0,1.750194,1.0819,1156.0,1.092,1.0819,-0.00125,-0.00125,-1.710180,-1.710180
-29.0,Id=1:BME680:breathVocEquivalent,1.470,False,False,2025-07-19 17:25:08,0 days 00:19:16,-29.0,-29.0,2.047873,1.4944,1156.0,1.470,1.4944,0.00235,0.00235,-0.086590,-0.086590
-28.0,Id=2:BME680:breathVocEquivalent,1.096,False,True,2025-07-19 17:25:09,0 days 00:19:17,-28.0,-28.0,1.754015,1.0806,1157.0,1.096,1.0806,-0.00140,-0.00140,-1.715297,-1.715297
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
297.0,Id=1:BME680:breathVocEquivalent,1.913,True,False,2025-07-19 17:30:34,0 days 00:24:42,297.0,297.0,2.490831,1.9152,1482.0,1.913,1.9152,0.00325,0.00325,1.569669,1.569669
298.0,Id=2:BME680:breathVocEquivalent,1.980,True,False,2025-07-19 17:30:35,0 days 00:24:43,298.0,298.0,2.637750,2.0040,1483.0,1.980,2.0040,0.01300,0.01300,1.919184,1.919184
298.0,Id=1:BME680:breathVocEquivalent,1.919,True,False,2025-07-19 17:30:35,0 days 00:24:43,298.0,298.0,2.496685,1.9185,1483.0,1.919,1.9185,0.00335,0.00335,1.582658,1.582658
299.0,Id=2:BME680:breathVocEquivalent,1.991,True,False,2025-07-19 17:30:36,0 days 00:24:44,299.0,299.0,2.649344,2.0172,1484.0,1.991,2.0172,0.01320,0.01320,1.971139,1.971139
299.0,Id=1:BME680:breathVocEquivalent,1.925,True,True,2025-07-19 17:30:36,0 days 00:24:44,299.0,299.0,2.503186,1.9219,1484.0,1.925,1.9219,0.00340,0.00340,1.596040,1.596040

In [108]:
#create a huge dataframe to save it 

# Combine into one DataFrame, keeping the dictionary key
timeSeriesData_BIG = pd.concat(dict_of_timeseries, names=["keys"])

# Reset index so the key becomes a column
timeSeriesData_BIG = timeSeriesData_BIG.reset_index(level="keys").reset_index(drop=True)
timeSeriesData_BIG["seconds"] = timeSeriesData_BIG["seconds"].astype(int)
timeSeriesData_BIG = timeSeriesData_BIG.set_index("seconds",drop=False)

In [109]:
timeSeriesData_BIG

,keys,sensors,VOC,after_insertion,original_value,datetime_timestamp,timestamp,seconds,seconds passed from insertionSource,VOC original,VOC rolling average,original seconds,VOC-capped,VOC rolling average-capped,VOC gradient,VOC rolling average gradient,VOC rolling average standard scaler whole experiment,VOC rolling average-capped standard scaler whole experiment
seconds,,,,,,,,,,,,,,,,,,
-30,0,Id=1:BME680:breathVocEquivalent,1.337,False,True,2025-07-01 16:09:12,0 days 00:41:53,-30,-30.0,2.167955,1.3307,2513.0,1.337,1.3307,0.00090,0.00090,-1.337079,-1.337079
-30,0,Id=2:BME680:breathVocEquivalent,5.037,False,False,2025-07-01 16:09:12,0 days 00:41:53,-30,-30.0,6.467633,4.9908,2513.0,5.037,4.9908,0.00020,0.00020,0.086874,0.086874
-29,0,Id=1:BME680:breathVocEquivalent,1.338,False,False,2025-07-01 16:09:13,0 days 00:41:54,-29,-29.0,2.168206,1.3316,2514.0,1.338,1.3316,0.00085,0.00085,-1.336729,-1.336729
-29,0,Id=2:BME680:breathVocEquivalent,5.041,False,True,2025-07-01 16:09:13,0 days 00:41:54,-29,-29.0,6.471519,4.9910,2514.0,5.041,4.9910,0.00035,0.00035,0.086951,0.086951
-28,0,Id=1:BME680:breathVocEquivalent,1.335,False,False,2025-07-01 16:09:14,0 days 00:41:55,-28,-28.0,2.165358,1.3324,2515.0,1.335,1.3324,0.00085,0.00085,-1.336418,-1.336418
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,258,Id=1:BME680:breathVocEquivalent,1.421,True,True,2025-10-24 21:59:04,0 days 00:06:46,298,298.0,2.948842,1.4032,406.0,1.421,1.4032,-0.00500,-0.00500,0.089182,0.089182
298,258,Id=2:BME680:breathVocEquivalent,3.343,True,False,2025-10-24 21:59:04,0 days 00:06:46,298,298.0,5.567955,3.3352,406.0,3.343,3.3352,-0.00835,-0.00835,2.251684,2.251684
299,258,Id=0:BME680:breathVocEquivalent,2.143,True,False,2025-10-24 21:59:05,0 days 00:06:47,299,299.0,3.110278,2.1139,407.0,2.143,2.1139,0.01260,0.01260,0.884674,0.884674
299,258,Id=1:BME680:breathVocEquivalent,1.409,True,False,2025-10-24 21:59:05,0 days 00:06:47,299,299.0,2.936916,1.3982,407.0,1.409,1.3982,-0.00500,-0.00500,0.083585,0.083585
299,258,Id=2:BME680:breathVocEquivalent,3.307,True,False,2025-10-24 21:59:05,0 days 00:06:47,299,299.0,5.531128,3.3265,407.0,3.307,3.3265,-0.00870,-0.00870,2.241946,2.241946

In [110]:
print(timeSeriesData_BIG.loc[timeSeriesData_BIG["keys"] == 157].max())
print(userInputData.loc[157])

keys                                                                                       157
sensors                                                        Id=2:BME680:breathVocEquivalent
VOC                                                                                      4.206
after_insertion                                                                           True
original_value                                                                            True
datetime_timestamp                                                         2025-10-13 22:32:46
timestamp                                                                      0 days 00:06:34
seconds                                                                                    299
seconds passed from insertionSource                                                      299.0
VOC original                                                                          5.655352
VOC rolling average                                                                     4.0522
original seconds                                                                         394.0
VOC-capped                                                                               4.206
VOC rolling average-capped                                                              4.0522
VOC gradient                                                                            0.0812
VOC rolling average gradient                                                            0.0812
VOC rolling average standard scaler whole experiment                                  2.970206
VOC rolling average-capped standard scaler whole experiment                           2.970206
dtype: object
experimentState                                          InsertingSourcePollutant
are-doors-opened                                                             None
are-people-inside                                                            None
are-windows-opened                                                           None
front-wall                                                                    1.5
                                                                   ...
position of Id=1:BME680:breathVocEquivalent x-y axis                  (-0.5, 1.7)
position of Id=2:BME680:breathVocEquivalent x-y axis                 (-2.25, 0.4)
Euclidian distance to Id=0:BME680:breathVocEquivalent                        1.19
Euclidian distance to Id=1:BME680:breathVocEquivalent                        2.15
Euclidian distance to Id=2:BME680:breathVocEquivalent                        2.11
Name: 157, Length: 67, dtype: object

In [111]:
userInputData.loc[:,"timestamp InsertingSource timedelta"] = userInputData["timestamp InsertingSource timedelta"].astype("timedelta64[ns]")

In [112]:
userInputData.dtypes

experimentState                                           object
are-doors-opened                                          object
are-people-inside                                         object
are-windows-opened                                        object
front-wall                                               float64
                                                          ...
position of Id=1:BME680:breathVocEquivalent x-y axis      object
position of Id=2:BME680:breathVocEquivalent x-y axis      object
Euclidian distance to Id=0:BME680:breathVocEquivalent    float64
Euclidian distance to Id=1:BME680:breathVocEquivalent    float64
Euclidian distance to Id=2:BME680:breathVocEquivalent    float64
Length: 67, dtype: object

In [113]:
userInputData

,experimentState,are-doors-opened,are-people-inside,are-windows-opened,front-wall,item-used,notes,room,side-right-wall,back-wall,side-left-wall,are-fans-on,no-source-located,timestamp InsertingSource,timestamp StartingExperiment,timestamp EndingExperiment,date of experiment,actual timestamp StartingExperiment,actual timestamp EndingExperiment,time taken total,timestamp InsertingSource timedelta,timestamp InsertingSource seconds,time taken after insertion,time taken before insertion,time taken before insertion (seconds),time taken after insertion (seconds),time taken total (seconds),time taken total (seconds)-capped,time taken before insertion (seconds)-capped,time taken after insertion (seconds)-capped,Id=1:BME680:breathVocEquivalent MAX value VOC rolling average,Id=1:BME680:breathVocEquivalent index of MAX value VOC rolling average,Id=2:BME680:breathVocEquivalent MAX value VOC rolling average,Id=2:BME680:breathVocEquivalent index of MAX value VOC rolling average,Id=0:BME680:breathVocEquivalent MAX value VOC rolling average,Id=0:BME680:breathVocEquivalent index of MAX value VOC rolling average,sensor with MAX value experiment,sensor with second MAX value experiment,Id=1:BME680:breathVocEquivalent quantile 90.0% VOC rolling average,Id=1:BME680:breathVocEquivalent quantile 99.0% VOC rolling average,Id=2:BME680:breathVocEquivalent quantile 90.0% VOC rolling average,Id=2:BME680:breathVocEquivalent quantile 99.0% VOC rolling average,Id=0:BME680:breathVocEquivalent quantile 90.0% VOC rolling average,Id=0:BME680:breathVocEquivalent quantile 99.0% VOC rolling average,whole experiment quantile 90.0% VOC rolling average,whole experiment quantile 99.0% VOC rolling average,Id=1:BME680:breathVocEquivalent VOC mean calm period,Id=1:BME680:breathVocEquivalent VOC gradient mean calm period,Id=2:BME680:breathVocEquivalent VOC mean calm period,Id=2:BME680:breathVocEquivalent VOC gradient mean calm period,Id=0:BME680:breathVocEquivalent VOC mean calm period,Id=0:BME680:breathVocEquivalent VOC gradient mean calm period,x axis,y axis,x-y axis,position of Id=0:BME680:breathVocEquivalent-x axis,position of Id=0:BME680:breathVocEquivalent-y axis,position of Id=1:BME680:breathVocEquivalent-x axis,position of Id=1:BME680:breathVocEquivalent-y axis,position of Id=2:BME680:breathVocEquivalent-x axis,position of Id=2:BME680:breathVocEquivalent-y axis,position of Id=0:BME680:breathVocEquivalent x-y axis,position of Id=1:BME680:breathVocEquivalent x-y axis,position of Id=2:BME680:breathVocEquivalent x-y axis,Euclidian distance to Id=0:BME680:breathVocEquivalent,Euclidian distance to Id=1:BME680:breathVocEquivalent,Euclidian distance to Id=2:BME680:breathVocEquivalent
0,InsertingSourcePollutant,on,None,None,1.0,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.0,None,None,2025-07-01 16:09:41,2025-07-01 15:27:16,2025-07-01 16:14:44,2025-07-01,2025-07-01 15:27:19,2025-07-01 16:14:42,0 days 00:47:23,0 days 00:42:23,2543.0,0 days 00:05:00,0 days 00:42:23,2543.0,300.0,2843.0,270.0,-30.0,299.0,4.3501,299.0,8.1928,243.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,4.10260,4.342653,8.13641,8.191397,NaN,NaN,8.03289,8.186653,1.338333,0.000302,5.003467,0.001410,NaN,NaN,-2.25,3.0,"(-2.25, 3.0)",NaN,NaN,2.4,3.05,1.70,3.05,"(nan, nan)","(2.4, 3.05)","(1.7, 3.05)",NaN,4.65,3.95
1,InsertingSourcePollutant,on,None,None,1.0,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.0,None,None,2025-07-02 15:59:29,2025-07-02 15:42:50,2025-07-02 16:04:52,2025-07-02,2025-07-02 15:42:50,2025-07-02 16:04:50,0 days 00:22:00,0 days 00:16:40,1000.0,0 days 00:05:20,0 days 00:16:40,1000.0,320.0,1320.0,270.0,-30.0,299.0,1.1333,201.0,0.3304,80.0,NaN,NaN,Id=1:BME680:breathVocEquivalent MAX value VOC ...,Id=2:BME680:breathVocEquivalent MAX value VOC ...,0.96260,1.130830,0.30518,0.330042,NaN,NaN,0.74384,1.123456,0.050000,-0.000188,0.149700,0.002748,NaN,NaN,-2.25,3.0,"(-2.25, 3.0)",NaN,NaN,2.4,3.05,1.70,3.05,"(nan, nan)","(2.4, 3.05)","(1.7, 3.05)",NaN,4.65,3.95
2,InsertingSourcePollutant,on,None,None,0.4,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.0,None,None,2025-07-03 12:34:32,2025-07-03 12:30:25,2025-07-03 12:45:31,2025-07-03,2025-07-03 12:30:25,2025-07-03 12:45:31,0 days 00:15:06,0 days 00:04:08,248.0,0 days 00:10:58,0 days 00:04:08,248.0,658.0,906.0,270.0,-30.0,299.0,1.3923,235.0,2.2994,299.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,1.34093,1.390726,1.62716,2.182643,NaN,NaN,1.46438,2.073907,0.133633,-0.003248,0.412300,-0.007478,NaN,NaN,-2.25,3.6,"(-2.25, 3.6)",NaN,NaN,2.4,3.05,1.70,3.05,"(nan, nan)","(2.4, 3.05)","(1.7, 3.05)",NaN,4.68,3.99
3,InsertingSourcePollutant,on,None,None,1.0,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.8,None,None,2025-07-03 15:53:07,2025-07-03 15:43:27,2025-07-03 15:59:11,2025-07-03,2025-07-03 15:51:40,2025-07-03 15:59:10,0 days 00:07:30,0 days 00:01:28,88.0,0 days 00:06:02,0 days 00:01:28,88.0,362.0,450.0,270.0,-30.0,299.0,0.3439,299.0,18.4943,299.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.26763,0.334346,16.09553,17.771554,NaN,NaN,6.84825,17.295804,0.027200,0.000002,0.505133,0.005152,NaN,NaN,-1.45,3.0,"(-1.45, 3.0)",NaN,NaN,2.4,3.05,1.70,3.05,"(nan, nan)","(2.4, 3.05)","(1.7, 3.05)",NaN,3.85,3.15
4,InsertingSourcePollutant,on,None,None,1.4,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.4,None,None,2025-07-09 19:19:19,2025-07-09 19:01:42,2025-07-09 19:27:50,2025-07-09,2025-07-09 19:01:44,2025-07-09 19:27:49,0 days 00:26:05,0 days 00:17:36,1056.0,0 days 00:08:29,0 days 00:17:36,1056.0,509.0,1565.0,270.0,-30.0,299.0,0.6066,246.0,0.7315,299.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.58644,0.606300,0.70629,0.726681,NaN,NaN,0.62712,0.723846,0.030767,-0.000302,0.343333,-0.000157,NaN,NaN,-1.85,2.6,"(-1.85, 2.6)",NaN,NaN,2.4,3.05,1.70,3.05,"(nan, nan)","(2.4, 3.05)","(1.7, 3.05)",NaN,4.27,3.58
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
254,InsertingSourcePollutant,None,None,None,0.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",0.5,NaN,NaN,None,None,2025-10-24 20:32:03,2025-10-24 20:29:36,2025-10-24 20:37:33,2025-10-24,2025-10-24 20:29:37,2025-10-24 20:37:31,0 days 00:07:54,0 days 00:02:27,147.0,0 days 00:05:27,0 days 00:02:27,147.0,327.0,474.0,270.0,-30.0,299.0,2.0134,131.0,4.9923,299.0,2.8096,286.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=0:BME680:breathVocEquivalent MAX value VOC ...,1.85013,2.010252,4.58879,4.944112,2.74257,2.806868,3.70824,4.844487,0.384700,-0.004535,0.790767,0.014290,1.095967,-0.005078,-0.50,3.5,"(-0.5, 3.5)",-1.85,3.5,-0.5,1.70,-2.25,0.40,"(-1.85, 3.5)","(-0.5, 1.7)","(-2.25, 0.4)",1.35,1.80,3.56
255,InsertingSourcePollutant,None,None,None,0.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:05:46,2025-10-24 21:03:22,2025-10-24 21:11:21,2025-10-24,2025-10-24 21:03:24,2025-10-24 21:11:19,0 days 00:07:55,0 days 00:02:23,143.0,0 days 00:05:32,0 days 00:02:23,143.0,332.0,475.0,270.0,-30.0,299.0,1.5436,269.0,6.0745,299.0,2.4431,236.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=0:BME680:breathVocEquivalent MAX value VOC ...,1.50536,1.541913,4.53166,5.938517,2.38429,2.439926,3.22484,5.639461,0.830100,0.003192,0.938300,0.004927,0.278667,0.009215,-2.95,3.5,"(-2.95, 3.5)",-1.85,3.5,-0.5,1.70,-2.25,0.40,"(-1.85, 3.5)","(-0.5, 1.7)","(-2.25, 0.4)",1.10,3.04,3.18
256,InsertingSourcePollutant,None,None,None,1.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:18:43,2025-10-24 21:17:10,2025-10-24 21:24:48,2025-10-24,2025-10-24 21:17:12,2025-10-24 21:24:46,0 days 00:07:34,0 days 00:01:32,92.0,0 days 00:06:02,0 days 00:01:32,92.0,362.0,454.0,270.0,-30.0,299.0,2.0029,299.0,13.3480,277.0,2.0105,141.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=0:BME680:breathVocEquivalent MAX value VOC ...,1.27778,1.931717,13.17579,13.337491,1.89556,2.009913,10.16265,13.288696,0.130833,0.003005,1.964067,0.021602,0.356100,0.002903,-2.95,2.5,"(-2.95, 2.5)",-1.85,3.5,-0.5,1.70,-2.25,0.40,"(-1.85, 3.5)","(-0.5, 1.7)","(-2.25, 0.4)",1.49,2.58,2.21
257,InsertingSourcePollutant,None,None,None,2.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:34:58,2025-10-24 21:33:44,2025-10-24 21:41:06,2025-10-24,2025-10-24 21:33:46,2025-10-24 21:41:04,0 days 00:07:18,0 days 00:01:13,73.0,0 days 00:06:05,0 days 00:01:13,73.0,365.0,438.0,270.0,-30.0,299.0,1.8114,299.0,7.5793,261.0,1.2671,299.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,1.71769,1.786738,7.36787,7.576884,1.24307,1.262000,6.72750,7.545522,0.316533,0.002780,0.425500,0.012363,0.281700,0.004330,-2.95,1.5,"(-2.95, 1.5)",-1.85,3.5,-0.5,1.70,-2.25,0.40,"(-1.85, 3.5)","(-0.5, 1.7)","(-2.25, 0.4)",2.28,2.46,1.30
258,InsertingSourcePollutant,None,None,None,3.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:54:05,2025-10-24 21:52:16,2025-10-24 22:01:25,2025-10-24,2025-10-24 21:52:18,2025-10-24 22:01:24,0 days 00:09:06,0 days 00:01:48,108.0,0 days 00:07:18,0 days 00:01:48,108.0,438.0,546.0,270.0,-30.0,299.0,1.6312,213.0,3.3710,287.0,2.1139,299.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=0:BME680:breathVocEquivalent MAX value VOC ...,1.57461,1.630197,3.24331,3.369713,1.76254,2.072233,2.77298,3.363343,0.104633,-0.002098,0.727733,0.008225,0.324233,0.004552,-2.95,0.5,"(-2.95, 0.5)",-1.85,3.5,-0.5,1.70,-2.25,0.40,"(-1.85, 3.5)","(-0.5, 1.7)","(-2.25, 0.4)",3.20,2.73,0.71

In [114]:
userInputData

,experimentState,are-doors-opened,are-people-inside,are-windows-opened,front-wall,item-used,notes,room,side-right-wall,back-wall,side-left-wall,are-fans-on,no-source-located,timestamp InsertingSource,timestamp StartingExperiment,timestamp EndingExperiment,date of experiment,actual timestamp StartingExperiment,actual timestamp EndingExperiment,time taken total,timestamp InsertingSource timedelta,timestamp InsertingSource seconds,time taken after insertion,time taken before insertion,time taken before insertion (seconds),time taken after insertion (seconds),time taken total (seconds),time taken total (seconds)-capped,time taken before insertion (seconds)-capped,time taken after insertion (seconds)-capped,Id=1:BME680:breathVocEquivalent MAX value VOC rolling average,Id=1:BME680:breathVocEquivalent index of MAX value VOC rolling average,Id=2:BME680:breathVocEquivalent MAX value VOC rolling average,Id=2:BME680:breathVocEquivalent index of MAX value VOC rolling average,Id=0:BME680:breathVocEquivalent MAX value VOC rolling average,Id=0:BME680:breathVocEquivalent index of MAX value VOC rolling average,sensor with MAX value experiment,sensor with second MAX value experiment,Id=1:BME680:breathVocEquivalent quantile 90.0% VOC rolling average,Id=1:BME680:breathVocEquivalent quantile 99.0% VOC rolling average,Id=2:BME680:breathVocEquivalent quantile 90.0% VOC rolling average,Id=2:BME680:breathVocEquivalent quantile 99.0% VOC rolling average,Id=0:BME680:breathVocEquivalent quantile 90.0% VOC rolling average,Id=0:BME680:breathVocEquivalent quantile 99.0% VOC rolling average,whole experiment quantile 90.0% VOC rolling average,whole experiment quantile 99.0% VOC rolling average,Id=1:BME680:breathVocEquivalent VOC mean calm period,Id=1:BME680:breathVocEquivalent VOC gradient mean calm period,Id=2:BME680:breathVocEquivalent VOC mean calm period,Id=2:BME680:breathVocEquivalent VOC gradient mean calm period,Id=0:BME680:breathVocEquivalent VOC mean calm period,Id=0:BME680:breathVocEquivalent VOC gradient mean calm period,x axis,y axis,x-y axis,position of Id=0:BME680:breathVocEquivalent-x axis,position of Id=0:BME680:breathVocEquivalent-y axis,position of Id=1:BME680:breathVocEquivalent-x axis,position of Id=1:BME680:breathVocEquivalent-y axis,position of Id=2:BME680:breathVocEquivalent-x axis,position of Id=2:BME680:breathVocEquivalent-y axis,position of Id=0:BME680:breathVocEquivalent x-y axis,position of Id=1:BME680:breathVocEquivalent x-y axis,position of Id=2:BME680:breathVocEquivalent x-y axis,Euclidian distance to Id=0:BME680:breathVocEquivalent,Euclidian distance to Id=1:BME680:breathVocEquivalent,Euclidian distance to Id=2:BME680:breathVocEquivalent
0,InsertingSourcePollutant,on,None,None,1.0,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.0,None,None,2025-07-01 16:09:41,2025-07-01 15:27:16,2025-07-01 16:14:44,2025-07-01,2025-07-01 15:27:19,2025-07-01 16:14:42,0 days 00:47:23,0 days 00:42:23,2543.0,0 days 00:05:00,0 days 00:42:23,2543.0,300.0,2843.0,270.0,-30.0,299.0,4.3501,299.0,8.1928,243.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,4.10260,4.342653,8.13641,8.191397,NaN,NaN,8.03289,8.186653,1.338333,0.000302,5.003467,0.001410,NaN,NaN,-2.25,3.0,"(-2.25, 3.0)",NaN,NaN,2.4,3.05,1.70,3.05,"(nan, nan)","(2.4, 3.05)","(1.7, 3.05)",NaN,4.65,3.95
1,InsertingSourcePollutant,on,None,None,1.0,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.0,None,None,2025-07-02 15:59:29,2025-07-02 15:42:50,2025-07-02 16:04:52,2025-07-02,2025-07-02 15:42:50,2025-07-02 16:04:50,0 days 00:22:00,0 days 00:16:40,1000.0,0 days 00:05:20,0 days 00:16:40,1000.0,320.0,1320.0,270.0,-30.0,299.0,1.1333,201.0,0.3304,80.0,NaN,NaN,Id=1:BME680:breathVocEquivalent MAX value VOC ...,Id=2:BME680:breathVocEquivalent MAX value VOC ...,0.96260,1.130830,0.30518,0.330042,NaN,NaN,0.74384,1.123456,0.050000,-0.000188,0.149700,0.002748,NaN,NaN,-2.25,3.0,"(-2.25, 3.0)",NaN,NaN,2.4,3.05,1.70,3.05,"(nan, nan)","(2.4, 3.05)","(1.7, 3.05)",NaN,4.65,3.95
2,InsertingSourcePollutant,on,None,None,0.4,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.0,None,None,2025-07-03 12:34:32,2025-07-03 12:30:25,2025-07-03 12:45:31,2025-07-03,2025-07-03 12:30:25,2025-07-03 12:45:31,0 days 00:15:06,0 days 00:04:08,248.0,0 days 00:10:58,0 days 00:04:08,248.0,658.0,906.0,270.0,-30.0,299.0,1.3923,235.0,2.2994,299.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,1.34093,1.390726,1.62716,2.182643,NaN,NaN,1.46438,2.073907,0.133633,-0.003248,0.412300,-0.007478,NaN,NaN,-2.25,3.6,"(-2.25, 3.6)",NaN,NaN,2.4,3.05,1.70,3.05,"(nan, nan)","(2.4, 3.05)","(1.7, 3.05)",NaN,4.68,3.99
3,InsertingSourcePollutant,on,None,None,1.0,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.8,None,None,2025-07-03 15:53:07,2025-07-03 15:43:27,2025-07-03 15:59:11,2025-07-03,2025-07-03 15:51:40,2025-07-03 15:59:10,0 days 00:07:30,0 days 00:01:28,88.0,0 days 00:06:02,0 days 00:01:28,88.0,362.0,450.0,270.0,-30.0,299.0,0.3439,299.0,18.4943,299.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.26763,0.334346,16.09553,17.771554,NaN,NaN,6.84825,17.295804,0.027200,0.000002,0.505133,0.005152,NaN,NaN,-1.45,3.0,"(-1.45, 3.0)",NaN,NaN,2.4,3.05,1.70,3.05,"(nan, nan)","(2.4, 3.05)","(1.7, 3.05)",NaN,3.85,3.15
4,InsertingSourcePollutant,on,None,None,1.4,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.4,None,None,2025-07-09 19:19:19,2025-07-09 19:01:42,2025-07-09 19:27:50,2025-07-09,2025-07-09 19:01:44,2025-07-09 19:27:49,0 days 00:26:05,0 days 00:17:36,1056.0,0 days 00:08:29,0 days 00:17:36,1056.0,509.0,1565.0,270.0,-30.0,299.0,0.6066,246.0,0.7315,299.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.58644,0.606300,0.70629,0.726681,NaN,NaN,0.62712,0.723846,0.030767,-0.000302,0.343333,-0.000157,NaN,NaN,-1.85,2.6,"(-1.85, 2.6)",NaN,NaN,2.4,3.05,1.70,3.05,"(nan, nan)","(2.4, 3.05)","(1.7, 3.05)",NaN,4.27,3.58
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
254,InsertingSourcePollutant,None,None,None,0.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",0.5,NaN,NaN,None,None,2025-10-24 20:32:03,2025-10-24 20:29:36,2025-10-24 20:37:33,2025-10-24,2025-10-24 20:29:37,2025-10-24 20:37:31,0 days 00:07:54,0 days 00:02:27,147.0,0 days 00:05:27,0 days 00:02:27,147.0,327.0,474.0,270.0,-30.0,299.0,2.0134,131.0,4.9923,299.0,2.8096,286.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=0:BME680:breathVocEquivalent MAX value VOC ...,1.85013,2.010252,4.58879,4.944112,2.74257,2.806868,3.70824,4.844487,0.384700,-0.004535,0.790767,0.014290,1.095967,-0.005078,-0.50,3.5,"(-0.5, 3.5)",-1.85,3.5,-0.5,1.70,-2.25,0.40,"(-1.85, 3.5)","(-0.5, 1.7)","(-2.25, 0.4)",1.35,1.80,3.56
255,InsertingSourcePollutant,None,None,None,0.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:05:46,2025-10-24 21:03:22,2025-10-24 21:11:21,2025-10-24,2025-10-24 21:03:24,2025-10-24 21:11:19,0 days 00:07:55,0 days 00:02:23,143.0,0 days 00:05:32,0 days 00:02:23,143.0,332.0,475.0,270.0,-30.0,299.0,1.5436,269.0,6.0745,299.0,2.4431,236.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=0:BME680:breathVocEquivalent MAX value VOC ...,1.50536,1.541913,4.53166,5.938517,2.38429,2.439926,3.22484,5.639461,0.830100,0.003192,0.938300,0.004927,0.278667,0.009215,-2.95,3.5,"(-2.95, 3.5)",-1.85,3.5,-0.5,1.70,-2.25,0.40,"(-1.85, 3.5)","(-0.5, 1.7)","(-2.25, 0.4)",1.10,3.04,3.18
256,InsertingSourcePollutant,None,None,None,1.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:18:43,2025-10-24 21:17:10,2025-10-24 21:24:48,2025-10-24,2025-10-24 21:17:12,2025-10-24 21:24:46,0 days 00:07:34,0 days 00:01:32,92.0,0 days 00:06:02,0 days 00:01:32,92.0,362.0,454.0,270.0,-30.0,299.0,2.0029,299.0,13.3480,277.0,2.0105,141.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=0:BME680:breathVocEquivalent MAX value VOC ...,1.27778,1.931717,13.17579,13.337491,1.89556,2.009913,10.16265,13.288696,0.130833,0.003005,1.964067,0.021602,0.356100,0.002903,-2.95,2.5,"(-2.95, 2.5)",-1.85,3.5,-0.5,1.70,-2.25,0.40,"(-1.85, 3.5)","(-0.5, 1.7)","(-2.25, 0.4)",1.49,2.58,2.21
257,InsertingSourcePollutant,None,None,None,2.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:34:58,2025-10-24 21:33:44,2025-10-24 21:41:06,2025-10-24,2025-10-24 21:33:46,2025-10-24 21:41:04,0 days 00:07:18,0 days 00:01:13,73.0,0 days 00:06:05,0 days 00:01:13,73.0,365.0,438.0,270.0,-30.0,299.0,1.8114,299.0,7.5793,261.0,1.2671,299.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,1.71769,1.786738,7.36787,7.576884,1.24307,1.262000,6.72750,7.545522,0.316533,0.002780,0.425500,0.012363,0.281700,0.004330,-2.95,1.5,"(-2.95, 1.5)",-1.85,3.5,-0.5,1.70,-2.25,0.40,"(-1.85, 3.5)","(-0.5, 1.7)","(-2.25, 0.4)",2.28,2.46,1.30
258,InsertingSourcePollutant,None,None,None,3.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:54:05,2025-10-24 21:52:16,2025-10-24 22:01:25,2025-10-24,2025-10-24 21:52:18,2025-10-24 22:01:24,0 days 00:09:06,0 days 00:01:48,108.0,0 days 00:07:18,0 days 00:01:48,108.0,438.0,546.0,270.0,-30.0,299.0,1.6312,213.0,3.3710,287.0,2.1139,299.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=0:BME680:breathVocEquivalent MAX value VOC ...,1.57461,1.630197,3.24331,3.369713,1.76254,2.072233,2.77298,3.363343,0.104633,-0.002098,0.727733,0.008225,0.324233,0.004552,-2.95,0.5,"(-2.95, 0.5)",-1.85,3.5,-0.5,1.70,-2.25,0.40,"(-1.85, 3.5)","(-0.5, 1.7)","(-2.25, 0.4)",3.20,2.73,0.71

In [115]:
userInputData.columns

Index(['experimentState', 'are-doors-opened', 'are-people-inside',
       'are-windows-opened', 'front-wall', 'item-used', 'notes', 'room',
       'side-right-wall', 'back-wall', 'side-left-wall', 'are-fans-on',
       'no-source-located', 'timestamp InsertingSource',
       'timestamp StartingExperiment', 'timestamp EndingExperiment',
       'date of experiment', 'actual timestamp StartingExperiment',
       'actual timestamp EndingExperiment', 'time taken total',
       'timestamp InsertingSource timedelta',
       'timestamp InsertingSource seconds', 'time taken after insertion',
       'time taken before insertion', 'time taken before insertion (seconds)',
       'time taken after insertion (seconds)', 'time taken total (seconds)',
       'time taken total (seconds)-capped',
       'time taken before insertion (seconds)-capped',
       'time taken after insertion (seconds)-capped',
       'Id=1:BME680:breathVocEquivalent MAX value VOC rolling average',
       'Id=1:BME680:breathVocEquivalent index of MAX value VOC rolling average',
       'Id=2:BME680:breathVocEquivalent MAX value VOC rolling average',
       'Id=2:BME680:breathVocEquivalent index of MAX value VOC rolling average',
       'Id=0:BME680:breathVocEquivalent MAX value VOC rolling average',
       'Id=0:BME680:breathVocEquivalent index of MAX value VOC rolling average',
       'sensor with MAX value experiment',
       'sensor with second MAX value experiment',
       'Id=1:BME680:breathVocEquivalent quantile 90.0% VOC rolling average',
       'Id=1:BME680:breathVocEquivalent quantile 99.0% VOC rolling average',
       'Id=2:BME680:breathVocEquivalent quantile 90.0% VOC rolling average',
       'Id=2:BME680:breathVocEquivalent quantile 99.0% VOC rolling average',
       'Id=0:BME680:breathVocEquivalent quantile 90.0% VOC rolling average',
       'Id=0:BME680:breathVocEquivalent quantile 99.0% VOC rolling average',
       'whole experiment quantile 90.0% VOC rolling average',
       'whole experiment quantile 99.0% VOC rolling average',
       'Id=1:BME680:breathVocEquivalent VOC mean calm period',
       'Id=1:BME680:breathVocEquivalent VOC gradient mean calm period',
       'Id=2:BME680:breathVocEquivalent VOC mean calm period',
       'Id=2:BME680:breathVocEquivalent VOC gradient mean calm period',
       'Id=0:BME680:breathVocEquivalent VOC mean calm period',
       'Id=0:BME680:breathVocEquivalent VOC gradient mean calm period',
       'x axis', 'y axis', 'x-y axis',
       'position of Id=0:BME680:breathVocEquivalent-x axis',
       'position of Id=0:BME680:breathVocEquivalent-y axis',
       'position of Id=1:BME680:breathVocEquivalent-x axis',
       'position of Id=1:BME680:breathVocEquivalent-y axis',
       'position of Id=2:BME680:breathVocEquivalent-x axis',
       'position of Id=2:BME680:breathVocEquivalent-y axis',
       'position of Id=0:BME680:breathVocEquivalent x-y axis',
       'position of Id=1:BME680:breathVocEquivalent x-y axis',
       'position of Id=2:BME680:breathVocEquivalent x-y axis',
       'Euclidian distance to Id=0:BME680:breathVocEquivalent',
       'Euclidian distance to Id=1:BME680:breathVocEquivalent',
       'Euclidian distance to Id=2:BME680:breathVocEquivalent'],
      dtype='object')

In [116]:
timeSeriesData_BIG

,keys,sensors,VOC,after_insertion,original_value,datetime_timestamp,timestamp,seconds,seconds passed from insertionSource,VOC original,VOC rolling average,original seconds,VOC-capped,VOC rolling average-capped,VOC gradient,VOC rolling average gradient,VOC rolling average standard scaler whole experiment,VOC rolling average-capped standard scaler whole experiment
seconds,,,,,,,,,,,,,,,,,,
-30,0,Id=1:BME680:breathVocEquivalent,1.337,False,True,2025-07-01 16:09:12,0 days 00:41:53,-30,-30.0,2.167955,1.3307,2513.0,1.337,1.3307,0.00090,0.00090,-1.337079,-1.337079
-30,0,Id=2:BME680:breathVocEquivalent,5.037,False,False,2025-07-01 16:09:12,0 days 00:41:53,-30,-30.0,6.467633,4.9908,2513.0,5.037,4.9908,0.00020,0.00020,0.086874,0.086874
-29,0,Id=1:BME680:breathVocEquivalent,1.338,False,False,2025-07-01 16:09:13,0 days 00:41:54,-29,-29.0,2.168206,1.3316,2514.0,1.338,1.3316,0.00085,0.00085,-1.336729,-1.336729
-29,0,Id=2:BME680:breathVocEquivalent,5.041,False,True,2025-07-01 16:09:13,0 days 00:41:54,-29,-29.0,6.471519,4.9910,2514.0,5.041,4.9910,0.00035,0.00035,0.086951,0.086951
-28,0,Id=1:BME680:breathVocEquivalent,1.335,False,False,2025-07-01 16:09:14,0 days 00:41:55,-28,-28.0,2.165358,1.3324,2515.0,1.335,1.3324,0.00085,0.00085,-1.336418,-1.336418
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,258,Id=1:BME680:breathVocEquivalent,1.421,True,True,2025-10-24 21:59:04,0 days 00:06:46,298,298.0,2.948842,1.4032,406.0,1.421,1.4032,-0.00500,-0.00500,0.089182,0.089182
298,258,Id=2:BME680:breathVocEquivalent,3.343,True,False,2025-10-24 21:59:04,0 days 00:06:46,298,298.0,5.567955,3.3352,406.0,3.343,3.3352,-0.00835,-0.00835,2.251684,2.251684
299,258,Id=0:BME680:breathVocEquivalent,2.143,True,False,2025-10-24 21:59:05,0 days 00:06:47,299,299.0,3.110278,2.1139,407.0,2.143,2.1139,0.01260,0.01260,0.884674,0.884674
299,258,Id=1:BME680:breathVocEquivalent,1.409,True,False,2025-10-24 21:59:05,0 days 00:06:47,299,299.0,2.936916,1.3982,407.0,1.409,1.3982,-0.00500,-0.00500,0.083585,0.083585
299,258,Id=2:BME680:breathVocEquivalent,3.307,True,False,2025-10-24 21:59:05,0 days 00:06:47,299,299.0,5.531128,3.3265,407.0,3.307,3.3265,-0.00870,-0.00870,2.241946,2.241946

In [117]:
def saveDataIntoDataFolder(data,data_file_name):
    script_dir = Path().resolve().parent
    data_folder = script_dir / 'dataAnalysis and machine learning'/'data'
    print(data_folder)
    data_folder.mkdir(exist_ok=True)
    
    file_path = data_folder / (data_file_name + ".json")
    with open(file_path, 'w') as file:
        if isinstance(data, pd.DataFrame):
            print("It's a DataFrame")
            if  data.empty:
                print("No data to save.")
            else:
                data.to_json(file_path, orient='records', lines=False)             
                print(f"Data saved to {file_path}")

        else:  
            print("It's NOT a DataFrame.")    
            if not data:
                print("No data to save.")
            else:    
                json.dump(data, file)
                print(f"Data saved to {file_path}")


saveDataIntoDataFolder(userInputData,"UserPrevious experiments-preprocessed")
saveDataIntoDataFolder(timeSeriesData_BIG,"Data:Previous experiments-preprocessed")

C:\Users\Andreas\Documents\PlatformIO\Projects\Diploma Project\dataAnalysis and machine learning\data
It's a DataFrame
Data saved to C:\Users\Andreas\Documents\PlatformIO\Projects\Diploma Project\dataAnalysis and machine learning\data\UserPrevious experiments-preprocessed.json
C:\Users\Andreas\Documents\PlatformIO\Projects\Diploma Project\dataAnalysis and machine learning\data
It's a DataFrame
Data saved to C:\Users\Andreas\Documents\PlatformIO\Projects\Diploma Project\dataAnalysis and machine learning\data\Data:Previous experiments-preprocessed.json