In [105]:
#the import packages
import requests
import pandas as pd
from pandas import json_normalize
import requests
import os
from pathlib import Path
from datetime import datetime, timezone,timedelta,time
from scipy import stats
import json
import numpy as np

import seaborn as sns
import matplotlib.pyplot as plt

In [106]:
pd.set_option("display.max_columns", None)

In [107]:
def loadDataFromFile(file_name):
    script_dir = Path().resolve().parent

    data_folder = script_dir / 'dataAnalysis and machine learning'/'data'
    print(data_folder)
    data_folder.mkdir(exist_ok=True)
    
    file_path = data_folder / (file_name + ".json")
    
    if file_path.exists():
        df = pd.read_json(file_path)
        print(f"Loaded {len(df)} records from {file_path}")
        return df
    else:
        print(f"File {file_path} does not exist.")
        return None

In [108]:
userInputDataRaw = loadDataFromFile("User:Previous experiments")
timeSeriesData = loadDataFromFile("Data:Previous experiments")

C:\Users\Andreas\Documents\PlatformIO\Projects\Diploma Project\dataAnalysis and machine learning\data
Loaded 777 records from C:\Users\Andreas\Documents\PlatformIO\Projects\Diploma Project\dataAnalysis and machine learning\data\User:Previous experiments.json
C:\Users\Andreas\Documents\PlatformIO\Projects\Diploma Project\dataAnalysis and machine learning\data
Loaded 855293 records from C:\Users\Andreas\Documents\PlatformIO\Projects\Diploma Project\dataAnalysis and machine learning\data\Data:Previous experiments.json

In [109]:
userInputDataRaw

,_id,experimentState,timestamp,userInputCategory,are-doors-opened,are-people-inside,are-windows-opened,front-wall,item-used,notes,pollutant-type,quantity-used,room,side-right-wall,back-wall,side-left-wall,are-fans-on,no-source-located,epoch_ms,timestamp_local
0,{'$oid': '6863fe54cdf92819382e6866'},StartingExperiment,{'$date': 1751383636513},ExperimentState,None,None,None,NaN,None,None,None,None,None,NaN,NaN,NaN,None,None,1751383636513,2025-07-01 15:27:16.513
1,{'$oid': '686408456a2505a88d9b0665'},InsertingSourcePollutant,{'$date': 1751386181232},ExperimentState,on,None,None,0.95,Φαρμακευτικό αλκοόλ 95%,,VOC,30 ml,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,0.95,None,None,1751386181232,2025-07-01 16:09:41.232
2,{'$oid': '686409746a2505a88d9b087a'},RemovingSourcePollutant,{'$date': 1751386484742},ExperimentState,None,None,None,NaN,None,None,None,None,None,NaN,NaN,NaN,None,None,1751386484742,2025-07-01 16:14:44.742
3,{'$oid': '6865537ae30f2ab561c621a8'},StartingExperiment,{'$date': 1751470970240},ExperimentState,None,None,None,NaN,None,None,None,None,None,NaN,NaN,NaN,None,None,1751470970240,2025-07-02 15:42:50.240
4,{'$oid': '68655761e30f2ab561c629a2'},InsertingSourcePollutant,{'$date': 1751471969827},ExperimentState,on,None,None,0.95,Φαρμακευτικό αλκοόλ 95%,,VOC,30 ml,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,0.95,None,None,1751471969827,2025-07-02 15:59:29.827
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
772,{'$oid': '68fbf1027c6adebb72ced61d'},InsertingSourcePollutant,{'$date': 1761341698285},ExperimentState,None,None,None,2.50,Φαρμακευτικό αλκοόλ 95%,,VOC,30 ml,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.30,None,None,1761341698285,2025-10-24 21:34:58.285
773,{'$oid': '68fbf2727c6adebb72ceda7d'},RemovingSourcePollutant,{'$date': 1761342066926},ExperimentState,None,None,None,NaN,None,None,None,None,None,NaN,NaN,NaN,None,None,1761342066926,2025-10-24 21:41:06.926
774,{'$oid': '68fbf5107c6adebb72cee28d'},StartingExperiment,{'$date': 1761342736556},ExperimentState,None,None,None,NaN,None,None,None,None,None,NaN,NaN,NaN,None,None,1761342736556,2025-10-24 21:52:16.556
775,{'$oid': '68fbf57d7c6adebb72cee3ed'},InsertingSourcePollutant,{'$date': 1761342845443},ExperimentState,None,None,None,3.50,Φαρμακευτικό αλκοόλ 95%,,VOC,30 ml,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.30,None,None,1761342845443,2025-10-24 21:54:05.443
776,{'$oid': '68fbf7357c6adebb72cee922'},RemovingSourcePollutant,{'$date': 1761343285817},ExperimentState,None,None,None,NaN,None,None,None,None,None,NaN,NaN,NaN,None,None,1761343285817,2025-10-24 22:01:25.817

In [110]:
userInputDataRaw["room"].unique()

array([None, 'Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55',
       'Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1',
       'Κρεβατοκάμαρα-Όλοι οι αισθητήρες μαζί Μ:0.80 , Α:0.90',
       'Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0.5  ,id:2 Π:0.4 Α:1.0',
       'Κρεβατοκάμαρα Όλοι οι αισθητήρες μαζί Π:1.80 , Δ:2.00'],
      dtype=object)

In [111]:
timeSeriesData

,timestamp,Id=0:BME680:breathVocEquivalent,Id=1:BME680:breathVocEquivalent,Id=2:BME680:breathVocEquivalent
0,2025-07-01 15:27:18,NaN,1.480697,NaN
1,2025-07-01 15:27:19,NaN,NaN,1.430472
2,2025-07-01 15:27:21,NaN,1.469428,NaN
3,2025-07-01 15:27:22,NaN,NaN,1.441322
4,2025-07-01 15:27:24,NaN,1.476243,NaN
...,...,...,...,...
855288,2025-10-24 22:01:22,2.987463,NaN,NaN
855289,2025-10-24 22:01:22,NaN,2.595613,NaN
855290,2025-10-24 22:01:24,NaN,NaN,7.399793
855291,2025-10-24 22:01:25,2.989213,NaN,NaN
855292,2025-10-24 22:01:25,NaN,2.602333,NaN

In [112]:
userInputData = userInputDataRaw.drop(columns=["_id","timestamp","epoch_ms","userInputCategory","pollutant-type","quantity-used"])

In [113]:
userInputData["timestamp_local"] = pd.to_datetime(userInputData["timestamp_local"])  # ensure datetime
userInputData["timestamp_local"] = userInputData["timestamp_local"].dt.floor("s")

In [114]:
userInputData

,experimentState,are-doors-opened,are-people-inside,are-windows-opened,front-wall,item-used,notes,room,side-right-wall,back-wall,side-left-wall,are-fans-on,no-source-located,timestamp_local
0,StartingExperiment,None,None,None,NaN,None,None,None,NaN,NaN,NaN,None,None,2025-07-01 15:27:16
1,InsertingSourcePollutant,on,None,None,0.95,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,0.95,None,None,2025-07-01 16:09:41
2,RemovingSourcePollutant,None,None,None,NaN,None,None,None,NaN,NaN,NaN,None,None,2025-07-01 16:14:44
3,StartingExperiment,None,None,None,NaN,None,None,None,NaN,NaN,NaN,None,None,2025-07-02 15:42:50
4,InsertingSourcePollutant,on,None,None,0.95,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,0.95,None,None,2025-07-02 15:59:29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
772,InsertingSourcePollutant,None,None,None,2.50,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.30,None,None,2025-10-24 21:34:58
773,RemovingSourcePollutant,None,None,None,NaN,None,None,None,NaN,NaN,NaN,None,None,2025-10-24 21:41:06
774,StartingExperiment,None,None,None,NaN,None,None,None,NaN,NaN,NaN,None,None,2025-10-24 21:52:16
775,InsertingSourcePollutant,None,None,None,3.50,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.30,None,None,2025-10-24 21:54:05
776,RemovingSourcePollutant,None,None,None,NaN,None,None,None,NaN,NaN,NaN,None,None,2025-10-24 22:01:25

In [115]:
userInputDataTemp = userInputData[userInputData["experimentState"].isin(["NoSourcePollutantInserted","InsertingSourcePollutant"])].copy()

userInputDataTemp["timestamp StartingExperiment"] = userInputData["timestamp_local"].shift(1).loc[userInputData.index]
userInputDataTemp["timestamp EndingExperiment"]= userInputData["timestamp_local"].shift(-1).loc[userInputData.index]
userInputData =userInputDataTemp
userInputData = userInputData.reset_index(drop = True)
userInputData = userInputData.rename(columns={"timestamp_local":"timestamp InsertingSource"})

In [116]:
userInputData.head(20)

,experimentState,are-doors-opened,are-people-inside,are-windows-opened,front-wall,item-used,notes,room,side-right-wall,back-wall,side-left-wall,are-fans-on,no-source-located,timestamp InsertingSource,timestamp StartingExperiment,timestamp EndingExperiment
0,InsertingSourcePollutant,on,None,None,0.95,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,0.95,None,None,2025-07-01 16:09:41,2025-07-01 15:27:16,2025-07-01 16:14:44
1,InsertingSourcePollutant,on,None,None,0.95,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,0.95,None,None,2025-07-02 15:59:29,2025-07-02 15:42:50,2025-07-02 16:04:52
2,InsertingSourcePollutant,on,None,None,0.40,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,0.95,None,None,2025-07-03 12:34:32,2025-07-03 12:30:25,2025-07-03 12:45:31
3,InsertingSourcePollutant,on,None,None,0.95,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.85,None,None,2025-07-03 15:53:07,2025-07-03 15:43:27,2025-07-03 15:59:11
4,InsertingSourcePollutant,on,None,None,1.40,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.35,None,None,2025-07-09 19:19:19,2025-07-09 19:01:42,2025-07-09 19:27:50
5,InsertingSourcePollutant,None,None,None,0.95,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.75,None,None,2025-07-12 22:57:57,2025-07-12 22:31:25,2025-07-12 23:02:13
6,InsertingSourcePollutant,on,None,None,1.40,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.75,None,None,2025-07-14 19:40:37,2025-07-14 17:50:04,2025-07-14 19:48:32
7,InsertingSourcePollutant,on,on,None,1.80,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.10,None,None,2025-07-19 15:04:09,2025-07-19 14:59:47,2025-07-19 15:08:10
8,InsertingSourcePollutant,on,on,None,1.80,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.10,None,None,2025-07-19 15:17:10,2025-07-19 15:14:13,2025-07-19 15:21:23
9,InsertingSourcePollutant,on,on,None,1.80,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.10,None,None,2025-07-19 15:30:49,2025-07-19 15:25:07,2025-07-19 15:44:28
10,InsertingSourcePollutant,on,on,None,1.80,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.10,None,None,2025-07-19 16:12:54,2025-07-19 16:04:22,2025-07-19 16:21:55
11,InsertingSourcePollutant,on,on,None,1.80,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.10,None,None,2025-07-19 16:46:45,2025-07-19 16:36:03,2025-07-19 16:54:19
12,InsertingSourcePollutant,on,on,None,1.80,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.10,None,None,2025-07-19 17:25:36,2025-07-19 17:05:51,2025-07-19 17:35:58
13,InsertingSourcePollutant,on,None,None,1.80,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.10,None,None,2025-07-20 13:46:03,2025-07-20 13:36:41,2025-07-20 14:48:43
14,InsertingSourcePollutant,on,on,None,1.80,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.10,None,None,2025-07-20 15:15:34,2025-07-20 15:04:15,2025-07-20 15:39:22
15,InsertingSourcePollutant,on,on,None,1.80,Φαρμακευτικό αλκοόλ 95%,ανεμιστήρας,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.10,None,None,2025-07-20 15:52:33,2025-07-20 15:47:36,2025-07-20 16:08:05
16,InsertingSourcePollutant,on,None,None,1.80,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.10,None,None,2025-07-20 16:34:39,2025-07-20 16:20:42,2025-07-20 16:43:55
17,InsertingSourcePollutant,on,on,None,1.80,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.10,None,None,2025-07-20 18:13:07,2025-07-20 18:04:08,2025-07-20 18:22:22
18,InsertingSourcePollutant,on,on,on,1.80,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.10,None,None,2025-07-20 18:31:41,2025-07-20 18:29:19,2025-07-20 18:40:12
19,InsertingSourcePollutant,on,on,None,1.80,Φαρμακευτικό αλκοόλ 95%,ανεμιστήρας,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.10,None,None,2025-07-20 18:47:26,2025-07-20 18:41:09,2025-07-20 19:00:09

In [117]:
userInputData["room"].unique()

array(['Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55',
       'Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1',
       'Κρεβατοκάμαρα-Όλοι οι αισθητήρες μαζί Μ:0.80 , Α:0.90',
       'Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0.5  ,id:2 Π:0.4 Α:1.0',
       'Κρεβατοκάμαρα Όλοι οι αισθητήρες μαζί Π:1.80 , Δ:2.00'],
      dtype=object)

In [118]:
dict_of_timeseries = {}
for index, row in userInputData.iterrows():
    #get datetime
    start = row["timestamp StartingExperiment"]
    turning_point = row["timestamp InsertingSource"]
    end = row["timestamp EndingExperiment"]
    #Grab data
    particular_experiment = timeSeriesData[(timeSeriesData["timestamp"] >= start) & (timeSeriesData["timestamp"] <= end)]
    particular_experiment = particular_experiment.sort_values(by = ["timestamp"],ignore_index = True)
    dict_of_timeseries[index] = particular_experiment

In [119]:
print(dict_of_timeseries[157].max())
print(userInputData.loc[157])

timestamp                          2025-10-13 22:34:17
Id=0:BME680:breathVocEquivalent               5.654722
Id=1:BME680:breathVocEquivalent               4.692824
Id=2:BME680:breathVocEquivalent               9.690211
dtype: object
experimentState                                          InsertingSourcePollutant
are-doors-opened                                                             None
are-people-inside                                                            None
are-windows-opened                                                           None
front-wall                                                                    1.5
item-used                                                 Φαρμακευτικό αλκοόλ 95%
notes
room                            Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...
side-right-wall                                                               2.5
back-wall                                                                     NaN
side-left-wall                                                                NaN
are-fans-on                                                                  None
no-source-located                                                            None
timestamp InsertingSource                                     2025-10-13 22:27:46
timestamp StartingExperiment                                  2025-10-13 22:26:11
timestamp EndingExperiment                                    2025-10-13 22:34:17
Name: 157, dtype: object

In [120]:
example_df = dict_of_timeseries[10]
example_df

,timestamp,Id=0:BME680:breathVocEquivalent,Id=1:BME680:breathVocEquivalent,Id=2:BME680:breathVocEquivalent
0,2025-07-19 16:04:22,NaN,0.513479,NaN
1,2025-07-19 16:04:24,NaN,NaN,0.508068
2,2025-07-19 16:04:25,NaN,0.518917,NaN
3,2025-07-19 16:04:27,NaN,NaN,0.504020
4,2025-07-19 16:04:28,NaN,0.521494,NaN
...,...,...,...,...
699,2025-07-19 16:21:49,NaN,2.617029,NaN
700,2025-07-19 16:21:51,NaN,NaN,5.626779
701,2025-07-19 16:21:52,NaN,2.615562,NaN
702,2025-07-19 16:21:54,NaN,NaN,5.601505
703,2025-07-19 16:21:55,NaN,2.590167,NaN

In [121]:
for index, row in userInputData.iterrows():
    particular_experiment =  dict_of_timeseries[index]

    #make the dataframe from multiple columns to have the data for each sensor to just one column
    particular_experiment = particular_experiment.melt(
        id_vars=["timestamp"], 
        value_vars=[
            "Id=0:BME680:breathVocEquivalent",
            "Id=1:BME680:breathVocEquivalent",
            "Id=2:BME680:breathVocEquivalent"
        ],
        var_name="sensors", 
        value_name="VOC"
    )
    particular_experiment = particular_experiment.dropna(ignore_index = True)

    particular_experiment = particular_experiment.sort_values(by = ["timestamp"],ignore_index = True)
    dict_of_timeseries[index] = particular_experiment

In [122]:
example_df = dict_of_timeseries[10]
example_df.head(20)

             timestamp                          sensors       VOC
0  2025-07-19 16:04:22  Id=1:BME680:breathVocEquivalent  0.513479
1  2025-07-19 16:04:24  Id=2:BME680:breathVocEquivalent  0.508068
2  2025-07-19 16:04:25  Id=1:BME680:breathVocEquivalent  0.518917
3  2025-07-19 16:04:27  Id=2:BME680:breathVocEquivalent  0.504020
4  2025-07-19 16:04:28  Id=1:BME680:breathVocEquivalent  0.521494
5  2025-07-19 16:04:30  Id=2:BME680:breathVocEquivalent  0.509921
6  2025-07-19 16:04:31  Id=1:BME680:breathVocEquivalent  0.518891
7  2025-07-19 16:04:33  Id=2:BME680:breathVocEquivalent  0.507465
8  2025-07-19 16:04:34  Id=1:BME680:breathVocEquivalent  0.514929
9  2025-07-19 16:04:36  Id=2:BME680:breathVocEquivalent  0.509477
10 2025-07-19 16:04:37  Id=1:BME680:breathVocEquivalent  0.509976
11 2025-07-19 16:04:39  Id=2:BME680:breathVocEquivalent  0.510929
12 2025-07-19 16:04:40  Id=1:BME680:breathVocEquivalent  0.509532
13 2025-07-19 16:04:42  Id=2:BME680:breathVocEquivalent  0.508344
14 2025-07-19 16:04:43  Id=1:BME680:breathVocEquivalent  0.516288
15 2025-07-19 16:04:45  Id=2:BME680:breathVocEquivalent  0.515360
16 2025-07-19 16:04:46  Id=1:BME680:breathVocEquivalent  0.511147
17 2025-07-19 16:04:48  Id=2:BME680:breathVocEquivalent  0.512273
18 2025-07-19 16:04:49  Id=1:BME680:breathVocEquivalent  0.511506
19 2025-07-19 16:04:51  Id=2:BME680:breathVocEquivalent  0.510924

In [123]:
print(dict_of_timeseries[157].max())
print(userInputData.loc[157])

timestamp                2025-10-13 22:34:17
sensors      Id=2:BME680:breathVocEquivalent
VOC                                 9.690211
dtype: object
experimentState                                          InsertingSourcePollutant
are-doors-opened                                                             None
are-people-inside                                                            None
are-windows-opened                                                           None
front-wall                                                                    1.5
item-used                                                 Φαρμακευτικό αλκοόλ 95%
notes
room                            Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...
side-right-wall                                                               2.5
back-wall                                                                     NaN
side-left-wall                                                                NaN
are-fans-on                                                                  None
no-source-located                                                            None
timestamp InsertingSource                                     2025-10-13 22:27:46
timestamp StartingExperiment                                  2025-10-13 22:26:11
timestamp EndingExperiment                                    2025-10-13 22:34:17
Name: 157, dtype: object

In [129]:
userInputData

,experimentState,are-doors-opened,are-people-inside,are-windows-opened,front-wall,item-used,notes,room,side-right-wall,back-wall,side-left-wall,are-fans-on,no-source-located,timestamp InsertingSource,timestamp StartingExperiment,timestamp EndingExperiment,date of experiment
0,InsertingSourcePollutant,on,None,None,0.95,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,0.95,None,None,2025-07-01 16:09:41,2025-07-01 15:27:16,2025-07-01 16:14:44,2025-07-01
1,InsertingSourcePollutant,on,None,None,0.95,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,0.95,None,None,2025-07-02 15:59:29,2025-07-02 15:42:50,2025-07-02 16:04:52,2025-07-02
2,InsertingSourcePollutant,on,None,None,0.40,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,0.95,None,None,2025-07-03 12:34:32,2025-07-03 12:30:25,2025-07-03 12:45:31,2025-07-03
3,InsertingSourcePollutant,on,None,None,0.95,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.85,None,None,2025-07-03 15:53:07,2025-07-03 15:43:27,2025-07-03 15:59:11,2025-07-03
4,InsertingSourcePollutant,on,None,None,1.40,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.35,None,None,2025-07-09 19:19:19,2025-07-09 19:01:42,2025-07-09 19:27:50,2025-07-09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
254,InsertingSourcePollutant,None,None,None,0.50,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",0.5,NaN,NaN,None,None,2025-10-24 20:32:03,2025-10-24 20:29:36,2025-10-24 20:37:33,2025-10-24
255,InsertingSourcePollutant,None,None,None,0.50,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.30,None,None,2025-10-24 21:05:46,2025-10-24 21:03:22,2025-10-24 21:11:21,2025-10-24
256,InsertingSourcePollutant,None,None,None,1.50,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.30,None,None,2025-10-24 21:18:43,2025-10-24 21:17:10,2025-10-24 21:24:48,2025-10-24
257,InsertingSourcePollutant,None,None,None,2.50,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.30,None,None,2025-10-24 21:34:58,2025-10-24 21:33:44,2025-10-24 21:41:06,2025-10-24
258,InsertingSourcePollutant,None,None,None,3.50,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.30,None,None,2025-10-24 21:54:05,2025-10-24 21:52:16,2025-10-24 22:01:25,2025-10-24

In [130]:
for index, row in userInputData.iterrows():
#Now, we only have timestamps based of whenever the sensor took the value, but we want to have times 
    # Get full range of seconds from start to end timestamp
    particular_experiment =  dict_of_timeseries[index]
    start = row["timestamp StartingExperiment"]
    turning_point = row["timestamp InsertingSource"]

    end = row["timestamp EndingExperiment"]
    full_time_range = pd.date_range(start, end, freq="s")
    
    all_sensors = particular_experiment["sensors"].unique()
    particular_experiment["timestamp"] = pd.to_datetime(particular_experiment["timestamp"])
    
    full_index = pd.MultiIndex.from_product([full_time_range, all_sensors], names=["timestamp", "sensors"])
    extended_particular_experiment= pd.DataFrame(index=full_index).reset_index()
    particular_experiment = extended_particular_experiment.merge(particular_experiment, on=["timestamp", "sensors"], how="left",suffixes=["",None])
    particular_experiment["after_insertion"] = particular_experiment["timestamp"] > turning_point
    particular_experiment["original_value"] = pd.notna(particular_experiment["VOC"])
    dict_of_timeseries[index] = particular_experiment

In [131]:
userInputData["date of experiment"] = userInputData["timestamp EndingExperiment"].apply(lambda x:x.date())

In [132]:
example_df = dict_of_timeseries[10]
example_df

,timestamp,sensors,VOC,after_insertion,original_value
0,2025-07-19 16:04:22,Id=1:BME680:breathVocEquivalent,0.513479,False,True
1,2025-07-19 16:04:22,Id=2:BME680:breathVocEquivalent,NaN,False,False
2,2025-07-19 16:04:23,Id=1:BME680:breathVocEquivalent,0.515345,False,True
3,2025-07-19 16:04:23,Id=2:BME680:breathVocEquivalent,NaN,False,False
4,2025-07-19 16:04:24,Id=1:BME680:breathVocEquivalent,0.517211,False,True
...,...,...,...,...,...
2104,2025-07-19 16:21:53,Id=2:BME680:breathVocEquivalent,5.629334,True,True
2105,2025-07-19 16:21:54,Id=1:BME680:breathVocEquivalent,2.601317,True,True
2106,2025-07-19 16:21:54,Id=2:BME680:breathVocEquivalent,5.601505,True,True
2107,2025-07-19 16:21:55,Id=1:BME680:breathVocEquivalent,2.590167,True,True
2108,2025-07-19 16:21:55,Id=2:BME680:breathVocEquivalent,NaN,True,False

In [133]:
for index, row in userInputData.iterrows():
    
        particular_experiment =  dict_of_timeseries[index]

        particular_experiment["VOC"] = (
            particular_experiment
            .groupby("sensors")["VOC"]
            .transform(lambda s: s.interpolate(method = "cubic"))
        )
        dict_of_timeseries[index] = particular_experiment

In [134]:
example_df = dict_of_timeseries[10]
example_df

,timestamp,sensors,VOC,after_insertion,original_value
0,2025-07-19 16:04:22,Id=1:BME680:breathVocEquivalent,0.513479,False,True
1,2025-07-19 16:04:22,Id=2:BME680:breathVocEquivalent,NaN,False,False
2,2025-07-19 16:04:23,Id=1:BME680:breathVocEquivalent,0.515345,False,True
3,2025-07-19 16:04:23,Id=2:BME680:breathVocEquivalent,NaN,False,False
4,2025-07-19 16:04:24,Id=1:BME680:breathVocEquivalent,0.517211,False,True
...,...,...,...,...,...
2104,2025-07-19 16:21:53,Id=2:BME680:breathVocEquivalent,5.629334,True,True
2105,2025-07-19 16:21:54,Id=1:BME680:breathVocEquivalent,2.601317,True,True
2106,2025-07-19 16:21:54,Id=2:BME680:breathVocEquivalent,5.601505,True,True
2107,2025-07-19 16:21:55,Id=1:BME680:breathVocEquivalent,2.590167,True,True
2108,2025-07-19 16:21:55,Id=2:BME680:breathVocEquivalent,NaN,True,False

In [135]:
print(dict_of_timeseries[157].max())
print(userInputData.loc[157])

timestamp                      2025-10-13 22:34:17
sensors            Id=2:BME680:breathVocEquivalent
VOC                                       9.690211
after_insertion                               True
original_value                                True
dtype: object
experimentState                                          InsertingSourcePollutant
are-doors-opened                                                             None
are-people-inside                                                            None
are-windows-opened                                                           None
front-wall                                                                    1.5
item-used                                                 Φαρμακευτικό αλκοόλ 95%
notes
room                            Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...
side-right-wall                                                               2.5
back-wall                                                                     NaN
side-left-wall                                                                NaN
are-fans-on                                                                  None
no-source-located                                                            None
timestamp InsertingSource                                     2025-10-13 22:27:46
timestamp StartingExperiment                                  2025-10-13 22:26:11
timestamp EndingExperiment                                    2025-10-13 22:34:17
date of experiment                                                     2025-10-13
Name: 157, dtype: object

In [136]:
# Ensure the columns exist and have datetime dtype
userInputData["actual timestamp StartingExperiment"] = pd.NaT
userInputData["actual timestamp EndingExperiment"] = pd.NaT
userInputData = userInputData.astype({
    "actual timestamp StartingExperiment": "datetime64[ns]",
    "actual timestamp EndingExperiment": "datetime64[ns]"
})

for index, row in userInputData.iterrows():
    particular_experiment = dict_of_timeseries[index]

    first_timestamps = particular_experiment[particular_experiment["VOC"].notna()] \
        .groupby("sensors", as_index=False)["timestamp"].min()
    last_timestamps = particular_experiment[particular_experiment["VOC"].notna()] \
        .groupby("sensors", as_index=False)["timestamp"].max()

    start = first_timestamps["timestamp"].max()
    end = last_timestamps["timestamp"].min()

    userInputData.at[index, "actual timestamp StartingExperiment"] = start
    userInputData.at[index, "actual timestamp EndingExperiment"] = end

    particular_experiment = particular_experiment.loc[
        particular_experiment["timestamp"].between(start, end, inclusive="both")
    ].reset_index(drop=True)

    dict_of_timeseries[index] = particular_experiment

In [137]:
userInputData.head(20)

,experimentState,are-doors-opened,are-people-inside,are-windows-opened,front-wall,item-used,notes,room,side-right-wall,back-wall,side-left-wall,are-fans-on,no-source-located,timestamp InsertingSource,timestamp StartingExperiment,timestamp EndingExperiment,date of experiment,actual timestamp StartingExperiment,actual timestamp EndingExperiment
0,InsertingSourcePollutant,on,None,None,0.95,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,0.95,None,None,2025-07-01 16:09:41,2025-07-01 15:27:16,2025-07-01 16:14:44,2025-07-01,2025-07-01 15:27:19,2025-07-01 16:14:42
1,InsertingSourcePollutant,on,None,None,0.95,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,0.95,None,None,2025-07-02 15:59:29,2025-07-02 15:42:50,2025-07-02 16:04:52,2025-07-02,2025-07-02 15:42:50,2025-07-02 16:04:50
2,InsertingSourcePollutant,on,None,None,0.40,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,0.95,None,None,2025-07-03 12:34:32,2025-07-03 12:30:25,2025-07-03 12:45:31,2025-07-03,2025-07-03 12:30:25,2025-07-03 12:45:31
3,InsertingSourcePollutant,on,None,None,0.95,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.85,None,None,2025-07-03 15:53:07,2025-07-03 15:43:27,2025-07-03 15:59:11,2025-07-03,2025-07-03 15:51:40,2025-07-03 15:59:10
4,InsertingSourcePollutant,on,None,None,1.40,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.35,None,None,2025-07-09 19:19:19,2025-07-09 19:01:42,2025-07-09 19:27:50,2025-07-09,2025-07-09 19:01:44,2025-07-09 19:27:49
5,InsertingSourcePollutant,None,None,None,0.95,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.75,None,None,2025-07-12 22:57:57,2025-07-12 22:31:25,2025-07-12 23:02:13,2025-07-12,2025-07-12 22:34:03,2025-07-12 23:02:11
6,InsertingSourcePollutant,on,None,None,1.40,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.75,None,None,2025-07-14 19:40:37,2025-07-14 17:50:04,2025-07-14 19:48:32,2025-07-14,2025-07-14 18:30:00,2025-07-14 19:20:03
7,InsertingSourcePollutant,on,on,None,1.80,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.10,None,None,2025-07-19 15:04:09,2025-07-19 14:59:47,2025-07-19 15:08:10,2025-07-19,2025-07-19 14:59:49,2025-07-19 15:08:09
8,InsertingSourcePollutant,on,on,None,1.80,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.10,None,None,2025-07-19 15:17:10,2025-07-19 15:14:13,2025-07-19 15:21:23,2025-07-19,2025-07-19 15:14:15,2025-07-19 15:21:21
9,InsertingSourcePollutant,on,on,None,1.80,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.10,None,None,2025-07-19 15:30:49,2025-07-19 15:25:07,2025-07-19 15:44:28,2025-07-19,2025-07-19 15:25:09,2025-07-19 15:44:27
10,InsertingSourcePollutant,on,on,None,1.80,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.10,None,None,2025-07-19 16:12:54,2025-07-19 16:04:22,2025-07-19 16:21:55,2025-07-19,2025-07-19 16:04:24,2025-07-19 16:21:54
11,InsertingSourcePollutant,on,on,None,1.80,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.10,None,None,2025-07-19 16:46:45,2025-07-19 16:36:03,2025-07-19 16:54:19,2025-07-19,2025-07-19 16:36:04,2025-07-19 16:54:18
12,InsertingSourcePollutant,on,on,None,1.80,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.10,None,None,2025-07-19 17:25:36,2025-07-19 17:05:51,2025-07-19 17:35:58,2025-07-19,2025-07-19 17:05:52,2025-07-19 17:35:57
13,InsertingSourcePollutant,on,None,None,1.80,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.10,None,None,2025-07-20 13:46:03,2025-07-20 13:36:41,2025-07-20 14:48:43,2025-07-20,2025-07-20 13:36:42,2025-07-20 14:48:41
14,InsertingSourcePollutant,on,on,None,1.80,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.10,None,None,2025-07-20 15:15:34,2025-07-20 15:04:15,2025-07-20 15:39:22,2025-07-20,2025-07-20 15:04:17,2025-07-20 15:39:20
15,InsertingSourcePollutant,on,on,None,1.80,Φαρμακευτικό αλκοόλ 95%,ανεμιστήρας,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.10,None,None,2025-07-20 15:52:33,2025-07-20 15:47:36,2025-07-20 16:08:05,2025-07-20,2025-07-20 15:47:38,2025-07-20 16:08:03
16,InsertingSourcePollutant,on,None,None,1.80,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.10,None,None,2025-07-20 16:34:39,2025-07-20 16:20:42,2025-07-20 16:43:55,2025-07-20,2025-07-20 16:20:44,2025-07-20 16:43:54
17,InsertingSourcePollutant,on,on,None,1.80,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.10,None,None,2025-07-20 18:13:07,2025-07-20 18:04:08,2025-07-20 18:22:22,2025-07-20,2025-07-20 18:04:10,2025-07-20 18:22:20
18,InsertingSourcePollutant,on,on,on,1.80,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.10,None,None,2025-07-20 18:31:41,2025-07-20 18:29:19,2025-07-20 18:40:12,2025-07-20,2025-07-20 18:29:21,2025-07-20 18:40:11
19,InsertingSourcePollutant,on,on,None,1.80,Φαρμακευτικό αλκοόλ 95%,ανεμιστήρας,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.10,None,None,2025-07-20 18:47:26,2025-07-20 18:41:09,2025-07-20 19:00:09,2025-07-20,2025-07-20 18:41:11,2025-07-20 19:00:08

In [138]:
print(dict_of_timeseries[157].max())
print(userInputData.loc[157])

timestamp                      2025-10-13 22:34:15
sensors            Id=2:BME680:breathVocEquivalent
VOC                                       9.690211
after_insertion                               True
original_value                                True
dtype: object
experimentState                                                 InsertingSourcePollutant
are-doors-opened                                                                    None
are-people-inside                                                                   None
are-windows-opened                                                                  None
front-wall                                                                           1.5
item-used                                                        Φαρμακευτικό αλκοόλ 95%
notes
room                                   Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...
side-right-wall                                                                      2.5
back-wall                                                                            NaN
side-left-wall                                                                       NaN
are-fans-on                                                                         None
no-source-located                                                                   None
timestamp InsertingSource                                            2025-10-13 22:27:46
timestamp StartingExperiment                                         2025-10-13 22:26:11
timestamp EndingExperiment                                           2025-10-13 22:34:17
date of experiment                                                            2025-10-13
actual timestamp StartingExperiment                                  2025-10-13 22:26:12
actual timestamp EndingExperiment                                    2025-10-13 22:34:15
Name: 157, dtype: object

In [139]:
example_df = dict_of_timeseries[10]
example_df

,timestamp,sensors,VOC,after_insertion,original_value
0,2025-07-19 16:04:24,Id=1:BME680:breathVocEquivalent,0.517211,False,True
1,2025-07-19 16:04:24,Id=2:BME680:breathVocEquivalent,0.508068,False,True
2,2025-07-19 16:04:25,Id=1:BME680:breathVocEquivalent,0.518917,False,True
3,2025-07-19 16:04:25,Id=2:BME680:breathVocEquivalent,0.503896,False,True
4,2025-07-19 16:04:26,Id=1:BME680:breathVocEquivalent,0.520305,False,True
...,...,...,...,...,...
2098,2025-07-19 16:21:52,Id=2:BME680:breathVocEquivalent,5.635052,True,True
2099,2025-07-19 16:21:53,Id=1:BME680:breathVocEquivalent,2.609777,True,True
2100,2025-07-19 16:21:53,Id=2:BME680:breathVocEquivalent,5.629334,True,True
2101,2025-07-19 16:21:54,Id=1:BME680:breathVocEquivalent,2.601317,True,True
2102,2025-07-19 16:21:54,Id=2:BME680:breathVocEquivalent,5.601505,True,True

In [140]:


for index, row in userInputData.iterrows():
    particular_experiment =  dict_of_timeseries[index]

    print(f"index is {index}")
    particular_experiment =  dict_of_timeseries[index]
    
    # keep only rows with VOC present
    filtered = particular_experiment[particular_experiment["VOC"].notna()]
    min_timestamp_for_each_sensor = (
        filtered
        .groupby("sensors", as_index=False)["timestamp"]
        .min()
        )
    print(f"min value")
    print(min_timestamp_for_each_sensor)
    first_timestamp_to_keep = min_timestamp_for_each_sensor["timestamp"].max()
    
    particular_experiment = particular_experiment[particular_experiment["timestamp"] >= first_timestamp_to_keep]
    
    print(f"max value")
    max_timestamp_for_each_sensor =(
        filtered
        .groupby("sensors", as_index=False)["timestamp"]
        .max()
        )
    print(max_timestamp_for_each_sensor)

index is 0
min value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-01 15:27:19
1  Id=2:BME680:breathVocEquivalent 2025-07-01 15:27:19
max value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-01 16:14:42
1  Id=2:BME680:breathVocEquivalent 2025-07-01 16:14:42
index is 1
min value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-02 15:42:50
1  Id=2:BME680:breathVocEquivalent 2025-07-02 15:42:50
max value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-02 16:04:50
1  Id=2:BME680:breathVocEquivalent 2025-07-02 16:04:50
index is 2
min value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-03 12:30:25
1  Id=2:BME680:breathVocEquivalent 2025-07-03 12:30:25
max value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-03 12:45:31
1  Id=2:BME680:breathVocEquivalent 2025-07-03 12:45:31
index is 3
min value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-03 15:51:40
1  Id=2:BME680:breathVocEquivalent 2025-07-03 15:51:40
max value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-03 15:59:10
1  Id=2:BME680:breathVocEquivalent 2025-07-03 15:59:10
index is 4
min value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-09 19:01:44
1  Id=2:BME680:breathVocEquivalent 2025-07-09 19:01:44
max value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-09 19:27:49
1  Id=2:BME680:breathVocEquivalent 2025-07-09 19:27:49
index is 5
min value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-12 22:34:03
1  Id=2:BME680:breathVocEquivalent 2025-07-12 22:34:03
max value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-12 23:02:11
1  Id=2:BME680:breathVocEquivalent 2025-07-12 23:02:11
index is 6
min value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-14 18:30:00
1  Id=2:BME680:breathVocEquivalent 2025-07-14 18:30:00
max value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-14 19:20:03
1  Id=2:BME680:breathVocEquivalent 2025-07-14 19:20:03
index is 7
min value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-19 14:59:49
1  Id=2:BME680:breathVocEquivalent 2025-07-19 14:59:49
max value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-19 15:08:09
1  Id=2:BME680:breathVocEquivalent 2025-07-19 15:08:09
index is 8
min value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-19 15:14:15
1  Id=2:BME680:breathVocEquivalent 2025-07-19 15:14:15
max value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-19 15:21:21
1  Id=2:BME680:breathVocEquivalent 2025-07-19 15:21:21
index is 9
min value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-19 15:25:09
1  Id=2:BME680:breathVocEquivalent 2025-07-19 15:25:09
max value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-19 15:44:27
1  Id=2:BME680:breathVocEquivalent 2025-07-19 15:44:27
index is 10
min value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-19 16:04:24
1  Id=2:BME680:breathVocEquivalent 2025-07-19 16:04:24
max value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-19 16:21:54
1  Id=2:BME680:breathVocEquivalent 2025-07-19 16:21:54
index is 11
min value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-19 16:36:04
1  Id=2:BME680:breathVocEquivalent 2025-07-19 16:36:04
max value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-19 16:54:18
1  Id=2:BME680:breathVocEquivalent 2025-07-19 16:54:18
index is 12
min value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-19 17:05:52
1  Id=2:BME680:breathVocEquivalent 2025-07-19 17:05:52
max value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-19 17:35:57
1  Id=2:BME680:breathVocEquivalent 2025-07-19 17:35:57
index is 13
min value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-20 13:36:42
1  Id=2:BME680:breathVocEquivalent 2025-07-20 13:36:42
max value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-20 14:48:41
1  Id=2:BME680:breathVocEquivalent 2025-07-20 14:48:41
index is 14
min value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-20 15:04:17
1  Id=2:BME680:breathVocEquivalent 2025-07-20 15:04:17
max value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-20 15:39:20
1  Id=2:BME680:breathVocEquivalent 2025-07-20 15:39:20
index is 15
min value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-20 15:47:38
1  Id=2:BME680:breathVocEquivalent 2025-07-20 15:47:38
max value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-20 16:08:03
1  Id=2:BME680:breathVocEquivalent 2025-07-20 16:08:03
index is 16
min value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-20 16:20:44
1  Id=2:BME680:breathVocEquivalent 2025-07-20 16:20:44
max value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-20 16:43:54
1  Id=2:BME680:breathVocEquivalent 2025-07-20 16:43:54
index is 17
min value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-20 18:04:10
1  Id=2:BME680:breathVocEquivalent 2025-07-20 18:04:10
max value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-20 18:22:20
1  Id=2:BME680:breathVocEquivalent 2025-07-20 18:22:20
index is 18
min value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-20 18:29:21
1  Id=2:BME680:breathVocEquivalent 2025-07-20 18:29:21
max value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-20 18:40:11
1  Id=2:BME680:breathVocEquivalent 2025-07-20 18:40:11
index is 19
min value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-20 18:41:11
1  Id=2:BME680:breathVocEquivalent 2025-07-20 18:41:11
max value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-20 19:00:08
1  Id=2:BME680:breathVocEquivalent 2025-07-20 19:00:08
index is 20
min value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-20 19:13:36
1  Id=2:BME680:breathVocEquivalent 2025-07-20 19:13:36
max value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-20 19:23:42
1  Id=2:BME680:breathVocEquivalent 2025-07-20 19:23:42
index is 21
min value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-20 19:30:53
1  Id=2:BME680:breathVocEquivalent 2025-07-20 19:30:53
max value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-20 19:46:26
1  Id=2:BME680:breathVocEquivalent 2025-07-20 19:46:26
index is 22
min value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-20 19:55:48
1  Id=2:BME680:breathVocEquivalent 2025-07-20 19:55:48
max value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-20 20:05:20
1  Id=2:BME680:breathVocEquivalent 2025-07-20 20:05:20
index is 23
min value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-20 20:25:42
1  Id=2:BME680:breathVocEquivalent 2025-07-20 20:25:42
max value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-20 20:30:33
1  Id=2:BME680:breathVocEquivalent 2025-07-20 20:30:33
index is 24
min value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-20 20:47:11
1  Id=2:BME680:breathVocEquivalent 2025-07-20 20:47:11
max value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-20 20:55:23
1  Id=2:BME680:breathVocEquivalent 2025-07-20 20:55:23
index is 25
min value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-20 21:08:21
1  Id=2:BME680:breathVocEquivalent 2025-07-20 21:08:21
max value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-20 21:19:41
1  Id=2:BME680:breathVocEquivalent 2025-07-20 21:19:41
index is 26
min value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-21 14:24:58
1  Id=2:BME680:breathVocEquivalent 2025-07-21 14:24:58
max value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-21 14:46:39
1  Id=2:BME680:breathVocEquivalent 2025-07-21 14:46:39
index is 27
min value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-21 19:33:56
1  Id=2:BME680:breathVocEquivalent 2025-07-21 19:33:56
max value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-21 19:48:49
1  Id=2:BME680:breathVocEquivalent 2025-07-21 19:48:49
index is 28
min value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-21 19:59:28
1  Id=2:BME680:breathVocEquivalent 2025-07-21 19:59:28
max value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-21 20:08:55
1  Id=2:BME680:breathVocEquivalent 2025-07-21 20:08:55
index is 29
min value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-21 20:49:40
1  Id=2:BME680:breathVocEquivalent 2025-07-21 20:49:40
max value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-21 21:03:41
1  Id=2:BME680:breathVocEquivalent 2025-07-21 21:03:41
index is 30
min value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-21 21:24:32
1  Id=2:BME680:breathVocEquivalent 2025-07-21 21:24:32
max value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-21 21:39:20
1  Id=2:BME680:breathVocEquivalent 2025-07-21 21:39:20
index is 31
min value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-21 21:57:13
1  Id=2:BME680:breathVocEquivalent 2025-07-21 21:57:13
max value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-21 22:14:09
1  Id=2:BME680:breathVocEquivalent 2025-07-21 22:14:09
index is 32
min value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-21 22:41:51
1  Id=2:BME680:breathVocEquivalent 2025-07-21 22:41:51
max value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-21 22:55:19
1  Id=2:BME680:breathVocEquivalent 2025-07-21 22:55:19
index is 33
min value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-21 23:06:34
1  Id=2:BME680:breathVocEquivalent 2025-07-21 23:06:34
max value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-21 23:16:46
1  Id=2:BME680:breathVocEquivalent 2025-07-21 23:16:46
index is 34
min value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-22 13:37:49
1  Id=2:BME680:breathVocEquivalent 2025-07-22 13:37:49
max value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-22 13:48:16
1  Id=2:BME680:breathVocEquivalent 2025-07-22 13:48:16
index is 35
min value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-22 14:02:00
1  Id=2:BME680:breathVocEquivalent 2025-07-22 14:02:00
max value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-22 14:16:48
1  Id=2:BME680:breathVocEquivalent 2025-07-22 14:16:48
index is 36
min value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-22 14:32:16
1  Id=2:BME680:breathVocEquivalent 2025-07-22 14:32:16
max value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-22 14:41:52
1  Id=2:BME680:breathVocEquivalent 2025-07-22 14:41:52
index is 37
min value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-22 15:11:10
1  Id=2:BME680:breathVocEquivalent 2025-07-22 15:11:10
max value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-22 15:18:18
1  Id=2:BME680:breathVocEquivalent 2025-07-22 15:18:18
index is 38
min value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-22 15:34:18
1  Id=2:BME680:breathVocEquivalent 2025-07-22 15:34:18
max value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-22 15:47:15
1  Id=2:BME680:breathVocEquivalent 2025-07-22 15:47:15
index is 39
min value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-22 16:25:09
1  Id=2:BME680:breathVocEquivalent 2025-07-22 16:25:09
max value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-22 16:46:48
1  Id=2:BME680:breathVocEquivalent 2025-07-22 16:46:48
index is 40
min value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-22 17:02:58
1  Id=2:BME680:breathVocEquivalent 2025-07-22 17:02:58
max value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-22 17:23:10
1  Id=2:BME680:breathVocEquivalent 2025-07-22 17:23:10
index is 41
min value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-22 17:35:52
1  Id=2:BME680:breathVocEquivalent 2025-07-22 17:35:52
max value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-22 17:43:52
1  Id=2:BME680:breathVocEquivalent 2025-07-22 17:43:52
index is 42
min value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-22 18:00:43
1  Id=2:BME680:breathVocEquivalent 2025-07-22 18:00:43
max value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-22 18:08:01
1  Id=2:BME680:breathVocEquivalent 2025-07-22 18:08:01
index is 43
min value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-22 18:34:07
1  Id=2:BME680:breathVocEquivalent 2025-07-22 18:34:07
max value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-22 18:42:43
1  Id=2:BME680:breathVocEquivalent 2025-07-22 18:42:43
index is 44
min value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-22 19:42:37
1  Id=2:BME680:breathVocEquivalent 2025-07-22 19:42:37
max value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-22 19:52:18
1  Id=2:BME680:breathVocEquivalent 2025-07-22 19:52:18
index is 45
min value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-23 11:52:37
1  Id=2:BME680:breathVocEquivalent 2025-07-23 11:52:37
max value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-23 12:11:55
1  Id=2:BME680:breathVocEquivalent 2025-07-23 12:11:55
index is 46
min value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-26 14:41:56
1  Id=2:BME680:breathVocEquivalent 2025-07-26 14:41:56
max value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-26 14:53:17
1  Id=2:BME680:breathVocEquivalent 2025-07-26 14:53:17
index is 47
min value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-26 14:59:53
1  Id=2:BME680:breathVocEquivalent 2025-07-26 14:59:53
max value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-26 15:09:31
1  Id=2:BME680:breathVocEquivalent 2025-07-26 15:09:31
index is 48
min value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-26 15:29:01
1  Id=2:BME680:breathVocEquivalent 2025-07-26 15:29:01
max value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-26 15:48:04
1  Id=2:BME680:breathVocEquivalent 2025-07-26 15:48:04
index is 49
min value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-26 18:35:04
1  Id=2:BME680:breathVocEquivalent 2025-07-26 18:35:04
max value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-26 18:35:58
1  Id=2:BME680:breathVocEquivalent 2025-07-26 18:35:58
index is 50
min value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-26 19:20:46
1  Id=2:BME680:breathVocEquivalent 2025-07-26 19:20:46
max value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-26 19:25:31
1  Id=2:BME680:breathVocEquivalent 2025-07-26 19:25:31
index is 51
min value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-26 20:01:47
1  Id=2:BME680:breathVocEquivalent 2025-07-26 20:01:47
max value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-26 20:08:58
1  Id=2:BME680:breathVocEquivalent 2025-07-26 20:08:58
index is 52
min value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-26 20:28:07
1  Id=2:BME680:breathVocEquivalent 2025-07-26 20:28:07
max value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-26 20:36:02
1  Id=2:BME680:breathVocEquivalent 2025-07-26 20:36:02
index is 53
min value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-26 20:47:20
1  Id=2:BME680:breathVocEquivalent 2025-07-26 20:47:20
max value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-26 20:54:17
1  Id=2:BME680:breathVocEquivalent 2025-07-26 20:54:17
index is 54
min value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-26 21:06:38
1  Id=2:BME680:breathVocEquivalent 2025-07-26 21:06:38
max value
                           sensors           timestamp
0  Id=1:BME680:breathVocEquivalent 2025-07-26 21:13:44
1  Id=2:BME680:breathVocEquivalent 2025-07-26 21:13:44
index is 55
min value
                           sensors           timestamp

In [141]:
userInputData

,experimentState,are-doors-opened,are-people-inside,are-windows-opened,front-wall,item-used,notes,room,side-right-wall,back-wall,side-left-wall,are-fans-on,no-source-located,timestamp InsertingSource,timestamp StartingExperiment,timestamp EndingExperiment,date of experiment,actual timestamp StartingExperiment,actual timestamp EndingExperiment
0,InsertingSourcePollutant,on,None,None,0.95,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,0.95,None,None,2025-07-01 16:09:41,2025-07-01 15:27:16,2025-07-01 16:14:44,2025-07-01,2025-07-01 15:27:19,2025-07-01 16:14:42
1,InsertingSourcePollutant,on,None,None,0.95,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,0.95,None,None,2025-07-02 15:59:29,2025-07-02 15:42:50,2025-07-02 16:04:52,2025-07-02,2025-07-02 15:42:50,2025-07-02 16:04:50
2,InsertingSourcePollutant,on,None,None,0.40,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,0.95,None,None,2025-07-03 12:34:32,2025-07-03 12:30:25,2025-07-03 12:45:31,2025-07-03,2025-07-03 12:30:25,2025-07-03 12:45:31
3,InsertingSourcePollutant,on,None,None,0.95,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.85,None,None,2025-07-03 15:53:07,2025-07-03 15:43:27,2025-07-03 15:59:11,2025-07-03,2025-07-03 15:51:40,2025-07-03 15:59:10
4,InsertingSourcePollutant,on,None,None,1.40,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.35,None,None,2025-07-09 19:19:19,2025-07-09 19:01:42,2025-07-09 19:27:50,2025-07-09,2025-07-09 19:01:44,2025-07-09 19:27:49
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
254,InsertingSourcePollutant,None,None,None,0.50,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",0.5,NaN,NaN,None,None,2025-10-24 20:32:03,2025-10-24 20:29:36,2025-10-24 20:37:33,2025-10-24,2025-10-24 20:29:37,2025-10-24 20:37:31
255,InsertingSourcePollutant,None,None,None,0.50,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.30,None,None,2025-10-24 21:05:46,2025-10-24 21:03:22,2025-10-24 21:11:21,2025-10-24,2025-10-24 21:03:24,2025-10-24 21:11:19
256,InsertingSourcePollutant,None,None,None,1.50,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.30,None,None,2025-10-24 21:18:43,2025-10-24 21:17:10,2025-10-24 21:24:48,2025-10-24,2025-10-24 21:17:12,2025-10-24 21:24:46
257,InsertingSourcePollutant,None,None,None,2.50,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.30,None,None,2025-10-24 21:34:58,2025-10-24 21:33:44,2025-10-24 21:41:06,2025-10-24,2025-10-24 21:33:46,2025-10-24 21:41:04
258,InsertingSourcePollutant,None,None,None,3.50,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.30,None,None,2025-10-24 21:54:05,2025-10-24 21:52:16,2025-10-24 22:01:25,2025-10-24,2025-10-24 21:52:18,2025-10-24 22:01:24

index = 6
particular_experiment =  dict_of_timeseries[index]
sensors = particular_experiment["sensors"].unique()

print(index)
for sensor in sensors:
    mask = particular_experiment["sensors"]==sensor
    masked_data = particular_experiment.loc[mask]
    diffs = masked_data["timestamp"].diff()
    expected_step = diffs.mode()[0]
    broken_rows = masked_data["timestamp"][diffs != expected_step]
    print("Rows breaking frequency:\n", broken_rows)
    print()

In [142]:
for index, row in userInputData.iterrows():

    particular_experiment =  dict_of_timeseries[index]
    particular_experiment = particular_experiment.drop_duplicates()
    dict_of_timeseries[index] = particular_experiment

In [143]:
print(dict_of_timeseries[157].max())
print(userInputData.loc[157])

timestamp                      2025-10-13 22:34:15
sensors            Id=2:BME680:breathVocEquivalent
VOC                                       9.690211
after_insertion                               True
original_value                                True
dtype: object
experimentState                                                 InsertingSourcePollutant
are-doors-opened                                                                    None
are-people-inside                                                                   None
are-windows-opened                                                                  None
front-wall                                                                           1.5
item-used                                                        Φαρμακευτικό αλκοόλ 95%
notes
room                                   Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...
side-right-wall                                                                      2.5
back-wall                                                                            NaN
side-left-wall                                                                       NaN
are-fans-on                                                                         None
no-source-located                                                                   None
timestamp InsertingSource                                            2025-10-13 22:27:46
timestamp StartingExperiment                                         2025-10-13 22:26:11
timestamp EndingExperiment                                           2025-10-13 22:34:17
date of experiment                                                            2025-10-13
actual timestamp StartingExperiment                                  2025-10-13 22:26:12
actual timestamp EndingExperiment                                    2025-10-13 22:34:15
Name: 157, dtype: object

In [144]:
dict_of_timeseries[7]

,timestamp,sensors,VOC,after_insertion,original_value
0,2025-07-19 14:59:49,Id=2:BME680:breathVocEquivalent,0.680033,False,True
1,2025-07-19 14:59:49,Id=1:BME680:breathVocEquivalent,2.118851,False,True
2,2025-07-19 14:59:50,Id=2:BME680:breathVocEquivalent,0.679083,False,True
3,2025-07-19 14:59:50,Id=1:BME680:breathVocEquivalent,2.125827,False,True
4,2025-07-19 14:59:51,Id=2:BME680:breathVocEquivalent,0.681077,False,True
...,...,...,...,...,...
997,2025-07-19 15:08:07,Id=1:BME680:breathVocEquivalent,1.193376,True,True
998,2025-07-19 15:08:08,Id=2:BME680:breathVocEquivalent,1.186056,True,True
999,2025-07-19 15:08:08,Id=1:BME680:breathVocEquivalent,1.192881,True,True
1000,2025-07-19 15:08:09,Id=2:BME680:breathVocEquivalent,1.184700,True,True
1001,2025-07-19 15:08:09,Id=1:BME680:breathVocEquivalent,1.193156,True,True

In [145]:
userInputData["time taken total"] = np.nan

for index, row in userInputData.iterrows():

    particular_experiment =  dict_of_timeseries[index]
    sensors = particular_experiment["sensors"].unique()
    particular_experiment["datetime_timestamp"] = particular_experiment["timestamp"]
    particular_experiment = particular_experiment.drop(columns="timestamp")
    particular_experiment["timestamp"] = np.nan
    particular_experiment["timestamp"] = particular_experiment["timestamp"].astype("timedelta64[ns]")
    for sensor in sensors:
        
        mask = particular_experiment["sensors"]==sensor
        #masked_data = particular_experiment.loc[mask]
        
        start = particular_experiment.loc[mask]["datetime_timestamp"].min()
        end = particular_experiment.loc[mask]["datetime_timestamp"].max()
        
        duration = end - start
        
        timeline = pd.timedelta_range(start="0s", end=duration, freq="s")
        
        particular_experiment.loc[mask,"timestamp"] = timeline
        particular_experiment.loc[mask,"seconds"] = timeline.total_seconds()
        userInputData.at[index,"time taken total"] = duration    
    dict_of_timeseries[index] =   particular_experiment

C:\Users\Andreas\AppData\Local\Temp\ipykernel_6164\3649789654.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  particular_experiment["datetime_timestamp"] = particular_experiment["timestamp"]

In [146]:
userInputData

,experimentState,are-doors-opened,are-people-inside,are-windows-opened,front-wall,item-used,notes,room,side-right-wall,back-wall,side-left-wall,are-fans-on,no-source-located,timestamp InsertingSource,timestamp StartingExperiment,timestamp EndingExperiment,date of experiment,actual timestamp StartingExperiment,actual timestamp EndingExperiment,time taken total
0,InsertingSourcePollutant,on,None,None,0.95,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,0.95,None,None,2025-07-01 16:09:41,2025-07-01 15:27:16,2025-07-01 16:14:44,2025-07-01,2025-07-01 15:27:19,2025-07-01 16:14:42,0 days 00:47:23
1,InsertingSourcePollutant,on,None,None,0.95,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,0.95,None,None,2025-07-02 15:59:29,2025-07-02 15:42:50,2025-07-02 16:04:52,2025-07-02,2025-07-02 15:42:50,2025-07-02 16:04:50,0 days 00:22:00
2,InsertingSourcePollutant,on,None,None,0.40,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,0.95,None,None,2025-07-03 12:34:32,2025-07-03 12:30:25,2025-07-03 12:45:31,2025-07-03,2025-07-03 12:30:25,2025-07-03 12:45:31,0 days 00:15:06
3,InsertingSourcePollutant,on,None,None,0.95,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.85,None,None,2025-07-03 15:53:07,2025-07-03 15:43:27,2025-07-03 15:59:11,2025-07-03,2025-07-03 15:51:40,2025-07-03 15:59:10,0 days 00:07:30
4,InsertingSourcePollutant,on,None,None,1.40,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.35,None,None,2025-07-09 19:19:19,2025-07-09 19:01:42,2025-07-09 19:27:50,2025-07-09,2025-07-09 19:01:44,2025-07-09 19:27:49,0 days 00:26:05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
254,InsertingSourcePollutant,None,None,None,0.50,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",0.5,NaN,NaN,None,None,2025-10-24 20:32:03,2025-10-24 20:29:36,2025-10-24 20:37:33,2025-10-24,2025-10-24 20:29:37,2025-10-24 20:37:31,0 days 00:07:54
255,InsertingSourcePollutant,None,None,None,0.50,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.30,None,None,2025-10-24 21:05:46,2025-10-24 21:03:22,2025-10-24 21:11:21,2025-10-24,2025-10-24 21:03:24,2025-10-24 21:11:19,0 days 00:07:55
256,InsertingSourcePollutant,None,None,None,1.50,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.30,None,None,2025-10-24 21:18:43,2025-10-24 21:17:10,2025-10-24 21:24:48,2025-10-24,2025-10-24 21:17:12,2025-10-24 21:24:46,0 days 00:07:34
257,InsertingSourcePollutant,None,None,None,2.50,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.30,None,None,2025-10-24 21:34:58,2025-10-24 21:33:44,2025-10-24 21:41:06,2025-10-24,2025-10-24 21:33:46,2025-10-24 21:41:04,0 days 00:07:18
258,InsertingSourcePollutant,None,None,None,3.50,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.30,None,None,2025-10-24 21:54:05,2025-10-24 21:52:16,2025-10-24 22:01:25,2025-10-24,2025-10-24 21:52:18,2025-10-24 22:01:24,0 days 00:09:06

In [147]:
userInputData.columns

Index(['experimentState', 'are-doors-opened', 'are-people-inside',
       'are-windows-opened', 'front-wall', 'item-used', 'notes', 'room',
       'side-right-wall', 'back-wall', 'side-left-wall', 'are-fans-on',
       'no-source-located', 'timestamp InsertingSource',
       'timestamp StartingExperiment', 'timestamp EndingExperiment',
       'date of experiment', 'actual timestamp StartingExperiment',
       'actual timestamp EndingExperiment', 'time taken total'],
      dtype='object')

In [148]:
 dict_of_timeseries[10]

,sensors,VOC,after_insertion,original_value,datetime_timestamp,timestamp,seconds
0,Id=1:BME680:breathVocEquivalent,0.517211,False,True,2025-07-19 16:04:24,0 days 00:00:00,0.0
1,Id=2:BME680:breathVocEquivalent,0.508068,False,True,2025-07-19 16:04:24,0 days 00:00:00,0.0
2,Id=1:BME680:breathVocEquivalent,0.518917,False,True,2025-07-19 16:04:25,0 days 00:00:01,1.0
3,Id=2:BME680:breathVocEquivalent,0.503896,False,True,2025-07-19 16:04:25,0 days 00:00:01,1.0
4,Id=1:BME680:breathVocEquivalent,0.520305,False,True,2025-07-19 16:04:26,0 days 00:00:02,2.0
...,...,...,...,...,...,...,...
2098,Id=2:BME680:breathVocEquivalent,5.635052,True,True,2025-07-19 16:21:52,0 days 00:17:28,1048.0
2099,Id=1:BME680:breathVocEquivalent,2.609777,True,True,2025-07-19 16:21:53,0 days 00:17:29,1049.0
2100,Id=2:BME680:breathVocEquivalent,5.629334,True,True,2025-07-19 16:21:53,0 days 00:17:29,1049.0
2101,Id=1:BME680:breathVocEquivalent,2.601317,True,True,2025-07-19 16:21:54,0 days 00:17:30,1050.0
2102,Id=2:BME680:breathVocEquivalent,5.601505,True,True,2025-07-19 16:21:54,0 days 00:17:30,1050.0

In [149]:
userInputData.dtypes

experimentState                                object
are-doors-opened                               object
are-people-inside                              object
are-windows-opened                             object
front-wall                                    float64
item-used                                      object
notes                                          object
room                                           object
side-right-wall                               float64
back-wall                                     float64
side-left-wall                                float64
are-fans-on                                    object
no-source-located                              object
timestamp InsertingSource              datetime64[ns]
timestamp StartingExperiment           datetime64[ns]
timestamp EndingExperiment             datetime64[ns]
date of experiment                             object
actual timestamp StartingExperiment    datetime64[ns]
actual timestamp EndingExperiment      datetime64[ns]
time taken total                               object
dtype: object

In [150]:
userInputData["timestamp InsertingSource timedelta"] = np.nan
userInputData["timestamp InsertingSource seconds"] = np.nan

for index, row in userInputData.iterrows():

    particular_experiment =  dict_of_timeseries[index]
    sensors = particular_experiment["sensors"].unique()

    for sensor in sensors:
        
        mask = particular_experiment["sensors"]==sensor
        #print(masker)

        start = particular_experiment.loc[mask,:]["timestamp"].min()
       # print(start)
        end = particular_experiment.loc[mask,:]["timestamp"].max()
        #print(end)
       # print(sensor)
        
        mask = (particular_experiment["sensors"] == sensor) & (particular_experiment["after_insertion"] == True)
        filtered = particular_experiment.loc[mask]
        #print(first_index)
        if not filtered.empty:
            first_index = filtered.index[0]
            insertion_time = filtered.at[first_index, "timestamp"]
        
            userInputData.at[index, "timestamp InsertingSource timedelta"] = insertion_time
            userInputData.at[index, "timestamp InsertingSource seconds"] = insertion_time.total_seconds()
            userInputData.at[index, "time taken after insertion"] = (userInputData.at[index, "time taken total"] - insertion_time)
            userInputData.at[index, "time taken before insertion"] = (userInputData.at[index, "time taken total"] - userInputData.at[index, "time taken after insertion"])
            
userInputData["time taken before insertion (seconds)"]  = userInputData["time taken before insertion"].dt.total_seconds() 
userInputData["time taken after insertion (seconds)"]  = userInputData["time taken after insertion"].dt.total_seconds() 
userInputData["time taken total"] = pd.to_timedelta(userInputData["time taken total"], errors="coerce")
userInputData["time taken total (seconds)"] = userInputData["time taken total"].dt.total_seconds()

In [151]:
userInputData

,experimentState,are-doors-opened,are-people-inside,are-windows-opened,front-wall,item-used,notes,room,side-right-wall,back-wall,side-left-wall,are-fans-on,no-source-located,timestamp InsertingSource,timestamp StartingExperiment,timestamp EndingExperiment,date of experiment,actual timestamp StartingExperiment,actual timestamp EndingExperiment,time taken total,timestamp InsertingSource timedelta,timestamp InsertingSource seconds,time taken after insertion,time taken before insertion,time taken before insertion (seconds),time taken after insertion (seconds),time taken total (seconds)
0,InsertingSourcePollutant,on,None,None,0.95,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,0.95,None,None,2025-07-01 16:09:41,2025-07-01 15:27:16,2025-07-01 16:14:44,2025-07-01,2025-07-01 15:27:19,2025-07-01 16:14:42,0 days 00:47:23,0 days 00:42:23,2543.0,0 days 00:05:00,0 days 00:42:23,2543.0,300.0,2843.0
1,InsertingSourcePollutant,on,None,None,0.95,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,0.95,None,None,2025-07-02 15:59:29,2025-07-02 15:42:50,2025-07-02 16:04:52,2025-07-02,2025-07-02 15:42:50,2025-07-02 16:04:50,0 days 00:22:00,0 days 00:16:40,1000.0,0 days 00:05:20,0 days 00:16:40,1000.0,320.0,1320.0
2,InsertingSourcePollutant,on,None,None,0.40,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,0.95,None,None,2025-07-03 12:34:32,2025-07-03 12:30:25,2025-07-03 12:45:31,2025-07-03,2025-07-03 12:30:25,2025-07-03 12:45:31,0 days 00:15:06,0 days 00:04:08,248.0,0 days 00:10:58,0 days 00:04:08,248.0,658.0,906.0
3,InsertingSourcePollutant,on,None,None,0.95,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.85,None,None,2025-07-03 15:53:07,2025-07-03 15:43:27,2025-07-03 15:59:11,2025-07-03,2025-07-03 15:51:40,2025-07-03 15:59:10,0 days 00:07:30,0 days 00:01:28,88.0,0 days 00:06:02,0 days 00:01:28,88.0,362.0,450.0
4,InsertingSourcePollutant,on,None,None,1.40,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.35,None,None,2025-07-09 19:19:19,2025-07-09 19:01:42,2025-07-09 19:27:50,2025-07-09,2025-07-09 19:01:44,2025-07-09 19:27:49,0 days 00:26:05,0 days 00:17:36,1056.0,0 days 00:08:29,0 days 00:17:36,1056.0,509.0,1565.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
254,InsertingSourcePollutant,None,None,None,0.50,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",0.5,NaN,NaN,None,None,2025-10-24 20:32:03,2025-10-24 20:29:36,2025-10-24 20:37:33,2025-10-24,2025-10-24 20:29:37,2025-10-24 20:37:31,0 days 00:07:54,0 days 00:02:27,147.0,0 days 00:05:27,0 days 00:02:27,147.0,327.0,474.0
255,InsertingSourcePollutant,None,None,None,0.50,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.30,None,None,2025-10-24 21:05:46,2025-10-24 21:03:22,2025-10-24 21:11:21,2025-10-24,2025-10-24 21:03:24,2025-10-24 21:11:19,0 days 00:07:55,0 days 00:02:23,143.0,0 days 00:05:32,0 days 00:02:23,143.0,332.0,475.0
256,InsertingSourcePollutant,None,None,None,1.50,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.30,None,None,2025-10-24 21:18:43,2025-10-24 21:17:10,2025-10-24 21:24:48,2025-10-24,2025-10-24 21:17:12,2025-10-24 21:24:46,0 days 00:07:34,0 days 00:01:32,92.0,0 days 00:06:02,0 days 00:01:32,92.0,362.0,454.0
257,InsertingSourcePollutant,None,None,None,2.50,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.30,None,None,2025-10-24 21:34:58,2025-10-24 21:33:44,2025-10-24 21:41:06,2025-10-24,2025-10-24 21:33:46,2025-10-24 21:41:04,0 days 00:07:18,0 days 00:01:13,73.0,0 days 00:06:05,0 days 00:01:13,73.0,365.0,438.0
258,InsertingSourcePollutant,None,None,None,3.50,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.30,None,None,2025-10-24 21:54:05,2025-10-24 21:52:16,2025-10-24 22:01:25,2025-10-24,2025-10-24 21:52:18,2025-10-24 22:01:24,0 days 00:09:06,0 days 00:01:48,108.0,0 days 00:07:18,0 days 00:01:48,108.0,438.0,546.0

In [152]:
print(dict_of_timeseries[157].max())
print(userInputData.loc[157])

sensors               Id=2:BME680:breathVocEquivalent
VOC                                          9.690211
after_insertion                                  True
original_value                                   True
datetime_timestamp                2025-10-13 22:34:15
timestamp                             0 days 00:08:03
seconds                                         483.0
dtype: object
experimentState                                                   InsertingSourcePollutant
are-doors-opened                                                                      None
are-people-inside                                                                     None
are-windows-opened                                                                    None
front-wall                                                                             1.5
item-used                                                          Φαρμακευτικό αλκοόλ 95%
notes
room                                     Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...
side-right-wall                                                                        2.5
back-wall                                                                              NaN
side-left-wall                                                                         NaN
are-fans-on                                                                           None
no-source-located                                                                     None
timestamp InsertingSource                                              2025-10-13 22:27:46
timestamp StartingExperiment                                           2025-10-13 22:26:11
timestamp EndingExperiment                                             2025-10-13 22:34:17
date of experiment                                                              2025-10-13
actual timestamp StartingExperiment                                    2025-10-13 22:26:12
actual timestamp EndingExperiment                                      2025-10-13 22:34:15
time taken total                                                           0 days 00:08:03
timestamp InsertingSource timedelta                                        0 days 00:01:35
timestamp InsertingSource seconds                                                     95.0
time taken after insertion                                                 0 days 00:06:28
time taken before insertion                                                0 days 00:01:35
time taken before insertion (seconds)                                                 95.0
time taken after insertion (seconds)                                                 388.0
time taken total (seconds)                                                           483.0
Name: 157, dtype: object

In [153]:
room_mask = userInputData["room"].isin(['Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0.5  ,id:2 Π:0.4 Α:1.0', 'Κρεβατοκάμαρα Όλοι οι αισθητήρες μαζί Π:1.80 , Δ:2.00'])

open_door_mask = userInputData["are-doors-opened"] != "on"
exp_state_mask = (userInputData["experimentState"] =="InsertingSourcePollutant")
mask = room_mask & open_door_mask & exp_state_mask
userInputDataCheck = userInputData.loc[mask]

value = 300  # your threshold value
percentage = (userInputDataCheck["time taken after insertion (seconds)"] >= value).mean() * 100
print(f"{percentage:.2f}% of rows have time taken after insertion (seconds) > {value}")

value = 360  # your threshold value
percentage = (userInputDataCheck["time taken after insertion (seconds)"] >= value).mean() * 100
print(f"{percentage:.2f}% of rows have time taken after insertion (seconds) > {value}")

value = 420  # your threshold value
percentage = (userInputDataCheck["time taken after insertion (seconds)"] >= value).mean() * 100
print(f"{percentage:.2f}% of rows have time taken after insertion (seconds) < {value}")

100.00% of rows have time taken after insertion (seconds) > 300
47.62% of rows have time taken after insertion (seconds) > 360
19.05% of rows have time taken after insertion (seconds) < 420

In [154]:
room_mask =( userInputData["room"].isin(['Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0.5  ,id:2 Π:0.4 Α:1.0', 'Κρεβατοκάμαρα Όλοι οι αισθητήρες μαζί Π:1.80 , Δ:2.00']) ) 

open_door_mask = userInputData["are-doors-opened"] != "on"
exp_state_mask = (userInputData["experimentState"] =="InsertingSourcePollutant")
mask = room_mask & open_door_mask & exp_state_mask
userInputDataCheck = userInputData.loc[mask]

value = 60  # your threshold value
percentage = (userInputDataCheck["time taken before insertion (seconds)"] >= value).mean() * 100
print(f"{percentage:.2f}% of rows have time taken before insertion (seconds) >= {value}")

value = 120  # your threshold value
percentage = (userInputDataCheck["time taken before insertion (seconds)"] >= value).mean() * 100
print(f"{percentage:.2f}% of rows have time taken before insertion (seconds) >= {value}")

value = 180  # your threshold value
percentage = (userInputDataCheck["time taken before insertion (seconds)"] >= value).mean() * 100
print(f"{percentage:.2f}% of rows have time taken before insertion (seconds) >= {value}")

98.10% of rows have time taken before insertion (seconds) >= 60
37.14% of rows have time taken before insertion (seconds) >= 120
9.52% of rows have time taken before insertion (seconds) >= 180

In [155]:
value=60
userInputDataCheck.loc[mask & (userInputDataCheck["time taken before insertion (seconds)"] < value)]

,experimentState,are-doors-opened,are-people-inside,are-windows-opened,front-wall,item-used,notes,room,side-right-wall,back-wall,side-left-wall,are-fans-on,no-source-located,timestamp InsertingSource,timestamp StartingExperiment,timestamp EndingExperiment,date of experiment,actual timestamp StartingExperiment,actual timestamp EndingExperiment,time taken total,timestamp InsertingSource timedelta,timestamp InsertingSource seconds,time taken after insertion,time taken before insertion,time taken before insertion (seconds),time taken after insertion (seconds),time taken total (seconds)
162,InsertingSourcePollutant,None,None,None,2.2,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα Όλοι οι αισθητήρες μαζί Π:1.80 ,...",NaN,NaN,0.5,None,None,2025-10-14 15:04:56,2025-10-14 15:04:15,2025-10-14 15:13:46,2025-10-14,2025-10-14 15:04:17,2025-10-14 15:13:44,0 days 00:09:27,0 days 00:00:40,40.0,0 days 00:08:47,0 days 00:00:40,40.0,527.0,567.0
214,InsertingSourcePollutant,None,None,None,1.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",2.5,NaN,NaN,None,None,2025-10-19 19:17:52,2025-10-19 19:17:03,2025-10-19 19:23:27,2025-10-19,2025-10-19 19:17:05,2025-10-19 19:23:25,0 days 00:06:20,0 days 00:00:48,48.0,0 days 00:05:32,0 days 00:00:48,48.0,332.0,380.0

In [156]:
# Find indices where the column is NaN
to_drop_idx = userInputData[userInputData["timestamp InsertingSource timedelta"].isna()].index
print(to_drop_idx)
# Remove those entries from the dictionary
for key in to_drop_idx:
    dict_of_timeseries.pop(key, None)

# Drop them from the DataFrame
userInputData = userInputData.dropna(subset=["timestamp InsertingSource timedelta"])

Index([6, 49], dtype='int64')

In [157]:
#if set is empty, the deletion at dictionary was succesful
missing_from_dict = set(userInputData.index) - set(dict_of_timeseries.keys())
print("Keys missing from dictionary:", missing_from_dict)

Keys missing from dictionary: set()

In [158]:
userInputData

,experimentState,are-doors-opened,are-people-inside,are-windows-opened,front-wall,item-used,notes,room,side-right-wall,back-wall,side-left-wall,are-fans-on,no-source-located,timestamp InsertingSource,timestamp StartingExperiment,timestamp EndingExperiment,date of experiment,actual timestamp StartingExperiment,actual timestamp EndingExperiment,time taken total,timestamp InsertingSource timedelta,timestamp InsertingSource seconds,time taken after insertion,time taken before insertion,time taken before insertion (seconds),time taken after insertion (seconds),time taken total (seconds)
0,InsertingSourcePollutant,on,None,None,0.95,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,0.95,None,None,2025-07-01 16:09:41,2025-07-01 15:27:16,2025-07-01 16:14:44,2025-07-01,2025-07-01 15:27:19,2025-07-01 16:14:42,0 days 00:47:23,0 days 00:42:23,2543.0,0 days 00:05:00,0 days 00:42:23,2543.0,300.0,2843.0
1,InsertingSourcePollutant,on,None,None,0.95,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,0.95,None,None,2025-07-02 15:59:29,2025-07-02 15:42:50,2025-07-02 16:04:52,2025-07-02,2025-07-02 15:42:50,2025-07-02 16:04:50,0 days 00:22:00,0 days 00:16:40,1000.0,0 days 00:05:20,0 days 00:16:40,1000.0,320.0,1320.0
2,InsertingSourcePollutant,on,None,None,0.40,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,0.95,None,None,2025-07-03 12:34:32,2025-07-03 12:30:25,2025-07-03 12:45:31,2025-07-03,2025-07-03 12:30:25,2025-07-03 12:45:31,0 days 00:15:06,0 days 00:04:08,248.0,0 days 00:10:58,0 days 00:04:08,248.0,658.0,906.0
3,InsertingSourcePollutant,on,None,None,0.95,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.85,None,None,2025-07-03 15:53:07,2025-07-03 15:43:27,2025-07-03 15:59:11,2025-07-03,2025-07-03 15:51:40,2025-07-03 15:59:10,0 days 00:07:30,0 days 00:01:28,88.0,0 days 00:06:02,0 days 00:01:28,88.0,362.0,450.0
4,InsertingSourcePollutant,on,None,None,1.40,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.35,None,None,2025-07-09 19:19:19,2025-07-09 19:01:42,2025-07-09 19:27:50,2025-07-09,2025-07-09 19:01:44,2025-07-09 19:27:49,0 days 00:26:05,0 days 00:17:36,1056.0,0 days 00:08:29,0 days 00:17:36,1056.0,509.0,1565.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
254,InsertingSourcePollutant,None,None,None,0.50,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",0.5,NaN,NaN,None,None,2025-10-24 20:32:03,2025-10-24 20:29:36,2025-10-24 20:37:33,2025-10-24,2025-10-24 20:29:37,2025-10-24 20:37:31,0 days 00:07:54,0 days 00:02:27,147.0,0 days 00:05:27,0 days 00:02:27,147.0,327.0,474.0
255,InsertingSourcePollutant,None,None,None,0.50,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.30,None,None,2025-10-24 21:05:46,2025-10-24 21:03:22,2025-10-24 21:11:21,2025-10-24,2025-10-24 21:03:24,2025-10-24 21:11:19,0 days 00:07:55,0 days 00:02:23,143.0,0 days 00:05:32,0 days 00:02:23,143.0,332.0,475.0
256,InsertingSourcePollutant,None,None,None,1.50,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.30,None,None,2025-10-24 21:18:43,2025-10-24 21:17:10,2025-10-24 21:24:48,2025-10-24,2025-10-24 21:17:12,2025-10-24 21:24:46,0 days 00:07:34,0 days 00:01:32,92.0,0 days 00:06:02,0 days 00:01:32,92.0,362.0,454.0
257,InsertingSourcePollutant,None,None,None,2.50,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.30,None,None,2025-10-24 21:34:58,2025-10-24 21:33:44,2025-10-24 21:41:06,2025-10-24,2025-10-24 21:33:46,2025-10-24 21:41:04,0 days 00:07:18,0 days 00:01:13,73.0,0 days 00:06:05,0 days 00:01:13,73.0,365.0,438.0
258,InsertingSourcePollutant,None,None,None,3.50,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.30,None,None,2025-10-24 21:54:05,2025-10-24 21:52:16,2025-10-24 22:01:25,2025-10-24,2025-10-24 21:52:18,2025-10-24 22:01:24,0 days 00:09:06,0 days 00:01:48,108.0,0 days 00:07:18,0 days 00:01:48,108.0,438.0,546.0

In [159]:
for index, row in userInputData.iterrows():
    
    particular_experiment =  dict_of_timeseries[index]
    particular_experiment["seconds passed from insertionSource"] = np.nan
    sensors = particular_experiment["sensors"].unique()
    
    for sensor in sensors:
        
        mask = particular_experiment["sensors"]==sensor
        particular_experiment.loc[mask,"seconds passed from insertionSource"] = particular_experiment.loc[mask,"seconds"] - row["timestamp InsertingSource seconds"]  
    dict_of_timeseries[index] =   particular_experiment

In [160]:
dict_of_timeseries[10]

,sensors,VOC,after_insertion,original_value,datetime_timestamp,timestamp,seconds,seconds passed from insertionSource
0,Id=1:BME680:breathVocEquivalent,0.517211,False,True,2025-07-19 16:04:24,0 days 00:00:00,0.0,-511.0
1,Id=2:BME680:breathVocEquivalent,0.508068,False,True,2025-07-19 16:04:24,0 days 00:00:00,0.0,-511.0
2,Id=1:BME680:breathVocEquivalent,0.518917,False,True,2025-07-19 16:04:25,0 days 00:00:01,1.0,-510.0
3,Id=2:BME680:breathVocEquivalent,0.503896,False,True,2025-07-19 16:04:25,0 days 00:00:01,1.0,-510.0
4,Id=1:BME680:breathVocEquivalent,0.520305,False,True,2025-07-19 16:04:26,0 days 00:00:02,2.0,-509.0
...,...,...,...,...,...,...,...,...
2098,Id=2:BME680:breathVocEquivalent,5.635052,True,True,2025-07-19 16:21:52,0 days 00:17:28,1048.0,537.0
2099,Id=1:BME680:breathVocEquivalent,2.609777,True,True,2025-07-19 16:21:53,0 days 00:17:29,1049.0,538.0
2100,Id=2:BME680:breathVocEquivalent,5.629334,True,True,2025-07-19 16:21:53,0 days 00:17:29,1049.0,538.0
2101,Id=1:BME680:breathVocEquivalent,2.601317,True,True,2025-07-19 16:21:54,0 days 00:17:30,1050.0,539.0
2102,Id=2:BME680:breathVocEquivalent,5.601505,True,True,2025-07-19 16:21:54,0 days 00:17:30,1050.0,539.0

In [161]:
print(dict_of_timeseries[157].max())
print(userInputData.loc[157])

sensors                                Id=2:BME680:breathVocEquivalent
VOC                                                           9.690211
after_insertion                                                   True
original_value                                                    True
datetime_timestamp                                 2025-10-13 22:34:15
timestamp                                              0 days 00:08:03
seconds                                                          483.0
seconds passed from insertionSource                              388.0
dtype: object
experimentState                                                   InsertingSourcePollutant
are-doors-opened                                                                      None
are-people-inside                                                                     None
are-windows-opened                                                                    None
front-wall                                                                             1.5
item-used                                                          Φαρμακευτικό αλκοόλ 95%
notes
room                                     Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...
side-right-wall                                                                        2.5
back-wall                                                                              NaN
side-left-wall                                                                         NaN
are-fans-on                                                                           None
no-source-located                                                                     None
timestamp InsertingSource                                              2025-10-13 22:27:46
timestamp StartingExperiment                                           2025-10-13 22:26:11
timestamp EndingExperiment                                             2025-10-13 22:34:17
date of experiment                                                              2025-10-13
actual timestamp StartingExperiment                                    2025-10-13 22:26:12
actual timestamp EndingExperiment                                      2025-10-13 22:34:15
time taken total                                                           0 days 00:08:03
timestamp InsertingSource timedelta                                        0 days 00:01:35
timestamp InsertingSource seconds                                                     95.0
time taken after insertion                                                 0 days 00:06:28
time taken before insertion                                                0 days 00:01:35
time taken before insertion (seconds)                                                 95.0
time taken after insertion (seconds)                                                 388.0
time taken total (seconds)                                                           483.0
Name: 157, dtype: object

In [162]:

#use rolling window
for index, row in userInputData.iterrows():
    particular_experiment =  dict_of_timeseries[index].copy()
    sensors = particular_experiment["sensors"].unique()

    for sensor in sensors:
        mask = particular_experiment["sensors"]==sensor
        particular_experiment.loc[mask,"VOC rolling average"] = particular_experiment.loc[mask].rolling(30,center= True ,min_periods=1,on="seconds")["VOC"].mean()


        
 #   scaler = StandardScaler()
#    particular_experiment.loc[:,"VOC standard scaled"] = scaler.fit_transform(particular_experiment.loc[:,"VOC"].to_numpy().reshape(-1,1))
#    particular_experiment.loc[:,"VOC rolling average standard scaled"] = scaler.fit_transform(particular_experiment.loc[:,"VOC rolling average"].to_numpy().reshape(-1,1))


    dict_of_timeseries[index] = particular_experiment

In [163]:
#round VOC rolling average data at 3 decimals
for index, row in userInputData.iterrows():
    
    particular_experiment =  dict_of_timeseries[index].copy()
    particular_experiment["VOC rolling average"] = particular_experiment["VOC rolling average"].round(3)
    dict_of_timeseries[index]  =  particular_experiment

In [164]:
#trim the time before insertion to be less than two minutes 
#trim the time after insertion to be less than ten minutes
max_before= 61
max_after = 300
columns_to_add = ["time taken total (seconds)-capped","time taken before insertion (seconds)-capped","time taken after insertion (seconds)-capped"]
for index, row in userInputData.iterrows():
    particular_experiment =  dict_of_timeseries[index]
    for col in columns_to_add:
        if col not in userInputData.columns:
            userInputData[col] = np.nan  
      
    time_mask = (particular_experiment["seconds passed from insertionSource"] > ( - max_before)) & (particular_experiment["seconds passed from insertionSource"] < max_after)
    particular_experiment = particular_experiment.loc[time_mask,:].copy()
   
    
    particular_experiment["original seconds"] = particular_experiment["seconds"]
    sensors = particular_experiment["sensors"].unique()
    
    for sensor in sensors:
        mask = particular_experiment["sensors"] == sensor 
        min_sensor_time = particular_experiment.loc[mask,"seconds passed from insertionSource"].min()
        max_sensor_time = particular_experiment.loc[mask,"seconds passed from insertionSource"].max()
        particular_experiment.loc[mask,"seconds"] = np.arange(min_sensor_time,max_sensor_time + 1) 
    min_sensor_time = particular_experiment["seconds passed from insertionSource"].min()    
    max_sensor_time = particular_experiment["seconds passed from insertionSource"].max()    

    userInputData.at[index,"time taken before insertion (seconds)-capped"] = min_sensor_time
    userInputData.at[index,"time taken after insertion (seconds)-capped"] =max_sensor_time
    userInputData.at[index,"time taken total (seconds)-capped"] = min_sensor_time +  max_sensor_time +1

    dict_of_timeseries[index]  =  particular_experiment

C:\Users\Andreas\AppData\Local\Temp\ipykernel_6164\3247368483.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  userInputData[col] = np.nan
C:\Users\Andreas\AppData\Local\Temp\ipykernel_6164\3247368483.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  userInputData[col] = np.nan
C:\Users\Andreas\AppData\Local\Temp\ipykernel_6164\3247368483.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  userInputData[col] = np.nan

In [165]:
dict_of_timeseries[11]

,sensors,VOC,after_insertion,original_value,datetime_timestamp,timestamp,seconds,seconds passed from insertionSource,VOC rolling average,original seconds
1166,Id=2:BME680:breathVocEquivalent,1.287301,False,True,2025-07-19 16:45:47,0 days 00:09:43,-59.0,-59.0,1.293,583.0
1167,Id=1:BME680:breathVocEquivalent,1.325307,False,True,2025-07-19 16:45:47,0 days 00:09:43,-59.0,-59.0,1.319,583.0
1168,Id=2:BME680:breathVocEquivalent,1.281282,False,True,2025-07-19 16:45:48,0 days 00:09:44,-58.0,-58.0,1.295,584.0
1169,Id=1:BME680:breathVocEquivalent,1.323364,False,True,2025-07-19 16:45:48,0 days 00:09:44,-58.0,-58.0,1.320,584.0
1170,Id=2:BME680:breathVocEquivalent,1.281010,False,True,2025-07-19 16:45:49,0 days 00:09:45,-57.0,-57.0,1.296,585.0
...,...,...,...,...,...,...,...,...,...,...
1881,Id=1:BME680:breathVocEquivalent,1.927478,True,True,2025-07-19 16:51:44,0 days 00:15:40,298.0,298.0,1.934,940.0
1882,Id=2:BME680:breathVocEquivalent,3.148859,True,True,2025-07-19 16:51:45,0 days 00:15:41,299.0,299.0,3.151,941.0
1883,Id=1:BME680:breathVocEquivalent,1.941105,True,True,2025-07-19 16:51:45,0 days 00:15:41,299.0,299.0,1.940,941.0
1884,Id=2:BME680:breathVocEquivalent,3.170057,True,True,2025-07-19 16:51:46,0 days 00:15:42,300.0,300.0,3.170,942.0
1885,Id=1:BME680:breathVocEquivalent,1.952947,True,True,2025-07-19 16:51:46,0 days 00:15:42,300.0,300.0,1.947,942.0

In [166]:
print(dict_of_timeseries[157].max())
print(userInputData.loc[157])

sensors                                Id=2:BME680:breathVocEquivalent
VOC                                                           5.655352
after_insertion                                                   True
original_value                                                    True
datetime_timestamp                                 2025-10-13 22:32:47
timestamp                                              0 days 00:06:35
seconds                                                          300.0
seconds passed from insertionSource                              300.0
VOC rolling average                                              5.501
original seconds                                                 395.0
dtype: object
experimentState                                                          InsertingSourcePollutant
are-doors-opened                                                                             None
are-people-inside                                                                            None
are-windows-opened                                                                           None
front-wall                                                                                    1.5
item-used                                                                 Φαρμακευτικό αλκοόλ 95%
notes
room                                            Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...
side-right-wall                                                                               2.5
back-wall                                                                                     NaN
side-left-wall                                                                                NaN
are-fans-on                                                                                  None
no-source-located                                                                            None
timestamp InsertingSource                                                     2025-10-13 22:27:46
timestamp StartingExperiment                                                  2025-10-13 22:26:11
timestamp EndingExperiment                                                    2025-10-13 22:34:17
date of experiment                                                                     2025-10-13
actual timestamp StartingExperiment                                           2025-10-13 22:26:12
actual timestamp EndingExperiment                                             2025-10-13 22:34:15
time taken total                                                                  0 days 00:08:03
timestamp InsertingSource timedelta                                               0 days 00:01:35
timestamp InsertingSource seconds                                                            95.0
time taken after insertion                                                        0 days 00:06:28
time taken before insertion                                                       0 days 00:01:35
time taken before insertion (seconds)                                                        95.0
time taken after insertion (seconds)                                                        388.0
time taken total (seconds)                                                                  483.0
time taken total (seconds)-capped                                                           242.0
time taken before insertion (seconds)-capped                                                -59.0
time taken after insertion (seconds)-capped                                                 300.0
Name: 157, dtype: object

In [167]:
dict_of_timeseries[12]

,sensors,VOC,after_insertion,original_value,datetime_timestamp,timestamp,seconds,seconds passed from insertionSource,VOC rolling average,original seconds
2252,Id=2:BME680:breathVocEquivalent,1.709757,False,True,2025-07-19 17:24:38,0 days 00:18:46,-59.0,-59.0,1.733,1126.0
2253,Id=1:BME680:breathVocEquivalent,2.037875,False,True,2025-07-19 17:24:38,0 days 00:18:46,-59.0,-59.0,2.018,1126.0
2254,Id=2:BME680:breathVocEquivalent,1.710618,False,True,2025-07-19 17:24:39,0 days 00:18:47,-58.0,-58.0,1.733,1127.0
2255,Id=1:BME680:breathVocEquivalent,2.028574,False,True,2025-07-19 17:24:39,0 days 00:18:47,-58.0,-58.0,2.020,1127.0
2256,Id=2:BME680:breathVocEquivalent,1.716466,False,True,2025-07-19 17:24:40,0 days 00:18:48,-57.0,-57.0,1.734,1128.0
...,...,...,...,...,...,...,...,...,...,...
2967,Id=1:BME680:breathVocEquivalent,2.496685,True,True,2025-07-19 17:30:35,0 days 00:24:43,298.0,298.0,2.496,1483.0
2968,Id=2:BME680:breathVocEquivalent,2.649344,True,True,2025-07-19 17:30:36,0 days 00:24:44,299.0,299.0,2.675,1484.0
2969,Id=1:BME680:breathVocEquivalent,2.503186,True,True,2025-07-19 17:30:36,0 days 00:24:44,299.0,299.0,2.500,1484.0
2970,Id=2:BME680:breathVocEquivalent,2.663743,True,True,2025-07-19 17:30:37,0 days 00:24:45,300.0,300.0,2.689,1485.0
2971,Id=1:BME680:breathVocEquivalent,2.509936,True,True,2025-07-19 17:30:37,0 days 00:24:45,300.0,300.0,2.503,1485.0

In [168]:
userInputData.loc[:,["front-wall","side-right-wall","back-wall","side-left-wall"]] = userInputData.loc[:,["front-wall","side-right-wall","back-wall","side-left-wall"]].round(1)

In [169]:
userInputData

,experimentState,are-doors-opened,are-people-inside,are-windows-opened,front-wall,item-used,notes,room,side-right-wall,back-wall,side-left-wall,are-fans-on,no-source-located,timestamp InsertingSource,timestamp StartingExperiment,timestamp EndingExperiment,date of experiment,actual timestamp StartingExperiment,actual timestamp EndingExperiment,time taken total,timestamp InsertingSource timedelta,timestamp InsertingSource seconds,time taken after insertion,time taken before insertion,time taken before insertion (seconds),time taken after insertion (seconds),time taken total (seconds),time taken total (seconds)-capped,time taken before insertion (seconds)-capped,time taken after insertion (seconds)-capped
0,InsertingSourcePollutant,on,None,None,1.0,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.0,None,None,2025-07-01 16:09:41,2025-07-01 15:27:16,2025-07-01 16:14:44,2025-07-01,2025-07-01 15:27:19,2025-07-01 16:14:42,0 days 00:47:23,0 days 00:42:23,2543.0,0 days 00:05:00,0 days 00:42:23,2543.0,300.0,2843.0,242.0,-59.0,300.0
1,InsertingSourcePollutant,on,None,None,1.0,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.0,None,None,2025-07-02 15:59:29,2025-07-02 15:42:50,2025-07-02 16:04:52,2025-07-02,2025-07-02 15:42:50,2025-07-02 16:04:50,0 days 00:22:00,0 days 00:16:40,1000.0,0 days 00:05:20,0 days 00:16:40,1000.0,320.0,1320.0,242.0,-59.0,300.0
2,InsertingSourcePollutant,on,None,None,0.4,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.0,None,None,2025-07-03 12:34:32,2025-07-03 12:30:25,2025-07-03 12:45:31,2025-07-03,2025-07-03 12:30:25,2025-07-03 12:45:31,0 days 00:15:06,0 days 00:04:08,248.0,0 days 00:10:58,0 days 00:04:08,248.0,658.0,906.0,242.0,-59.0,300.0
3,InsertingSourcePollutant,on,None,None,1.0,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.8,None,None,2025-07-03 15:53:07,2025-07-03 15:43:27,2025-07-03 15:59:11,2025-07-03,2025-07-03 15:51:40,2025-07-03 15:59:10,0 days 00:07:30,0 days 00:01:28,88.0,0 days 00:06:02,0 days 00:01:28,88.0,362.0,450.0,242.0,-59.0,300.0
4,InsertingSourcePollutant,on,None,None,1.4,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.4,None,None,2025-07-09 19:19:19,2025-07-09 19:01:42,2025-07-09 19:27:50,2025-07-09,2025-07-09 19:01:44,2025-07-09 19:27:49,0 days 00:26:05,0 days 00:17:36,1056.0,0 days 00:08:29,0 days 00:17:36,1056.0,509.0,1565.0,242.0,-59.0,300.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
254,InsertingSourcePollutant,None,None,None,0.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",0.5,NaN,NaN,None,None,2025-10-24 20:32:03,2025-10-24 20:29:36,2025-10-24 20:37:33,2025-10-24,2025-10-24 20:29:37,2025-10-24 20:37:31,0 days 00:07:54,0 days 00:02:27,147.0,0 days 00:05:27,0 days 00:02:27,147.0,327.0,474.0,242.0,-59.0,300.0
255,InsertingSourcePollutant,None,None,None,0.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:05:46,2025-10-24 21:03:22,2025-10-24 21:11:21,2025-10-24,2025-10-24 21:03:24,2025-10-24 21:11:19,0 days 00:07:55,0 days 00:02:23,143.0,0 days 00:05:32,0 days 00:02:23,143.0,332.0,475.0,242.0,-59.0,300.0
256,InsertingSourcePollutant,None,None,None,1.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:18:43,2025-10-24 21:17:10,2025-10-24 21:24:48,2025-10-24,2025-10-24 21:17:12,2025-10-24 21:24:46,0 days 00:07:34,0 days 00:01:32,92.0,0 days 00:06:02,0 days 00:01:32,92.0,362.0,454.0,242.0,-59.0,300.0
257,InsertingSourcePollutant,None,None,None,2.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:34:58,2025-10-24 21:33:44,2025-10-24 21:41:06,2025-10-24,2025-10-24 21:33:46,2025-10-24 21:41:04,0 days 00:07:18,0 days 00:01:13,73.0,0 days 00:06:05,0 days 00:01:13,73.0,365.0,438.0,242.0,-59.0,300.0
258,InsertingSourcePollutant,None,None,None,3.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:54:05,2025-10-24 21:52:16,2025-10-24 22:01:25,2025-10-24,2025-10-24 21:52:18,2025-10-24 22:01:24,0 days 00:09:06,0 days 00:01:48,108.0,0 days 00:07:18,0 days 00:01:48,108.0,438.0,546.0,242.0,-59.0,300.0

In [170]:
#make for each experiment and sensor as min the value zero
for index, row in userInputData.iterrows():
    particular_experiment =  dict_of_timeseries[index].copy()
    sensors = particular_experiment["sensors"].unique()
    col_name = "VOC rolling average"
    if col_name  not in particular_experiment.columns:
        particular_experiment[col_name] = np.nan
    for sensor in sensors:
        mask = particular_experiment["sensors"]==sensor
        particular_experiment.loc[mask,col_name] = particular_experiment.loc[mask,"VOC rolling average"] - particular_experiment.loc[mask,"VOC rolling average"].min()
    dict_of_timeseries[index]  =  particular_experiment

In [171]:
dict_of_timeseries[157]

,sensors,VOC,after_insertion,original_value,datetime_timestamp,timestamp,seconds,seconds passed from insertionSource,VOC rolling average,original seconds
108,Id=0:BME680:breathVocEquivalent,1.670143,False,True,2025-10-13 22:26:48,0 days 00:00:36,-59.0,-59.0,0.000,36.0
109,Id=1:BME680:breathVocEquivalent,2.413401,False,True,2025-10-13 22:26:48,0 days 00:00:36,-59.0,-59.0,0.155,36.0
110,Id=2:BME680:breathVocEquivalent,1.253582,False,True,2025-10-13 22:26:48,0 days 00:00:36,-59.0,-59.0,0.000,36.0
111,Id=0:BME680:breathVocEquivalent,1.677506,False,True,2025-10-13 22:26:49,0 days 00:00:37,-58.0,-58.0,0.009,37.0
112,Id=1:BME680:breathVocEquivalent,2.409750,False,True,2025-10-13 22:26:49,0 days 00:00:37,-58.0,-58.0,0.163,37.0
...,...,...,...,...,...,...,...,...,...,...
1183,Id=1:BME680:breathVocEquivalent,4.553225,True,True,2025-10-13 22:32:46,0 days 00:06:34,299.0,299.0,2.326,394.0
1184,Id=2:BME680:breathVocEquivalent,4.865380,True,True,2025-10-13 22:32:46,0 days 00:06:34,299.0,299.0,3.591,394.0
1185,Id=0:BME680:breathVocEquivalent,5.587928,True,True,2025-10-13 22:32:47,0 days 00:06:35,300.0,300.0,3.803,395.0
1186,Id=1:BME680:breathVocEquivalent,4.564097,True,True,2025-10-13 22:32:47,0 days 00:06:35,300.0,300.0,2.334,395.0
1187,Id=2:BME680:breathVocEquivalent,4.920298,True,True,2025-10-13 22:32:47,0 days 00:06:35,300.0,300.0,3.673,395.0

In [172]:
dict_of_timeseries[157]

,sensors,VOC,after_insertion,original_value,datetime_timestamp,timestamp,seconds,seconds passed from insertionSource,VOC rolling average,original seconds
108,Id=0:BME680:breathVocEquivalent,1.670143,False,True,2025-10-13 22:26:48,0 days 00:00:36,-59.0,-59.0,0.000,36.0
109,Id=1:BME680:breathVocEquivalent,2.413401,False,True,2025-10-13 22:26:48,0 days 00:00:36,-59.0,-59.0,0.155,36.0
110,Id=2:BME680:breathVocEquivalent,1.253582,False,True,2025-10-13 22:26:48,0 days 00:00:36,-59.0,-59.0,0.000,36.0
111,Id=0:BME680:breathVocEquivalent,1.677506,False,True,2025-10-13 22:26:49,0 days 00:00:37,-58.0,-58.0,0.009,37.0
112,Id=1:BME680:breathVocEquivalent,2.409750,False,True,2025-10-13 22:26:49,0 days 00:00:37,-58.0,-58.0,0.163,37.0
...,...,...,...,...,...,...,...,...,...,...
1183,Id=1:BME680:breathVocEquivalent,4.553225,True,True,2025-10-13 22:32:46,0 days 00:06:34,299.0,299.0,2.326,394.0
1184,Id=2:BME680:breathVocEquivalent,4.865380,True,True,2025-10-13 22:32:46,0 days 00:06:34,299.0,299.0,3.591,394.0
1185,Id=0:BME680:breathVocEquivalent,5.587928,True,True,2025-10-13 22:32:47,0 days 00:06:35,300.0,300.0,3.803,395.0
1186,Id=1:BME680:breathVocEquivalent,4.564097,True,True,2025-10-13 22:32:47,0 days 00:06:35,300.0,300.0,2.334,395.0
1187,Id=2:BME680:breathVocEquivalent,4.920298,True,True,2025-10-13 22:32:47,0 days 00:06:35,300.0,300.0,3.673,395.0

In [173]:
#make the seconds to be index
for index, row in userInputData.iterrows():
    
    particular_experiment =  dict_of_timeseries[index].copy()
    
    dict_of_timeseries[index]  =  particular_experiment.set_index("seconds",drop = False)

In [174]:
dict_of_timeseries[190]

,sensors,VOC,after_insertion,original_value,datetime_timestamp,timestamp,seconds,seconds passed from insertionSource,VOC rolling average,original seconds
seconds,,,,,,,,,,
-59.0,Id=0:BME680:breathVocEquivalent,1.638338,False,True,2025-10-17 12:26:11,0 days 00:00:21,-59.0,-59.0,0.000,21.0
-59.0,Id=2:BME680:breathVocEquivalent,1.817220,False,True,2025-10-17 12:26:11,0 days 00:00:21,-59.0,-59.0,0.000,21.0
-59.0,Id=1:BME680:breathVocEquivalent,1.763197,False,True,2025-10-17 12:26:11,0 days 00:00:21,-59.0,-59.0,0.044,21.0
-58.0,Id=0:BME680:breathVocEquivalent,1.644204,False,True,2025-10-17 12:26:12,0 days 00:00:22,-58.0,-58.0,0.003,22.0
-58.0,Id=2:BME680:breathVocEquivalent,1.823438,False,True,2025-10-17 12:26:12,0 days 00:00:22,-58.0,-58.0,0.001,22.0
...,...,...,...,...,...,...,...,...,...,...
299.0,Id=2:BME680:breathVocEquivalent,2.537247,True,True,2025-10-17 12:32:09,0 days 00:06:19,299.0,299.0,0.732,379.0
299.0,Id=1:BME680:breathVocEquivalent,2.191384,True,True,2025-10-17 12:32:09,0 days 00:06:19,299.0,299.0,0.497,379.0
300.0,Id=0:BME680:breathVocEquivalent,2.872036,True,True,2025-10-17 12:32:10,0 days 00:06:20,300.0,300.0,1.206,380.0
300.0,Id=2:BME680:breathVocEquivalent,2.531267,True,True,2025-10-17 12:32:10,0 days 00:06:20,300.0,300.0,0.732,380.0
300.0,Id=1:BME680:breathVocEquivalent,2.191455,True,True,2025-10-17 12:32:10,0 days 00:06:20,300.0,300.0,0.498,380.0

In [175]:
#find max values and its position
for index, row in userInputData.iterrows():
    particular_experiment =  dict_of_timeseries[index].copy()
    sensors = particular_experiment["sensors"].unique()
    column_to_find_values = "VOC rolling average"
    for sensor in sensors:
        mask = particular_experiment["sensors"]==sensor
        
        col_name = f"{sensor} MAX value {column_to_find_values}"
        if col_name  not in userInputData.columns:
            userInputData.loc[:,col_name] = np.nan
        userInputData.at[index,col_name] = particular_experiment.loc[mask,column_to_find_values].max()
    
            
        col_name = f"{sensor} index of MAX value {column_to_find_values}"
        if col_name  not in userInputData.columns:
            userInputData.loc[:,col_name] = np.nan    
        userInputData.at[index,col_name] = particular_experiment.loc[mask,column_to_find_values].idxmax()

dict_of_timeseries[index]  =  particular_experiment

C:\Users\Andreas\AppData\Local\Temp\ipykernel_6164\1512944631.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  userInputData.loc[:,col_name] = np.nan
C:\Users\Andreas\AppData\Local\Temp\ipykernel_6164\1512944631.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  userInputData.loc[:,col_name] = np.nan
C:\Users\Andreas\AppData\Local\Temp\ipykernel_6164\1512944631.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  userInputData.loc[:,col_name] = np.nan
C:\Users\Andreas\AppData\Local\Temp\ipykernel_6164\1512944631.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  userInputData.loc[:,col_name] = np.nan
C:\Users\Andreas\AppData\Local\Temp\ipykernel_6164\1512944631.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  userInputData.loc[:,col_name] = np.nan
C:\Users\Andreas\AppData\Local\Temp\ipykernel_6164\1512944631.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  userInputData.loc[:,col_name] = np.nan

In [176]:
userInputData

,experimentState,are-doors-opened,are-people-inside,are-windows-opened,front-wall,item-used,notes,room,side-right-wall,back-wall,side-left-wall,are-fans-on,no-source-located,timestamp InsertingSource,timestamp StartingExperiment,timestamp EndingExperiment,date of experiment,actual timestamp StartingExperiment,actual timestamp EndingExperiment,time taken total,timestamp InsertingSource timedelta,timestamp InsertingSource seconds,time taken after insertion,time taken before insertion,time taken before insertion (seconds),time taken after insertion (seconds),time taken total (seconds),time taken total (seconds)-capped,time taken before insertion (seconds)-capped,time taken after insertion (seconds)-capped,Id=1:BME680:breathVocEquivalent MAX value VOC rolling average,Id=1:BME680:breathVocEquivalent index of MAX value VOC rolling average,Id=2:BME680:breathVocEquivalent MAX value VOC rolling average,Id=2:BME680:breathVocEquivalent index of MAX value VOC rolling average,Id=0:BME680:breathVocEquivalent MAX value VOC rolling average,Id=0:BME680:breathVocEquivalent index of MAX value VOC rolling average
0,InsertingSourcePollutant,on,None,None,1.0,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.0,None,None,2025-07-01 16:09:41,2025-07-01 15:27:16,2025-07-01 16:14:44,2025-07-01,2025-07-01 15:27:19,2025-07-01 16:14:42,0 days 00:47:23,0 days 00:42:23,2543.0,0 days 00:05:00,0 days 00:42:23,2543.0,300.0,2843.0,242.0,-59.0,300.0,3.063,299.0,3.322,242.0,NaN,NaN
1,InsertingSourcePollutant,on,None,None,1.0,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.0,None,None,2025-07-02 15:59:29,2025-07-02 15:42:50,2025-07-02 16:04:52,2025-07-02,2025-07-02 15:42:50,2025-07-02 16:04:50,0 days 00:22:00,0 days 00:16:40,1000.0,0 days 00:05:20,0 days 00:16:40,1000.0,320.0,1320.0,242.0,-59.0,300.0,1.083,201.0,0.307,78.0,NaN,NaN
2,InsertingSourcePollutant,on,None,None,0.4,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.0,None,None,2025-07-03 12:34:32,2025-07-03 12:30:25,2025-07-03 12:45:31,2025-07-03,2025-07-03 12:30:25,2025-07-03 12:45:31,0 days 00:15:06,0 days 00:04:08,248.0,0 days 00:10:58,0 days 00:04:08,248.0,658.0,906.0,242.0,-59.0,300.0,1.372,235.0,2.294,300.0,NaN,NaN
3,InsertingSourcePollutant,on,None,None,1.0,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.8,None,None,2025-07-03 15:53:07,2025-07-03 15:43:27,2025-07-03 15:59:11,2025-07-03,2025-07-03 15:51:40,2025-07-03 15:59:10,0 days 00:07:30,0 days 00:01:28,88.0,0 days 00:06:02,0 days 00:01:28,88.0,362.0,450.0,242.0,-59.0,300.0,0.332,300.0,18.486,300.0,NaN,NaN
4,InsertingSourcePollutant,on,None,None,1.4,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.4,None,None,2025-07-09 19:19:19,2025-07-09 19:01:42,2025-07-09 19:27:50,2025-07-09,2025-07-09 19:01:44,2025-07-09 19:27:49,0 days 00:26:05,0 days 00:17:36,1056.0,0 days 00:08:29,0 days 00:17:36,1056.0,509.0,1565.0,242.0,-59.0,300.0,0.600,245.0,0.512,300.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
254,InsertingSourcePollutant,None,None,None,0.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",0.5,NaN,NaN,None,None,2025-10-24 20:32:03,2025-10-24 20:29:36,2025-10-24 20:37:33,2025-10-24,2025-10-24 20:29:37,2025-10-24 20:37:31,0 days 00:07:54,0 days 00:02:27,147.0,0 days 00:05:27,0 days 00:02:27,147.0,327.0,474.0,242.0,-59.0,300.0,1.748,131.0,4.850,300.0,1.947,285.0
255,InsertingSourcePollutant,None,None,None,0.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:05:46,2025-10-24 21:03:22,2025-10-24 21:11:21,2025-10-24,2025-10-24 21:03:24,2025-10-24 21:11:19,0 days 00:07:55,0 days 00:02:23,143.0,0 days 00:05:32,0 days 00:02:23,143.0,332.0,475.0,242.0,-59.0,300.0,1.057,300.0,5.182,300.0,2.413,236.0
256,InsertingSourcePollutant,None,None,None,1.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:18:43,2025-10-24 21:17:10,2025-10-24 21:24:48,2025-10-24,2025-10-24 21:17:12,2025-10-24 21:24:46,0 days 00:07:34,0 days 00:01:32,92.0,0 days 00:06:02,0 days 00:01:32,92.0,362.0,454.0,242.0,-59.0,300.0,1.948,300.0,12.093,277.0,1.837,140.0
257,InsertingSourcePollutant,None,None,None,2.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:34:58,2025-10-24 21:33:44,2025-10-24 21:41:06,2025-10-24,2025-10-24 21:33:46,2025-10-24 21:41:04,0 days 00:07:18,0 days 00:01:13,73.0,0 days 00:06:05,0 days 00:01:13,73.0,365.0,438.0,242.0,-59.0,300.0,1.745,300.0,7.490,260.0,1.193,300.0
258,InsertingSourcePollutant,None,None,None,3.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:54:05,2025-10-24 21:52:16,2025-10-24 22:01:25,2025-10-24,2025-10-24 21:52:18,2025-10-24 22:01:24,0 days 00:09:06,0 days 00:01:48,108.0,0 days 00:07:18,0 days 00:01:48,108.0,438.0,546.0,242.0,-59.0,300.0,1.613,212.0,2.972,287.0,1.935,300.0

In [177]:
print(dict_of_timeseries[157].max())
print(userInputData.loc[157])

sensors                                Id=2:BME680:breathVocEquivalent
VOC                                                           5.655352
after_insertion                                                   True
original_value                                                    True
datetime_timestamp                                 2025-10-13 22:32:47
timestamp                                              0 days 00:06:35
seconds                                                          300.0
seconds passed from insertionSource                              300.0
VOC rolling average                                              3.835
original seconds                                                 395.0
dtype: object
experimentState                                                                                    InsertingSourcePollutant
are-doors-opened                                                                                                       None
are-people-inside                                                                                                      None
are-windows-opened                                                                                                     None
front-wall                                                                                                              1.5
item-used                                                                                           Φαρμακευτικό αλκοόλ 95%
notes
room                                                                      Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...
side-right-wall                                                                                                         2.5
back-wall                                                                                                               NaN
side-left-wall                                                                                                          NaN
are-fans-on                                                                                                            None
no-source-located                                                                                                      None
timestamp InsertingSource                                                                               2025-10-13 22:27:46
timestamp StartingExperiment                                                                            2025-10-13 22:26:11
timestamp EndingExperiment                                                                              2025-10-13 22:34:17
date of experiment                                                                                               2025-10-13
actual timestamp StartingExperiment                                                                     2025-10-13 22:26:12
actual timestamp EndingExperiment                                                                       2025-10-13 22:34:15
time taken total                                                                                            0 days 00:08:03
timestamp InsertingSource timedelta                                                                         0 days 00:01:35
timestamp InsertingSource seconds                                                                                      95.0
time taken after insertion                                                                                  0 days 00:06:28
time taken before insertion                                                                                 0 days 00:01:35
time taken before insertion (seconds)                                                                                  95.0
time taken after insertion (seconds)                                                                                  388.0
time taken total (seconds)                                                                                            483.0
time taken total (seconds)-capped                                                                                     242.0
time taken before insertion (seconds)-capped                                                                          -59.0
time taken after insertion (seconds)-capped                                                                           300.0
Id=1:BME680:breathVocEquivalent MAX value VOC rolling average                                                         2.334
Id=1:BME680:breathVocEquivalent index of MAX value VOC rolling average                                                300.0
Id=2:BME680:breathVocEquivalent MAX value VOC rolling average                                                         3.673
Id=2:BME680:breathVocEquivalent index of MAX value VOC rolling average                                                300.0
Id=0:BME680:breathVocEquivalent MAX value VOC rolling average                                                         3.835
Id=0:BME680:breathVocEquivalent index of MAX value VOC rolling average                                                295.0
Name: 157, dtype: object

In [178]:
col_list = []

for sensor in sensors:
    col_name = f"{sensor} MAX value {column_to_find_values}"
    col_list.append(col_name)
colunn_to_create = "sensor with MAX value experiment"    
if colunn_to_create not in userInputData.columns:
    userInputData[colunn_to_create] = np.nan
colunn_to_create_second = "sensor with second MAX value experiment"
if colunn_to_create not in userInputData.columns:
    userInputData[colunn_to_create] = np.nan
for index, row in userInputData.iterrows():
    max_dict = row[col_list].to_dict()  
    # Sort correctly — key must be inside sorted()
    sorted_items = sorted(
    max_dict.items(),
    key=lambda x: (pd.notna(x[1]), x[1])
)
    # Handle missing/NaN gracefully
    if len(sorted_items) > 0 and pd.notna(sorted_items[2][1]):
        userInputData.at[index, colunn_to_create] = sorted_items[2][0]
    if len(sorted_items) > 1 and pd.notna(sorted_items[1][1]):
        userInputData.at[index, colunn_to_create_second] = sorted_items[1][0]

C:\Users\Andreas\AppData\Local\Temp\ipykernel_6164\2114904390.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  userInputData[colunn_to_create] = np.nan
C:\Users\Andreas\AppData\Local\Temp\ipykernel_6164\2114904390.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  userInputData.at[index, colunn_to_create_second] = sorted_items[1][0]

In [179]:
#FIND 90% quantile and 99% quantile not yet use at capping values
#find quantile per sensor 
def create_column_quantile(userInputData,sensor,quantile_number,column_to_find_values):
    colunn_to_create = f"{sensor} quantile {quantile_number * 100}% {column_to_find_values}"    
    if colunn_to_create not in userInputData.columns:
        userInputData[colunn_to_create] = np.nan
    return colunn_to_create

    
for index, row in userInputData.iterrows():
    particular_experiment =  dict_of_timeseries[index].copy()

    column_to_find_values = "VOC rolling average"
    sensors = particular_experiment["sensors"].unique()

    for sensor in sensors:
        mask = particular_experiment["sensors"]==sensor

        quantile_number = 0.9
        colunn_to_create = create_column_quantile(userInputData,sensor,quantile_number,column_to_find_values)
    
        userInputData.at[index, colunn_to_create] = particular_experiment.loc[mask,column_to_find_values].quantile(quantile_number)

        quantile_number = 0.99
        colunn_to_create = create_column_quantile(userInputData,sensor,quantile_number,column_to_find_values)
    
        userInputData.at[index, colunn_to_create] = particular_experiment.loc[mask,column_to_find_values].quantile(quantile_number)


        
    dict_of_timeseries[index]  =   particular_experiment

C:\Users\Andreas\AppData\Local\Temp\ipykernel_6164\1746646411.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  userInputData[colunn_to_create] = np.nan
C:\Users\Andreas\AppData\Local\Temp\ipykernel_6164\1746646411.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  userInputData[colunn_to_create] = np.nan
C:\Users\Andreas\AppData\Local\Temp\ipykernel_6164\1746646411.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  userInputData[colunn_to_create] = np.nan
C:\Users\Andreas\AppData\Local\Temp\ipykernel_6164\1746646411.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  userInputData[colunn_to_create] = np.nan
C:\Users\Andreas\AppData\Local\Temp\ipykernel_6164\1746646411.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  userInputData[colunn_to_create] = np.nan
C:\Users\Andreas\AppData\Local\Temp\ipykernel_6164\1746646411.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  userInputData[colunn_to_create] = np.nan

In [180]:
#FIND 90% quantile and 99% quantile not yet use at capping values
#find quantile per experiment
def create_column_quantile(userInputData,sensor,quantile_number,column_to_find_values):
    colunn_to_create = f"{sensor} quantile {quantile_number * 100}% {column_to_find_values}"    
    if colunn_to_create not in userInputData.columns:
        userInputData[colunn_to_create] = np.nan
    return colunn_to_create

    
for index, row in userInputData.iterrows():
    particular_experiment =  dict_of_timeseries[index].copy()

    column_to_find_values = "VOC rolling average"
    sensor = "whole experiment"


    quantile_number = 0.9
    colunn_to_create = create_column_quantile(userInputData,sensor,quantile_number,column_to_find_values)

    userInputData.at[index, colunn_to_create] = particular_experiment.loc[:,column_to_find_values].quantile(quantile_number)

    quantile_number = 0.99
    colunn_to_create = create_column_quantile(userInputData,sensor,quantile_number,column_to_find_values)

    userInputData.at[index, colunn_to_create] = particular_experiment.loc[:,column_to_find_values].quantile(quantile_number)


        
    dict_of_timeseries[index]  =   particular_experiment

C:\Users\Andreas\AppData\Local\Temp\ipykernel_6164\1476829008.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  userInputData[colunn_to_create] = np.nan
C:\Users\Andreas\AppData\Local\Temp\ipykernel_6164\1476829008.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  userInputData[colunn_to_create] = np.nan

In [181]:
userInputData

,experimentState,are-doors-opened,are-people-inside,are-windows-opened,front-wall,item-used,notes,room,side-right-wall,back-wall,side-left-wall,are-fans-on,no-source-located,timestamp InsertingSource,timestamp StartingExperiment,timestamp EndingExperiment,date of experiment,actual timestamp StartingExperiment,actual timestamp EndingExperiment,time taken total,timestamp InsertingSource timedelta,timestamp InsertingSource seconds,time taken after insertion,time taken before insertion,time taken before insertion (seconds),time taken after insertion (seconds),time taken total (seconds),time taken total (seconds)-capped,time taken before insertion (seconds)-capped,time taken after insertion (seconds)-capped,Id=1:BME680:breathVocEquivalent MAX value VOC rolling average,Id=1:BME680:breathVocEquivalent index of MAX value VOC rolling average,Id=2:BME680:breathVocEquivalent MAX value VOC rolling average,Id=2:BME680:breathVocEquivalent index of MAX value VOC rolling average,Id=0:BME680:breathVocEquivalent MAX value VOC rolling average,Id=0:BME680:breathVocEquivalent index of MAX value VOC rolling average,sensor with MAX value experiment,sensor with second MAX value experiment,Id=1:BME680:breathVocEquivalent quantile 90.0% VOC rolling average,Id=1:BME680:breathVocEquivalent quantile 99.0% VOC rolling average,Id=2:BME680:breathVocEquivalent quantile 90.0% VOC rolling average,Id=2:BME680:breathVocEquivalent quantile 99.0% VOC rolling average,Id=0:BME680:breathVocEquivalent quantile 90.0% VOC rolling average,Id=0:BME680:breathVocEquivalent quantile 99.0% VOC rolling average,whole experiment quantile 90.0% VOC rolling average,whole experiment quantile 99.0% VOC rolling average
0,InsertingSourcePollutant,on,None,None,1.0,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.0,None,None,2025-07-01 16:09:41,2025-07-01 15:27:16,2025-07-01 16:14:44,2025-07-01,2025-07-01 15:27:19,2025-07-01 16:14:42,0 days 00:47:23,0 days 00:42:23,2543.0,0 days 00:05:00,0 days 00:42:23,2543.0,300.0,2843.0,242.0,-59.0,300.0,3.063,299.0,3.322,242.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,2.8016,3.05823,3.2545,3.32041,NaN,NaN,3.1453,3.31500
1,InsertingSourcePollutant,on,None,None,1.0,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.0,None,None,2025-07-02 15:59:29,2025-07-02 15:42:50,2025-07-02 16:04:52,2025-07-02,2025-07-02 15:42:50,2025-07-02 16:04:50,0 days 00:22:00,0 days 00:16:40,1000.0,0 days 00:05:20,0 days 00:16:40,1000.0,320.0,1320.0,242.0,-59.0,300.0,1.083,201.0,0.307,78.0,NaN,NaN,Id=1:BME680:breathVocEquivalent MAX value VOC ...,Id=2:BME680:breathVocEquivalent MAX value VOC ...,0.8909,1.08023,0.2811,0.30700,NaN,NaN,0.6645,1.07224
2,InsertingSourcePollutant,on,None,None,0.4,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.0,None,None,2025-07-03 12:34:32,2025-07-03 12:30:25,2025-07-03 12:45:31,2025-07-03,2025-07-03 12:30:25,2025-07-03 12:45:31,0 days 00:15:06,0 days 00:04:08,248.0,0 days 00:10:58,0 days 00:04:08,248.0,658.0,906.0,242.0,-59.0,300.0,1.372,235.0,2.294,300.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,1.3124,1.37000,1.5840,2.16494,NaN,NaN,1.3710,2.04492
3,InsertingSourcePollutant,on,None,None,1.0,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.8,None,None,2025-07-03 15:53:07,2025-07-03 15:43:27,2025-07-03 15:59:11,2025-07-03,2025-07-03 15:51:40,2025-07-03 15:59:10,0 days 00:07:30,0 days 00:01:28,88.0,0 days 00:06:02,0 days 00:01:28,88.0,362.0,450.0,242.0,-59.0,300.0,0.332,300.0,18.486,300.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.2483,0.32182,15.5041,17.63282,NaN,NaN,5.3774,17.06834
4,InsertingSourcePollutant,on,None,None,1.4,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.4,None,None,2025-07-09 19:19:19,2025-07-09 19:01:42,2025-07-09 19:27:50,2025-07-09,2025-07-09 19:01:44,2025-07-09 19:27:49,0 days 00:26:05,0 days 00:17:36,1056.0,0 days 00:08:29,0 days 00:17:36,1056.0,509.0,1565.0,242.0,-59.0,300.0,0.600,245.0,0.512,300.0,NaN,NaN,Id=1:BME680:breathVocEquivalent MAX value VOC ...,Id=2:BME680:breathVocEquivalent MAX value VOC ...,0.5762,0.60000,0.4803,0.50641,NaN,NaN,0.5321,0.59881
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
254,InsertingSourcePollutant,None,None,None,0.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",0.5,NaN,NaN,None,None,2025-10-24 20:32:03,2025-10-24 20:29:36,2025-10-24 20:37:33,2025-10-24,2025-10-24 20:29:37,2025-10-24 20:37:31,0 days 00:07:54,0 days 00:02:27,147.0,0 days 00:05:27,0 days 00:02:27,147.0,327.0,474.0,242.0,-59.0,300.0,1.748,131.0,4.850,300.0,1.947,285.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=0:BME680:breathVocEquivalent MAX value VOC ...,1.5612,1.74482,4.4074,4.80156,1.8771,1.94441,3.5261,4.69152
255,InsertingSourcePollutant,None,None,None,0.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:05:46,2025-10-24 21:03:22,2025-10-24 21:11:21,2025-10-24,2025-10-24 21:03:24,2025-10-24 21:11:19,0 days 00:07:55,0 days 00:02:23,143.0,0 days 00:05:32,0 days 00:02:23,143.0,332.0,475.0,242.0,-59.0,300.0,1.057,300.0,5.182,300.0,2.413,236.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=0:BME680:breathVocEquivalent MAX value VOC ...,1.0160,1.05441,3.5239,5.03822,2.3453,2.40941,2.3893,4.71445
256,InsertingSourcePollutant,None,None,None,1.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:18:43,2025-10-24 21:17:10,2025-10-24 21:24:48,2025-10-24,2025-10-24 21:17:12,2025-10-24 21:24:46,0 days 00:07:34,0 days 00:01:32,92.0,0 days 00:06:02,0 days 00:01:32,92.0,362.0,454.0,242.0,-59.0,300.0,1.948,300.0,12.093,277.0,1.837,140.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,1.1753,1.87102,11.9171,12.08182,1.7081,1.83641,8.0527,12.03042
257,InsertingSourcePollutant,None,None,None,2.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:34:58,2025-10-24 21:33:44,2025-10-24 21:41:06,2025-10-24,2025-10-24 21:33:46,2025-10-24 21:41:04,0 days 00:07:18,0 days 00:01:13,73.0,0 days 00:06:05,0 days 00:01:13,73.0,365.0,438.0,242.0,-59.0,300.0,1.745,300.0,7.490,260.0,1.193,300.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,1.6422,1.71928,7.2742,7.48800,1.1576,1.18782,6.4991,7.44789
258,InsertingSourcePollutant,None,None,None,3.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:54:05,2025-10-24 21:52:16,2025-10-24 22:01:25,2025-10-24,2025-10-24 21:52:18,2025-10-24 22:01:24,0 days 00:09:06,0 days 00:01:48,108.0,0 days 00:07:18,0 days 00:01:48,108.0,438.0,546.0,242.0,-59.0,300.0,1.613,212.0,2.972,287.0,1.935,300.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=0:BME680:breathVocEquivalent MAX value VOC ...,1.5463,1.61141,2.8288,2.97000,1.5596,1.89033,2.3350,2.96242

In [182]:
userInputData.head(20)

,experimentState,are-doors-opened,are-people-inside,are-windows-opened,front-wall,item-used,notes,room,side-right-wall,back-wall,side-left-wall,are-fans-on,no-source-located,timestamp InsertingSource,timestamp StartingExperiment,timestamp EndingExperiment,date of experiment,actual timestamp StartingExperiment,actual timestamp EndingExperiment,time taken total,timestamp InsertingSource timedelta,timestamp InsertingSource seconds,time taken after insertion,time taken before insertion,time taken before insertion (seconds),time taken after insertion (seconds),time taken total (seconds),time taken total (seconds)-capped,time taken before insertion (seconds)-capped,time taken after insertion (seconds)-capped,Id=1:BME680:breathVocEquivalent MAX value VOC rolling average,Id=1:BME680:breathVocEquivalent index of MAX value VOC rolling average,Id=2:BME680:breathVocEquivalent MAX value VOC rolling average,Id=2:BME680:breathVocEquivalent index of MAX value VOC rolling average,Id=0:BME680:breathVocEquivalent MAX value VOC rolling average,Id=0:BME680:breathVocEquivalent index of MAX value VOC rolling average,sensor with MAX value experiment,sensor with second MAX value experiment,Id=1:BME680:breathVocEquivalent quantile 90.0% VOC rolling average,Id=1:BME680:breathVocEquivalent quantile 99.0% VOC rolling average,Id=2:BME680:breathVocEquivalent quantile 90.0% VOC rolling average,Id=2:BME680:breathVocEquivalent quantile 99.0% VOC rolling average,Id=0:BME680:breathVocEquivalent quantile 90.0% VOC rolling average,Id=0:BME680:breathVocEquivalent quantile 99.0% VOC rolling average,whole experiment quantile 90.0% VOC rolling average,whole experiment quantile 99.0% VOC rolling average
0,InsertingSourcePollutant,on,None,None,1.0,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.0,None,None,2025-07-01 16:09:41,2025-07-01 15:27:16,2025-07-01 16:14:44,2025-07-01,2025-07-01 15:27:19,2025-07-01 16:14:42,0 days 00:47:23,0 days 00:42:23,2543.0,0 days 00:05:00,0 days 00:42:23,2543.0,300.0,2843.0,242.0,-59.0,300.0,3.063,299.0,3.322,242.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,2.8016,3.05823,3.2545,3.32041,NaN,NaN,3.1453,3.31500
1,InsertingSourcePollutant,on,None,None,1.0,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.0,None,None,2025-07-02 15:59:29,2025-07-02 15:42:50,2025-07-02 16:04:52,2025-07-02,2025-07-02 15:42:50,2025-07-02 16:04:50,0 days 00:22:00,0 days 00:16:40,1000.0,0 days 00:05:20,0 days 00:16:40,1000.0,320.0,1320.0,242.0,-59.0,300.0,1.083,201.0,0.307,78.0,NaN,NaN,Id=1:BME680:breathVocEquivalent MAX value VOC ...,Id=2:BME680:breathVocEquivalent MAX value VOC ...,0.8909,1.08023,0.2811,0.30700,NaN,NaN,0.6645,1.07224
2,InsertingSourcePollutant,on,None,None,0.4,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.0,None,None,2025-07-03 12:34:32,2025-07-03 12:30:25,2025-07-03 12:45:31,2025-07-03,2025-07-03 12:30:25,2025-07-03 12:45:31,0 days 00:15:06,0 days 00:04:08,248.0,0 days 00:10:58,0 days 00:04:08,248.0,658.0,906.0,242.0,-59.0,300.0,1.372,235.0,2.294,300.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,1.3124,1.37000,1.5840,2.16494,NaN,NaN,1.3710,2.04492
3,InsertingSourcePollutant,on,None,None,1.0,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.8,None,None,2025-07-03 15:53:07,2025-07-03 15:43:27,2025-07-03 15:59:11,2025-07-03,2025-07-03 15:51:40,2025-07-03 15:59:10,0 days 00:07:30,0 days 00:01:28,88.0,0 days 00:06:02,0 days 00:01:28,88.0,362.0,450.0,242.0,-59.0,300.0,0.332,300.0,18.486,300.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.2483,0.32182,15.5041,17.63282,NaN,NaN,5.3774,17.06834
4,InsertingSourcePollutant,on,None,None,1.4,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.4,None,None,2025-07-09 19:19:19,2025-07-09 19:01:42,2025-07-09 19:27:50,2025-07-09,2025-07-09 19:01:44,2025-07-09 19:27:49,0 days 00:26:05,0 days 00:17:36,1056.0,0 days 00:08:29,0 days 00:17:36,1056.0,509.0,1565.0,242.0,-59.0,300.0,0.600,245.0,0.512,300.0,NaN,NaN,Id=1:BME680:breathVocEquivalent MAX value VOC ...,Id=2:BME680:breathVocEquivalent MAX value VOC ...,0.5762,0.60000,0.4803,0.50641,NaN,NaN,0.5321,0.59881
5,InsertingSourcePollutant,None,None,None,1.0,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.8,None,None,2025-07-12 22:57:57,2025-07-12 22:31:25,2025-07-12 23:02:13,2025-07-12,2025-07-12 22:34:03,2025-07-12 23:02:11,0 days 00:28:08,0 days 00:23:55,1435.0,0 days 00:04:13,0 days 00:23:55,1435.0,253.0,1688.0,195.0,-59.0,253.0,0.224,-59.0,0.817,253.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.1678,0.21888,0.6874,0.80252,NaN,NaN,0.6280,0.79100
7,InsertingSourcePollutant,on,on,None,1.8,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,None,None,2025-07-19 15:04:09,2025-07-19 14:59:47,2025-07-19 15:08:10,2025-07-19,2025-07-19 14:59:49,2025-07-19 15:08:09,0 days 00:08:20,0 days 00:04:21,261.0,0 days 00:03:59,0 days 00:04:21,261.0,239.0,500.0,181.0,-59.0,239.0,0.216,-59.0,0.411,173.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.1960,0.21104,0.4042,0.41000,NaN,NaN,0.3893,0.41000
8,InsertingSourcePollutant,on,on,None,1.8,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,None,None,2025-07-19 15:17:10,2025-07-19 15:14:13,2025-07-19 15:21:23,2025-07-19,2025-07-19 15:14:15,2025-07-19 15:21:21,0 days 00:07:06,0 days 00:02:56,176.0,0 days 00:04:10,0 days 00:02:56,176.0,250.0,426.0,192.0,-59.0,250.0,0.365,250.0,1.054,250.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.3291,0.36291,0.8815,1.04364,NaN,NaN,0.6760,1.03005
9,InsertingSourcePollutant,on,on,None,1.8,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,None,None,2025-07-19 15:30:49,2025-07-19 15:25:07,2025-07-19 15:44:28,2025-07-19,2025-07-19 15:25:09,2025-07-19 15:44:27,0 days 00:19:18,0 days 00:05:41,341.0,0 days 00:13:37,0 days 00:05:41,341.0,817.0,1158.0,242.0,-59.0,300.0,1.443,300.0,0.974,300.0,NaN,NaN,Id=1:BME680:breathVocEquivalent MAX value VOC ...,Id=2:BME680:breathVocEquivalent MAX value VOC ...,1.0807,1.40810,0.6571,0.95705,NaN,NaN,0.9061,1.36891
10,InsertingSourcePollutant,on,on,None,1.8,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,None,None,2025-07-19 16:12:54,2025-07-19 16:04:22,2025-07-19 16:21:55,2025-07-19,2025-07-19 16:04:24,2025-07-19 16:21:54,0 days 00:17:30,0 days 00:08:31,511.0,0 days 00:08:59,0 days 00:08:31,511.0,539.0,1050.0,242.0,-59.0,300.0,1.575,300.0,2.679,300.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,1.3208,1.55805,2.0410,2.62556,NaN,NaN,1.5226,2.56677
11,InsertingSourcePollutant,on,on,None,1.8,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,None,None,2025-07-19 16:46:45,2025-07-19 16:36:03,2025-07-19 16:54:19,2025-07-19,2025-07-19 16:36:04,2025-07-19 16:54:18,0 days 00:18:14,0 days 00:10:42,642.0,0 days 00:07:32,0 days 00:10:42,642.0,452.0,1094.0,242.0,-59.0,300.0,0.628,300.0,1.877,300.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.4495,0.60605,1.3313,1.81315,NaN,NaN,0.9301,1.75596
12,InsertingSourcePollutant,on,on,None,1.8,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,None,None,2025-07-19 17:25:36,2025-07-19 17:05:51,2025-07-19 17:35:58,2025-07-19,2025-07-19 17:05:52,2025-07-19 17:35:57,0 days 00:30:05,0 days 00:19:45,1185.0,0 days 00:10:20,0 days 00:19:45,1185.0,620.0,1805.0,242.0,-59.0,300.0,0.485,300.0,0.964,300.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.3802,0.47323,0.6636,0.91692,NaN,NaN,0.4750,0.87591
13,InsertingSourcePollutant,on,None,None,1.8,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,None,None,2025-07-20 13:46:03,2025-07-20 13:36:41,2025-07-20 14:48:43,2025-07-20,2025-07-20 13:36:42,2025-07-20 14:48:41,0 days 01:11:59,0 days 00:09:22,562.0,0 days 01:02:37,0 days 00:09:22,562.0,3757.0,4319.0,242.0,-59.0,300.0,0.116,258.0,0.168,160.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.1100,0.11600,0.1541,0.16700,NaN,NaN,0.1450,0.16700
14,InsertingSourcePollutant,on,on,None,1.8,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,None,None,2025-07-20 15:15:34,2025-07-20 15:04:15,2025-07-20 15:39:22,2025-07-20,2025-07-20 15:04:17,2025-07-20 15:39:20,0 days 00:35:03,0 days 00:11:18,678.0,0 days 00:23:45,0 days 00:11:18,678.0,1425.0,2103.0,242.0,-59.0,300.0,0.139,171.0,0.536,300.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.1330,0.13900,0.3724,0.51446,NaN,NaN,0.2191,0.49086
15,InsertingSourcePollutant,on,on,None,1.8,Φαρμακευτικό αλκοόλ 95%,ανεμιστήρας,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,None,None,2025-07-20 15:52:33,2025-07-20 15:47:36,2025-07-20 16:08:05,2025-07-20,2025-07-20 15:47:38,2025-07-20 16:08:03,0 days 00:20:25,0 days 00:04:56,296.0,0 days 00:15:29,0 days 00:04:56,296.0,929.0,1225.0,242.0,-59.0,300.0,0.984,300.0,0.831,300.0,NaN,NaN,Id=1:BME680:breathVocEquivalent MAX value VOC ...,Id=2:BME680:breathVocEquivalent MAX value VOC ...,0.8206,0.96705,0.6954,0.81464,NaN,NaN,0.7423,0.95124
16,InsertingSourcePollutant,on,None,None,1.8,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,None,None,2025-07-20 16:34:39,2025-07-20 16:20:42,2025-07-20 16:43:55,2025-07-20,2025-07-20 16:20:44,2025-07-20 16:43:54,0 days 00:23:10,0 days 00:13:56,836.0,0 days 00:09:14,0 days 00:13:56,836.0,554.0,1390.0,242.0,-59.0,300.0,0.207,284.0,0.352,300.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.1802,0.20600,0.2222,0.33505,NaN,NaN,0.2000,0.31805
17,InsertingSourcePollutant,on,on,None,1.8,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,None,None,2025-07-20 18:13:07,2025-07-20 18:04:08,2025-07-20 18:22:22,2025-07-20,2025-07-20 18:04:10,2025-07-20 18:22:20,0 days 00:18:10,0 days 00:08:58,538.0,0 days 00:09:12,0 days 00:08:58,538.0,552.0,1090.0,242.0,-59.0,300.0,0.496,300.0,0.688,231.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.4751,0.49341,0.6860,0.68800,NaN,NaN,0.6692,0.68800
18,InsertingSourcePollutant,on,on,on,1.8,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,None,None,2025-07-20 18:31:41,2025-07-20 18:29:19,2025-07-20 18:40:12,2025-07-20,2025-07-20 18:29:21,2025-07-20 18:40:11,0 days 00:10:50,0 days 00:02:21,141.0,0 days 00:08:29,0 days 00:02:21,141.0,509.0,650.0,242.0,-59.0,300.0,0.026,284.0,0.020,133.0,NaN,NaN,Id=1:BME680:breathVocEquivalent MAX value VOC ...,Id=2:BME680:breathVocEquivalent MAX value VOC ...,0.0191,0.02600,0.0180,0.02000,NaN,NaN,0.0181,0.02581
19,InsertingSourcePollutant,on,on,None,1.8,Φαρμακευτικό αλκοόλ 95%,ανεμιστήρας,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,None,None,2025-07-20 18:47:26,2025-07-20 18:41:09,2025-07-20 19:00:09,2025-07-20,2025-07-20 18:41:11,2025-07-20 19:00:08,0 days 00:18:57,0 days 00:06:16,376.0,0 days 00:12:41,0 days 00:06:16,376.0,761.0,1137.0,242.0,-59.0,300.0,0.799,300.0,1.144,300.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.6444,0.78264,0.9167,1.12546,NaN,NaN,0.7642,1.10386
20,InsertingSourcePollutant,on,on,None,1.8,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,None,None,2025-07-20 19:15:51,2025-07-20 19:13:35,2025-07-20 19:23:44,2025-07-20,2025-07-20 19:13:36,2025-07-20 19:23:42,0 days 00:10:06,0 days 00:02:16,136.0,0 days 00:07:50,0 days 00:02:16,136.0,470.0,606.0,242.0,-59.0,300.0,0.119,300.0,0.545,146.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.0980,0.11641,0.5380,0.54500,NaN,NaN,0.5301,0.54381

In [183]:
#cap by max value 
offset_to_increase_capped = 5
for index, row in userInputData.iterrows():
    
    particular_experiment =  dict_of_timeseries[index].copy()
    colunn_to_create = "VOC rolling average-capped"
    if colunn_to_create not in userInputData.columns:
        particular_experiment[colunn_to_create] = np.nan
        
    max_sensor = row["sensor with MAX value experiment"]

    max_sensor = max_sensor.split()[0]

    max_sensor_column_name = f"{max_sensor} MAX value VOC rolling average"
    max_value = row[max_sensor_column_name]
    
    second_max_sensor = row["sensor with second MAX value experiment"].split()[0]
    
    second_max_sensor_column_name = f"{second_max_sensor} MAX value VOC rolling average"
    second_max_value = row[second_max_sensor_column_name]  
    value_to_cap_into =  5  + second_max_value
   
        
    for sensor in sensors:
        mask = particular_experiment["sensors"]==sensor
        particular_experiment.loc[mask,colunn_to_create] = particular_experiment.loc[mask,"VOC rolling average"]

        if (sensor == max_sensor):
            full_mask = mask & (particular_experiment["VOC rolling average"]> value_to_cap_into)
            particular_experiment.loc[full_mask,colunn_to_create] = value_to_cap_into
        
    dict_of_timeseries[index]  =   particular_experiment

In [184]:
for index, row in userInputData.iterrows():
    particular_experiment =  dict_of_timeseries[index].copy()
    sensors = particular_experiment["sensors"].unique()

    for sensor in sensors:
        mask = particular_experiment["sensors"]==sensor
        column_to_create = "VOC rolling average gradient"
        if column_to_create not in particular_experiment.columns:
            particular_experiment.loc[:,column_to_create] = np.nan
        particular_experiment.loc[mask,column_to_create] = np.gradient(particular_experiment.loc[mask,"VOC rolling average"].to_numpy())
        
        column_to_create = "VOC rolling average gradient cumsum"
        if column_to_create not in particular_experiment.columns:    
            particular_experiment.loc[:,column_to_create] = np.nan
        particular_experiment.loc[mask,column_to_create] = particular_experiment.loc[mask,"VOC rolling average gradient"].cumsum()

    
 
        column_to_create = "VOC rolling average-capped gradient"
        if column_to_create not in particular_experiment.columns:
            particular_experiment.loc[:,column_to_create] = np.nan
        particular_experiment.loc[mask,column_to_create] = np.gradient(particular_experiment.loc[mask,"VOC rolling average-capped"].to_numpy())

    
        column_to_create = "VOC rolling average-capped gradient cumsum"
        if column_to_create not in particular_experiment.columns:    
            particular_experiment.loc[:,column_to_create] = np.nan
        particular_experiment.loc[mask,column_to_create] = particular_experiment.loc[mask,"VOC rolling average-capped gradient"].cumsum()

    dict_of_timeseries[index] = particular_experiment

In [185]:
#create standard scaler per experiment and per sensor, per VOC rolling average and VOC rolling average capped

In [186]:
#per sensor 
from sklearn.preprocessing import StandardScaler
def create_column_standard_scaler(particular_experiment,column_to_find_values):
    
    colunn_to_create = f"{column_to_find_values} standard scaler per sensor"    
    if colunn_to_create not in particular_experiment.columns:
        particular_experiment[colunn_to_create] = np.nan
    return colunn_to_create
    
columns_to_find_values = ["VOC rolling average","VOC rolling average-capped"]

for column_to_find_values in columns_to_find_values:
    for index, row in userInputData.iterrows():
    
        particular_experiment =  dict_of_timeseries[index].copy()
        scaler = StandardScaler()
        sensors = particular_experiment["sensors"].unique()
        for sensor in sensors:
            
            mask = particular_experiment["sensors"]==sensor
            colunn_to_create = create_column_standard_scaler(particular_experiment,column_to_find_values)
        
            particular_experiment.loc[mask, colunn_to_create] = scaler.fit_transform( (particular_experiment.loc[mask,column_to_find_values].to_numpy().reshape(-1,1)))
    
        dict_of_timeseries[index]  =   particular_experiment

In [187]:
#experiment
from sklearn.preprocessing import StandardScaler
def create_column_standard_scaler(particular_experiment,column_to_find_values):
    
    colunn_to_create = f"{column_to_find_values} standard scaler whole experiment"    
    if colunn_to_create not in particular_experiment.columns:
        particular_experiment[colunn_to_create] = np.nan
    return colunn_to_create
    
columns_to_find_values = ["VOC rolling average","VOC rolling average-capped"]

for column_to_find_values in columns_to_find_values:
    for index, row in userInputData.iterrows():
    
        particular_experiment =  dict_of_timeseries[index].copy()
        scaler = StandardScaler()
            
        colunn_to_create = create_column_standard_scaler(particular_experiment,column_to_find_values)
    
        particular_experiment.loc[:, colunn_to_create] = scaler.fit_transform((particular_experiment.loc[:,column_to_find_values].to_numpy().reshape(-1,1)))
    
        dict_of_timeseries[index]  =   particular_experiment

In [188]:
dict_of_timeseries[157]

,sensors,VOC,after_insertion,original_value,datetime_timestamp,timestamp,seconds,seconds passed from insertionSource,VOC rolling average,original seconds,VOC rolling average-capped,VOC rolling average gradient,VOC rolling average gradient cumsum,VOC rolling average-capped gradient,VOC rolling average-capped gradient cumsum,VOC rolling average standard scaler per sensor,VOC rolling average-capped standard scaler per sensor,VOC rolling average standard scaler whole experiment,VOC rolling average-capped standard scaler whole experiment
seconds,,,,,,,,,,,,,,,,,,,
-59.0,Id=0:BME680:breathVocEquivalent,1.670143,False,True,2025-10-13 22:26:48,0 days 00:00:36,-59.0,-59.0,0.000,36.0,0.000,0.0090,0.0090,0.0090,0.0090,-1.202429,-1.202429,-1.045199,-1.045199
-59.0,Id=1:BME680:breathVocEquivalent,2.413401,False,True,2025-10-13 22:26:48,0 days 00:00:36,-59.0,-59.0,0.155,36.0,0.155,0.0080,0.0080,0.0080,0.0080,-1.079408,-1.079408,-0.878828,-0.878828
-59.0,Id=2:BME680:breathVocEquivalent,1.253582,False,True,2025-10-13 22:26:48,0 days 00:00:36,-59.0,-59.0,0.000,36.0,0.000,0.0020,0.0020,0.0020,0.0020,-0.793947,-0.793947,-1.045199,-1.045199
-58.0,Id=0:BME680:breathVocEquivalent,1.677506,False,True,2025-10-13 22:26:49,0 days 00:00:37,-58.0,-58.0,0.009,37.0,0.009,0.0095,0.0185,0.0095,0.0185,-1.193984,-1.193984,-1.035539,-1.035539
-58.0,Id=1:BME680:breathVocEquivalent,2.409750,False,True,2025-10-13 22:26:49,0 days 00:00:37,-58.0,-58.0,0.163,37.0,0.163,0.0080,0.0160,0.0080,0.0160,-1.069078,-1.069078,-0.870241,-0.870241
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299.0,Id=1:BME680:breathVocEquivalent,4.553225,True,True,2025-10-13 22:32:46,0 days 00:06:34,299.0,299.0,2.326,394.0,2.326,0.0080,2.1790,0.0080,2.1790,1.724060,1.724060,1.451431,1.451431
299.0,Id=2:BME680:breathVocEquivalent,4.865380,True,True,2025-10-13 22:32:46,0 days 00:06:34,299.0,299.0,3.591,394.0,3.591,0.0815,3.6330,0.0815,3.6330,3.598873,3.598873,2.809228,2.809228
300.0,Id=0:BME680:breathVocEquivalent,5.587928,True,True,2025-10-13 22:32:47,0 days 00:06:35,300.0,300.0,3.803,395.0,3.803,-0.0120,3.8015,-0.0120,3.8015,2.366260,2.366260,3.036780,3.036780
300.0,Id=1:BME680:breathVocEquivalent,4.564097,True,True,2025-10-13 22:32:47,0 days 00:06:35,300.0,300.0,2.334,395.0,2.334,0.0080,2.1870,0.0080,2.1870,1.734390,1.734390,1.460018,1.460018
300.0,Id=2:BME680:breathVocEquivalent,4.920298,True,True,2025-10-13 22:32:47,0 days 00:06:35,300.0,300.0,3.673,395.0,3.673,0.0820,3.7150,0.0820,3.7150,3.699183,3.699183,2.897243,2.897243

In [189]:
room_length = 4.0
room_width = 3.25
userInputData["x axis"] = np.nan
userInputData["y axis"] = np.nan
#front is max,back is zero,right is max,left is zero
def find_x_axis(x,room_width):
    from_right = None
    from_left = None

    #return NaN either if numbers at the position columns are negative or above room width
    if (x["side-right-wall"]<0 and x["side-right-wall"]> room_width) or (x["side-left-wall"]< 0 and x["side-left-wall"]> room_width) or (pd.isna(x["side-right-wall"]) and pd.isna(x["side-left-wall"])):
        x["x axis"] = np.nan
        return x["x axis"] 
    if pd.notna(x["side-right-wall"]):
       from_right = -x["side-right-wall"]
    if pd.notna(x["side-left-wall"]):
       from_left = -room_width + x["side-left-wall"]
      
    if  from_right is not None and from_left is not None:
        if from_right == from_left:
            x["x axis"] = from_right
        else:
            x["x axis"] = np.nan
          

    elif pd.notna(x["side-left-wall"]):
    
        x["x axis"] = from_left

    elif pd.notna(x["side-right-wall"]):
        x["x axis"] = from_right
    return  x["x axis"]

def find_y_axis(x,room_length):
    from_front = None
    from_back = None

    #return NaN either if numbers at the position columns are negative or above room width
    if (x["front-wall"]<0 and x["front-wall"]> room_length) or (x["back-wall"]< 0 and x["back-wall"]> room_length) or (pd.isna(x["front-wall"]) and pd.isna(x["back-wall"])):
        x["y axis"] = np.nan
        return x["y axis"] 
    if pd.notna(x["front-wall"]):
       from_front = room_length - x["front-wall"]
    if pd.notna(x["back-wall"]):
       from_back = x["back-wall"]
    if from_front is not None and from_back is not None:
        if from_front == from_back:
            x["y axis"] = from_front
        else:
            x["y axis"] = np.nan
            
    elif pd.notna(x["back-wall"]):
    
        x["y axis"] = from_back

    elif pd.notna(x["front-wall"]):
        x["y axis"] = from_front

    return  x["y axis"]

userInputData["x axis"] = userInputData.apply(lambda x:find_x_axis(x,room_width),axis=1)
userInputData["y axis"] = userInputData.apply(lambda x:find_y_axis(x,room_length),axis=1)

C:\Users\Andreas\AppData\Local\Temp\ipykernel_6164\971905250.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  userInputData["x axis"] = np.nan
C:\Users\Andreas\AppData\Local\Temp\ipykernel_6164\971905250.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  userInputData["y axis"] = np.nan
C:\Users\Andreas\AppData\Local\Temp\ipykernel_6164\971905250.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  userInputData["x axis"] = userInputData.apply(lambda x:find_x_axis(x,room_width),axis=1)
C:\Users\Andreas\AppData\Local\Temp\ipykernel_6164\971905250.py:62: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  userInputData["y axis"] = userInputData.apply(lambda x:find_y_axis(x,room_length),axis=1)

In [190]:
userInputData.head(30)

,experimentState,are-doors-opened,are-people-inside,are-windows-opened,front-wall,item-used,notes,room,side-right-wall,back-wall,side-left-wall,are-fans-on,no-source-located,timestamp InsertingSource,timestamp StartingExperiment,timestamp EndingExperiment,date of experiment,actual timestamp StartingExperiment,actual timestamp EndingExperiment,time taken total,timestamp InsertingSource timedelta,timestamp InsertingSource seconds,time taken after insertion,time taken before insertion,time taken before insertion (seconds),time taken after insertion (seconds),time taken total (seconds),time taken total (seconds)-capped,time taken before insertion (seconds)-capped,time taken after insertion (seconds)-capped,Id=1:BME680:breathVocEquivalent MAX value VOC rolling average,Id=1:BME680:breathVocEquivalent index of MAX value VOC rolling average,Id=2:BME680:breathVocEquivalent MAX value VOC rolling average,Id=2:BME680:breathVocEquivalent index of MAX value VOC rolling average,Id=0:BME680:breathVocEquivalent MAX value VOC rolling average,Id=0:BME680:breathVocEquivalent index of MAX value VOC rolling average,sensor with MAX value experiment,sensor with second MAX value experiment,Id=1:BME680:breathVocEquivalent quantile 90.0% VOC rolling average,Id=1:BME680:breathVocEquivalent quantile 99.0% VOC rolling average,Id=2:BME680:breathVocEquivalent quantile 90.0% VOC rolling average,Id=2:BME680:breathVocEquivalent quantile 99.0% VOC rolling average,Id=0:BME680:breathVocEquivalent quantile 90.0% VOC rolling average,Id=0:BME680:breathVocEquivalent quantile 99.0% VOC rolling average,whole experiment quantile 90.0% VOC rolling average,whole experiment quantile 99.0% VOC rolling average,x axis,y axis
0,InsertingSourcePollutant,on,None,None,1.0,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.0,None,None,2025-07-01 16:09:41,2025-07-01 15:27:16,2025-07-01 16:14:44,2025-07-01,2025-07-01 15:27:19,2025-07-01 16:14:42,0 days 00:47:23,0 days 00:42:23,2543.0,0 days 00:05:00,0 days 00:42:23,2543.0,300.0,2843.0,242.0,-59.0,300.0,3.063,299.0,3.322,242.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,2.8016,3.05823,3.2545,3.32041,NaN,NaN,3.1453,3.31500,-2.25,3.0
1,InsertingSourcePollutant,on,None,None,1.0,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.0,None,None,2025-07-02 15:59:29,2025-07-02 15:42:50,2025-07-02 16:04:52,2025-07-02,2025-07-02 15:42:50,2025-07-02 16:04:50,0 days 00:22:00,0 days 00:16:40,1000.0,0 days 00:05:20,0 days 00:16:40,1000.0,320.0,1320.0,242.0,-59.0,300.0,1.083,201.0,0.307,78.0,NaN,NaN,Id=1:BME680:breathVocEquivalent MAX value VOC ...,Id=2:BME680:breathVocEquivalent MAX value VOC ...,0.8909,1.08023,0.2811,0.30700,NaN,NaN,0.6645,1.07224,-2.25,3.0
2,InsertingSourcePollutant,on,None,None,0.4,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.0,None,None,2025-07-03 12:34:32,2025-07-03 12:30:25,2025-07-03 12:45:31,2025-07-03,2025-07-03 12:30:25,2025-07-03 12:45:31,0 days 00:15:06,0 days 00:04:08,248.0,0 days 00:10:58,0 days 00:04:08,248.0,658.0,906.0,242.0,-59.0,300.0,1.372,235.0,2.294,300.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,1.3124,1.37000,1.5840,2.16494,NaN,NaN,1.3710,2.04492,-2.25,3.6
3,InsertingSourcePollutant,on,None,None,1.0,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.8,None,None,2025-07-03 15:53:07,2025-07-03 15:43:27,2025-07-03 15:59:11,2025-07-03,2025-07-03 15:51:40,2025-07-03 15:59:10,0 days 00:07:30,0 days 00:01:28,88.0,0 days 00:06:02,0 days 00:01:28,88.0,362.0,450.0,242.0,-59.0,300.0,0.332,300.0,18.486,300.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.2483,0.32182,15.5041,17.63282,NaN,NaN,5.3774,17.06834,-1.45,3.0
4,InsertingSourcePollutant,on,None,None,1.4,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.4,None,None,2025-07-09 19:19:19,2025-07-09 19:01:42,2025-07-09 19:27:50,2025-07-09,2025-07-09 19:01:44,2025-07-09 19:27:49,0 days 00:26:05,0 days 00:17:36,1056.0,0 days 00:08:29,0 days 00:17:36,1056.0,509.0,1565.0,242.0,-59.0,300.0,0.600,245.0,0.512,300.0,NaN,NaN,Id=1:BME680:breathVocEquivalent MAX value VOC ...,Id=2:BME680:breathVocEquivalent MAX value VOC ...,0.5762,0.60000,0.4803,0.50641,NaN,NaN,0.5321,0.59881,-1.85,2.6
5,InsertingSourcePollutant,None,None,None,1.0,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.8,None,None,2025-07-12 22:57:57,2025-07-12 22:31:25,2025-07-12 23:02:13,2025-07-12,2025-07-12 22:34:03,2025-07-12 23:02:11,0 days 00:28:08,0 days 00:23:55,1435.0,0 days 00:04:13,0 days 00:23:55,1435.0,253.0,1688.0,195.0,-59.0,253.0,0.224,-59.0,0.817,253.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.1678,0.21888,0.6874,0.80252,NaN,NaN,0.6280,0.79100,-1.45,3.0
7,InsertingSourcePollutant,on,on,None,1.8,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,None,None,2025-07-19 15:04:09,2025-07-19 14:59:47,2025-07-19 15:08:10,2025-07-19,2025-07-19 14:59:49,2025-07-19 15:08:09,0 days 00:08:20,0 days 00:04:21,261.0,0 days 00:03:59,0 days 00:04:21,261.0,239.0,500.0,181.0,-59.0,239.0,0.216,-59.0,0.411,173.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.1960,0.21104,0.4042,0.41000,NaN,NaN,0.3893,0.41000,-2.15,2.2
8,InsertingSourcePollutant,on,on,None,1.8,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,None,None,2025-07-19 15:17:10,2025-07-19 15:14:13,2025-07-19 15:21:23,2025-07-19,2025-07-19 15:14:15,2025-07-19 15:21:21,0 days 00:07:06,0 days 00:02:56,176.0,0 days 00:04:10,0 days 00:02:56,176.0,250.0,426.0,192.0,-59.0,250.0,0.365,250.0,1.054,250.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.3291,0.36291,0.8815,1.04364,NaN,NaN,0.6760,1.03005,-2.15,2.2
9,InsertingSourcePollutant,on,on,None,1.8,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,None,None,2025-07-19 15:30:49,2025-07-19 15:25:07,2025-07-19 15:44:28,2025-07-19,2025-07-19 15:25:09,2025-07-19 15:44:27,0 days 00:19:18,0 days 00:05:41,341.0,0 days 00:13:37,0 days 00:05:41,341.0,817.0,1158.0,242.0,-59.0,300.0,1.443,300.0,0.974,300.0,NaN,NaN,Id=1:BME680:breathVocEquivalent MAX value VOC ...,Id=2:BME680:breathVocEquivalent MAX value VOC ...,1.0807,1.40810,0.6571,0.95705,NaN,NaN,0.9061,1.36891,-2.15,2.2
10,InsertingSourcePollutant,on,on,None,1.8,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,None,None,2025-07-19 16:12:54,2025-07-19 16:04:22,2025-07-19 16:21:55,2025-07-19,2025-07-19 16:04:24,2025-07-19 16:21:54,0 days 00:17:30,0 days 00:08:31,511.0,0 days 00:08:59,0 days 00:08:31,511.0,539.0,1050.0,242.0,-59.0,300.0,1.575,300.0,2.679,300.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,1.3208,1.55805,2.0410,2.62556,NaN,NaN,1.5226,2.56677,-2.15,2.2
11,InsertingSourcePollutant,on,on,None,1.8,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,None,None,2025-07-19 16:46:45,2025-07-19 16:36:03,2025-07-19 16:54:19,2025-07-19,2025-07-19 16:36:04,2025-07-19 16:54:18,0 days 00:18:14,0 days 00:10:42,642.0,0 days 00:07:32,0 days 00:10:42,642.0,452.0,1094.0,242.0,-59.0,300.0,0.628,300.0,1.877,300.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.4495,0.60605,1.3313,1.81315,NaN,NaN,0.9301,1.75596,-2.15,2.2
12,InsertingSourcePollutant,on,on,None,1.8,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,None,None,2025-07-19 17:25:36,2025-07-19 17:05:51,2025-07-19 17:35:58,2025-07-19,2025-07-19 17:05:52,2025-07-19 17:35:57,0 days 00:30:05,0 days 00:19:45,1185.0,0 days 00:10:20,0 days 00:19:45,1185.0,620.0,1805.0,242.0,-59.0,300.0,0.485,300.0,0.964,300.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.3802,0.47323,0.6636,0.91692,NaN,NaN,0.4750,0.87591,-2.15,2.2
13,InsertingSourcePollutant,on,None,None,1.8,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,None,None,2025-07-20 13:46:03,2025-07-20 13:36:41,2025-07-20 14:48:43,2025-07-20,2025-07-20 13:36:42,2025-07-20 14:48:41,0 days 01:11:59,0 days 00:09:22,562.0,0 days 01:02:37,0 days 00:09:22,562.0,3757.0,4319.0,242.0,-59.0,300.0,0.116,258.0,0.168,160.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.1100,0.11600,0.1541,0.16700,NaN,NaN,0.1450,0.16700,-2.15,2.2
14,InsertingSourcePollutant,on,on,None,1.8,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,None,None,2025-07-20 15:15:34,2025-07-20 15:04:15,2025-07-20 15:39:22,2025-07-20,2025-07-20 15:04:17,2025-07-20 15:39:20,0 days 00:35:03,0 days 00:11:18,678.0,0 days 00:23:45,0 days 00:11:18,678.0,1425.0,2103.0,242.0,-59.0,300.0,0.139,171.0,0.536,300.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.1330,0.13900,0.3724,0.51446,NaN,NaN,0.2191,0.49086,-2.15,2.2
15,InsertingSourcePollutant,on,on,None,1.8,Φαρμακευτικό αλκοόλ 95%,ανεμιστήρας,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,None,None,2025-07-20 15:52:33,2025-07-20 15:47:36,2025-07-20 16:08:05,2025-07-20,2025-07-20 15:47:38,2025-07-20 16:08:03,0 days 00:20:25,0 days 00:04:56,296.0,0 days 00:15:29,0 days 00:04:56,296.0,929.0,1225.0,242.0,-59.0,300.0,0.984,300.0,0.831,300.0,NaN,NaN,Id=1:BME680:breathVocEquivalent MAX value VOC ...,Id=2:BME680:breathVocEquivalent MAX value VOC ...,0.8206,0.96705,0.6954,0.81464,NaN,NaN,0.7423,0.95124,-2.15,2.2
16,InsertingSourcePollutant,on,None,None,1.8,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,None,None,2025-07-20 16:34:39,2025-07-20 16:20:42,2025-07-20 16:43:55,2025-07-20,2025-07-20 16:20:44,2025-07-20 16:43:54,0 days 00:23:10,0 days 00:13:56,836.0,0 days 00:09:14,0 days 00:13:56,836.0,554.0,1390.0,242.0,-59.0,300.0,0.207,284.0,0.352,300.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.1802,0.20600,0.2222,0.33505,NaN,NaN,0.2000,0.31805,-2.15,2.2
17,InsertingSourcePollutant,on,on,None,1.8,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,None,None,2025-07-20 18:13:07,2025-07-20 18:04:08,2025-07-20 18:22:22,2025-07-20,2025-07-20 18:04:10,2025-07-20 18:22:20,0 days 00:18:10,0 days 00:08:58,538.0,0 days 00:09:12,0 days 00:08:58,538.0,552.0,1090.0,242.0,-59.0,300.0,0.496,300.0,0.688,231.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.4751,0.49341,0.6860,0.68800,NaN,NaN,0.6692,0.68800,-2.15,2.2
18,InsertingSourcePollutant,on,on,on,1.8,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,None,None,2025-07-20 18:31:41,2025-07-20 18:29:19,2025-07-20 18:40:12,2025-07-20,2025-07-20 18:29:21,2025-07-20 18:40:11,0 days 00:10:50,0 days 00:02:21,141.0,0 days 00:08:29,0 days 00:02:21,141.0,509.0,650.0,242.0,-59.0,300.0,0.026,284.0,0.020,133.0,NaN,NaN,Id=1:BME680:breathVocEquivalent MAX value VOC ...,Id=2:BME680:breathVocEquivalent MAX value VOC ...,0.0191,0.02600,0.0180,0.02000,NaN,NaN,0.0181,0.02581,-2.15,2.2
19,InsertingSourcePollutant,on,on,None,1.8,Φαρμακευτικό αλκοόλ 95%,ανεμιστήρας,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,None,None,2025-07-20 18:47:26,2025-07-20 18:41:09,2025-07-20 19:00:09,2025-07-20,2025-07-20 18:41:11,2025-07-20 19:00:08,0 days 00:18:57,0 days 00:06:16,376.0,0 days 00:12:41,0 days 00:06:16,376.0,761.0,1137.0,242.0,-59.0,300.0,0.799,300.0,1.144,300.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.6444,0.78264,0.9167,1.12546,NaN,NaN,0.7642,1.10386,-2.15,2.2
20,InsertingSourcePollutant,on,on,None,1.8,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,None,None,2025-07-20 19:15:51,2025-07-20 19:13:35,2025-07-20 19:23:44,2025-07-20,2025-07-20 19:13:36,2025-07-20 19:23:42,0 days 00:10:06,0 days 00:02:16,136.0,0 days 00:07:50,0 days 00:02:16,136.0,470.0,606.0,242.0,-59.0,300.0,0.119,300.0,0.545,146.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.0980,0.11641,0.5380,0.54500,NaN,NaN,0.5301,0.54381,-2.15,2.2
21,InsertingSourcePollutant,on,None,None,1.8,Φαρμακευτικό αλκοόλ 95%,ανεμιστήρας,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,None,None,2025-07-20 19:37:50,2025-07-20 19:30:51,2025-07-20 19:46:28,2025-07-20,2025-07-20 19:30:53,2025-07-20 19:46:26,0 days 00:15:33,0 days 00:06:58,418.0,0 days 00:08:35,0 days 00:06:58,418.0,515.0,933.0,242.0,-59.0,300.0,0.412,300.0,0.540,300.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.2813,0.39664,0.3924,0.52205,NaN,NaN,0.3430,0.50524,-2.15,2.2
22,InsertingSourcePollutant,on,on,None,1.8,Φαρμακευτικό αλκοόλ 95%,ανεμιστήρας,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,None,None,2025-07-20 19:59:56,2025-07-20 19:55:47,2025-07-20 20:05:21,2025-07-20,2025-07-20 19:55:48,2025-07-20 20:05:20,0 days 00:09:32,0 days 00:04:09,249.0,0 days 00:05:23,0 days 00:04:09,249.0,323.0,572.0,242.0,-59.0,300.0,1.377,300.0,1.477,300.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,1.1205,1.35546,1.2606,1.45087,NaN,NaN,1.1910,1.43005,-2.15,2.2
23,InsertingSourcePollutant,on,None,None,1.8,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,on,None,2025-07-20 20:29:17,2025-07-20 20:25:07,2025-07-20 20:34:24,2025-07-20,2025-07-20 20:25:42,2025-07-20 20:30:33,0 days 00:04:51,0 days 00:03:36,216.0,0 days 00:01:15,0 days 00:03:36,216.0,75.0,291.0,17.0,-59.0,75.0,0.045,72.0,0.037,75.0,NaN,NaN,Id=1:BME680:breathVocEquivalent MAX value VOC ...,Id=2:BME680:breathVocEquivalent MAX value VOC ...,0.0416,0.04500,0.0230,0.03466,NaN,NaN,0.0292,0.04431,-2.15,2.2
24,InsertingSourcePollutant,on,None,None,1.8,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,on,None,2025-07-20 20:48:43,2025-07-20 20:47:09,2025-07-20 20:55:25,2025-07-20,2025-07-20 20:47:11,2025-07-20 20:55:23,0 days 00:08:12,0 days 00:01:33,93.0,0 days 00:06:39,0 days 00:01:33,93.0,399.0,492.0,242.0,-59.0,300.0,0.639,300.0,0.562,300.0,NaN,NaN,Id=1:BME680:breathVocEquivalent MAX value VOC ...,Id=2:BME680:breathVocEquivalent MAX value VOC ...,0.4953,0.62364,0.4713,0.55482,NaN,NaN,0.4821,0.60705,-2.15,2.2
25,InsertingSourcePollutant,on,None,None,1.8,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,on,None,2025-07-20 21:11:42,2025-07-20 21:08:20,2025-07-20 21:19:43,2025-07-20,2025-07-20 21:08:21,2025-07-20 21:19:41,0 days 00:11:20,0 days 00:03:22,202.0,0 days 00:07:58,0 days 00:03:22,202.0,478.0,680.0,242.0,-59.0,300.0,0.698,300.0,0.593,300.0,NaN,NaN,Id=1:BME680:breathVocEquivalent MAX value VOC ...,Id=2:BME680:breathVocEquivalent MAX value VOC ...,0.5464,0.68264,0.4783,0.58682,NaN,NaN,0.5161,0.66624,-2.15,2.2
26,InsertingSourcePollutant,on,on,None,1.8,Φαρμακευτικό αλκοόλ 70%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,on,None,2025-07-21 14:32:35,2025-07-21 14:24:56,2025-07-21 14:46:41,2025-07-21,2025-07-21 14:24:58,2025-07-21 14:46:39,0 days 00:21:41,0 days 00:07:38,458.0,0 days 00:14:03,0 days 00:07:38,458.0,843.0,1301.0,242.0,-59.0,300.0,0.522,300.0,1.724,300.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.3983,0.50923,1.2011,1.66756,NaN,NaN,0.8188,1.60977,-2.15,2.2
27,InsertingSourcePollutant,on,None,None,1.8,Φαρμακευτικό αλκοόλ 70%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,NaN,1.1,None,None,2025-07-21 19:37:03,2025-07-21 19:33:55,2025-07-21 19:48:50,2025-07-21,2025-07-21 19:33:56,2025-07-21 19:48:49,0 days 00:14:53,0 days 00:03:08,188.0,0 days 00:11:45,0 days 00:03:08,188.0,705.0,893.0,242.0,-59.0,300.0,0.115,299.0,0.469,228.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.1030,0.11341,0.4501,0.46841,NaN,NaN,0.4450,0.46700,-2.15,2.2
28,InsertingSourcePollutant,on,None,None,NaN,Φαρμακευτικό αλκοόλ 70%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,1.2,1.2,on,None,2025-07-21 20:02:43,2025-07-21 19:59:26,2025-07-21 20:08:57,2025-07-21,2025-07-21 19:59:28,2025-07-21 20:08:55,0 days 00:09:27,0 days 00:03:16,196.0,0 days 00:06:11,0 days 00:03:16,196.0,371.0,567.0,242.0,-59.0,300.0,1.117,300.0,0.816,300.0,NaN,NaN,Id=1:BME680:breathVocEquivalent MAX value VOC ...,Id=2:BME680:breathVocEquivalent MAX value VOC ...,0.8384,1.09287,0.6765,0.80005,NaN,NaN,0.7922,1.06429,-2.05,1.2
29,InsertingSourcePollutant,on,None,None,NaN,Φαρμακευτικό αλκοόλ 70%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,1.2,1.2,None,None,2025-07-21 20:52:37,2025-07-21 20:49:38,2025-07-21 21:03:43,2025-07-21,2025-07-21 20:49:40,2025-07-21 21:03:41,0 days 00:14:01,0 days 00:02:58,178.0,0 days 00:11:03,0 days 00:02:58,178.0,663.0,841.0,242.0,-59.0,300.0,0.344,300.0,0.336,300.0,NaN,NaN,Id=1:BME680:breathVocEquivalent MAX value VOC ...,Id=2:BME680:breathVocEquivalent MAX value VOC ...,0.3220,0.33882,0.2871,0.33241,NaN,NaN,0.3200,0.33581,-2.05,1.2
30,InsertingSourcePollutant,on,None,None,NaN,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1,NaN,1.2,1.2,None,None,2025-07-21 21:31:10,2025-07-21 21:24:30,2025-07-21 21:39:20,2025-07-21,2025-07-21 21:24:32,2025-07-21 21:39:20,0 days 00:14:48,0 days 00:06:39,399.0,0 days 00:08:09,0 days 00:06:39,399.0,489.0,888.0,242.0,-59.0,300.0,1.144,300.0,0.229,300.0,NaN,NaN,Id=1:BME680:breathVocEquivalent MAX value VOC ...,Id=2:BME680:breathVocEquivalent MAX value VOC ...,1.0266,1.13623,0.1751,0.22182,NaN,NaN,0.7707,1.12562,-2.05,1.2

In [191]:
userInputData.loc[:, ["x axis", "y axis"]].tail(30)

     x axis  y axis
229   -1.50     2.5
230   -2.50     2.5
231   -2.95     2.5
232   -0.50     0.5
233   -1.50     0.5
234   -2.50     0.5
235   -2.95     0.5
236   -0.50     3.5
237   -1.50     3.5
238   -2.50     3.5
239   -2.95     3.5
240     NaN     NaN
241   -2.75     2.2
242     NaN     NaN
243   -1.50     1.5
244   -1.50     0.5
245   -1.50     2.5
246   -1.50     3.5
247   -2.50     3.5
248   -2.50     2.5
249   -2.50     1.5
250   -2.50     0.5
251   -0.50     0.5
252   -0.50     1.5
253   -0.50     2.5
254   -0.50     3.5
255   -2.95     3.5
256   -2.95     2.5
257   -2.95     1.5
258   -2.95     0.5

In [192]:
print(dict_of_timeseries[157].max())
print(userInputData.loc[157])

sensors                                                        Id=2:BME680:breathVocEquivalent
VOC                                                                                   5.655352
after_insertion                                                                           True
original_value                                                                            True
datetime_timestamp                                                         2025-10-13 22:32:47
timestamp                                                                      0 days 00:06:35
seconds                                                                                  300.0
seconds passed from insertionSource                                                      300.0
VOC rolling average                                                                      3.835
original seconds                                                                         395.0
VOC rolling average-capped                                                               3.835
VOC rolling average gradient                                                             0.082
VOC rolling average gradient cumsum                                                     3.8395
VOC rolling average-capped gradient                                                      0.082
VOC rolling average-capped gradient cumsum                                              3.8395
VOC rolling average standard scaler per sensor                                        3.699183
VOC rolling average-capped standard scaler per sensor                                 3.699183
VOC rolling average standard scaler whole experiment                                  3.071127
VOC rolling average-capped standard scaler whole experiment                           3.071127
dtype: object
experimentState                                                                                    InsertingSourcePollutant
are-doors-opened                                                                                                       None
are-people-inside                                                                                                      None
are-windows-opened                                                                                                     None
front-wall                                                                                                              1.5
item-used                                                                                           Φαρμακευτικό αλκοόλ 95%
notes
room                                                                      Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...
side-right-wall                                                                                                         2.5
back-wall                                                                                                               NaN
side-left-wall                                                                                                          NaN
are-fans-on                                                                                                            None
no-source-located                                                                                                      None
timestamp InsertingSource                                                                               2025-10-13 22:27:46
timestamp StartingExperiment                                                                            2025-10-13 22:26:11
timestamp EndingExperiment                                                                              2025-10-13 22:34:17
date of experiment                                                                                               2025-10-13
actual timestamp StartingExperiment                                                                     2025-10-13 22:26:12
actual timestamp EndingExperiment                                                                       2025-10-13 22:34:15
time taken total                                                                                            0 days 00:08:03
timestamp InsertingSource timedelta                                                                         0 days 00:01:35
timestamp InsertingSource seconds                                                                                      95.0
time taken after insertion                                                                                  0 days 00:06:28
time taken before insertion                                                                                 0 days 00:01:35
time taken before insertion (seconds)                                                                                  95.0
time taken after insertion (seconds)                                                                                  388.0
time taken total (seconds)                                                                                            483.0
time taken total (seconds)-capped                                                                                     242.0
time taken before insertion (seconds)-capped                                                                          -59.0
time taken after insertion (seconds)-capped                                                                           300.0
Id=1:BME680:breathVocEquivalent MAX value VOC rolling average                                                         2.334
Id=1:BME680:breathVocEquivalent index of MAX value VOC rolling average                                                300.0
Id=2:BME680:breathVocEquivalent MAX value VOC rolling average                                                         3.673
Id=2:BME680:breathVocEquivalent index of MAX value VOC rolling average                                                300.0
Id=0:BME680:breathVocEquivalent MAX value VOC rolling average                                                         3.835
Id=0:BME680:breathVocEquivalent index of MAX value VOC rolling average                                                295.0
sensor with MAX value experiment                                          Id=0:BME680:breathVocEquivalent MAX value VOC ...
sensor with second MAX value experiment                                   Id=2:BME680:breathVocEquivalent MAX value VOC ...
Id=1:BME680:breathVocEquivalent quantile 90.0% VOC rolling average                                                   2.1283
Id=1:BME680:breathVocEquivalent quantile 99.0% VOC rolling average                                                   2.3041
Id=2:BME680:breathVocEquivalent quantile 90.0% VOC rolling average                                                   1.9567
Id=2:BME680:breathVocEquivalent quantile 99.0% VOC rolling average                                                  3.38616
Id=0:BME680:breathVocEquivalent quantile 90.0% VOC rolling average                                                   2.9553
Id=0:BME680:breathVocEquivalent quantile 99.0% VOC rolling average                                                  3.82905
whole experiment quantile 90.0% VOC rolling average                                                                  2.1582
whole experiment quantile 99.0% VOC rolling average                                                                 3.80063
x axis                                                                                                                 -2.5
y axis                                                                                                                  2.5
Name: 157, dtype: object

In [193]:
userInputData["room"].unique()

array(['Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55',
       'Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1',
       'Κρεβατοκάμαρα-Όλοι οι αισθητήρες μαζί Μ:0.80 , Α:0.90',
       'Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0.5  ,id:2 Π:0.4 Α:1.0',
       'Κρεβατοκάμαρα Όλοι οι αισθητήρες μαζί Π:1.80 , Δ:2.00'],
      dtype=object)

In [194]:
room_length = 4.0
room_width = 3.25
pos_id0 = 'position of Id=0:BME680:breathVocEquivalent'
pos_id1 = 'position of Id=1:BME680:breathVocEquivalent'
pos_id2 = 'position of Id=2:BME680:breathVocEquivalent'
pos_id_all = [pos_id0,pos_id1,pos_id2]
room_positions = {
    'Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55' : {
        pos_id1 +"-x axis" : room_width - 0.85 ,
        pos_id1 +"-y axis" : room_length - 0.95,
        pos_id2+"-x axis" :  room_width - 1.55 ,
        pos_id2+  "-y axis" : room_length - 0.95
              
    },
        
    'Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1' : {
        pos_id1+"-x axis" :  room_width - 1.2 ,
        pos_id1+"-y axis" :  0.6,
        pos_id2+"-x axis" :  room_width -1.1 ,
        pos_id2+"-y axis" : room_length - 0.8
   
    },      
        
    'Κρεβατοκάμαρα-Όλοι οι αισθητήρες μαζί Μ:0.80 , Α:0.90' : {
        
        pos_id0+"-x axis" : -room_width + 0.9, 
        pos_id0+"-y axis" : room_length - 0.8,
        
        pos_id1+"-x axis" : -room_width + 0.9,
        pos_id1+"-y axis" : room_length - 0.8,
        
        pos_id2+"-x axis" : -room_width + 0.9,
        pos_id2+"-y axis" : room_length - 0.8
     },
    'Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0.5  ,id:2 Π:0.4 Α:1.0' :{
        pos_id0+"-x axis" : -room_width  + 1.4, 
        pos_id0+"-y axis" : room_length - 0.5,
        
        pos_id1+"-x axis" :   -0.5,
        pos_id1+"-y axis" :   1.7,
        
        pos_id2+"-x axis" :  -room_width +1.0,
        pos_id2+"-y axis" :  0.4    
    }
}
room_positions

{'Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55': {'position of Id=1:BME680:breathVocEquivalent-x axis': 2.4,
  'position of Id=1:BME680:breathVocEquivalent-y axis': 3.05,
  'position of Id=2:BME680:breathVocEquivalent-x axis': 1.7,
  'position of Id=2:BME680:breathVocEquivalent-y axis': 3.05},
 'Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1': {'position of Id=1:BME680:breathVocEquivalent-x axis': 2.05,
  'position of Id=1:BME680:breathVocEquivalent-y axis': 0.6,
  'position of Id=2:BME680:breathVocEquivalent-x axis': 2.15,
  'position of Id=2:BME680:breathVocEquivalent-y axis': 3.2},
 'Κρεβατοκάμαρα-Όλοι οι αισθητήρες μαζί Μ:0.80 , Α:0.90': {'position of Id=0:BME680:breathVocEquivalent-x axis': -2.35,
  'position of Id=0:BME680:breathVocEquivalent-y axis': 3.2,
  'position of Id=1:BME680:breathVocEquivalent-x axis': -2.35,
  'position of Id=1:BME680:breathVocEquivalent-y axis': 3.2,
  'position of Id=2:BME680:breathVocEquivalent-x axis': -2.35,
  'position of Id=2:BME680:breathVocEquivalent-y axis': 3.2},
 'Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0.5  ,id:2 Π:0.4 Α:1.0': {'position of Id=0:BME680:breathVocEquivalent-x axis': -1.85,
  'position of Id=0:BME680:breathVocEquivalent-y axis': 3.5,
  'position of Id=1:BME680:breathVocEquivalent-x axis': -0.5,
  'position of Id=1:BME680:breathVocEquivalent-y axis': 1.7,
  'position of Id=2:BME680:breathVocEquivalent-x axis': -2.25,
  'position of Id=2:BME680:breathVocEquivalent-y axis': 0.4}}

In [195]:
pos_id0 = 'position of Id=0:BME680:breathVocEquivalent'
pos_id1 = 'position of Id=1:BME680:breathVocEquivalent'
pos_id2 = 'position of Id=2:BME680:breathVocEquivalent'
pos_id_all = [pos_id0,pos_id1,pos_id2]
for pos_id in pos_id_all:
    userInputData[pos_id+"-x axis"] = np.nan
    userInputData[pos_id+"-y axis"] = np.nan
    


for room,sensor_positions in room_positions.items():
   # print(f"room:{room}")
    outer_mask = userInputData["room"] == room
  #  print(f"sensor_positions:{sensor_positions}")
    for sensor_position,value  in sensor_positions.items():
 
        userInputData.loc[outer_mask,sensor_position] = value

C:\Users\Andreas\AppData\Local\Temp\ipykernel_6164\1617816513.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  userInputData[pos_id+"-x axis"] = np.nan
C:\Users\Andreas\AppData\Local\Temp\ipykernel_6164\1617816513.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  userInputData[pos_id+"-y axis"] = np.nan
C:\Users\Andreas\AppData\Local\Temp\ipykernel_6164\1617816513.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  userInputData[pos_id+"-x axis"] = np.nan
C:\Users\Andreas\AppData\Local\Temp\ipykernel_6164\1617816513.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  userInputData[pos_id+"-y axis"] = np.nan
C:\Users\Andreas\AppData\Local\Temp\ipykernel_6164\1617816513.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  userInputData[pos_id+"-x axis"] = np.nan
C:\Users\Andreas\AppData\Local\Temp\ipykernel_6164\1617816513.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  userInputData[pos_id+"-y axis"] = np.nan

In [196]:
userInputData

,experimentState,are-doors-opened,are-people-inside,are-windows-opened,front-wall,item-used,notes,room,side-right-wall,back-wall,side-left-wall,are-fans-on,no-source-located,timestamp InsertingSource,timestamp StartingExperiment,timestamp EndingExperiment,date of experiment,actual timestamp StartingExperiment,actual timestamp EndingExperiment,time taken total,timestamp InsertingSource timedelta,timestamp InsertingSource seconds,time taken after insertion,time taken before insertion,time taken before insertion (seconds),time taken after insertion (seconds),time taken total (seconds),time taken total (seconds)-capped,time taken before insertion (seconds)-capped,time taken after insertion (seconds)-capped,Id=1:BME680:breathVocEquivalent MAX value VOC rolling average,Id=1:BME680:breathVocEquivalent index of MAX value VOC rolling average,Id=2:BME680:breathVocEquivalent MAX value VOC rolling average,Id=2:BME680:breathVocEquivalent index of MAX value VOC rolling average,Id=0:BME680:breathVocEquivalent MAX value VOC rolling average,Id=0:BME680:breathVocEquivalent index of MAX value VOC rolling average,sensor with MAX value experiment,sensor with second MAX value experiment,Id=1:BME680:breathVocEquivalent quantile 90.0% VOC rolling average,Id=1:BME680:breathVocEquivalent quantile 99.0% VOC rolling average,Id=2:BME680:breathVocEquivalent quantile 90.0% VOC rolling average,Id=2:BME680:breathVocEquivalent quantile 99.0% VOC rolling average,Id=0:BME680:breathVocEquivalent quantile 90.0% VOC rolling average,Id=0:BME680:breathVocEquivalent quantile 99.0% VOC rolling average,whole experiment quantile 90.0% VOC rolling average,whole experiment quantile 99.0% VOC rolling average,x axis,y axis,position of Id=0:BME680:breathVocEquivalent-x axis,position of Id=0:BME680:breathVocEquivalent-y axis,position of Id=1:BME680:breathVocEquivalent-x axis,position of Id=1:BME680:breathVocEquivalent-y axis,position of Id=2:BME680:breathVocEquivalent-x axis,position of Id=2:BME680:breathVocEquivalent-y axis
0,InsertingSourcePollutant,on,None,None,1.0,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.0,None,None,2025-07-01 16:09:41,2025-07-01 15:27:16,2025-07-01 16:14:44,2025-07-01,2025-07-01 15:27:19,2025-07-01 16:14:42,0 days 00:47:23,0 days 00:42:23,2543.0,0 days 00:05:00,0 days 00:42:23,2543.0,300.0,2843.0,242.0,-59.0,300.0,3.063,299.0,3.322,242.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,2.8016,3.05823,3.2545,3.32041,NaN,NaN,3.1453,3.31500,-2.25,3.0,NaN,NaN,2.4,3.05,1.70,3.05
1,InsertingSourcePollutant,on,None,None,1.0,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.0,None,None,2025-07-02 15:59:29,2025-07-02 15:42:50,2025-07-02 16:04:52,2025-07-02,2025-07-02 15:42:50,2025-07-02 16:04:50,0 days 00:22:00,0 days 00:16:40,1000.0,0 days 00:05:20,0 days 00:16:40,1000.0,320.0,1320.0,242.0,-59.0,300.0,1.083,201.0,0.307,78.0,NaN,NaN,Id=1:BME680:breathVocEquivalent MAX value VOC ...,Id=2:BME680:breathVocEquivalent MAX value VOC ...,0.8909,1.08023,0.2811,0.30700,NaN,NaN,0.6645,1.07224,-2.25,3.0,NaN,NaN,2.4,3.05,1.70,3.05
2,InsertingSourcePollutant,on,None,None,0.4,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.0,None,None,2025-07-03 12:34:32,2025-07-03 12:30:25,2025-07-03 12:45:31,2025-07-03,2025-07-03 12:30:25,2025-07-03 12:45:31,0 days 00:15:06,0 days 00:04:08,248.0,0 days 00:10:58,0 days 00:04:08,248.0,658.0,906.0,242.0,-59.0,300.0,1.372,235.0,2.294,300.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,1.3124,1.37000,1.5840,2.16494,NaN,NaN,1.3710,2.04492,-2.25,3.6,NaN,NaN,2.4,3.05,1.70,3.05
3,InsertingSourcePollutant,on,None,None,1.0,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.8,None,None,2025-07-03 15:53:07,2025-07-03 15:43:27,2025-07-03 15:59:11,2025-07-03,2025-07-03 15:51:40,2025-07-03 15:59:10,0 days 00:07:30,0 days 00:01:28,88.0,0 days 00:06:02,0 days 00:01:28,88.0,362.0,450.0,242.0,-59.0,300.0,0.332,300.0,18.486,300.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.2483,0.32182,15.5041,17.63282,NaN,NaN,5.3774,17.06834,-1.45,3.0,NaN,NaN,2.4,3.05,1.70,3.05
4,InsertingSourcePollutant,on,None,None,1.4,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.4,None,None,2025-07-09 19:19:19,2025-07-09 19:01:42,2025-07-09 19:27:50,2025-07-09,2025-07-09 19:01:44,2025-07-09 19:27:49,0 days 00:26:05,0 days 00:17:36,1056.0,0 days 00:08:29,0 days 00:17:36,1056.0,509.0,1565.0,242.0,-59.0,300.0,0.600,245.0,0.512,300.0,NaN,NaN,Id=1:BME680:breathVocEquivalent MAX value VOC ...,Id=2:BME680:breathVocEquivalent MAX value VOC ...,0.5762,0.60000,0.4803,0.50641,NaN,NaN,0.5321,0.59881,-1.85,2.6,NaN,NaN,2.4,3.05,1.70,3.05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
254,InsertingSourcePollutant,None,None,None,0.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",0.5,NaN,NaN,None,None,2025-10-24 20:32:03,2025-10-24 20:29:36,2025-10-24 20:37:33,2025-10-24,2025-10-24 20:29:37,2025-10-24 20:37:31,0 days 00:07:54,0 days 00:02:27,147.0,0 days 00:05:27,0 days 00:02:27,147.0,327.0,474.0,242.0,-59.0,300.0,1.748,131.0,4.850,300.0,1.947,285.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=0:BME680:breathVocEquivalent MAX value VOC ...,1.5612,1.74482,4.4074,4.80156,1.8771,1.94441,3.5261,4.69152,-0.50,3.5,-1.85,3.5,-0.5,1.70,-2.25,0.40
255,InsertingSourcePollutant,None,None,None,0.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:05:46,2025-10-24 21:03:22,2025-10-24 21:11:21,2025-10-24,2025-10-24 21:03:24,2025-10-24 21:11:19,0 days 00:07:55,0 days 00:02:23,143.0,0 days 00:05:32,0 days 00:02:23,143.0,332.0,475.0,242.0,-59.0,300.0,1.057,300.0,5.182,300.0,2.413,236.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=0:BME680:breathVocEquivalent MAX value VOC ...,1.0160,1.05441,3.5239,5.03822,2.3453,2.40941,2.3893,4.71445,-2.95,3.5,-1.85,3.5,-0.5,1.70,-2.25,0.40
256,InsertingSourcePollutant,None,None,None,1.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:18:43,2025-10-24 21:17:10,2025-10-24 21:24:48,2025-10-24,2025-10-24 21:17:12,2025-10-24 21:24:46,0 days 00:07:34,0 days 00:01:32,92.0,0 days 00:06:02,0 days 00:01:32,92.0,362.0,454.0,242.0,-59.0,300.0,1.948,300.0,12.093,277.0,1.837,140.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,1.1753,1.87102,11.9171,12.08182,1.7081,1.83641,8.0527,12.03042,-2.95,2.5,-1.85,3.5,-0.5,1.70,-2.25,0.40
257,InsertingSourcePollutant,None,None,None,2.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:34:58,2025-10-24 21:33:44,2025-10-24 21:41:06,2025-10-24,2025-10-24 21:33:46,2025-10-24 21:41:04,0 days 00:07:18,0 days 00:01:13,73.0,0 days 00:06:05,0 days 00:01:13,73.0,365.0,438.0,242.0,-59.0,300.0,1.745,300.0,7.490,260.0,1.193,300.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,1.6422,1.71928,7.2742,7.48800,1.1576,1.18782,6.4991,7.44789,-2.95,1.5,-1.85,3.5,-0.5,1.70,-2.25,0.40
258,InsertingSourcePollutant,None,None,None,3.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:54:05,2025-10-24 21:52:16,2025-10-24 22:01:25,2025-10-24,2025-10-24 21:52:18,2025-10-24 22:01:24,0 days 00:09:06,0 days 00:01:48,108.0,0 days 00:07:18,0 days 00:01:48,108.0,438.0,546.0,242.0,-59.0,300.0,1.613,212.0,2.972,287.0,1.935,300.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=0:BME680:breathVocEquivalent MAX value VOC ...,1.5463,1.61141,2.8288,2.97000,1.5596,1.89033,2.3350,2.96242,-2.95,0.5,-1.85,3.5,-0.5,1.70,-2.25,0.40

In [197]:
#find euclidian distance between sensors position and source

x_axis_source = userInputData["x axis"].to_numpy()
y_axis_source = userInputData["y axis"].to_numpy()


for id_sensor_number in range(3):
    sensor_name = "Id="+str(id_sensor_number)+":BME680:breathVocEquivalent"
    x_axis_sensor = userInputData["position of "+ sensor_name + "-x axis"].to_numpy()
    y_axis_sensor = userInputData["position of "+ sensor_name + "-y axis"].to_numpy()
    # Euclidean distance per row
    distances = np.sqrt((x_axis_sensor - x_axis_source)**2 + (y_axis_sensor - y_axis_source)**2)
    var_name = "Euclidian distance to "+sensor_name
    userInputData[var_name] = distances

C:\Users\Andreas\AppData\Local\Temp\ipykernel_6164\3513323104.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  userInputData[var_name] = distances
C:\Users\Andreas\AppData\Local\Temp\ipykernel_6164\3513323104.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  userInputData[var_name] = distances
C:\Users\Andreas\AppData\Local\Temp\ipykernel_6164\3513323104.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  userInputData[var_name] = distances

In [198]:
userInputData

,experimentState,are-doors-opened,are-people-inside,are-windows-opened,front-wall,item-used,notes,room,side-right-wall,back-wall,side-left-wall,are-fans-on,no-source-located,timestamp InsertingSource,timestamp StartingExperiment,timestamp EndingExperiment,date of experiment,actual timestamp StartingExperiment,actual timestamp EndingExperiment,time taken total,timestamp InsertingSource timedelta,timestamp InsertingSource seconds,time taken after insertion,time taken before insertion,time taken before insertion (seconds),time taken after insertion (seconds),time taken total (seconds),time taken total (seconds)-capped,time taken before insertion (seconds)-capped,time taken after insertion (seconds)-capped,Id=1:BME680:breathVocEquivalent MAX value VOC rolling average,Id=1:BME680:breathVocEquivalent index of MAX value VOC rolling average,Id=2:BME680:breathVocEquivalent MAX value VOC rolling average,Id=2:BME680:breathVocEquivalent index of MAX value VOC rolling average,Id=0:BME680:breathVocEquivalent MAX value VOC rolling average,Id=0:BME680:breathVocEquivalent index of MAX value VOC rolling average,sensor with MAX value experiment,sensor with second MAX value experiment,Id=1:BME680:breathVocEquivalent quantile 90.0% VOC rolling average,Id=1:BME680:breathVocEquivalent quantile 99.0% VOC rolling average,Id=2:BME680:breathVocEquivalent quantile 90.0% VOC rolling average,Id=2:BME680:breathVocEquivalent quantile 99.0% VOC rolling average,Id=0:BME680:breathVocEquivalent quantile 90.0% VOC rolling average,Id=0:BME680:breathVocEquivalent quantile 99.0% VOC rolling average,whole experiment quantile 90.0% VOC rolling average,whole experiment quantile 99.0% VOC rolling average,x axis,y axis,position of Id=0:BME680:breathVocEquivalent-x axis,position of Id=0:BME680:breathVocEquivalent-y axis,position of Id=1:BME680:breathVocEquivalent-x axis,position of Id=1:BME680:breathVocEquivalent-y axis,position of Id=2:BME680:breathVocEquivalent-x axis,position of Id=2:BME680:breathVocEquivalent-y axis,Euclidian distance to Id=0:BME680:breathVocEquivalent,Euclidian distance to Id=1:BME680:breathVocEquivalent,Euclidian distance to Id=2:BME680:breathVocEquivalent
0,InsertingSourcePollutant,on,None,None,1.0,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.0,None,None,2025-07-01 16:09:41,2025-07-01 15:27:16,2025-07-01 16:14:44,2025-07-01,2025-07-01 15:27:19,2025-07-01 16:14:42,0 days 00:47:23,0 days 00:42:23,2543.0,0 days 00:05:00,0 days 00:42:23,2543.0,300.0,2843.0,242.0,-59.0,300.0,3.063,299.0,3.322,242.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,2.8016,3.05823,3.2545,3.32041,NaN,NaN,3.1453,3.31500,-2.25,3.0,NaN,NaN,2.4,3.05,1.70,3.05,NaN,4.650269,3.950316
1,InsertingSourcePollutant,on,None,None,1.0,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.0,None,None,2025-07-02 15:59:29,2025-07-02 15:42:50,2025-07-02 16:04:52,2025-07-02,2025-07-02 15:42:50,2025-07-02 16:04:50,0 days 00:22:00,0 days 00:16:40,1000.0,0 days 00:05:20,0 days 00:16:40,1000.0,320.0,1320.0,242.0,-59.0,300.0,1.083,201.0,0.307,78.0,NaN,NaN,Id=1:BME680:breathVocEquivalent MAX value VOC ...,Id=2:BME680:breathVocEquivalent MAX value VOC ...,0.8909,1.08023,0.2811,0.30700,NaN,NaN,0.6645,1.07224,-2.25,3.0,NaN,NaN,2.4,3.05,1.70,3.05,NaN,4.650269,3.950316
2,InsertingSourcePollutant,on,None,None,0.4,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.0,None,None,2025-07-03 12:34:32,2025-07-03 12:30:25,2025-07-03 12:45:31,2025-07-03,2025-07-03 12:30:25,2025-07-03 12:45:31,0 days 00:15:06,0 days 00:04:08,248.0,0 days 00:10:58,0 days 00:04:08,248.0,658.0,906.0,242.0,-59.0,300.0,1.372,235.0,2.294,300.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,1.3124,1.37000,1.5840,2.16494,NaN,NaN,1.3710,2.04492,-2.25,3.6,NaN,NaN,2.4,3.05,1.70,3.05,NaN,4.682414,3.988107
3,InsertingSourcePollutant,on,None,None,1.0,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.8,None,None,2025-07-03 15:53:07,2025-07-03 15:43:27,2025-07-03 15:59:11,2025-07-03,2025-07-03 15:51:40,2025-07-03 15:59:10,0 days 00:07:30,0 days 00:01:28,88.0,0 days 00:06:02,0 days 00:01:28,88.0,362.0,450.0,242.0,-59.0,300.0,0.332,300.0,18.486,300.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.2483,0.32182,15.5041,17.63282,NaN,NaN,5.3774,17.06834,-1.45,3.0,NaN,NaN,2.4,3.05,1.70,3.05,NaN,3.850325,3.150397
4,InsertingSourcePollutant,on,None,None,1.4,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.4,None,None,2025-07-09 19:19:19,2025-07-09 19:01:42,2025-07-09 19:27:50,2025-07-09,2025-07-09 19:01:44,2025-07-09 19:27:49,0 days 00:26:05,0 days 00:17:36,1056.0,0 days 00:08:29,0 days 00:17:36,1056.0,509.0,1565.0,242.0,-59.0,300.0,0.600,245.0,0.512,300.0,NaN,NaN,Id=1:BME680:breathVocEquivalent MAX value VOC ...,Id=2:BME680:breathVocEquivalent MAX value VOC ...,0.5762,0.60000,0.4803,0.50641,NaN,NaN,0.5321,0.59881,-1.85,2.6,NaN,NaN,2.4,3.05,1.70,3.05,NaN,4.273757,3.578407
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
254,InsertingSourcePollutant,None,None,None,0.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",0.5,NaN,NaN,None,None,2025-10-24 20:32:03,2025-10-24 20:29:36,2025-10-24 20:37:33,2025-10-24,2025-10-24 20:29:37,2025-10-24 20:37:31,0 days 00:07:54,0 days 00:02:27,147.0,0 days 00:05:27,0 days 00:02:27,147.0,327.0,474.0,242.0,-59.0,300.0,1.748,131.0,4.850,300.0,1.947,285.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=0:BME680:breathVocEquivalent MAX value VOC ...,1.5612,1.74482,4.4074,4.80156,1.8771,1.94441,3.5261,4.69152,-0.50,3.5,-1.85,3.5,-0.5,1.70,-2.25,0.40,1.350000,1.800000,3.559846
255,InsertingSourcePollutant,None,None,None,0.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:05:46,2025-10-24 21:03:22,2025-10-24 21:11:21,2025-10-24,2025-10-24 21:03:24,2025-10-24 21:11:19,0 days 00:07:55,0 days 00:02:23,143.0,0 days 00:05:32,0 days 00:02:23,143.0,332.0,475.0,242.0,-59.0,300.0,1.057,300.0,5.182,300.0,2.413,236.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=0:BME680:breathVocEquivalent MAX value VOC ...,1.0160,1.05441,3.5239,5.03822,2.3453,2.40941,2.3893,4.71445,-2.95,3.5,-1.85,3.5,-0.5,1.70,-2.25,0.40,1.100000,3.040148,3.178050
256,InsertingSourcePollutant,None,None,None,1.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:18:43,2025-10-24 21:17:10,2025-10-24 21:24:48,2025-10-24,2025-10-24 21:17:12,2025-10-24 21:24:46,0 days 00:07:34,0 days 00:01:32,92.0,0 days 00:06:02,0 days 00:01:32,92.0,362.0,454.0,242.0,-59.0,300.0,1.948,300.0,12.093,277.0,1.837,140.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,1.1753,1.87102,11.9171,12.08182,1.7081,1.83641,8.0527,12.03042,-2.95,2.5,-1.85,3.5,-0.5,1.70,-2.25,0.40,1.486607,2.577305,2.213594
257,InsertingSourcePollutant,None,None,None,2.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:34:58,2025-10-24 21:33:44,2025-10-24 21:41:06,2025-10-24,2025-10-24 21:33:46,2025-10-24 21:41:04,0 days 00:07:18,0 days 00:01:13,73.0,0 days 00:06:05,0 days 00:01:13,73.0,365.0,438.0,242.0,-59.0,300.0,1.745,300.0,7.490,260.0,1.193,300.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,1.6422,1.71928,7.2742,7.48800,1.1576,1.18782,6.4991,7.44789,-2.95,1.5,-1.85,3.5,-0.5,1.70,-2.25,0.40,2.282542,2.458150,1.303840
258,InsertingSourcePollutant,None,None,None,3.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:54:05,2025-10-24 21:52:16,2025-10-24 22:01:25,2025-10-24,2025-10-24 21:52:18,2025-10-24 22:01:24,0 days 00:09:06,0 days 00:01:48,108.0,0 days 00:07:18,0 days 00:01:48,108.0,438.0,546.0,242.0,-59.0,300.0,1.613,212.0,2.972,287.0,1.935,300.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=0:BME680:breathVocEquivalent MAX value VOC ...,1.5463,1.61141,2.8288,2.97000,1.5596,1.89033,2.3350,2.96242,-2.95,0.5,-1.85,3.5,-0.5,1.70,-2.25,0.40,3.195309,2.728095,0.707107

In [199]:
userInputData.loc[:, ["x axis", "y axis"]]

     x axis  y axis
0     -2.25     3.0
1     -2.25     3.0
2     -2.25     3.6
3     -1.45     3.0
4     -1.85     2.6
..      ...     ...
254   -0.50     3.5
255   -2.95     3.5
256   -2.95     2.5
257   -2.95     1.5
258   -2.95     0.5

[257 rows x 2 columns]

In [200]:
print(dict_of_timeseries[157].max())
print(userInputData.loc[157])

sensors                                                        Id=2:BME680:breathVocEquivalent
VOC                                                                                   5.655352
after_insertion                                                                           True
original_value                                                                            True
datetime_timestamp                                                         2025-10-13 22:32:47
timestamp                                                                      0 days 00:06:35
seconds                                                                                  300.0
seconds passed from insertionSource                                                      300.0
VOC rolling average                                                                      3.835
original seconds                                                                         395.0
VOC rolling average-capped                                                               3.835
VOC rolling average gradient                                                             0.082
VOC rolling average gradient cumsum                                                     3.8395
VOC rolling average-capped gradient                                                      0.082
VOC rolling average-capped gradient cumsum                                              3.8395
VOC rolling average standard scaler per sensor                                        3.699183
VOC rolling average-capped standard scaler per sensor                                 3.699183
VOC rolling average standard scaler whole experiment                                  3.071127
VOC rolling average-capped standard scaler whole experiment                           3.071127
dtype: object
experimentState                                                                                    InsertingSourcePollutant
are-doors-opened                                                                                                       None
are-people-inside                                                                                                      None
are-windows-opened                                                                                                     None
front-wall                                                                                                              1.5
item-used                                                                                           Φαρμακευτικό αλκοόλ 95%
notes
room                                                                      Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...
side-right-wall                                                                                                         2.5
back-wall                                                                                                               NaN
side-left-wall                                                                                                          NaN
are-fans-on                                                                                                            None
no-source-located                                                                                                      None
timestamp InsertingSource                                                                               2025-10-13 22:27:46
timestamp StartingExperiment                                                                            2025-10-13 22:26:11
timestamp EndingExperiment                                                                              2025-10-13 22:34:17
date of experiment                                                                                               2025-10-13
actual timestamp StartingExperiment                                                                     2025-10-13 22:26:12
actual timestamp EndingExperiment                                                                       2025-10-13 22:34:15
time taken total                                                                                            0 days 00:08:03
timestamp InsertingSource timedelta                                                                         0 days 00:01:35
timestamp InsertingSource seconds                                                                                      95.0
time taken after insertion                                                                                  0 days 00:06:28
time taken before insertion                                                                                 0 days 00:01:35
time taken before insertion (seconds)                                                                                  95.0
time taken after insertion (seconds)                                                                                  388.0
time taken total (seconds)                                                                                            483.0
time taken total (seconds)-capped                                                                                     242.0
time taken before insertion (seconds)-capped                                                                          -59.0
time taken after insertion (seconds)-capped                                                                           300.0
Id=1:BME680:breathVocEquivalent MAX value VOC rolling average                                                         2.334
Id=1:BME680:breathVocEquivalent index of MAX value VOC rolling average                                                300.0
Id=2:BME680:breathVocEquivalent MAX value VOC rolling average                                                         3.673
Id=2:BME680:breathVocEquivalent index of MAX value VOC rolling average                                                300.0
Id=0:BME680:breathVocEquivalent MAX value VOC rolling average                                                         3.835
Id=0:BME680:breathVocEquivalent index of MAX value VOC rolling average                                                295.0
sensor with MAX value experiment                                          Id=0:BME680:breathVocEquivalent MAX value VOC ...
sensor with second MAX value experiment                                   Id=2:BME680:breathVocEquivalent MAX value VOC ...
Id=1:BME680:breathVocEquivalent quantile 90.0% VOC rolling average                                                   2.1283
Id=1:BME680:breathVocEquivalent quantile 99.0% VOC rolling average                                                   2.3041
Id=2:BME680:breathVocEquivalent quantile 90.0% VOC rolling average                                                   1.9567
Id=2:BME680:breathVocEquivalent quantile 99.0% VOC rolling average                                                  3.38616
Id=0:BME680:breathVocEquivalent quantile 90.0% VOC rolling average                                                   2.9553
Id=0:BME680:breathVocEquivalent quantile 99.0% VOC rolling average                                                  3.82905
whole experiment quantile 90.0% VOC rolling average                                                                  2.1582
whole experiment quantile 99.0% VOC rolling average                                                                 3.80063
x axis                                                                                                                 -2.5
y axis                                                                                                                  2.5
position of Id=0:BME680:breathVocEquivalent-x axis                                                                    -1.85
position of Id=0:BME680:breathVocEquivalent-y axis                                                                      3.5
position of Id=1:BME680:breathVocEquivalent-x axis                                                                     -0.5
position of Id=1:BME680:breathVocEquivalent-y axis                                                                      1.7
position of Id=2:BME680:breathVocEquivalent-x axis                                                                    -2.25
position of Id=2:BME680:breathVocEquivalent-y axis                                                                      0.4
Euclidian distance to Id=0:BME680:breathVocEquivalent                                                              1.192686
Euclidian distance to Id=1:BME680:breathVocEquivalent                                                              2.154066
Euclidian distance to Id=2:BME680:breathVocEquivalent                                                              2.114829
Name: 157, dtype: object

from matplotlib.ticker import FuncFormatter

def createTheTitleForTheFigure(experiment_number):
    date = userInputData.iloc[experiment_number]["timestamp InsertingSource"].date()
    row  = userInputData.iloc[experiment_number]
    if ((experiment_number > 0 )):
        previous_date = userInputData.iloc[experiment_number - 1]["timestamp InsertingSource"].date()
        if (date != previous_date):
            print("........................................................\n\n")
    
    title = "Experiment at row " + str(experiment_number)+ "At "+date.strftime("%Y-%m-%d")+ f" BME680:breathVocEquivalent.\n"
    if (userInputData.iloc[experiment_number]["experimentState"] == "InsertingSourcePollutant"):
        title= title + "at the pollution source position to be "
        if (pd.isna(userInputData.iloc[experiment_number]['front-wall'])==False):
           title =title + f"{userInputData.iloc[experiment_number]['front-wall']} meters from the front wall, "
        if (pd.isna(userInputData.iloc[experiment_number]['back-wall'])==False):
           title =title +f"{userInputData.iloc[experiment_number]['back-wall']} meters from the back wall, "
        if (pd.isna(userInputData.iloc[experiment_number]['side-right-wall'])==False):
           title =title+ f"{userInputData.iloc[experiment_number]['side-right-wall']} meters from the side right wall, "
        if (pd.isna(userInputData.iloc[experiment_number]['side-left-wall'])==False):
           title =title+ f"{userInputData.iloc[experiment_number]['side-left-wall']} meters from the side left wall, "
    elif (userInputData.iloc[experiment_number]["experimentState"] == "NoSourcePollutantInserted"):  
        title =title + "without source insertion.\n"
        
        
    
    title =title +"at the room:"+userInputData.iloc[experiment_number]["room"]+"\n"   
    title=title +"Στοιχεία για το μενωμένο πείραμα:"
    title= title+"Αντικείμενο που χρησιμοποιείται¨"+row["item-used"]+", "
    if (pd.isna(row["are-doors-opened"]) == False):
        title = title + "Οι πόρτες είναι ανοιχτές, "
    if (pd.isna(row["are-fans-on"]) == False):
        title = title + "Οι ανεμιστήρες είναι ενεργοποιημένοι, "
    if (pd.isna(row["are-people-inside"]) == False):
        title = title + "Βρίσκονται άνθρωποι μέσα, "
    if (pd.isna(row["are-windows-opened"]) == False):
        title = title + "Τα παράθυρα είναι ανοιχτά, "
    if (pd.isna(row["notes"])== False):
        title= title + "Σημειώσεις:"+ row["notes"]

    return title

def printData(dict_of_timeseries,plot_old_data = True):
    for experiment_number in dict_of_timeseries:
        particular_experiment =  dict_of_timeseries[experiment_number]
        
        title = createTheTitleForTheFigure(experiment_number)
            
       
        plt.figure(figsize=(18, 8))
        if plot_old_data:
            y_column_data = "VOC"
        else:
            y_column_data = "cutted_VOC"
            
        sns.lineplot(data=particular_experiment, x="seconds", y=y_column_data, hue="sensors")
        def format_seconds(x, _):
            return str(pd.to_timedelta(x, unit="s")).split()[-1]  # hh:mm:ss only
        plt.gca().xaxis.set_major_formatter(FuncFormatter(format_seconds))
        plt.xticks(rotation=45)
        
        plt.axvline(x=userInputData.at[experiment_number,"timestamp InsertingSource seconds"], color="red", linestyle="--", linewidth=2, label="timestamp of the inserting source")
        plt.title(title)
    
        plt.show()
    
        print("\n")

In [201]:
#printData(dict_of_timeseries,plot_old_data = True)

In [202]:
userInputData

,experimentState,are-doors-opened,are-people-inside,are-windows-opened,front-wall,item-used,notes,room,side-right-wall,back-wall,side-left-wall,are-fans-on,no-source-located,timestamp InsertingSource,timestamp StartingExperiment,timestamp EndingExperiment,date of experiment,actual timestamp StartingExperiment,actual timestamp EndingExperiment,time taken total,timestamp InsertingSource timedelta,timestamp InsertingSource seconds,time taken after insertion,time taken before insertion,time taken before insertion (seconds),time taken after insertion (seconds),time taken total (seconds),time taken total (seconds)-capped,time taken before insertion (seconds)-capped,time taken after insertion (seconds)-capped,Id=1:BME680:breathVocEquivalent MAX value VOC rolling average,Id=1:BME680:breathVocEquivalent index of MAX value VOC rolling average,Id=2:BME680:breathVocEquivalent MAX value VOC rolling average,Id=2:BME680:breathVocEquivalent index of MAX value VOC rolling average,Id=0:BME680:breathVocEquivalent MAX value VOC rolling average,Id=0:BME680:breathVocEquivalent index of MAX value VOC rolling average,sensor with MAX value experiment,sensor with second MAX value experiment,Id=1:BME680:breathVocEquivalent quantile 90.0% VOC rolling average,Id=1:BME680:breathVocEquivalent quantile 99.0% VOC rolling average,Id=2:BME680:breathVocEquivalent quantile 90.0% VOC rolling average,Id=2:BME680:breathVocEquivalent quantile 99.0% VOC rolling average,Id=0:BME680:breathVocEquivalent quantile 90.0% VOC rolling average,Id=0:BME680:breathVocEquivalent quantile 99.0% VOC rolling average,whole experiment quantile 90.0% VOC rolling average,whole experiment quantile 99.0% VOC rolling average,x axis,y axis,position of Id=0:BME680:breathVocEquivalent-x axis,position of Id=0:BME680:breathVocEquivalent-y axis,position of Id=1:BME680:breathVocEquivalent-x axis,position of Id=1:BME680:breathVocEquivalent-y axis,position of Id=2:BME680:breathVocEquivalent-x axis,position of Id=2:BME680:breathVocEquivalent-y axis,Euclidian distance to Id=0:BME680:breathVocEquivalent,Euclidian distance to Id=1:BME680:breathVocEquivalent,Euclidian distance to Id=2:BME680:breathVocEquivalent
0,InsertingSourcePollutant,on,None,None,1.0,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.0,None,None,2025-07-01 16:09:41,2025-07-01 15:27:16,2025-07-01 16:14:44,2025-07-01,2025-07-01 15:27:19,2025-07-01 16:14:42,0 days 00:47:23,0 days 00:42:23,2543.0,0 days 00:05:00,0 days 00:42:23,2543.0,300.0,2843.0,242.0,-59.0,300.0,3.063,299.0,3.322,242.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,2.8016,3.05823,3.2545,3.32041,NaN,NaN,3.1453,3.31500,-2.25,3.0,NaN,NaN,2.4,3.05,1.70,3.05,NaN,4.650269,3.950316
1,InsertingSourcePollutant,on,None,None,1.0,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.0,None,None,2025-07-02 15:59:29,2025-07-02 15:42:50,2025-07-02 16:04:52,2025-07-02,2025-07-02 15:42:50,2025-07-02 16:04:50,0 days 00:22:00,0 days 00:16:40,1000.0,0 days 00:05:20,0 days 00:16:40,1000.0,320.0,1320.0,242.0,-59.0,300.0,1.083,201.0,0.307,78.0,NaN,NaN,Id=1:BME680:breathVocEquivalent MAX value VOC ...,Id=2:BME680:breathVocEquivalent MAX value VOC ...,0.8909,1.08023,0.2811,0.30700,NaN,NaN,0.6645,1.07224,-2.25,3.0,NaN,NaN,2.4,3.05,1.70,3.05,NaN,4.650269,3.950316
2,InsertingSourcePollutant,on,None,None,0.4,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.0,None,None,2025-07-03 12:34:32,2025-07-03 12:30:25,2025-07-03 12:45:31,2025-07-03,2025-07-03 12:30:25,2025-07-03 12:45:31,0 days 00:15:06,0 days 00:04:08,248.0,0 days 00:10:58,0 days 00:04:08,248.0,658.0,906.0,242.0,-59.0,300.0,1.372,235.0,2.294,300.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,1.3124,1.37000,1.5840,2.16494,NaN,NaN,1.3710,2.04492,-2.25,3.6,NaN,NaN,2.4,3.05,1.70,3.05,NaN,4.682414,3.988107
3,InsertingSourcePollutant,on,None,None,1.0,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.8,None,None,2025-07-03 15:53:07,2025-07-03 15:43:27,2025-07-03 15:59:11,2025-07-03,2025-07-03 15:51:40,2025-07-03 15:59:10,0 days 00:07:30,0 days 00:01:28,88.0,0 days 00:06:02,0 days 00:01:28,88.0,362.0,450.0,242.0,-59.0,300.0,0.332,300.0,18.486,300.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.2483,0.32182,15.5041,17.63282,NaN,NaN,5.3774,17.06834,-1.45,3.0,NaN,NaN,2.4,3.05,1.70,3.05,NaN,3.850325,3.150397
4,InsertingSourcePollutant,on,None,None,1.4,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.4,None,None,2025-07-09 19:19:19,2025-07-09 19:01:42,2025-07-09 19:27:50,2025-07-09,2025-07-09 19:01:44,2025-07-09 19:27:49,0 days 00:26:05,0 days 00:17:36,1056.0,0 days 00:08:29,0 days 00:17:36,1056.0,509.0,1565.0,242.0,-59.0,300.0,0.600,245.0,0.512,300.0,NaN,NaN,Id=1:BME680:breathVocEquivalent MAX value VOC ...,Id=2:BME680:breathVocEquivalent MAX value VOC ...,0.5762,0.60000,0.4803,0.50641,NaN,NaN,0.5321,0.59881,-1.85,2.6,NaN,NaN,2.4,3.05,1.70,3.05,NaN,4.273757,3.578407
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
254,InsertingSourcePollutant,None,None,None,0.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",0.5,NaN,NaN,None,None,2025-10-24 20:32:03,2025-10-24 20:29:36,2025-10-24 20:37:33,2025-10-24,2025-10-24 20:29:37,2025-10-24 20:37:31,0 days 00:07:54,0 days 00:02:27,147.0,0 days 00:05:27,0 days 00:02:27,147.0,327.0,474.0,242.0,-59.0,300.0,1.748,131.0,4.850,300.0,1.947,285.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=0:BME680:breathVocEquivalent MAX value VOC ...,1.5612,1.74482,4.4074,4.80156,1.8771,1.94441,3.5261,4.69152,-0.50,3.5,-1.85,3.5,-0.5,1.70,-2.25,0.40,1.350000,1.800000,3.559846
255,InsertingSourcePollutant,None,None,None,0.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:05:46,2025-10-24 21:03:22,2025-10-24 21:11:21,2025-10-24,2025-10-24 21:03:24,2025-10-24 21:11:19,0 days 00:07:55,0 days 00:02:23,143.0,0 days 00:05:32,0 days 00:02:23,143.0,332.0,475.0,242.0,-59.0,300.0,1.057,300.0,5.182,300.0,2.413,236.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=0:BME680:breathVocEquivalent MAX value VOC ...,1.0160,1.05441,3.5239,5.03822,2.3453,2.40941,2.3893,4.71445,-2.95,3.5,-1.85,3.5,-0.5,1.70,-2.25,0.40,1.100000,3.040148,3.178050
256,InsertingSourcePollutant,None,None,None,1.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:18:43,2025-10-24 21:17:10,2025-10-24 21:24:48,2025-10-24,2025-10-24 21:17:12,2025-10-24 21:24:46,0 days 00:07:34,0 days 00:01:32,92.0,0 days 00:06:02,0 days 00:01:32,92.0,362.0,454.0,242.0,-59.0,300.0,1.948,300.0,12.093,277.0,1.837,140.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,1.1753,1.87102,11.9171,12.08182,1.7081,1.83641,8.0527,12.03042,-2.95,2.5,-1.85,3.5,-0.5,1.70,-2.25,0.40,1.486607,2.577305,2.213594
257,InsertingSourcePollutant,None,None,None,2.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:34:58,2025-10-24 21:33:44,2025-10-24 21:41:06,2025-10-24,2025-10-24 21:33:46,2025-10-24 21:41:04,0 days 00:07:18,0 days 00:01:13,73.0,0 days 00:06:05,0 days 00:01:13,73.0,365.0,438.0,242.0,-59.0,300.0,1.745,300.0,7.490,260.0,1.193,300.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,1.6422,1.71928,7.2742,7.48800,1.1576,1.18782,6.4991,7.44789,-2.95,1.5,-1.85,3.5,-0.5,1.70,-2.25,0.40,2.282542,2.458150,1.303840
258,InsertingSourcePollutant,None,None,None,3.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:54:05,2025-10-24 21:52:16,2025-10-24 22:01:25,2025-10-24,2025-10-24 21:52:18,2025-10-24 22:01:24,0 days 00:09:06,0 days 00:01:48,108.0,0 days 00:07:18,0 days 00:01:48,108.0,438.0,546.0,242.0,-59.0,300.0,1.613,212.0,2.972,287.0,1.935,300.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=0:BME680:breathVocEquivalent MAX value VOC ...,1.5463,1.61141,2.8288,2.97000,1.5596,1.89033,2.3350,2.96242,-2.95,0.5,-1.85,3.5,-0.5,1.70,-2.25,0.40,3.195309,2.728095,0.707107

In [203]:
dict_of_timeseries[12]

,sensors,VOC,after_insertion,original_value,datetime_timestamp,timestamp,seconds,seconds passed from insertionSource,VOC rolling average,original seconds,VOC rolling average-capped,VOC rolling average gradient,VOC rolling average gradient cumsum,VOC rolling average-capped gradient,VOC rolling average-capped gradient cumsum,VOC rolling average standard scaler per sensor,VOC rolling average-capped standard scaler per sensor,VOC rolling average standard scaler whole experiment,VOC rolling average-capped standard scaler whole experiment
seconds,,,,,,,,,,,,,,,,,,,
-59.0,Id=2:BME680:breathVocEquivalent,1.709757,False,True,2025-07-19 17:24:38,0 days 00:18:46,-59.0,-59.0,0.008,1126.0,0.008,0.0000,0.0000,0.0000,0.0000,-0.996509,-0.996509,-1.230674,-1.230674
-59.0,Id=1:BME680:breathVocEquivalent,2.037875,False,True,2025-07-19 17:24:38,0 days 00:18:46,-59.0,-59.0,0.000,1126.0,0.000,0.0020,0.0020,0.0020,0.0020,-2.183510,-2.183510,-1.272317,-1.272317
-58.0,Id=2:BME680:breathVocEquivalent,1.710618,False,True,2025-07-19 17:24:39,0 days 00:18:47,-58.0,-58.0,0.008,1127.0,0.008,0.0005,0.0005,0.0005,0.0005,-0.996509,-0.996509,-1.230674,-1.230674
-58.0,Id=1:BME680:breathVocEquivalent,2.028574,False,True,2025-07-19 17:24:39,0 days 00:18:47,-58.0,-58.0,0.002,1127.0,0.002,0.0015,0.0035,0.0015,0.0035,-2.164713,-2.164713,-1.261907,-1.261907
-57.0,Id=2:BME680:breathVocEquivalent,1.716466,False,True,2025-07-19 17:24:40,0 days 00:18:48,-57.0,-57.0,0.009,1128.0,0.009,0.0010,0.0015,0.0010,0.0015,-0.992499,-0.992499,-1.225469,-1.225469
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298.0,Id=1:BME680:breathVocEquivalent,2.496685,True,True,2025-07-19 17:30:35,0 days 00:24:43,298.0,298.0,0.478,1483.0,0.478,0.0035,0.4810,0.0035,0.4810,2.309034,2.309034,1.215853,1.215853
299.0,Id=2:BME680:breathVocEquivalent,2.649344,True,True,2025-07-19 17:30:36,0 days 00:24:44,299.0,299.0,0.950,1484.0,0.950,0.0135,0.9490,0.0135,0.9490,2.780622,2.780622,3.672792,3.672792
299.0,Id=1:BME680:breathVocEquivalent,2.503186,True,True,2025-07-19 17:30:36,0 days 00:24:44,299.0,299.0,0.482,1484.0,0.482,0.0035,0.4845,0.0035,0.4845,2.346628,2.346628,1.236675,1.236675
300.0,Id=2:BME680:breathVocEquivalent,2.663743,True,True,2025-07-19 17:30:37,0 days 00:24:45,300.0,300.0,0.964,1485.0,0.964,0.0140,0.9630,0.0140,0.9630,2.836757,2.836757,3.745667,3.745667
300.0,Id=1:BME680:breathVocEquivalent,2.509936,True,True,2025-07-19 17:30:37,0 days 00:24:45,300.0,300.0,0.485,1485.0,0.485,0.0030,0.4875,0.0030,0.4875,2.374824,2.374824,1.252291,1.252291

In [204]:
#create a huge dataframe to save it 

# Combine into one DataFrame, keeping the dictionary key
timeSeriesData_BIG = pd.concat(dict_of_timeseries, names=["keys"])

# Reset index so the key becomes a column
timeSeriesData_BIG = timeSeriesData_BIG.reset_index(level="keys").reset_index(drop=True)
timeSeriesData_BIG["seconds"] = timeSeriesData_BIG["seconds"].astype(int)
timeSeriesData_BIG = timeSeriesData_BIG.set_index("seconds",drop=False)

In [205]:
timeSeriesData_BIG

,keys,sensors,VOC,after_insertion,original_value,datetime_timestamp,timestamp,seconds,seconds passed from insertionSource,VOC rolling average,original seconds,VOC rolling average-capped,VOC rolling average gradient,VOC rolling average gradient cumsum,VOC rolling average-capped gradient,VOC rolling average-capped gradient cumsum,VOC rolling average standard scaler per sensor,VOC rolling average-capped standard scaler per sensor,VOC rolling average standard scaler whole experiment,VOC rolling average-capped standard scaler whole experiment
seconds,,,,,,,,,,,,,,,,,,,,
-59,0,Id=1:BME680:breathVocEquivalent,2.123734,False,True,2025-07-01 16:08:43,0 days 00:41:24,-59,-59.0,0.000,2484.0,0.000,0.0020,0.0020,0.0020,0.0020,-1.004635,-1.004635,-1.200893,-1.200893
-59,0,Id=2:BME680:breathVocEquivalent,6.271760,False,True,2025-07-01 16:08:43,0 days 00:41:24,-59,-59.0,0.000,2484.0,0.000,0.0020,0.0020,0.0020,0.0020,-1.524477,-1.524477,-1.200893,-1.200893
-58,0,Id=1:BME680:breathVocEquivalent,2.115316,False,True,2025-07-01 16:08:44,0 days 00:41:25,-58,-58.0,0.002,2485.0,0.002,0.0015,0.0035,0.0015,0.0035,-1.002812,-1.002812,-1.199353,-1.199353
-58,0,Id=2:BME680:breathVocEquivalent,6.271980,False,True,2025-07-01 16:08:44,0 days 00:41:25,-58,-58.0,0.002,2485.0,0.002,0.0025,0.0045,0.0025,0.0045,-1.522965,-1.522965,-1.199353,-1.199353
-57,0,Id=1:BME680:breathVocEquivalent,2.109475,False,True,2025-07-01 16:08:45,0 days 00:41:26,-57,-57.0,0.003,2486.0,0.003,0.0010,0.0045,0.0010,0.0045,-1.001900,-1.001900,-1.198583,-1.198583
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299,258,Id=1:BME680:breathVocEquivalent,2.936916,True,True,2025-10-24 21:59:05,0 days 00:06:47,299,299.0,1.380,407.0,1.380,-0.0050,1.1795,-0.0050,1.1795,1.089929,1.089929,0.415369,0.415369
299,258,Id=2:BME680:breathVocEquivalent,5.531128,True,True,2025-10-24 21:59:05,0 days 00:06:47,299,299.0,2.927,407.0,2.927,-0.0090,2.9275,-0.0090,2.9275,1.437768,1.437768,2.316519,2.316519
300,258,Id=0:BME680:breathVocEquivalent,3.134668,True,True,2025-10-24 21:59:06,0 days 00:06:48,300,300.0,1.935,408.0,1.935,0.0120,1.9430,0.0120,1.9430,2.449701,2.449701,1.097424,1.097424
300,258,Id=1:BME680:breathVocEquivalent,2.923614,True,True,2025-10-24 21:59:06,0 days 00:06:48,300,300.0,1.375,408.0,1.375,-0.0050,1.1745,-0.0050,1.1745,1.081772,1.081772,0.409225,0.409225
300,258,Id=2:BME680:breathVocEquivalent,5.503153,True,True,2025-10-24 21:59:06,0 days 00:06:48,300,300.0,2.918,408.0,2.918,-0.0090,2.9185,-0.0090,2.9185,1.427336,1.427336,2.305459,2.305459

In [206]:
print(timeSeriesData_BIG.loc[timeSeriesData_BIG["keys"] == 157].max())
print(userInputData.loc[157])

keys                                                                                       157
sensors                                                        Id=2:BME680:breathVocEquivalent
VOC                                                                                   5.655352
after_insertion                                                                           True
original_value                                                                            True
datetime_timestamp                                                         2025-10-13 22:32:47
timestamp                                                                      0 days 00:06:35
seconds                                                                                    300
seconds passed from insertionSource                                                      300.0
VOC rolling average                                                                      3.835
original seconds                                                                         395.0
VOC rolling average-capped                                                               3.835
VOC rolling average gradient                                                             0.082
VOC rolling average gradient cumsum                                                     3.8395
VOC rolling average-capped gradient                                                      0.082
VOC rolling average-capped gradient cumsum                                              3.8395
VOC rolling average standard scaler per sensor                                        3.699183
VOC rolling average-capped standard scaler per sensor                                 3.699183
VOC rolling average standard scaler whole experiment                                  3.071127
VOC rolling average-capped standard scaler whole experiment                           3.071127
dtype: object
experimentState                                                                                    InsertingSourcePollutant
are-doors-opened                                                                                                       None
are-people-inside                                                                                                      None
are-windows-opened                                                                                                     None
front-wall                                                                                                              1.5
item-used                                                                                           Φαρμακευτικό αλκοόλ 95%
notes
room                                                                      Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...
side-right-wall                                                                                                         2.5
back-wall                                                                                                               NaN
side-left-wall                                                                                                          NaN
are-fans-on                                                                                                            None
no-source-located                                                                                                      None
timestamp InsertingSource                                                                               2025-10-13 22:27:46
timestamp StartingExperiment                                                                            2025-10-13 22:26:11
timestamp EndingExperiment                                                                              2025-10-13 22:34:17
date of experiment                                                                                               2025-10-13
actual timestamp StartingExperiment                                                                     2025-10-13 22:26:12
actual timestamp EndingExperiment                                                                       2025-10-13 22:34:15
time taken total                                                                                            0 days 00:08:03
timestamp InsertingSource timedelta                                                                         0 days 00:01:35
timestamp InsertingSource seconds                                                                                      95.0
time taken after insertion                                                                                  0 days 00:06:28
time taken before insertion                                                                                 0 days 00:01:35
time taken before insertion (seconds)                                                                                  95.0
time taken after insertion (seconds)                                                                                  388.0
time taken total (seconds)                                                                                            483.0
time taken total (seconds)-capped                                                                                     242.0
time taken before insertion (seconds)-capped                                                                          -59.0
time taken after insertion (seconds)-capped                                                                           300.0
Id=1:BME680:breathVocEquivalent MAX value VOC rolling average                                                         2.334
Id=1:BME680:breathVocEquivalent index of MAX value VOC rolling average                                                300.0
Id=2:BME680:breathVocEquivalent MAX value VOC rolling average                                                         3.673
Id=2:BME680:breathVocEquivalent index of MAX value VOC rolling average                                                300.0
Id=0:BME680:breathVocEquivalent MAX value VOC rolling average                                                         3.835
Id=0:BME680:breathVocEquivalent index of MAX value VOC rolling average                                                295.0
sensor with MAX value experiment                                          Id=0:BME680:breathVocEquivalent MAX value VOC ...
sensor with second MAX value experiment                                   Id=2:BME680:breathVocEquivalent MAX value VOC ...
Id=1:BME680:breathVocEquivalent quantile 90.0% VOC rolling average                                                   2.1283
Id=1:BME680:breathVocEquivalent quantile 99.0% VOC rolling average                                                   2.3041
Id=2:BME680:breathVocEquivalent quantile 90.0% VOC rolling average                                                   1.9567
Id=2:BME680:breathVocEquivalent quantile 99.0% VOC rolling average                                                  3.38616
Id=0:BME680:breathVocEquivalent quantile 90.0% VOC rolling average                                                   2.9553
Id=0:BME680:breathVocEquivalent quantile 99.0% VOC rolling average                                                  3.82905
whole experiment quantile 90.0% VOC rolling average                                                                  2.1582
whole experiment quantile 99.0% VOC rolling average                                                                 3.80063
x axis                                                                                                                 -2.5
y axis                                                                                                                  2.5
position of Id=0:BME680:breathVocEquivalent-x axis                                                                    -1.85
position of Id=0:BME680:breathVocEquivalent-y axis                                                                      3.5
position of Id=1:BME680:breathVocEquivalent-x axis                                                                     -0.5
position of Id=1:BME680:breathVocEquivalent-y axis                                                                      1.7
position of Id=2:BME680:breathVocEquivalent-x axis                                                                    -2.25
position of Id=2:BME680:breathVocEquivalent-y axis                                                                      0.4
Euclidian distance to Id=0:BME680:breathVocEquivalent                                                              1.192686
Euclidian distance to Id=1:BME680:breathVocEquivalent                                                              2.154066
Euclidian distance to Id=2:BME680:breathVocEquivalent                                                              2.114829
Name: 157, dtype: object

In [207]:
userInputData.loc[:,"timestamp InsertingSource timedelta"] = userInputData["timestamp InsertingSource timedelta"].astype("timedelta64[ns]")

In [208]:
userInputData.dtypes

experimentState                                                                    object
are-doors-opened                                                                   object
are-people-inside                                                                  object
are-windows-opened                                                                 object
front-wall                                                                        float64
item-used                                                                          object
notes                                                                              object
room                                                                               object
side-right-wall                                                                   float64
back-wall                                                                         float64
side-left-wall                                                                    float64
are-fans-on                                                                        object
no-source-located                                                                  object
timestamp InsertingSource                                                  datetime64[ns]
timestamp StartingExperiment                                               datetime64[ns]
timestamp EndingExperiment                                                 datetime64[ns]
date of experiment                                                                 object
actual timestamp StartingExperiment                                        datetime64[ns]
actual timestamp EndingExperiment                                          datetime64[ns]
time taken total                                                          timedelta64[ns]
timestamp InsertingSource timedelta                                                object
timestamp InsertingSource seconds                                                 float64
time taken after insertion                                                timedelta64[ns]
time taken before insertion                                               timedelta64[ns]
time taken before insertion (seconds)                                             float64
time taken after insertion (seconds)                                              float64
time taken total (seconds)                                                        float64
time taken total (seconds)-capped                                                 float64
time taken before insertion (seconds)-capped                                      float64
time taken after insertion (seconds)-capped                                       float64
Id=1:BME680:breathVocEquivalent MAX value VOC rolling average                     float64
Id=1:BME680:breathVocEquivalent index of MAX value VOC rolling average            float64
Id=2:BME680:breathVocEquivalent MAX value VOC rolling average                     float64
Id=2:BME680:breathVocEquivalent index of MAX value VOC rolling average            float64
Id=0:BME680:breathVocEquivalent MAX value VOC rolling average                     float64
Id=0:BME680:breathVocEquivalent index of MAX value VOC rolling average            float64
sensor with MAX value experiment                                                   object
sensor with second MAX value experiment                                            object
Id=1:BME680:breathVocEquivalent quantile 90.0% VOC rolling average                float64
Id=1:BME680:breathVocEquivalent quantile 99.0% VOC rolling average                float64
Id=2:BME680:breathVocEquivalent quantile 90.0% VOC rolling average                float64
Id=2:BME680:breathVocEquivalent quantile 99.0% VOC rolling average                float64
Id=0:BME680:breathVocEquivalent quantile 90.0% VOC rolling average                float64
Id=0:BME680:breathVocEquivalent quantile 99.0% VOC rolling average                float64
whole experiment quantile 90.0% VOC rolling average                               float64
whole experiment quantile 99.0% VOC rolling average                               float64
x axis                                                                            float64
y axis                                                                            float64
position of Id=0:BME680:breathVocEquivalent-x axis                                float64
position of Id=0:BME680:breathVocEquivalent-y axis                                float64
position of Id=1:BME680:breathVocEquivalent-x axis                                float64
position of Id=1:BME680:breathVocEquivalent-y axis                                float64
position of Id=2:BME680:breathVocEquivalent-x axis                                float64
position of Id=2:BME680:breathVocEquivalent-y axis                                float64
Euclidian distance to Id=0:BME680:breathVocEquivalent                             float64
Euclidian distance to Id=1:BME680:breathVocEquivalent                             float64
Euclidian distance to Id=2:BME680:breathVocEquivalent                             float64
dtype: object

In [209]:
userInputData

,experimentState,are-doors-opened,are-people-inside,are-windows-opened,front-wall,item-used,notes,room,side-right-wall,back-wall,side-left-wall,are-fans-on,no-source-located,timestamp InsertingSource,timestamp StartingExperiment,timestamp EndingExperiment,date of experiment,actual timestamp StartingExperiment,actual timestamp EndingExperiment,time taken total,timestamp InsertingSource timedelta,timestamp InsertingSource seconds,time taken after insertion,time taken before insertion,time taken before insertion (seconds),time taken after insertion (seconds),time taken total (seconds),time taken total (seconds)-capped,time taken before insertion (seconds)-capped,time taken after insertion (seconds)-capped,Id=1:BME680:breathVocEquivalent MAX value VOC rolling average,Id=1:BME680:breathVocEquivalent index of MAX value VOC rolling average,Id=2:BME680:breathVocEquivalent MAX value VOC rolling average,Id=2:BME680:breathVocEquivalent index of MAX value VOC rolling average,Id=0:BME680:breathVocEquivalent MAX value VOC rolling average,Id=0:BME680:breathVocEquivalent index of MAX value VOC rolling average,sensor with MAX value experiment,sensor with second MAX value experiment,Id=1:BME680:breathVocEquivalent quantile 90.0% VOC rolling average,Id=1:BME680:breathVocEquivalent quantile 99.0% VOC rolling average,Id=2:BME680:breathVocEquivalent quantile 90.0% VOC rolling average,Id=2:BME680:breathVocEquivalent quantile 99.0% VOC rolling average,Id=0:BME680:breathVocEquivalent quantile 90.0% VOC rolling average,Id=0:BME680:breathVocEquivalent quantile 99.0% VOC rolling average,whole experiment quantile 90.0% VOC rolling average,whole experiment quantile 99.0% VOC rolling average,x axis,y axis,position of Id=0:BME680:breathVocEquivalent-x axis,position of Id=0:BME680:breathVocEquivalent-y axis,position of Id=1:BME680:breathVocEquivalent-x axis,position of Id=1:BME680:breathVocEquivalent-y axis,position of Id=2:BME680:breathVocEquivalent-x axis,position of Id=2:BME680:breathVocEquivalent-y axis,Euclidian distance to Id=0:BME680:breathVocEquivalent,Euclidian distance to Id=1:BME680:breathVocEquivalent,Euclidian distance to Id=2:BME680:breathVocEquivalent
0,InsertingSourcePollutant,on,None,None,1.0,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.0,None,None,2025-07-01 16:09:41,2025-07-01 15:27:16,2025-07-01 16:14:44,2025-07-01,2025-07-01 15:27:19,2025-07-01 16:14:42,0 days 00:47:23,0 days 00:42:23,2543.0,0 days 00:05:00,0 days 00:42:23,2543.0,300.0,2843.0,242.0,-59.0,300.0,3.063,299.0,3.322,242.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,2.8016,3.05823,3.2545,3.32041,NaN,NaN,3.1453,3.31500,-2.25,3.0,NaN,NaN,2.4,3.05,1.70,3.05,NaN,4.650269,3.950316
1,InsertingSourcePollutant,on,None,None,1.0,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.0,None,None,2025-07-02 15:59:29,2025-07-02 15:42:50,2025-07-02 16:04:52,2025-07-02,2025-07-02 15:42:50,2025-07-02 16:04:50,0 days 00:22:00,0 days 00:16:40,1000.0,0 days 00:05:20,0 days 00:16:40,1000.0,320.0,1320.0,242.0,-59.0,300.0,1.083,201.0,0.307,78.0,NaN,NaN,Id=1:BME680:breathVocEquivalent MAX value VOC ...,Id=2:BME680:breathVocEquivalent MAX value VOC ...,0.8909,1.08023,0.2811,0.30700,NaN,NaN,0.6645,1.07224,-2.25,3.0,NaN,NaN,2.4,3.05,1.70,3.05,NaN,4.650269,3.950316
2,InsertingSourcePollutant,on,None,None,0.4,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.0,None,None,2025-07-03 12:34:32,2025-07-03 12:30:25,2025-07-03 12:45:31,2025-07-03,2025-07-03 12:30:25,2025-07-03 12:45:31,0 days 00:15:06,0 days 00:04:08,248.0,0 days 00:10:58,0 days 00:04:08,248.0,658.0,906.0,242.0,-59.0,300.0,1.372,235.0,2.294,300.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,1.3124,1.37000,1.5840,2.16494,NaN,NaN,1.3710,2.04492,-2.25,3.6,NaN,NaN,2.4,3.05,1.70,3.05,NaN,4.682414,3.988107
3,InsertingSourcePollutant,on,None,None,1.0,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.8,None,None,2025-07-03 15:53:07,2025-07-03 15:43:27,2025-07-03 15:59:11,2025-07-03,2025-07-03 15:51:40,2025-07-03 15:59:10,0 days 00:07:30,0 days 00:01:28,88.0,0 days 00:06:02,0 days 00:01:28,88.0,362.0,450.0,242.0,-59.0,300.0,0.332,300.0,18.486,300.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.2483,0.32182,15.5041,17.63282,NaN,NaN,5.3774,17.06834,-1.45,3.0,NaN,NaN,2.4,3.05,1.70,3.05,NaN,3.850325,3.150397
4,InsertingSourcePollutant,on,None,None,1.4,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.4,None,None,2025-07-09 19:19:19,2025-07-09 19:01:42,2025-07-09 19:27:50,2025-07-09,2025-07-09 19:01:44,2025-07-09 19:27:49,0 days 00:26:05,0 days 00:17:36,1056.0,0 days 00:08:29,0 days 00:17:36,1056.0,509.0,1565.0,242.0,-59.0,300.0,0.600,245.0,0.512,300.0,NaN,NaN,Id=1:BME680:breathVocEquivalent MAX value VOC ...,Id=2:BME680:breathVocEquivalent MAX value VOC ...,0.5762,0.60000,0.4803,0.50641,NaN,NaN,0.5321,0.59881,-1.85,2.6,NaN,NaN,2.4,3.05,1.70,3.05,NaN,4.273757,3.578407
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
254,InsertingSourcePollutant,None,None,None,0.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",0.5,NaN,NaN,None,None,2025-10-24 20:32:03,2025-10-24 20:29:36,2025-10-24 20:37:33,2025-10-24,2025-10-24 20:29:37,2025-10-24 20:37:31,0 days 00:07:54,0 days 00:02:27,147.0,0 days 00:05:27,0 days 00:02:27,147.0,327.0,474.0,242.0,-59.0,300.0,1.748,131.0,4.850,300.0,1.947,285.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=0:BME680:breathVocEquivalent MAX value VOC ...,1.5612,1.74482,4.4074,4.80156,1.8771,1.94441,3.5261,4.69152,-0.50,3.5,-1.85,3.5,-0.5,1.70,-2.25,0.40,1.350000,1.800000,3.559846
255,InsertingSourcePollutant,None,None,None,0.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:05:46,2025-10-24 21:03:22,2025-10-24 21:11:21,2025-10-24,2025-10-24 21:03:24,2025-10-24 21:11:19,0 days 00:07:55,0 days 00:02:23,143.0,0 days 00:05:32,0 days 00:02:23,143.0,332.0,475.0,242.0,-59.0,300.0,1.057,300.0,5.182,300.0,2.413,236.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=0:BME680:breathVocEquivalent MAX value VOC ...,1.0160,1.05441,3.5239,5.03822,2.3453,2.40941,2.3893,4.71445,-2.95,3.5,-1.85,3.5,-0.5,1.70,-2.25,0.40,1.100000,3.040148,3.178050
256,InsertingSourcePollutant,None,None,None,1.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:18:43,2025-10-24 21:17:10,2025-10-24 21:24:48,2025-10-24,2025-10-24 21:17:12,2025-10-24 21:24:46,0 days 00:07:34,0 days 00:01:32,92.0,0 days 00:06:02,0 days 00:01:32,92.0,362.0,454.0,242.0,-59.0,300.0,1.948,300.0,12.093,277.0,1.837,140.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,1.1753,1.87102,11.9171,12.08182,1.7081,1.83641,8.0527,12.03042,-2.95,2.5,-1.85,3.5,-0.5,1.70,-2.25,0.40,1.486607,2.577305,2.213594
257,InsertingSourcePollutant,None,None,None,2.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:34:58,2025-10-24 21:33:44,2025-10-24 21:41:06,2025-10-24,2025-10-24 21:33:46,2025-10-24 21:41:04,0 days 00:07:18,0 days 00:01:13,73.0,0 days 00:06:05,0 days 00:01:13,73.0,365.0,438.0,242.0,-59.0,300.0,1.745,300.0,7.490,260.0,1.193,300.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,1.6422,1.71928,7.2742,7.48800,1.1576,1.18782,6.4991,7.44789,-2.95,1.5,-1.85,3.5,-0.5,1.70,-2.25,0.40,2.282542,2.458150,1.303840
258,InsertingSourcePollutant,None,None,None,3.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:54:05,2025-10-24 21:52:16,2025-10-24 22:01:25,2025-10-24,2025-10-24 21:52:18,2025-10-24 22:01:24,0 days 00:09:06,0 days 00:01:48,108.0,0 days 00:07:18,0 days 00:01:48,108.0,438.0,546.0,242.0,-59.0,300.0,1.613,212.0,2.972,287.0,1.935,300.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=0:BME680:breathVocEquivalent MAX value VOC ...,1.5463,1.61141,2.8288,2.97000,1.5596,1.89033,2.3350,2.96242,-2.95,0.5,-1.85,3.5,-0.5,1.70,-2.25,0.40,3.195309,2.728095,0.707107

def find_column_values_passed_by_function(timeSeriesData_BIG,userInputData,column,callback_function):
    sensors = timeSeriesData_BIG["sensors"].unique()
    #create columns first if they don't exist for the UserInputDAta
    for sensor in sensors:
        
        col_name_before = f"{sensor} before insertion {str(callback_function.__name__)} {column}"
        
        if col_name_before not in userInputData.columns:
            userInputData.loc[:,col_name_before] = np.nan
            
        col_name_after = f"{sensor} after insertion {str(callback_function.__name__)} {column}" 
    
        if col_name_after not in userInputData.columns:
            userInputData.loc[:,col_name_before] = np.nan
            
        callback_function_before_insertion ={}
        callback_function_after_insertion = {}
            # Define masks
        mask_before = timeSeriesData_BIG["seconds passed from insertionSource"] < 0
        mask_after = ~mask_before
    
       # ---- Before insertion ----
        series_before = (
            timeSeriesData_BIG[mask_before & (timeSeriesData_BIG["sensors"] == sensor)]
            .groupby("keys")[column].apply(lambda x:callback_function(x))
        )
        # ---- After insertion ----
        series_after = (
            timeSeriesData_BIG[mask_after & (timeSeriesData_BIG["sensors"] == sensor)]
            .groupby("keys")[column].apply(lambda x:callback_function(x))
        )
        userInputData.loc[:,col_name_before] = series_before
        userInputData.loc[:,col_name_after] = series_after


    return userInputData

def find_diff_between_two_columns_created_values(timeSeriesData_BIG,userInputData,column,callback_function_one,callback_function_second):
    sensors = timeSeriesData_BIG["sensors"].unique()
    for sensor in sensors:
        
        col_name_before = [f"{sensor} before insertion {str(callback_function_one.__name__)} {column}", f"{sensor} before insertion {str(callback_function_second.__name__)} {column}"]
        col_name_after = [f"{sensor} after insertion {str(callback_function_one.__name__)} {column}",f"{sensor} after insertion {str(callback_function_second.__name__)} {column}" ]
        col_name_before_diff = f"{sensor} before insertion diff between {str(callback_function_one.__name__)} and {str(callback_function_second.__name__)} {column}"
        col_name_after_diff = f"{sensor} before insertion diff between {str(callback_function_one.__name__)} and {str(callback_function_second.__name__)} {column}"
        userInputData.loc[:,col_name_before_diff] = userInputData[col_name_before[1]] - userInputData[col_name_before[0]]
        userInputData.loc[:,col_name_after_diff] = userInputData[col_name_after[1]] - userInputData[col_name_after[0]]
    return userInputData

columns = ["VOC","VOC rolling average"]
callback_function = [np.mean,np.median]
for column in columns:
    userInputData = find_column_values_passed_by_function(timeSeriesData_BIG,userInputData,column,callback_function[0])
    userInputData = find_column_values_passed_by_function(timeSeriesData_BIG,userInputData,column,callback_function[1])
    userInputData = find_diff_between_two_columns_created_values(timeSeriesData_BIG,userInputData,column,callback_function[0],callback_function[1])

In [210]:
userInputData

,experimentState,are-doors-opened,are-people-inside,are-windows-opened,front-wall,item-used,notes,room,side-right-wall,back-wall,side-left-wall,are-fans-on,no-source-located,timestamp InsertingSource,timestamp StartingExperiment,timestamp EndingExperiment,date of experiment,actual timestamp StartingExperiment,actual timestamp EndingExperiment,time taken total,timestamp InsertingSource timedelta,timestamp InsertingSource seconds,time taken after insertion,time taken before insertion,time taken before insertion (seconds),time taken after insertion (seconds),time taken total (seconds),time taken total (seconds)-capped,time taken before insertion (seconds)-capped,time taken after insertion (seconds)-capped,Id=1:BME680:breathVocEquivalent MAX value VOC rolling average,Id=1:BME680:breathVocEquivalent index of MAX value VOC rolling average,Id=2:BME680:breathVocEquivalent MAX value VOC rolling average,Id=2:BME680:breathVocEquivalent index of MAX value VOC rolling average,Id=0:BME680:breathVocEquivalent MAX value VOC rolling average,Id=0:BME680:breathVocEquivalent index of MAX value VOC rolling average,sensor with MAX value experiment,sensor with second MAX value experiment,Id=1:BME680:breathVocEquivalent quantile 90.0% VOC rolling average,Id=1:BME680:breathVocEquivalent quantile 99.0% VOC rolling average,Id=2:BME680:breathVocEquivalent quantile 90.0% VOC rolling average,Id=2:BME680:breathVocEquivalent quantile 99.0% VOC rolling average,Id=0:BME680:breathVocEquivalent quantile 90.0% VOC rolling average,Id=0:BME680:breathVocEquivalent quantile 99.0% VOC rolling average,whole experiment quantile 90.0% VOC rolling average,whole experiment quantile 99.0% VOC rolling average,x axis,y axis,position of Id=0:BME680:breathVocEquivalent-x axis,position of Id=0:BME680:breathVocEquivalent-y axis,position of Id=1:BME680:breathVocEquivalent-x axis,position of Id=1:BME680:breathVocEquivalent-y axis,position of Id=2:BME680:breathVocEquivalent-x axis,position of Id=2:BME680:breathVocEquivalent-y axis,Euclidian distance to Id=0:BME680:breathVocEquivalent,Euclidian distance to Id=1:BME680:breathVocEquivalent,Euclidian distance to Id=2:BME680:breathVocEquivalent
0,InsertingSourcePollutant,on,None,None,1.0,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.0,None,None,2025-07-01 16:09:41,2025-07-01 15:27:16,2025-07-01 16:14:44,2025-07-01,2025-07-01 15:27:19,2025-07-01 16:14:42,0 days 00:47:23,0 days 00:42:23,2543.0,0 days 00:05:00,0 days 00:42:23,2543.0,300.0,2843.0,242.0,-59.0,300.0,3.063,299.0,3.322,242.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,2.8016,3.05823,3.2545,3.32041,NaN,NaN,3.1453,3.31500,-2.25,3.0,NaN,NaN,2.4,3.05,1.70,3.05,NaN,4.650269,3.950316
1,InsertingSourcePollutant,on,None,None,1.0,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.0,None,None,2025-07-02 15:59:29,2025-07-02 15:42:50,2025-07-02 16:04:52,2025-07-02,2025-07-02 15:42:50,2025-07-02 16:04:50,0 days 00:22:00,0 days 00:16:40,1000.0,0 days 00:05:20,0 days 00:16:40,1000.0,320.0,1320.0,242.0,-59.0,300.0,1.083,201.0,0.307,78.0,NaN,NaN,Id=1:BME680:breathVocEquivalent MAX value VOC ...,Id=2:BME680:breathVocEquivalent MAX value VOC ...,0.8909,1.08023,0.2811,0.30700,NaN,NaN,0.6645,1.07224,-2.25,3.0,NaN,NaN,2.4,3.05,1.70,3.05,NaN,4.650269,3.950316
2,InsertingSourcePollutant,on,None,None,0.4,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.0,None,None,2025-07-03 12:34:32,2025-07-03 12:30:25,2025-07-03 12:45:31,2025-07-03,2025-07-03 12:30:25,2025-07-03 12:45:31,0 days 00:15:06,0 days 00:04:08,248.0,0 days 00:10:58,0 days 00:04:08,248.0,658.0,906.0,242.0,-59.0,300.0,1.372,235.0,2.294,300.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,1.3124,1.37000,1.5840,2.16494,NaN,NaN,1.3710,2.04492,-2.25,3.6,NaN,NaN,2.4,3.05,1.70,3.05,NaN,4.682414,3.988107
3,InsertingSourcePollutant,on,None,None,1.0,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.8,None,None,2025-07-03 15:53:07,2025-07-03 15:43:27,2025-07-03 15:59:11,2025-07-03,2025-07-03 15:51:40,2025-07-03 15:59:10,0 days 00:07:30,0 days 00:01:28,88.0,0 days 00:06:02,0 days 00:01:28,88.0,362.0,450.0,242.0,-59.0,300.0,0.332,300.0,18.486,300.0,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.2483,0.32182,15.5041,17.63282,NaN,NaN,5.3774,17.06834,-1.45,3.0,NaN,NaN,2.4,3.05,1.70,3.05,NaN,3.850325,3.150397
4,InsertingSourcePollutant,on,None,None,1.4,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.4,None,None,2025-07-09 19:19:19,2025-07-09 19:01:42,2025-07-09 19:27:50,2025-07-09,2025-07-09 19:01:44,2025-07-09 19:27:49,0 days 00:26:05,0 days 00:17:36,1056.0,0 days 00:08:29,0 days 00:17:36,1056.0,509.0,1565.0,242.0,-59.0,300.0,0.600,245.0,0.512,300.0,NaN,NaN,Id=1:BME680:breathVocEquivalent MAX value VOC ...,Id=2:BME680:breathVocEquivalent MAX value VOC ...,0.5762,0.60000,0.4803,0.50641,NaN,NaN,0.5321,0.59881,-1.85,2.6,NaN,NaN,2.4,3.05,1.70,3.05,NaN,4.273757,3.578407
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
254,InsertingSourcePollutant,None,None,None,0.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",0.5,NaN,NaN,None,None,2025-10-24 20:32:03,2025-10-24 20:29:36,2025-10-24 20:37:33,2025-10-24,2025-10-24 20:29:37,2025-10-24 20:37:31,0 days 00:07:54,0 days 00:02:27,147.0,0 days 00:05:27,0 days 00:02:27,147.0,327.0,474.0,242.0,-59.0,300.0,1.748,131.0,4.850,300.0,1.947,285.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=0:BME680:breathVocEquivalent MAX value VOC ...,1.5612,1.74482,4.4074,4.80156,1.8771,1.94441,3.5261,4.69152,-0.50,3.5,-1.85,3.5,-0.5,1.70,-2.25,0.40,1.350000,1.800000,3.559846
255,InsertingSourcePollutant,None,None,None,0.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:05:46,2025-10-24 21:03:22,2025-10-24 21:11:21,2025-10-24,2025-10-24 21:03:24,2025-10-24 21:11:19,0 days 00:07:55,0 days 00:02:23,143.0,0 days 00:05:32,0 days 00:02:23,143.0,332.0,475.0,242.0,-59.0,300.0,1.057,300.0,5.182,300.0,2.413,236.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=0:BME680:breathVocEquivalent MAX value VOC ...,1.0160,1.05441,3.5239,5.03822,2.3453,2.40941,2.3893,4.71445,-2.95,3.5,-1.85,3.5,-0.5,1.70,-2.25,0.40,1.100000,3.040148,3.178050
256,InsertingSourcePollutant,None,None,None,1.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:18:43,2025-10-24 21:17:10,2025-10-24 21:24:48,2025-10-24,2025-10-24 21:17:12,2025-10-24 21:24:46,0 days 00:07:34,0 days 00:01:32,92.0,0 days 00:06:02,0 days 00:01:32,92.0,362.0,454.0,242.0,-59.0,300.0,1.948,300.0,12.093,277.0,1.837,140.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,1.1753,1.87102,11.9171,12.08182,1.7081,1.83641,8.0527,12.03042,-2.95,2.5,-1.85,3.5,-0.5,1.70,-2.25,0.40,1.486607,2.577305,2.213594
257,InsertingSourcePollutant,None,None,None,2.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:34:58,2025-10-24 21:33:44,2025-10-24 21:41:06,2025-10-24,2025-10-24 21:33:46,2025-10-24 21:41:04,0 days 00:07:18,0 days 00:01:13,73.0,0 days 00:06:05,0 days 00:01:13,73.0,365.0,438.0,242.0,-59.0,300.0,1.745,300.0,7.490,260.0,1.193,300.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,1.6422,1.71928,7.2742,7.48800,1.1576,1.18782,6.4991,7.44789,-2.95,1.5,-1.85,3.5,-0.5,1.70,-2.25,0.40,2.282542,2.458150,1.303840
258,InsertingSourcePollutant,None,None,None,3.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:54:05,2025-10-24 21:52:16,2025-10-24 22:01:25,2025-10-24,2025-10-24 21:52:18,2025-10-24 22:01:24,0 days 00:09:06,0 days 00:01:48,108.0,0 days 00:07:18,0 days 00:01:48,108.0,438.0,546.0,242.0,-59.0,300.0,1.613,212.0,2.972,287.0,1.935,300.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=0:BME680:breathVocEquivalent MAX value VOC ...,1.5463,1.61141,2.8288,2.97000,1.5596,1.89033,2.3350,2.96242,-2.95,0.5,-1.85,3.5,-0.5,1.70,-2.25,0.40,3.195309,2.728095,0.707107

In [211]:
userInputData.columns

Index(['experimentState', 'are-doors-opened', 'are-people-inside',
       'are-windows-opened', 'front-wall', 'item-used', 'notes', 'room',
       'side-right-wall', 'back-wall', 'side-left-wall', 'are-fans-on',
       'no-source-located', 'timestamp InsertingSource',
       'timestamp StartingExperiment', 'timestamp EndingExperiment',
       'date of experiment', 'actual timestamp StartingExperiment',
       'actual timestamp EndingExperiment', 'time taken total',
       'timestamp InsertingSource timedelta',
       'timestamp InsertingSource seconds', 'time taken after insertion',
       'time taken before insertion', 'time taken before insertion (seconds)',
       'time taken after insertion (seconds)', 'time taken total (seconds)',
       'time taken total (seconds)-capped',
       'time taken before insertion (seconds)-capped',
       'time taken after insertion (seconds)-capped',
       'Id=1:BME680:breathVocEquivalent MAX value VOC rolling average',
       'Id=1:BME680:breathVocEquivalent index of MAX value VOC rolling average',
       'Id=2:BME680:breathVocEquivalent MAX value VOC rolling average',
       'Id=2:BME680:breathVocEquivalent index of MAX value VOC rolling average',
       'Id=0:BME680:breathVocEquivalent MAX value VOC rolling average',
       'Id=0:BME680:breathVocEquivalent index of MAX value VOC rolling average',
       'sensor with MAX value experiment',
       'sensor with second MAX value experiment',
       'Id=1:BME680:breathVocEquivalent quantile 90.0% VOC rolling average',
       'Id=1:BME680:breathVocEquivalent quantile 99.0% VOC rolling average',
       'Id=2:BME680:breathVocEquivalent quantile 90.0% VOC rolling average',
       'Id=2:BME680:breathVocEquivalent quantile 99.0% VOC rolling average',
       'Id=0:BME680:breathVocEquivalent quantile 90.0% VOC rolling average',
       'Id=0:BME680:breathVocEquivalent quantile 99.0% VOC rolling average',
       'whole experiment quantile 90.0% VOC rolling average',
       'whole experiment quantile 99.0% VOC rolling average', 'x axis',
       'y axis', 'position of Id=0:BME680:breathVocEquivalent-x axis',
       'position of Id=0:BME680:breathVocEquivalent-y axis',
       'position of Id=1:BME680:breathVocEquivalent-x axis',
       'position of Id=1:BME680:breathVocEquivalent-y axis',
       'position of Id=2:BME680:breathVocEquivalent-x axis',
       'position of Id=2:BME680:breathVocEquivalent-y axis',
       'Euclidian distance to Id=0:BME680:breathVocEquivalent',
       'Euclidian distance to Id=1:BME680:breathVocEquivalent',
       'Euclidian distance to Id=2:BME680:breathVocEquivalent'],
      dtype='object')

In [212]:
timeSeriesData_BIG

,keys,sensors,VOC,after_insertion,original_value,datetime_timestamp,timestamp,seconds,seconds passed from insertionSource,VOC rolling average,original seconds,VOC rolling average-capped,VOC rolling average gradient,VOC rolling average gradient cumsum,VOC rolling average-capped gradient,VOC rolling average-capped gradient cumsum,VOC rolling average standard scaler per sensor,VOC rolling average-capped standard scaler per sensor,VOC rolling average standard scaler whole experiment,VOC rolling average-capped standard scaler whole experiment
seconds,,,,,,,,,,,,,,,,,,,,
-59,0,Id=1:BME680:breathVocEquivalent,2.123734,False,True,2025-07-01 16:08:43,0 days 00:41:24,-59,-59.0,0.000,2484.0,0.000,0.0020,0.0020,0.0020,0.0020,-1.004635,-1.004635,-1.200893,-1.200893
-59,0,Id=2:BME680:breathVocEquivalent,6.271760,False,True,2025-07-01 16:08:43,0 days 00:41:24,-59,-59.0,0.000,2484.0,0.000,0.0020,0.0020,0.0020,0.0020,-1.524477,-1.524477,-1.200893,-1.200893
-58,0,Id=1:BME680:breathVocEquivalent,2.115316,False,True,2025-07-01 16:08:44,0 days 00:41:25,-58,-58.0,0.002,2485.0,0.002,0.0015,0.0035,0.0015,0.0035,-1.002812,-1.002812,-1.199353,-1.199353
-58,0,Id=2:BME680:breathVocEquivalent,6.271980,False,True,2025-07-01 16:08:44,0 days 00:41:25,-58,-58.0,0.002,2485.0,0.002,0.0025,0.0045,0.0025,0.0045,-1.522965,-1.522965,-1.199353,-1.199353
-57,0,Id=1:BME680:breathVocEquivalent,2.109475,False,True,2025-07-01 16:08:45,0 days 00:41:26,-57,-57.0,0.003,2486.0,0.003,0.0010,0.0045,0.0010,0.0045,-1.001900,-1.001900,-1.198583,-1.198583
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299,258,Id=1:BME680:breathVocEquivalent,2.936916,True,True,2025-10-24 21:59:05,0 days 00:06:47,299,299.0,1.380,407.0,1.380,-0.0050,1.1795,-0.0050,1.1795,1.089929,1.089929,0.415369,0.415369
299,258,Id=2:BME680:breathVocEquivalent,5.531128,True,True,2025-10-24 21:59:05,0 days 00:06:47,299,299.0,2.927,407.0,2.927,-0.0090,2.9275,-0.0090,2.9275,1.437768,1.437768,2.316519,2.316519
300,258,Id=0:BME680:breathVocEquivalent,3.134668,True,True,2025-10-24 21:59:06,0 days 00:06:48,300,300.0,1.935,408.0,1.935,0.0120,1.9430,0.0120,1.9430,2.449701,2.449701,1.097424,1.097424
300,258,Id=1:BME680:breathVocEquivalent,2.923614,True,True,2025-10-24 21:59:06,0 days 00:06:48,300,300.0,1.375,408.0,1.375,-0.0050,1.1745,-0.0050,1.1745,1.081772,1.081772,0.409225,0.409225
300,258,Id=2:BME680:breathVocEquivalent,5.503153,True,True,2025-10-24 21:59:06,0 days 00:06:48,300,300.0,2.918,408.0,2.918,-0.0090,2.9185,-0.0090,2.9185,1.427336,1.427336,2.305459,2.305459

In [213]:
def saveDataIntoDataFolder(data,data_file_name):
    script_dir = Path().resolve().parent
    data_folder = script_dir / 'dataAnalysis and machine learning'/'data'
    print(data_folder)
    data_folder.mkdir(exist_ok=True)
    
    file_path = data_folder / (data_file_name + ".json")
    with open(file_path, 'w') as file:
        if isinstance(data, pd.DataFrame):
            print("It's a DataFrame")
            if  data.empty:
                print("No data to save.")
            else:
                data.to_json(file_path, orient='records', lines=False)             
                print(f"Data saved to {file_path}")

        else:  
            print("It's NOT a DataFrame.")    
            if not data:
                print("No data to save.")
            else:    
                json.dump(data, file)
                print(f"Data saved to {file_path}")


saveDataIntoDataFolder(userInputData,"UserPrevious experiments-preprocessed")
saveDataIntoDataFolder(timeSeriesData_BIG,"Data:Previous experiments-preprocessed")

C:\Users\Andreas\Documents\PlatformIO\Projects\Diploma Project\dataAnalysis and machine learning\data
It's a DataFrame
Data saved to C:\Users\Andreas\Documents\PlatformIO\Projects\Diploma Project\dataAnalysis and machine learning\data\UserPrevious experiments-preprocessed.json
C:\Users\Andreas\Documents\PlatformIO\Projects\Diploma Project\dataAnalysis and machine learning\data
It's a DataFrame
Data saved to C:\Users\Andreas\Documents\PlatformIO\Projects\Diploma Project\dataAnalysis and machine learning\data\Data:Previous experiments-preprocessed.json