## PREPARING DATA

In [1]:
#the import packages
import requests
import pandas as pd
from pandas import json_normalize
import requests
import os
from pathlib import Path
from datetime import datetime, timezone,timedelta,time
from scipy import stats
import json
import numpy as np

import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
from matplotlib.ticker import MultipleLocator

In [3]:
pd.set_option("display.max_columns", None)

In [4]:
def loadDataFromFile(file_name):
    script_dir = Path().resolve().parent
    print(script_dir)
    data_folder = script_dir /'data'
    print(data_folder)
    data_folder.mkdir(exist_ok=True)
    
    file_path = data_folder / (file_name + ".json")
    
    if file_path.exists():
        df = pd.read_json(file_path)
        print(f"Loaded {len(df)} records from {file_path}")
        return df
    else:
        print(f"File {file_path} does not exist.")
        return None

In [5]:
userInputDataRaw = loadDataFromFile("UserPrevious experiments-preprocessed")
timeSeriesData_BIGraw = loadDataFromFile("Data:Previous experiments-preprocessed")

C:\Users\Andreas\Documents\PlatformIO\Projects\Diploma Project\dataAnalysis and machine learning
C:\Users\Andreas\Documents\PlatformIO\Projects\Diploma Project\dataAnalysis and machine learning\data
Loaded 257 records from C:\Users\Andreas\Documents\PlatformIO\Projects\Diploma Project\dataAnalysis and machine learning\data\UserPrevious experiments-preprocessed.json
C:\Users\Andreas\Documents\PlatformIO\Projects\Diploma Project\dataAnalysis and machine learning
C:\Users\Andreas\Documents\PlatformIO\Projects\Diploma Project\dataAnalysis and machine learning\data
Loaded 229277 records from C:\Users\Andreas\Documents\PlatformIO\Projects\Diploma Project\dataAnalysis and machine learning\data\Data:Previous experiments-preprocessed.json

In [6]:
timeSeriesData_BIGraw = timeSeriesData_BIGraw.set_index("seconds",drop=False)

In [7]:
a = userInputDataRaw.index
b = timeSeriesData_BIGraw["keys"].unique()
diff_all = list(set(a).symmetric_difference(set(b)))
print(diff_all)  
userInputDataRaw.index = timeSeriesData_BIGraw["keys"].unique()
print(userInputDataRaw.index)

[6, 49, 257, 258]
Index([  0,   1,   2,   3,   4,   5,   7,   8,   9,  10,
       ...
       249, 250, 251, 252, 253, 254, 255, 256, 257, 258],
      dtype='int64', length=257)

In [8]:
# Convert back to timedelta
timeSeriesData_BIGraw['timestamp'] = pd.to_timedelta(timeSeriesData_BIGraw['timestamp'], unit='ms')

# Convert back to datetime

timeSeriesData_BIGraw ["datetime_timestamp"]= timeSeriesData_BIGraw['datetime_timestamp'].transform(
    lambda x: pd.to_datetime(x, unit='ms')
)


columns_datetime= [
       'date of experiment', 'actual timestamp StartingExperiment',
       'actual timestamp EndingExperiment']
columns_timedelta = ['time taken total','time taken before insertion',
       'timestamp InsertingSource timedelta',
       'time taken after insertion']
# Ensure target columns are of object type before assignment
userInputDataRaw[columns_datetime] = userInputDataRaw[columns_datetime].astype('object')
userInputDataRaw[columns_timedelta] = userInputDataRaw[columns_timedelta].astype('object')

userInputDataRaw.loc[:,columns_datetime] = userInputDataRaw.loc[:,columns_datetime].apply(lambda x:pd.to_datetime(x, unit='ms'))
userInputDataRaw.loc[:,columns_timedelta] = userInputDataRaw.loc[:,columns_timedelta].apply(lambda x:pd.to_timedelta(x, unit='ms'))

In [9]:
timeSeriesData_BIG_Original = timeSeriesData_BIGraw.copy()
userInputData_Original = userInputDataRaw.copy()

In [10]:
userInputData_Original

,experimentState,are-doors-opened,are-people-inside,are-windows-opened,front-wall,item-used,notes,room,side-right-wall,back-wall,side-left-wall,are-fans-on,no-source-located,timestamp InsertingSource,timestamp StartingExperiment,timestamp EndingExperiment,date of experiment,actual timestamp StartingExperiment,actual timestamp EndingExperiment,time taken total,timestamp InsertingSource timedelta,timestamp InsertingSource seconds,time taken after insertion,time taken before insertion,time taken before insertion (seconds),time taken after insertion (seconds),time taken total (seconds),time taken total (seconds)-capped,time taken before insertion (seconds)-capped,time taken after insertion (seconds)-capped,Id=1:BME680:breathVocEquivalent MAX value VOC rolling average,Id=1:BME680:breathVocEquivalent index of MAX value VOC rolling average,Id=2:BME680:breathVocEquivalent MAX value VOC rolling average,Id=2:BME680:breathVocEquivalent index of MAX value VOC rolling average,Id=0:BME680:breathVocEquivalent MAX value VOC rolling average,Id=0:BME680:breathVocEquivalent index of MAX value VOC rolling average,sensor with MAX value experiment,sensor with second MAX value experiment,Id=1:BME680:breathVocEquivalent quantile 90.0% VOC rolling average,Id=1:BME680:breathVocEquivalent quantile 99.0% VOC rolling average,Id=2:BME680:breathVocEquivalent quantile 90.0% VOC rolling average,Id=2:BME680:breathVocEquivalent quantile 99.0% VOC rolling average,Id=0:BME680:breathVocEquivalent quantile 90.0% VOC rolling average,Id=0:BME680:breathVocEquivalent quantile 99.0% VOC rolling average,whole experiment quantile 90.0% VOC rolling average,whole experiment quantile 99.0% VOC rolling average,Id=1:BME680:breathVocEquivalent VOC mean calm period,Id=1:BME680:breathVocEquivalent VOC gradient mean calm period,Id=2:BME680:breathVocEquivalent VOC mean calm period,Id=2:BME680:breathVocEquivalent VOC gradient mean calm period,Id=0:BME680:breathVocEquivalent VOC mean calm period,Id=0:BME680:breathVocEquivalent VOC gradient mean calm period,x axis,y axis,x-y axis,position of Id=0:BME680:breathVocEquivalent-x axis,position of Id=0:BME680:breathVocEquivalent-y axis,position of Id=1:BME680:breathVocEquivalent-x axis,position of Id=1:BME680:breathVocEquivalent-y axis,position of Id=2:BME680:breathVocEquivalent-x axis,position of Id=2:BME680:breathVocEquivalent-y axis,position of Id=0:BME680:breathVocEquivalent x-y axis,position of Id=1:BME680:breathVocEquivalent x-y axis,position of Id=2:BME680:breathVocEquivalent x-y axis,Euclidian distance to Id=0:BME680:breathVocEquivalent,Euclidian distance to Id=1:BME680:breathVocEquivalent,Euclidian distance to Id=2:BME680:breathVocEquivalent
0,InsertingSourcePollutant,on,None,None,1.0,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.0,None,None,2025-07-01 16:09:41,2025-07-01 15:27:16,2025-07-01 16:14:44,2025-07-01 00:00:00,2025-07-01 15:27:19,2025-07-01 16:14:42,0 days 00:47:23,0 days 00:42:23,2543,0 days 00:05:00,0 days 00:42:23,2543,300,2843,270,-30,299,4.3501,299.0,8.1928,243,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,4.10260,4.342653,8.13641,8.191397,NaN,NaN,8.03289,8.186653,1.338333,0.000302,5.003467,0.001410,NaN,NaN,-2.25,3.0,"[-2.25, 3.0]",NaN,NaN,2.4,3.05,1.70,3.05,"[None, None]","[2.4, 3.05]","[1.7000000000000002, 3.05]",NaN,4.65,3.95
1,InsertingSourcePollutant,on,None,None,1.0,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.0,None,None,2025-07-02 15:59:29,2025-07-02 15:42:50,2025-07-02 16:04:52,2025-07-02 00:00:00,2025-07-02 15:42:50,2025-07-02 16:04:50,0 days 00:22:00,0 days 00:16:40,1000,0 days 00:05:20,0 days 00:16:40,1000,320,1320,270,-30,299,1.1333,201.0,0.3304,80,NaN,NaN,Id=1:BME680:breathVocEquivalent MAX value VOC ...,Id=2:BME680:breathVocEquivalent MAX value VOC ...,0.96260,1.130830,0.30518,0.330042,NaN,NaN,0.74384,1.123456,0.050000,-0.000188,0.149700,0.002748,NaN,NaN,-2.25,3.0,"[-2.25, 3.0]",NaN,NaN,2.4,3.05,1.70,3.05,"[None, None]","[2.4, 3.05]","[1.7000000000000002, 3.05]",NaN,4.65,3.95
2,InsertingSourcePollutant,on,None,None,0.4,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.0,None,None,2025-07-03 12:34:32,2025-07-03 12:30:25,2025-07-03 12:45:31,2025-07-03 00:00:00,2025-07-03 12:30:25,2025-07-03 12:45:31,0 days 00:15:06,0 days 00:04:08,248,0 days 00:10:58,0 days 00:04:08,248,658,906,270,-30,299,1.3923,235.0,2.2994,299,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,1.34093,1.390726,1.62716,2.182643,NaN,NaN,1.46438,2.073907,0.133633,-0.003248,0.412300,-0.007478,NaN,NaN,-2.25,3.6,"[-2.25, 3.6]",NaN,NaN,2.4,3.05,1.70,3.05,"[None, None]","[2.4, 3.05]","[1.7000000000000002, 3.05]",NaN,4.68,3.99
3,InsertingSourcePollutant,on,None,None,1.0,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.8,None,None,2025-07-03 15:53:07,2025-07-03 15:43:27,2025-07-03 15:59:11,2025-07-03 00:00:00,2025-07-03 15:51:40,2025-07-03 15:59:10,0 days 00:07:30,0 days 00:01:28,88,0 days 00:06:02,0 days 00:01:28,88,362,450,270,-30,299,0.3439,299.0,18.4943,299,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.26763,0.334346,16.09553,17.771554,NaN,NaN,6.84825,17.295804,0.027200,0.000002,0.505133,0.005152,NaN,NaN,-1.45,3.0,"[-1.45, 3.0]",NaN,NaN,2.4,3.05,1.70,3.05,"[None, None]","[2.4, 3.05]","[1.7000000000000002, 3.05]",NaN,3.85,3.15
4,InsertingSourcePollutant,on,None,None,1.4,Φαρμακευτικό αλκοόλ 95%,,Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55,NaN,NaN,1.4,None,None,2025-07-09 19:19:19,2025-07-09 19:01:42,2025-07-09 19:27:50,2025-07-09 00:00:00,2025-07-09 19:01:44,2025-07-09 19:27:49,0 days 00:26:05,0 days 00:17:36,1056,0 days 00:08:29,0 days 00:17:36,1056,509,1565,270,-30,299,0.6066,246.0,0.7315,299,NaN,NaN,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.58644,0.606300,0.70629,0.726681,NaN,NaN,0.62712,0.723846,0.030767,-0.000302,0.343333,-0.000157,NaN,NaN,-1.85,2.6,"[-1.85, 2.6]",NaN,NaN,2.4,3.05,1.70,3.05,"[None, None]","[2.4, 3.05]","[1.7000000000000002, 3.05]",NaN,4.27,3.58
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
254,InsertingSourcePollutant,None,None,None,0.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",0.5,NaN,NaN,None,None,2025-10-24 20:32:03,2025-10-24 20:29:36,2025-10-24 20:37:33,2025-10-24 00:00:00,2025-10-24 20:29:37,2025-10-24 20:37:31,0 days 00:07:54,0 days 00:02:27,147,0 days 00:05:27,0 days 00:02:27,147,327,474,270,-30,299,2.0134,131.0,4.9923,299,2.8096,286.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=0:BME680:breathVocEquivalent MAX value VOC ...,1.85013,2.010252,4.58879,4.944112,2.74257,2.806868,3.70824,4.844487,0.384700,-0.004535,0.790767,0.014290,1.095967,-0.005078,-0.50,3.5,"[-0.5, 3.5]",-1.85,3.5,-0.5,1.70,-2.25,0.40,"[-1.85, 3.5]","[-0.5, 1.7000000000000002]","[-2.25, 0.4]",1.35,1.80,3.56
255,InsertingSourcePollutant,None,None,None,0.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:05:46,2025-10-24 21:03:22,2025-10-24 21:11:21,2025-10-24 00:00:00,2025-10-24 21:03:24,2025-10-24 21:11:19,0 days 00:07:55,0 days 00:02:23,143,0 days 00:05:32,0 days 00:02:23,143,332,475,270,-30,299,1.5436,269.0,6.0745,299,2.4431,236.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=0:BME680:breathVocEquivalent MAX value VOC ...,1.50536,1.541913,4.53166,5.938517,2.38429,2.439926,3.22484,5.639461,0.830100,0.003192,0.938300,0.004927,0.278667,0.009215,-2.95,3.5,"[-2.95, 3.5]",-1.85,3.5,-0.5,1.70,-2.25,0.40,"[-1.85, 3.5]","[-0.5, 1.7000000000000002]","[-2.25, 0.4]",1.10,3.04,3.18
256,InsertingSourcePollutant,None,None,None,1.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:18:43,2025-10-24 21:17:10,2025-10-24 21:24:48,2025-10-24 00:00:00,2025-10-24 21:17:12,2025-10-24 21:24:46,0 days 00:07:34,0 days 00:01:32,92,0 days 00:06:02,0 days 00:01:32,92,362,454,270,-30,299,2.0029,299.0,13.3480,277,2.0105,141.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=0:BME680:breathVocEquivalent MAX value VOC ...,1.27778,1.931717,13.17579,13.337491,1.89556,2.009913,10.16265,13.288696,0.130833,0.003005,1.964067,0.021602,0.356100,0.002903,-2.95,2.5,"[-2.95, 2.5]",-1.85,3.5,-0.5,1.70,-2.25,0.40,"[-1.85, 3.5]","[-0.5, 1.7000000000000002]","[-2.25, 0.4]",1.49,2.58,2.21
257,InsertingSourcePollutant,None,None,None,2.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:34:58,2025-10-24 21:33:44,2025-10-24 21:41:06,2025-10-24 00:00:00,2025-10-24 21:33:46,2025-10-24 21:41:04,0 days 00:07:18,0 days 00:01:13,73,0 days 00:06:05,0 days 00:01:13,73,365,438,270,-30,299,1.8114,299.0,7.5793,261,1.2671,299.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,1.71769,1.786738,7.36787,7.576884,1.24307,1.262000,6.72750,7.545522,0.316533,0.002780,0.425500,0.012363,0.281700,0.004330,-2.95,1.5,"[-2.95, 1.5]",-1.85,3.5,-0.5,1.70,-2.25,0.40,"[-1.85, 3.5]","[-0.5, 1.7000000000000002]","[-2.25, 0.4]",2.28,2.46,1.30
258,InsertingSourcePollutant,None,None,None,3.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:54:05,2025-10-24 21:52:16,2025-10-24 22:01:25,2025-10-24 00:00:00,2025-10-24 21:52:18,2025-10-24 22:01:24,0 days 00:09:06,0 days 00:01:48,108,0 days 00:07:18,0 days 00:01:48,108,438,546,270,-30,299,1.6312,213.0,3.3710,287,2.1139,299.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=0:BME680:breathVocEquivalent MAX value VOC ...,1.57461,1.630197,3.24331,3.369713,1.76254,2.072233,2.77298,3.363343,0.104633,-0.002098,0.727733,0.008225,0.324233,0.004552,-2.95,0.5,"[-2.95, 0.5]",-1.85,3.5,-0.5,1.70,-2.25,0.40,"[-1.85, 3.5]","[-0.5, 1.7000000000000002]","[-2.25, 0.4]",3.20,2.73,0.71

In [11]:
userInputData_Original["room"].unique()

array(['Κρεβατοκάμαρα id:1 Μ0.95 Α0.85 id:2 Μ0.95 Α1.55',
       'Κρεβατοκάμαρα id:1 Π0.6 Α1.2 id:2 Μ0.8 Α1.1',
       'Κρεβατοκάμαρα-Όλοι οι αισθητήρες μαζί Μ:0.80 , Α:0.90',
       'Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0.5  ,id:2 Π:0.4 Α:1.0',
       'Κρεβατοκάμαρα Όλοι οι αισθητήρες μαζί Π:1.80 , Δ:2.00'],
      dtype=object)

In [12]:
#keep the data from the last set experiments made that have the 3 sensors in a triangle shape,they have 16 particular points in the space d
room_mask = userInputData_Original["room"].isin(['Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0.5  ,id:2 Π:0.4 Α:1.0'])
mask = room_mask  
userInputData_Original = userInputData_Original.loc[mask]
timeSeriesData_BIG_Original = timeSeriesData_BIG_Original.loc[timeSeriesData_BIG_Original["keys"].isin(userInputData_Original.index)]

In [13]:
userInputData_Original

,experimentState,are-doors-opened,are-people-inside,are-windows-opened,front-wall,item-used,notes,room,side-right-wall,back-wall,side-left-wall,are-fans-on,no-source-located,timestamp InsertingSource,timestamp StartingExperiment,timestamp EndingExperiment,date of experiment,actual timestamp StartingExperiment,actual timestamp EndingExperiment,time taken total,timestamp InsertingSource timedelta,timestamp InsertingSource seconds,time taken after insertion,time taken before insertion,time taken before insertion (seconds),time taken after insertion (seconds),time taken total (seconds),time taken total (seconds)-capped,time taken before insertion (seconds)-capped,time taken after insertion (seconds)-capped,Id=1:BME680:breathVocEquivalent MAX value VOC rolling average,Id=1:BME680:breathVocEquivalent index of MAX value VOC rolling average,Id=2:BME680:breathVocEquivalent MAX value VOC rolling average,Id=2:BME680:breathVocEquivalent index of MAX value VOC rolling average,Id=0:BME680:breathVocEquivalent MAX value VOC rolling average,Id=0:BME680:breathVocEquivalent index of MAX value VOC rolling average,sensor with MAX value experiment,sensor with second MAX value experiment,Id=1:BME680:breathVocEquivalent quantile 90.0% VOC rolling average,Id=1:BME680:breathVocEquivalent quantile 99.0% VOC rolling average,Id=2:BME680:breathVocEquivalent quantile 90.0% VOC rolling average,Id=2:BME680:breathVocEquivalent quantile 99.0% VOC rolling average,Id=0:BME680:breathVocEquivalent quantile 90.0% VOC rolling average,Id=0:BME680:breathVocEquivalent quantile 99.0% VOC rolling average,whole experiment quantile 90.0% VOC rolling average,whole experiment quantile 99.0% VOC rolling average,Id=1:BME680:breathVocEquivalent VOC mean calm period,Id=1:BME680:breathVocEquivalent VOC gradient mean calm period,Id=2:BME680:breathVocEquivalent VOC mean calm period,Id=2:BME680:breathVocEquivalent VOC gradient mean calm period,Id=0:BME680:breathVocEquivalent VOC mean calm period,Id=0:BME680:breathVocEquivalent VOC gradient mean calm period,x axis,y axis,x-y axis,position of Id=0:BME680:breathVocEquivalent-x axis,position of Id=0:BME680:breathVocEquivalent-y axis,position of Id=1:BME680:breathVocEquivalent-x axis,position of Id=1:BME680:breathVocEquivalent-y axis,position of Id=2:BME680:breathVocEquivalent-x axis,position of Id=2:BME680:breathVocEquivalent-y axis,position of Id=0:BME680:breathVocEquivalent x-y axis,position of Id=1:BME680:breathVocEquivalent x-y axis,position of Id=2:BME680:breathVocEquivalent x-y axis,Euclidian distance to Id=0:BME680:breathVocEquivalent,Euclidian distance to Id=1:BME680:breathVocEquivalent,Euclidian distance to Id=2:BME680:breathVocEquivalent
79,NoSourcePollutantInserted,on,on,None,NaN,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,NaN,None,on,2025-10-02 20:42:09,2025-10-02 20:37:01,2025-10-02 20:52:58,2025-10-02 00:00:00,2025-10-02 20:37:03,2025-10-02 20:52:57,0 days 00:15:54,0 days 00:05:07,307,0 days 00:10:47,0 days 00:05:07,307,647,954,270,-30,299,0.4661,262.0,0.2250,299,0.4772,299.0,Id=0:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.45302,0.465942,0.18039,0.223468,0.41637,0.469588,0.41954,0.465622,0.358697,0.000262,0.090906,0.000573,0.251418,0.001445,NaN,NaN,"[None, None]",-1.85,3.5,-0.5,1.7,-2.25,0.4,"[-1.85, 3.5]","[-0.5, 1.7000000000000002]","[-2.25, 0.4]",NaN,NaN,NaN
80,InsertingSourcePollutant,on,on,None,NaN,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,2.0,1.1,None,None,2025-10-02 20:55:56,2025-10-02 20:53:02,2025-10-02 21:05:57,2025-10-02 00:00:00,2025-10-02 20:53:04,2025-10-02 21:05:55,0 days 00:12:51,0 days 00:02:53,173,0 days 00:09:58,0 days 00:02:53,173,598,771,270,-30,299,0.5238,258.0,0.1611,199,1.2086,299.0,Id=0:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.44293,0.522223,0.15562,0.160700,1.16940,1.204478,0.76853,1.189132,0.125200,0.000248,0.098400,-0.001167,0.167200,-0.000300,-2.15,2.0,"[-2.15, 2.0]",-1.85,3.5,-0.5,1.7,-2.25,0.4,"[-1.85, 3.5]","[-0.5, 1.7000000000000002]","[-2.25, 0.4]",1.53,1.68,1.60
81,InsertingSourcePollutant,on,on,None,NaN,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,2.0,1.9,None,None,2025-10-02 21:16:59,2025-10-02 21:14:28,2025-10-02 21:25:10,2025-10-02 00:00:00,2025-10-02 21:14:30,2025-10-02 21:25:09,0 days 00:10:39,0 days 00:02:30,150,0 days 00:08:09,0 days 00:02:30,150,489,639,270,-30,299,0.7816,145.0,0.3451,254,2.7556,299.0,Id=0:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.68038,0.779913,0.31991,0.344613,1.72633,2.675893,1.55378,2.424291,0.111200,0.000783,0.033233,-0.000337,0.037333,0.001417,-1.35,2.0,"[-1.35, 2.0]",-1.85,3.5,-0.5,1.7,-2.25,0.4,"[-1.85, 3.5]","[-0.5, 1.7000000000000002]","[-2.25, 0.4]",1.58,0.90,1.84
82,InsertingSourcePollutant,on,on,None,NaN,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,1.5,1.9,None,None,2025-10-02 21:39:05,2025-10-02 21:36:31,2025-10-02 21:48:54,2025-10-02 00:00:00,2025-10-02 21:36:33,2025-10-02 21:48:52,0 days 00:12:19,0 days 00:02:33,153,0 days 00:09:46,0 days 00:02:33,153,586,739,270,-30,299,3.5926,55.0,1.2782,177,5.5386,106.0,Id=0:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,1.92389,3.564704,1.18201,1.276636,4.40749,5.519748,3.03350,5.400648,0.325100,0.003638,0.032033,-0.000230,0.273933,0.001463,-1.35,1.5,"[-1.35, 1.5]",-1.85,3.5,-0.5,1.7,-2.25,0.4,"[-1.85, 3.5]","[-0.5, 1.7000000000000002]","[-2.25, 0.4]",2.06,0.87,1.42
83,InsertingSourcePollutant,on,on,None,NaN,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,1.0,1.9,None,None,2025-10-02 22:09:24,2025-10-02 22:05:35,2025-10-02 22:16:01,2025-10-02 00:00:00,2025-10-02 22:05:37,2025-10-02 22:16:00,0 days 00:10:23,0 days 00:03:48,228,0 days 00:06:35,0 days 00:03:48,228,395,623,270,-30,299,17.5655,192.0,6.1899,280,6.0319,91.0,Id=1:BME680:breathVocEquivalent MAX value VOC ...,Id=2:BME680:breathVocEquivalent MAX value VOC ...,12.87797,17.482242,5.73510,6.183678,5.39436,6.008097,6.03232,17.028469,0.788433,0.005148,0.294367,0.002553,0.830967,-0.005940,-1.35,1.0,"[-1.35, 1.0]",-1.85,3.5,-0.5,1.7,-2.25,0.4,"[-1.85, 3.5]","[-0.5, 1.7000000000000002]","[-2.25, 0.4]",2.55,1.10,1.08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
254,InsertingSourcePollutant,None,None,None,0.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",0.5,NaN,NaN,None,None,2025-10-24 20:32:03,2025-10-24 20:29:36,2025-10-24 20:37:33,2025-10-24 00:00:00,2025-10-24 20:29:37,2025-10-24 20:37:31,0 days 00:07:54,0 days 00:02:27,147,0 days 00:05:27,0 days 00:02:27,147,327,474,270,-30,299,2.0134,131.0,4.9923,299,2.8096,286.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=0:BME680:breathVocEquivalent MAX value VOC ...,1.85013,2.010252,4.58879,4.944112,2.74257,2.806868,3.70824,4.844487,0.384700,-0.004535,0.790767,0.014290,1.095967,-0.005078,-0.50,3.5,"[-0.5, 3.5]",-1.85,3.5,-0.5,1.7,-2.25,0.4,"[-1.85, 3.5]","[-0.5, 1.7000000000000002]","[-2.25, 0.4]",1.35,1.80,3.56
255,InsertingSourcePollutant,None,None,None,0.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:05:46,2025-10-24 21:03:22,2025-10-24 21:11:21,2025-10-24 00:00:00,2025-10-24 21:03:24,2025-10-24 21:11:19,0 days 00:07:55,0 days 00:02:23,143,0 days 00:05:32,0 days 00:02:23,143,332,475,270,-30,299,1.5436,269.0,6.0745,299,2.4431,236.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=0:BME680:breathVocEquivalent MAX value VOC ...,1.50536,1.541913,4.53166,5.938517,2.38429,2.439926,3.22484,5.639461,0.830100,0.003192,0.938300,0.004927,0.278667,0.009215,-2.95,3.5,"[-2.95, 3.5]",-1.85,3.5,-0.5,1.7,-2.25,0.4,"[-1.85, 3.5]","[-0.5, 1.7000000000000002]","[-2.25, 0.4]",1.10,3.04,3.18
256,InsertingSourcePollutant,None,None,None,1.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:18:43,2025-10-24 21:17:10,2025-10-24 21:24:48,2025-10-24 00:00:00,2025-10-24 21:17:12,2025-10-24 21:24:46,0 days 00:07:34,0 days 00:01:32,92,0 days 00:06:02,0 days 00:01:32,92,362,454,270,-30,299,2.0029,299.0,13.3480,277,2.0105,141.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=0:BME680:breathVocEquivalent MAX value VOC ...,1.27778,1.931717,13.17579,13.337491,1.89556,2.009913,10.16265,13.288696,0.130833,0.003005,1.964067,0.021602,0.356100,0.002903,-2.95,2.5,"[-2.95, 2.5]",-1.85,3.5,-0.5,1.7,-2.25,0.4,"[-1.85, 3.5]","[-0.5, 1.7000000000000002]","[-2.25, 0.4]",1.49,2.58,2.21
257,InsertingSourcePollutant,None,None,None,2.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:34:58,2025-10-24 21:33:44,2025-10-24 21:41:06,2025-10-24 00:00:00,2025-10-24 21:33:46,2025-10-24 21:41:04,0 days 00:07:18,0 days 00:01:13,73,0 days 00:06:05,0 days 00:01:13,73,365,438,270,-30,299,1.8114,299.0,7.5793,261,1.2671,299.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,1.71769,1.786738,7.36787,7.576884,1.24307,1.262000,6.72750,7.545522,0.316533,0.002780,0.425500,0.012363,0.281700,0.004330,-2.95,1.5,"[-2.95, 1.5]",-1.85,3.5,-0.5,1.7,-2.25,0.4,"[-1.85, 3.5]","[-0.5, 1.7000000000000002]","[-2.25, 0.4]",2.28,2.46,1.30
258,InsertingSourcePollutant,None,None,None,3.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:54:05,2025-10-24 21:52:16,2025-10-24 22:01:25,2025-10-24 00:00:00,2025-10-24 21:52:18,2025-10-24 22:01:24,0 days 00:09:06,0 days 00:01:48,108,0 days 00:07:18,0 days 00:01:48,108,438,546,270,-30,299,1.6312,213.0,3.3710,287,2.1139,299.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=0:BME680:breathVocEquivalent MAX value VOC ...,1.57461,1.630197,3.24331,3.369713,1.76254,2.072233,2.77298,3.363343,0.104633,-0.002098,0.727733,0.008225,0.324233,0.004552,-2.95,0.5,"[-2.95, 0.5]",-1.85,3.5,-0.5,1.7,-2.25,0.4,"[-1.85, 3.5]","[-0.5, 1.7000000000000002]","[-2.25, 0.4]",3.20,2.73,0.71

In [14]:
timeSeriesData_BIG_Original

,keys,sensors,VOC,after_insertion,original_value,datetime_timestamp,timestamp,seconds,seconds passed from insertionSource,VOC original,VOC rolling average,original seconds,VOC-capped,VOC rolling average-capped,VOC gradient,VOC rolling average gradient,VOC rolling average standard scaler whole experiment,VOC rolling average-capped standard scaler whole experiment
seconds,,,,,,,,,,,,,,,,,,
-30,79,Id=2:BME680:breathVocEquivalent,0.026,False,True,2025-10-02 20:41:40,0 days 00:04:37,-30,-30,0.493066,0.0365,277,0.026,0.0365,0.00080,0.00080,-1.317429,-1.317429
-30,79,Id=0:BME680:breathVocEquivalent,0.000,False,False,2025-10-02 20:41:40,0 days 00:04:37,-30,-30,0.160967,0.0012,277,0.000,0.0012,0.00000,0.00000,-1.554070,-1.554070
-30,79,Id=1:BME680:breathVocEquivalent,0.226,False,False,2025-10-02 20:41:40,0 days 00:04:37,-30,-30,0.507368,0.2474,277,0.226,0.2474,0.00200,0.00200,0.096388,0.096388
-29,79,Id=2:BME680:breathVocEquivalent,0.028,False,False,2025-10-02 20:41:41,0 days 00:04:38,-29,-29,0.494639,0.0373,278,0.028,0.0373,0.00085,0.00085,-1.312066,-1.312066
-29,79,Id=0:BME680:breathVocEquivalent,0.000,False,False,2025-10-02 20:41:41,0 days 00:04:38,-29,-29,0.160991,0.0012,278,0.000,0.0012,0.00005,0.00005,-1.554070,-1.554070
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,258,Id=1:BME680:breathVocEquivalent,1.421,True,True,2025-10-24 21:59:04,0 days 00:06:46,298,298,2.948842,1.4032,406,1.421,1.4032,-0.00500,-0.00500,0.089182,0.089182
298,258,Id=2:BME680:breathVocEquivalent,3.343,True,False,2025-10-24 21:59:04,0 days 00:06:46,298,298,5.567955,3.3352,406,3.343,3.3352,-0.00835,-0.00835,2.251684,2.251684
299,258,Id=0:BME680:breathVocEquivalent,2.143,True,False,2025-10-24 21:59:05,0 days 00:06:47,299,299,3.110278,2.1139,407,2.143,2.1139,0.01260,0.01260,0.884674,0.884674
299,258,Id=1:BME680:breathVocEquivalent,1.409,True,False,2025-10-24 21:59:05,0 days 00:06:47,299,299,2.936916,1.3982,407,1.409,1.3982,-0.00500,-0.00500,0.083585,0.083585
299,258,Id=2:BME680:breathVocEquivalent,3.307,True,False,2025-10-24 21:59:05,0 days 00:06:47,299,299,5.531128,3.3265,407,3.307,3.3265,-0.00870,-0.00870,2.241946,2.241946

In [15]:
column_to_transform = "x-y axis"
userInputData_Original.loc[:,column_to_transform] = userInputData_Original.loc[:,column_to_transform].apply(tuple)

In [16]:
sensors_position_columns = ["position of Id="+str(id) + ":BME680:breathVocEquivalent x-y axis"
                            for id in range(3)]
sensors_euclidian_distance_columns = ["Euclidian distance to Id="+str(id) + ":BME680:breathVocEquivalent"
                                    for id in range(3)]

userInputData_Original.loc[:,sensors_position_columns] = userInputData_Original.loc[:,sensors_position_columns].applymap(lambda lst: [round(x,2) for x in lst])
userInputData_Original.loc[:,sensors_euclidian_distance_columns] = userInputData_Original.loc[:,sensors_euclidian_distance_columns].round(2)

In [17]:
sensors_position_columns = ["position of Id="+str(id) + ":BME680:breathVocEquivalent x-y axis"
                            for id in range(3)]
column_to_transform = sensors_position_columns
userInputData_Original.loc[:,column_to_transform] = userInputData_Original.loc[:,column_to_transform].apply(tuple)

In [18]:
userInputData_Original

,experimentState,are-doors-opened,are-people-inside,are-windows-opened,front-wall,item-used,notes,room,side-right-wall,back-wall,side-left-wall,are-fans-on,no-source-located,timestamp InsertingSource,timestamp StartingExperiment,timestamp EndingExperiment,date of experiment,actual timestamp StartingExperiment,actual timestamp EndingExperiment,time taken total,timestamp InsertingSource timedelta,timestamp InsertingSource seconds,time taken after insertion,time taken before insertion,time taken before insertion (seconds),time taken after insertion (seconds),time taken total (seconds),time taken total (seconds)-capped,time taken before insertion (seconds)-capped,time taken after insertion (seconds)-capped,Id=1:BME680:breathVocEquivalent MAX value VOC rolling average,Id=1:BME680:breathVocEquivalent index of MAX value VOC rolling average,Id=2:BME680:breathVocEquivalent MAX value VOC rolling average,Id=2:BME680:breathVocEquivalent index of MAX value VOC rolling average,Id=0:BME680:breathVocEquivalent MAX value VOC rolling average,Id=0:BME680:breathVocEquivalent index of MAX value VOC rolling average,sensor with MAX value experiment,sensor with second MAX value experiment,Id=1:BME680:breathVocEquivalent quantile 90.0% VOC rolling average,Id=1:BME680:breathVocEquivalent quantile 99.0% VOC rolling average,Id=2:BME680:breathVocEquivalent quantile 90.0% VOC rolling average,Id=2:BME680:breathVocEquivalent quantile 99.0% VOC rolling average,Id=0:BME680:breathVocEquivalent quantile 90.0% VOC rolling average,Id=0:BME680:breathVocEquivalent quantile 99.0% VOC rolling average,whole experiment quantile 90.0% VOC rolling average,whole experiment quantile 99.0% VOC rolling average,Id=1:BME680:breathVocEquivalent VOC mean calm period,Id=1:BME680:breathVocEquivalent VOC gradient mean calm period,Id=2:BME680:breathVocEquivalent VOC mean calm period,Id=2:BME680:breathVocEquivalent VOC gradient mean calm period,Id=0:BME680:breathVocEquivalent VOC mean calm period,Id=0:BME680:breathVocEquivalent VOC gradient mean calm period,x axis,y axis,x-y axis,position of Id=0:BME680:breathVocEquivalent-x axis,position of Id=0:BME680:breathVocEquivalent-y axis,position of Id=1:BME680:breathVocEquivalent-x axis,position of Id=1:BME680:breathVocEquivalent-y axis,position of Id=2:BME680:breathVocEquivalent-x axis,position of Id=2:BME680:breathVocEquivalent-y axis,position of Id=0:BME680:breathVocEquivalent x-y axis,position of Id=1:BME680:breathVocEquivalent x-y axis,position of Id=2:BME680:breathVocEquivalent x-y axis,Euclidian distance to Id=0:BME680:breathVocEquivalent,Euclidian distance to Id=1:BME680:breathVocEquivalent,Euclidian distance to Id=2:BME680:breathVocEquivalent
79,NoSourcePollutantInserted,on,on,None,NaN,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,NaN,None,on,2025-10-02 20:42:09,2025-10-02 20:37:01,2025-10-02 20:52:58,2025-10-02 00:00:00,2025-10-02 20:37:03,2025-10-02 20:52:57,0 days 00:15:54,0 days 00:05:07,307,0 days 00:10:47,0 days 00:05:07,307,647,954,270,-30,299,0.4661,262.0,0.2250,299,0.4772,299.0,Id=0:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.45302,0.465942,0.18039,0.223468,0.41637,0.469588,0.41954,0.465622,0.358697,0.000262,0.090906,0.000573,0.251418,0.001445,NaN,NaN,"(None, None)",-1.85,3.5,-0.5,1.7,-2.25,0.4,"[-1.85, 3.5]","[-0.5, 1.7]","[-2.25, 0.4]",NaN,NaN,NaN
80,InsertingSourcePollutant,on,on,None,NaN,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,2.0,1.1,None,None,2025-10-02 20:55:56,2025-10-02 20:53:02,2025-10-02 21:05:57,2025-10-02 00:00:00,2025-10-02 20:53:04,2025-10-02 21:05:55,0 days 00:12:51,0 days 00:02:53,173,0 days 00:09:58,0 days 00:02:53,173,598,771,270,-30,299,0.5238,258.0,0.1611,199,1.2086,299.0,Id=0:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.44293,0.522223,0.15562,0.160700,1.16940,1.204478,0.76853,1.189132,0.125200,0.000248,0.098400,-0.001167,0.167200,-0.000300,-2.15,2.0,"(-2.15, 2.0)",-1.85,3.5,-0.5,1.7,-2.25,0.4,"[-1.85, 3.5]","[-0.5, 1.7]","[-2.25, 0.4]",1.53,1.68,1.60
81,InsertingSourcePollutant,on,on,None,NaN,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,2.0,1.9,None,None,2025-10-02 21:16:59,2025-10-02 21:14:28,2025-10-02 21:25:10,2025-10-02 00:00:00,2025-10-02 21:14:30,2025-10-02 21:25:09,0 days 00:10:39,0 days 00:02:30,150,0 days 00:08:09,0 days 00:02:30,150,489,639,270,-30,299,0.7816,145.0,0.3451,254,2.7556,299.0,Id=0:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.68038,0.779913,0.31991,0.344613,1.72633,2.675893,1.55378,2.424291,0.111200,0.000783,0.033233,-0.000337,0.037333,0.001417,-1.35,2.0,"(-1.35, 2.0)",-1.85,3.5,-0.5,1.7,-2.25,0.4,"[-1.85, 3.5]","[-0.5, 1.7]","[-2.25, 0.4]",1.58,0.90,1.84
82,InsertingSourcePollutant,on,on,None,NaN,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,1.5,1.9,None,None,2025-10-02 21:39:05,2025-10-02 21:36:31,2025-10-02 21:48:54,2025-10-02 00:00:00,2025-10-02 21:36:33,2025-10-02 21:48:52,0 days 00:12:19,0 days 00:02:33,153,0 days 00:09:46,0 days 00:02:33,153,586,739,270,-30,299,3.5926,55.0,1.2782,177,5.5386,106.0,Id=0:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,1.92389,3.564704,1.18201,1.276636,4.40749,5.519748,3.03350,5.400648,0.325100,0.003638,0.032033,-0.000230,0.273933,0.001463,-1.35,1.5,"(-1.35, 1.5)",-1.85,3.5,-0.5,1.7,-2.25,0.4,"[-1.85, 3.5]","[-0.5, 1.7]","[-2.25, 0.4]",2.06,0.87,1.42
83,InsertingSourcePollutant,on,on,None,NaN,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,1.0,1.9,None,None,2025-10-02 22:09:24,2025-10-02 22:05:35,2025-10-02 22:16:01,2025-10-02 00:00:00,2025-10-02 22:05:37,2025-10-02 22:16:00,0 days 00:10:23,0 days 00:03:48,228,0 days 00:06:35,0 days 00:03:48,228,395,623,270,-30,299,17.5655,192.0,6.1899,280,6.0319,91.0,Id=1:BME680:breathVocEquivalent MAX value VOC ...,Id=2:BME680:breathVocEquivalent MAX value VOC ...,12.87797,17.482242,5.73510,6.183678,5.39436,6.008097,6.03232,17.028469,0.788433,0.005148,0.294367,0.002553,0.830967,-0.005940,-1.35,1.0,"(-1.35, 1.0)",-1.85,3.5,-0.5,1.7,-2.25,0.4,"[-1.85, 3.5]","[-0.5, 1.7]","[-2.25, 0.4]",2.55,1.10,1.08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
254,InsertingSourcePollutant,None,None,None,0.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",0.5,NaN,NaN,None,None,2025-10-24 20:32:03,2025-10-24 20:29:36,2025-10-24 20:37:33,2025-10-24 00:00:00,2025-10-24 20:29:37,2025-10-24 20:37:31,0 days 00:07:54,0 days 00:02:27,147,0 days 00:05:27,0 days 00:02:27,147,327,474,270,-30,299,2.0134,131.0,4.9923,299,2.8096,286.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=0:BME680:breathVocEquivalent MAX value VOC ...,1.85013,2.010252,4.58879,4.944112,2.74257,2.806868,3.70824,4.844487,0.384700,-0.004535,0.790767,0.014290,1.095967,-0.005078,-0.50,3.5,"(-0.5, 3.5)",-1.85,3.5,-0.5,1.7,-2.25,0.4,"[-1.85, 3.5]","[-0.5, 1.7]","[-2.25, 0.4]",1.35,1.80,3.56
255,InsertingSourcePollutant,None,None,None,0.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:05:46,2025-10-24 21:03:22,2025-10-24 21:11:21,2025-10-24 00:00:00,2025-10-24 21:03:24,2025-10-24 21:11:19,0 days 00:07:55,0 days 00:02:23,143,0 days 00:05:32,0 days 00:02:23,143,332,475,270,-30,299,1.5436,269.0,6.0745,299,2.4431,236.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=0:BME680:breathVocEquivalent MAX value VOC ...,1.50536,1.541913,4.53166,5.938517,2.38429,2.439926,3.22484,5.639461,0.830100,0.003192,0.938300,0.004927,0.278667,0.009215,-2.95,3.5,"(-2.95, 3.5)",-1.85,3.5,-0.5,1.7,-2.25,0.4,"[-1.85, 3.5]","[-0.5, 1.7]","[-2.25, 0.4]",1.10,3.04,3.18
256,InsertingSourcePollutant,None,None,None,1.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:18:43,2025-10-24 21:17:10,2025-10-24 21:24:48,2025-10-24 00:00:00,2025-10-24 21:17:12,2025-10-24 21:24:46,0 days 00:07:34,0 days 00:01:32,92,0 days 00:06:02,0 days 00:01:32,92,362,454,270,-30,299,2.0029,299.0,13.3480,277,2.0105,141.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=0:BME680:breathVocEquivalent MAX value VOC ...,1.27778,1.931717,13.17579,13.337491,1.89556,2.009913,10.16265,13.288696,0.130833,0.003005,1.964067,0.021602,0.356100,0.002903,-2.95,2.5,"(-2.95, 2.5)",-1.85,3.5,-0.5,1.7,-2.25,0.4,"[-1.85, 3.5]","[-0.5, 1.7]","[-2.25, 0.4]",1.49,2.58,2.21
257,InsertingSourcePollutant,None,None,None,2.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:34:58,2025-10-24 21:33:44,2025-10-24 21:41:06,2025-10-24 00:00:00,2025-10-24 21:33:46,2025-10-24 21:41:04,0 days 00:07:18,0 days 00:01:13,73,0 days 00:06:05,0 days 00:01:13,73,365,438,270,-30,299,1.8114,299.0,7.5793,261,1.2671,299.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,1.71769,1.786738,7.36787,7.576884,1.24307,1.262000,6.72750,7.545522,0.316533,0.002780,0.425500,0.012363,0.281700,0.004330,-2.95,1.5,"(-2.95, 1.5)",-1.85,3.5,-0.5,1.7,-2.25,0.4,"[-1.85, 3.5]","[-0.5, 1.7]","[-2.25, 0.4]",2.28,2.46,1.30
258,InsertingSourcePollutant,None,None,None,3.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:54:05,2025-10-24 21:52:16,2025-10-24 22:01:25,2025-10-24 00:00:00,2025-10-24 21:52:18,2025-10-24 22:01:24,0 days 00:09:06,0 days 00:01:48,108,0 days 00:07:18,0 days 00:01:48,108,438,546,270,-30,299,1.6312,213.0,3.3710,287,2.1139,299.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=0:BME680:breathVocEquivalent MAX value VOC ...,1.57461,1.630197,3.24331,3.369713,1.76254,2.072233,2.77298,3.363343,0.104633,-0.002098,0.727733,0.008225,0.324233,0.004552,-2.95,0.5,"(-2.95, 0.5)",-1.85,3.5,-0.5,1.7,-2.25,0.4,"[-1.85, 3.5]","[-0.5, 1.7]","[-2.25, 0.4]",3.20,2.73,0.71

In [19]:
userInputData_Original.columns

Index(['experimentState', 'are-doors-opened', 'are-people-inside',
       'are-windows-opened', 'front-wall', 'item-used', 'notes', 'room',
       'side-right-wall', 'back-wall', 'side-left-wall', 'are-fans-on',
       'no-source-located', 'timestamp InsertingSource',
       'timestamp StartingExperiment', 'timestamp EndingExperiment',
       'date of experiment', 'actual timestamp StartingExperiment',
       'actual timestamp EndingExperiment', 'time taken total',
       'timestamp InsertingSource timedelta',
       'timestamp InsertingSource seconds', 'time taken after insertion',
       'time taken before insertion', 'time taken before insertion (seconds)',
       'time taken after insertion (seconds)', 'time taken total (seconds)',
       'time taken total (seconds)-capped',
       'time taken before insertion (seconds)-capped',
       'time taken after insertion (seconds)-capped',
       'Id=1:BME680:breathVocEquivalent MAX value VOC rolling average',
       'Id=1:BME680:breathVocEquivalent index of MAX value VOC rolling average',
       'Id=2:BME680:breathVocEquivalent MAX value VOC rolling average',
       'Id=2:BME680:breathVocEquivalent index of MAX value VOC rolling average',
       'Id=0:BME680:breathVocEquivalent MAX value VOC rolling average',
       'Id=0:BME680:breathVocEquivalent index of MAX value VOC rolling average',
       'sensor with MAX value experiment',
       'sensor with second MAX value experiment',
       'Id=1:BME680:breathVocEquivalent quantile 90.0% VOC rolling average',
       'Id=1:BME680:breathVocEquivalent quantile 99.0% VOC rolling average',
       'Id=2:BME680:breathVocEquivalent quantile 90.0% VOC rolling average',
       'Id=2:BME680:breathVocEquivalent quantile 99.0% VOC rolling average',
       'Id=0:BME680:breathVocEquivalent quantile 90.0% VOC rolling average',
       'Id=0:BME680:breathVocEquivalent quantile 99.0% VOC rolling average',
       'whole experiment quantile 90.0% VOC rolling average',
       'whole experiment quantile 99.0% VOC rolling average',
       'Id=1:BME680:breathVocEquivalent VOC mean calm period',
       'Id=1:BME680:breathVocEquivalent VOC gradient mean calm period',
       'Id=2:BME680:breathVocEquivalent VOC mean calm period',
       'Id=2:BME680:breathVocEquivalent VOC gradient mean calm period',
       'Id=0:BME680:breathVocEquivalent VOC mean calm period',
       'Id=0:BME680:breathVocEquivalent VOC gradient mean calm period',
       'x axis', 'y axis', 'x-y axis',
       'position of Id=0:BME680:breathVocEquivalent-x axis',
       'position of Id=0:BME680:breathVocEquivalent-y axis',
       'position of Id=1:BME680:breathVocEquivalent-x axis',
       'position of Id=1:BME680:breathVocEquivalent-y axis',
       'position of Id=2:BME680:breathVocEquivalent-x axis',
       'position of Id=2:BME680:breathVocEquivalent-y axis',
       'position of Id=0:BME680:breathVocEquivalent x-y axis',
       'position of Id=1:BME680:breathVocEquivalent x-y axis',
       'position of Id=2:BME680:breathVocEquivalent x-y axis',
       'Euclidian distance to Id=0:BME680:breathVocEquivalent',
       'Euclidian distance to Id=1:BME680:breathVocEquivalent',
       'Euclidian distance to Id=2:BME680:breathVocEquivalent'],
      dtype='object')

In [20]:

euclidian_distance_columns = ["Euclidian distance to Id="+str(id)+":BME680:breathVocEquivalent"
                               for id in range(3) ]

mask = userInputData_Original["are-doors-opened"] == "on"
for i in range(3):
    print(f"userInputData_Original[are-doors-opened] == on at id={i}:{np.sort(userInputData_Original.loc[mask,euclidian_distance_columns[i]].unique())}")
mask = userInputData_Original["are-doors-opened"] != "on"    
for i in range(3):
    print(f"userInputData_Original[are-doors-opened] != on at id={i}:{np.sort(userInputData_Original.loc[mask,euclidian_distance_columns[i]].unique())}")

userInputData_Original[are-doors-opened] == on at id=0:[0.35 0.65 1.06 1.1  1.19 1.35 1.49 1.53 1.58 1.68 2.   2.03 2.06 2.1
 2.28 2.41 2.5  2.55 3.02 3.07 3.2  3.29  nan]
userInputData_Original[are-doors-opened] == on at id=1:[0.2  0.8  0.87 0.9  1.02 1.1  1.2  1.28 1.36 1.52 1.56 1.68 1.8  2.01
 2.06 2.15 2.33 2.46 2.58 2.69 2.73 3.04  nan]
userInputData_Original[are-doors-opened] == on at id=2:[0.27 0.71 0.72 0.76 1.08 1.13 1.17 1.3  1.33 1.42 1.6  1.75 1.84 2.07
 2.11 2.21 2.23 2.73 3.11 3.18 3.19 3.56  nan]
userInputData_Original[are-doors-opened] != on at id=0:[0.35 0.65 1.06 1.1  1.19 1.35 1.49 1.68 2.03 2.1  2.28 2.41 3.02 3.07
 3.2  3.29  nan]
userInputData_Original[are-doors-opened] != on at id=1:[0.2  0.8  1.02 1.2  1.28 1.56 1.8  2.01 2.06 2.15 2.33 2.46 2.58 2.69
 2.73 3.04  nan]
userInputData_Original[are-doors-opened] != on at id=2:[0.27 0.71 0.76 1.13 1.3  1.33 1.75 2.07 2.11 2.21 2.23 2.73 3.11 3.18
 3.19 3.56  nan]

In [21]:
userInputData_Original

,experimentState,are-doors-opened,are-people-inside,are-windows-opened,front-wall,item-used,notes,room,side-right-wall,back-wall,side-left-wall,are-fans-on,no-source-located,timestamp InsertingSource,timestamp StartingExperiment,timestamp EndingExperiment,date of experiment,actual timestamp StartingExperiment,actual timestamp EndingExperiment,time taken total,timestamp InsertingSource timedelta,timestamp InsertingSource seconds,time taken after insertion,time taken before insertion,time taken before insertion (seconds),time taken after insertion (seconds),time taken total (seconds),time taken total (seconds)-capped,time taken before insertion (seconds)-capped,time taken after insertion (seconds)-capped,Id=1:BME680:breathVocEquivalent MAX value VOC rolling average,Id=1:BME680:breathVocEquivalent index of MAX value VOC rolling average,Id=2:BME680:breathVocEquivalent MAX value VOC rolling average,Id=2:BME680:breathVocEquivalent index of MAX value VOC rolling average,Id=0:BME680:breathVocEquivalent MAX value VOC rolling average,Id=0:BME680:breathVocEquivalent index of MAX value VOC rolling average,sensor with MAX value experiment,sensor with second MAX value experiment,Id=1:BME680:breathVocEquivalent quantile 90.0% VOC rolling average,Id=1:BME680:breathVocEquivalent quantile 99.0% VOC rolling average,Id=2:BME680:breathVocEquivalent quantile 90.0% VOC rolling average,Id=2:BME680:breathVocEquivalent quantile 99.0% VOC rolling average,Id=0:BME680:breathVocEquivalent quantile 90.0% VOC rolling average,Id=0:BME680:breathVocEquivalent quantile 99.0% VOC rolling average,whole experiment quantile 90.0% VOC rolling average,whole experiment quantile 99.0% VOC rolling average,Id=1:BME680:breathVocEquivalent VOC mean calm period,Id=1:BME680:breathVocEquivalent VOC gradient mean calm period,Id=2:BME680:breathVocEquivalent VOC mean calm period,Id=2:BME680:breathVocEquivalent VOC gradient mean calm period,Id=0:BME680:breathVocEquivalent VOC mean calm period,Id=0:BME680:breathVocEquivalent VOC gradient mean calm period,x axis,y axis,x-y axis,position of Id=0:BME680:breathVocEquivalent-x axis,position of Id=0:BME680:breathVocEquivalent-y axis,position of Id=1:BME680:breathVocEquivalent-x axis,position of Id=1:BME680:breathVocEquivalent-y axis,position of Id=2:BME680:breathVocEquivalent-x axis,position of Id=2:BME680:breathVocEquivalent-y axis,position of Id=0:BME680:breathVocEquivalent x-y axis,position of Id=1:BME680:breathVocEquivalent x-y axis,position of Id=2:BME680:breathVocEquivalent x-y axis,Euclidian distance to Id=0:BME680:breathVocEquivalent,Euclidian distance to Id=1:BME680:breathVocEquivalent,Euclidian distance to Id=2:BME680:breathVocEquivalent
79,NoSourcePollutantInserted,on,on,None,NaN,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,NaN,None,on,2025-10-02 20:42:09,2025-10-02 20:37:01,2025-10-02 20:52:58,2025-10-02 00:00:00,2025-10-02 20:37:03,2025-10-02 20:52:57,0 days 00:15:54,0 days 00:05:07,307,0 days 00:10:47,0 days 00:05:07,307,647,954,270,-30,299,0.4661,262.0,0.2250,299,0.4772,299.0,Id=0:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.45302,0.465942,0.18039,0.223468,0.41637,0.469588,0.41954,0.465622,0.358697,0.000262,0.090906,0.000573,0.251418,0.001445,NaN,NaN,"(None, None)",-1.85,3.5,-0.5,1.7,-2.25,0.4,"[-1.85, 3.5]","[-0.5, 1.7]","[-2.25, 0.4]",NaN,NaN,NaN
80,InsertingSourcePollutant,on,on,None,NaN,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,2.0,1.1,None,None,2025-10-02 20:55:56,2025-10-02 20:53:02,2025-10-02 21:05:57,2025-10-02 00:00:00,2025-10-02 20:53:04,2025-10-02 21:05:55,0 days 00:12:51,0 days 00:02:53,173,0 days 00:09:58,0 days 00:02:53,173,598,771,270,-30,299,0.5238,258.0,0.1611,199,1.2086,299.0,Id=0:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.44293,0.522223,0.15562,0.160700,1.16940,1.204478,0.76853,1.189132,0.125200,0.000248,0.098400,-0.001167,0.167200,-0.000300,-2.15,2.0,"(-2.15, 2.0)",-1.85,3.5,-0.5,1.7,-2.25,0.4,"[-1.85, 3.5]","[-0.5, 1.7]","[-2.25, 0.4]",1.53,1.68,1.60
81,InsertingSourcePollutant,on,on,None,NaN,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,2.0,1.9,None,None,2025-10-02 21:16:59,2025-10-02 21:14:28,2025-10-02 21:25:10,2025-10-02 00:00:00,2025-10-02 21:14:30,2025-10-02 21:25:09,0 days 00:10:39,0 days 00:02:30,150,0 days 00:08:09,0 days 00:02:30,150,489,639,270,-30,299,0.7816,145.0,0.3451,254,2.7556,299.0,Id=0:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.68038,0.779913,0.31991,0.344613,1.72633,2.675893,1.55378,2.424291,0.111200,0.000783,0.033233,-0.000337,0.037333,0.001417,-1.35,2.0,"(-1.35, 2.0)",-1.85,3.5,-0.5,1.7,-2.25,0.4,"[-1.85, 3.5]","[-0.5, 1.7]","[-2.25, 0.4]",1.58,0.90,1.84
82,InsertingSourcePollutant,on,on,None,NaN,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,1.5,1.9,None,None,2025-10-02 21:39:05,2025-10-02 21:36:31,2025-10-02 21:48:54,2025-10-02 00:00:00,2025-10-02 21:36:33,2025-10-02 21:48:52,0 days 00:12:19,0 days 00:02:33,153,0 days 00:09:46,0 days 00:02:33,153,586,739,270,-30,299,3.5926,55.0,1.2782,177,5.5386,106.0,Id=0:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,1.92389,3.564704,1.18201,1.276636,4.40749,5.519748,3.03350,5.400648,0.325100,0.003638,0.032033,-0.000230,0.273933,0.001463,-1.35,1.5,"(-1.35, 1.5)",-1.85,3.5,-0.5,1.7,-2.25,0.4,"[-1.85, 3.5]","[-0.5, 1.7]","[-2.25, 0.4]",2.06,0.87,1.42
83,InsertingSourcePollutant,on,on,None,NaN,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,1.0,1.9,None,None,2025-10-02 22:09:24,2025-10-02 22:05:35,2025-10-02 22:16:01,2025-10-02 00:00:00,2025-10-02 22:05:37,2025-10-02 22:16:00,0 days 00:10:23,0 days 00:03:48,228,0 days 00:06:35,0 days 00:03:48,228,395,623,270,-30,299,17.5655,192.0,6.1899,280,6.0319,91.0,Id=1:BME680:breathVocEquivalent MAX value VOC ...,Id=2:BME680:breathVocEquivalent MAX value VOC ...,12.87797,17.482242,5.73510,6.183678,5.39436,6.008097,6.03232,17.028469,0.788433,0.005148,0.294367,0.002553,0.830967,-0.005940,-1.35,1.0,"(-1.35, 1.0)",-1.85,3.5,-0.5,1.7,-2.25,0.4,"[-1.85, 3.5]","[-0.5, 1.7]","[-2.25, 0.4]",2.55,1.10,1.08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
254,InsertingSourcePollutant,None,None,None,0.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",0.5,NaN,NaN,None,None,2025-10-24 20:32:03,2025-10-24 20:29:36,2025-10-24 20:37:33,2025-10-24 00:00:00,2025-10-24 20:29:37,2025-10-24 20:37:31,0 days 00:07:54,0 days 00:02:27,147,0 days 00:05:27,0 days 00:02:27,147,327,474,270,-30,299,2.0134,131.0,4.9923,299,2.8096,286.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=0:BME680:breathVocEquivalent MAX value VOC ...,1.85013,2.010252,4.58879,4.944112,2.74257,2.806868,3.70824,4.844487,0.384700,-0.004535,0.790767,0.014290,1.095967,-0.005078,-0.50,3.5,"(-0.5, 3.5)",-1.85,3.5,-0.5,1.7,-2.25,0.4,"[-1.85, 3.5]","[-0.5, 1.7]","[-2.25, 0.4]",1.35,1.80,3.56
255,InsertingSourcePollutant,None,None,None,0.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:05:46,2025-10-24 21:03:22,2025-10-24 21:11:21,2025-10-24 00:00:00,2025-10-24 21:03:24,2025-10-24 21:11:19,0 days 00:07:55,0 days 00:02:23,143,0 days 00:05:32,0 days 00:02:23,143,332,475,270,-30,299,1.5436,269.0,6.0745,299,2.4431,236.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=0:BME680:breathVocEquivalent MAX value VOC ...,1.50536,1.541913,4.53166,5.938517,2.38429,2.439926,3.22484,5.639461,0.830100,0.003192,0.938300,0.004927,0.278667,0.009215,-2.95,3.5,"(-2.95, 3.5)",-1.85,3.5,-0.5,1.7,-2.25,0.4,"[-1.85, 3.5]","[-0.5, 1.7]","[-2.25, 0.4]",1.10,3.04,3.18
256,InsertingSourcePollutant,None,None,None,1.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:18:43,2025-10-24 21:17:10,2025-10-24 21:24:48,2025-10-24 00:00:00,2025-10-24 21:17:12,2025-10-24 21:24:46,0 days 00:07:34,0 days 00:01:32,92,0 days 00:06:02,0 days 00:01:32,92,362,454,270,-30,299,2.0029,299.0,13.3480,277,2.0105,141.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=0:BME680:breathVocEquivalent MAX value VOC ...,1.27778,1.931717,13.17579,13.337491,1.89556,2.009913,10.16265,13.288696,0.130833,0.003005,1.964067,0.021602,0.356100,0.002903,-2.95,2.5,"(-2.95, 2.5)",-1.85,3.5,-0.5,1.7,-2.25,0.4,"[-1.85, 3.5]","[-0.5, 1.7]","[-2.25, 0.4]",1.49,2.58,2.21
257,InsertingSourcePollutant,None,None,None,2.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:34:58,2025-10-24 21:33:44,2025-10-24 21:41:06,2025-10-24 00:00:00,2025-10-24 21:33:46,2025-10-24 21:41:04,0 days 00:07:18,0 days 00:01:13,73,0 days 00:06:05,0 days 00:01:13,73,365,438,270,-30,299,1.8114,299.0,7.5793,261,1.2671,299.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,1.71769,1.786738,7.36787,7.576884,1.24307,1.262000,6.72750,7.545522,0.316533,0.002780,0.425500,0.012363,0.281700,0.004330,-2.95,1.5,"(-2.95, 1.5)",-1.85,3.5,-0.5,1.7,-2.25,0.4,"[-1.85, 3.5]","[-0.5, 1.7]","[-2.25, 0.4]",2.28,2.46,1.30
258,InsertingSourcePollutant,None,None,None,3.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:54:05,2025-10-24 21:52:16,2025-10-24 22:01:25,2025-10-24 00:00:00,2025-10-24 21:52:18,2025-10-24 22:01:24,0 days 00:09:06,0 days 00:01:48,108,0 days 00:07:18,0 days 00:01:48,108,438,546,270,-30,299,1.6312,213.0,3.3710,287,2.1139,299.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=0:BME680:breathVocEquivalent MAX value VOC ...,1.57461,1.630197,3.24331,3.369713,1.76254,2.072233,2.77298,3.363343,0.104633,-0.002098,0.727733,0.008225,0.324233,0.004552,-2.95,0.5,"(-2.95, 0.5)",-1.85,3.5,-0.5,1.7,-2.25,0.4,"[-1.85, 3.5]","[-0.5, 1.7]","[-2.25, 0.4]",3.20,2.73,0.71

In [22]:
timeSeriesData_BIG_Original

,keys,sensors,VOC,after_insertion,original_value,datetime_timestamp,timestamp,seconds,seconds passed from insertionSource,VOC original,VOC rolling average,original seconds,VOC-capped,VOC rolling average-capped,VOC gradient,VOC rolling average gradient,VOC rolling average standard scaler whole experiment,VOC rolling average-capped standard scaler whole experiment
seconds,,,,,,,,,,,,,,,,,,
-30,79,Id=2:BME680:breathVocEquivalent,0.026,False,True,2025-10-02 20:41:40,0 days 00:04:37,-30,-30,0.493066,0.0365,277,0.026,0.0365,0.00080,0.00080,-1.317429,-1.317429
-30,79,Id=0:BME680:breathVocEquivalent,0.000,False,False,2025-10-02 20:41:40,0 days 00:04:37,-30,-30,0.160967,0.0012,277,0.000,0.0012,0.00000,0.00000,-1.554070,-1.554070
-30,79,Id=1:BME680:breathVocEquivalent,0.226,False,False,2025-10-02 20:41:40,0 days 00:04:37,-30,-30,0.507368,0.2474,277,0.226,0.2474,0.00200,0.00200,0.096388,0.096388
-29,79,Id=2:BME680:breathVocEquivalent,0.028,False,False,2025-10-02 20:41:41,0 days 00:04:38,-29,-29,0.494639,0.0373,278,0.028,0.0373,0.00085,0.00085,-1.312066,-1.312066
-29,79,Id=0:BME680:breathVocEquivalent,0.000,False,False,2025-10-02 20:41:41,0 days 00:04:38,-29,-29,0.160991,0.0012,278,0.000,0.0012,0.00005,0.00005,-1.554070,-1.554070
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,258,Id=1:BME680:breathVocEquivalent,1.421,True,True,2025-10-24 21:59:04,0 days 00:06:46,298,298,2.948842,1.4032,406,1.421,1.4032,-0.00500,-0.00500,0.089182,0.089182
298,258,Id=2:BME680:breathVocEquivalent,3.343,True,False,2025-10-24 21:59:04,0 days 00:06:46,298,298,5.567955,3.3352,406,3.343,3.3352,-0.00835,-0.00835,2.251684,2.251684
299,258,Id=0:BME680:breathVocEquivalent,2.143,True,False,2025-10-24 21:59:05,0 days 00:06:47,299,299,3.110278,2.1139,407,2.143,2.1139,0.01260,0.01260,0.884674,0.884674
299,258,Id=1:BME680:breathVocEquivalent,1.409,True,False,2025-10-24 21:59:05,0 days 00:06:47,299,299,2.936916,1.3982,407,1.409,1.3982,-0.00500,-0.00500,0.083585,0.083585
299,258,Id=2:BME680:breathVocEquivalent,3.307,True,False,2025-10-24 21:59:05,0 days 00:06:47,299,299,5.531128,3.3265,407,3.307,3.3265,-0.00870,-0.00870,2.241946,2.241946

In [23]:
userInputData_Original.loc[userInputData_Original["are-doors-opened"]=="on"].shape

(66, 67)

In [24]:
userInputData_Original.loc[userInputData_Original["are-doors-opened"]!="on"].shape

(102, 67)

In [25]:
max_before= -30
max_after = 299

column_to_check = "time taken before insertion (seconds)-capped"
mask = userInputData_Original[column_to_check] >max_before
print(f"{column_to_check} < {max_before}:\n {userInputData_Original.loc[mask,column_to_check]}")

column_to_check = "time taken after insertion (seconds)-capped"
mask = userInputData_Original[column_to_check] < max_after
print(f"{column_to_check} < {max_after}:\n {userInputData_Original.loc[mask,column_to_check]}")
print(f"userInputData_Original rows {userInputData_Original.shape[0]}")

time taken before insertion (seconds)-capped < -30:
 86     -8
89    -25
104   -10
122   -16
128    -8
131   -12
139    -8
145   -12
187    -5
221   -11
242    -5
Name: time taken before insertion (seconds)-capped, dtype: int64
time taken after insertion (seconds)-capped < 299:
 Series([], Name: time taken after insertion (seconds)-capped, dtype: int64)
userInputData_Original rows 168

In [26]:
userInputData_Original.columns

Index(['experimentState', 'are-doors-opened', 'are-people-inside',
       'are-windows-opened', 'front-wall', 'item-used', 'notes', 'room',
       'side-right-wall', 'back-wall', 'side-left-wall', 'are-fans-on',
       'no-source-located', 'timestamp InsertingSource',
       'timestamp StartingExperiment', 'timestamp EndingExperiment',
       'date of experiment', 'actual timestamp StartingExperiment',
       'actual timestamp EndingExperiment', 'time taken total',
       'timestamp InsertingSource timedelta',
       'timestamp InsertingSource seconds', 'time taken after insertion',
       'time taken before insertion', 'time taken before insertion (seconds)',
       'time taken after insertion (seconds)', 'time taken total (seconds)',
       'time taken total (seconds)-capped',
       'time taken before insertion (seconds)-capped',
       'time taken after insertion (seconds)-capped',
       'Id=1:BME680:breathVocEquivalent MAX value VOC rolling average',
       'Id=1:BME680:breathVocEquivalent index of MAX value VOC rolling average',
       'Id=2:BME680:breathVocEquivalent MAX value VOC rolling average',
       'Id=2:BME680:breathVocEquivalent index of MAX value VOC rolling average',
       'Id=0:BME680:breathVocEquivalent MAX value VOC rolling average',
       'Id=0:BME680:breathVocEquivalent index of MAX value VOC rolling average',
       'sensor with MAX value experiment',
       'sensor with second MAX value experiment',
       'Id=1:BME680:breathVocEquivalent quantile 90.0% VOC rolling average',
       'Id=1:BME680:breathVocEquivalent quantile 99.0% VOC rolling average',
       'Id=2:BME680:breathVocEquivalent quantile 90.0% VOC rolling average',
       'Id=2:BME680:breathVocEquivalent quantile 99.0% VOC rolling average',
       'Id=0:BME680:breathVocEquivalent quantile 90.0% VOC rolling average',
       'Id=0:BME680:breathVocEquivalent quantile 99.0% VOC rolling average',
       'whole experiment quantile 90.0% VOC rolling average',
       'whole experiment quantile 99.0% VOC rolling average',
       'Id=1:BME680:breathVocEquivalent VOC mean calm period',
       'Id=1:BME680:breathVocEquivalent VOC gradient mean calm period',
       'Id=2:BME680:breathVocEquivalent VOC mean calm period',
       'Id=2:BME680:breathVocEquivalent VOC gradient mean calm period',
       'Id=0:BME680:breathVocEquivalent VOC mean calm period',
       'Id=0:BME680:breathVocEquivalent VOC gradient mean calm period',
       'x axis', 'y axis', 'x-y axis',
       'position of Id=0:BME680:breathVocEquivalent-x axis',
       'position of Id=0:BME680:breathVocEquivalent-y axis',
       'position of Id=1:BME680:breathVocEquivalent-x axis',
       'position of Id=1:BME680:breathVocEquivalent-y axis',
       'position of Id=2:BME680:breathVocEquivalent-x axis',
       'position of Id=2:BME680:breathVocEquivalent-y axis',
       'position of Id=0:BME680:breathVocEquivalent x-y axis',
       'position of Id=1:BME680:breathVocEquivalent x-y axis',
       'position of Id=2:BME680:breathVocEquivalent x-y axis',
       'Euclidian distance to Id=0:BME680:breathVocEquivalent',
       'Euclidian distance to Id=1:BME680:breathVocEquivalent',
       'Euclidian distance to Id=2:BME680:breathVocEquivalent'],
      dtype='object')

# LIBRARIES AND FUNCTIONS DECLARACTIONS

In [27]:
# Required imports
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.preprocessing import StandardScaler, PolynomialFeatures
from sklearn.pipeline import Pipeline

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.svm import SVR
from sklearn.metrics import mean_squared_error,mean_absolute_error, r2_score

In [ ]:

# 1. Linear Regression (no hyperparameters to tune, just for completeness)
lr = LinearRegression()
lr_params = {}  # No parameters for simple LinearRegression

# 2. Ridge Regression
ridge = Ridge()
ridge_params = {
    'alpha': [0.01, 0.1, 1, 10, 100],
    'solver': ['auto', 'svd', 'cholesky', 'lsqr']
}

# 3. Lasso Regression
lasso = Lasso()
lasso_params = {
    'max_iter':[10000],
    'alpha': [0.001, 0.01, 0.1, 1, 10],
}

# 4. ElasticNet
elastic = ElasticNet()
elastic_params = {
    'max_iter':[10000],
    'alpha': [0.001, 0.01, 0.1, 1, 10],
    'l1_ratio': [0.1, 0.5, 0.7, 0.9]
}

# 5. Support Vector Regression
svr = SVR()
svr_params = {
    'kernel':["rbf"],
    "C": [0.1, 1, 10, 100],
    "epsilon": [0.001, 0.01, 0.1, 0.2],
    "gamma": ["scale", "auto"]
}


# 7. Random Forest Regression
rf = RandomForestRegressor()
rf_params = {
    'random_state':[42],
    'n_estimators': [10, 50, 100,200],
    'max_depth': [None, 5, 10, 20],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

# 8. Gradient Boosting Regression
gbr = GradientBoostingRegressor()
gbr_params = {
    'random_state':[42],
    'n_estimators': [10, 50, 100,200],
    'learning_rate': [0.01, 0.05, 0.1, 0.2],
    'max_depth': [ 5, 10, 20],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

models = {
    'LinearRegression': (lr, lr_params),
    'Ridge': (ridge, ridge_params),
    'Lasso': (lasso, lasso_params),
    'ElasticNet': (elastic, elastic_params),
    'SVR': (svr, svr_params),
    'RandomForest': (rf, rf_params),
    #'GradientBoosting': (gbr, gbr_params)
}

from scipy.optimize import least_squares

In [28]:
def get_16_train_positions(userInputData_Original:pd.DataFrame):
    column_to_check = "x-y axis"
    mask = (userInputData_Original["are-doors-opened"] != "on") & (userInputData_Original["room"] =='Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0.5  ,id:2 Π:0.4 Α:1.0' ) & (userInputData_Original[column_to_check] != (None,None))
    training_positions = userInputData_Original.loc[mask,column_to_check].unique()
    return training_positions

In [29]:
get_16_train_positions(userInputData_Original)

array([(-2.95, 2.5), (-2.95, 3.5), (-0.5, 3.5), (-0.5, 2.5), (-0.5, 1.5),
       (-0.5, 0.5), (-1.5, 0.5), (-1.5, 1.5), (-1.5, 2.5), (-1.5, 3.5),
       (-2.5, 3.5), (-2.5, 2.5), (-2.5, 1.5), (-2.5, 0.5), (-2.95, 0.5),
       (-2.95, 1.5)], dtype=object)

In [30]:
def get_Data_To_Be_Used(userInputData_Original:pd.DataFrame,timeSeriesData_BIG_Original:pd.DataFrame,
                        keepOpenDoorData =False,drop_other_positions =True ,closeDoorTraining_openDoorTest = False ,anyOtherMaskToBeUsed = None)->(pd.DataFrame,pd.DataFrame):

    userInputData = userInputData_Original.copy()
    timeSeriesData_BIG = timeSeriesData_BIG_Original.copy()

    # clear the data that doesn't fit to the 330 columns we want
    max_before= -30
    max_after = 299
    
    mask_before = (userInputData["time taken before insertion (seconds)-capped"] == max_before)
    max_after = (userInputData["time taken after insertion (seconds)-capped"] == max_after)
    mask = mask_before & max_after
    print(f"data which doesn't fit our criteria of size:{userInputData.loc[~mask,:].index}")
    userInputData = userInputData.loc[mask,:].copy()
    timeSeriesData_BIG = timeSeriesData_BIG.loc[timeSeriesData_BIG["keys"].isin(userInputData.index)]
    if keepOpenDoorData:
        mask = userInputData["are-doors-opened"] == "on"

    else:
        mask =  userInputData["are-doors-opened"] != "on"

    if anyOtherMaskToBeUsed is not None:
        mask = mask & anyOtherMaskToBeUsed
    userInputData = userInputData.loc[mask].copy()
    #grab all the data that are contained in those experiments
    timeSeriesData_BIG = timeSeriesData_BIG.loc[timeSeriesData_BIG["keys"].isin(userInputData.index)].copy()
        
    
    if drop_other_positions & (not closeDoorTraining_openDoorTest):
        #from the experiments with door open, drop the positions which doesn't fit to the 16 source position we are going to check the model
        #also drop the experiments with the None values
        axis_list = get_16_train_positions(userInputData_Original)
        axis_mask = userInputData["x-y axis"].isin(axis_list)
        
        mask = axis_mask 
        userInputData = userInputData.loc[mask]
        #grab all the data that are contained in those experiments
        timeSeriesData_BIG = timeSeriesData_BIG.loc[timeSeriesData_BIG["keys"].isin(userInputData.index)]

    return userInputData,timeSeriesData_BIG

data which doesn't fit our criteria of size:Index([86, 89, 104, 122, 128, 131, 139, 145, 187, 221, 242], dtype='int64')

In [32]:
userInputData

,experimentState,are-doors-opened,are-people-inside,are-windows-opened,front-wall,item-used,notes,room,side-right-wall,back-wall,side-left-wall,are-fans-on,no-source-located,timestamp InsertingSource,timestamp StartingExperiment,timestamp EndingExperiment,date of experiment,actual timestamp StartingExperiment,actual timestamp EndingExperiment,time taken total,timestamp InsertingSource timedelta,timestamp InsertingSource seconds,time taken after insertion,time taken before insertion,time taken before insertion (seconds),time taken after insertion (seconds),time taken total (seconds),time taken total (seconds)-capped,time taken before insertion (seconds)-capped,time taken after insertion (seconds)-capped,Id=1:BME680:breathVocEquivalent MAX value VOC rolling average,Id=1:BME680:breathVocEquivalent index of MAX value VOC rolling average,Id=2:BME680:breathVocEquivalent MAX value VOC rolling average,Id=2:BME680:breathVocEquivalent index of MAX value VOC rolling average,Id=0:BME680:breathVocEquivalent MAX value VOC rolling average,Id=0:BME680:breathVocEquivalent index of MAX value VOC rolling average,sensor with MAX value experiment,sensor with second MAX value experiment,Id=1:BME680:breathVocEquivalent quantile 90.0% VOC rolling average,Id=1:BME680:breathVocEquivalent quantile 99.0% VOC rolling average,Id=2:BME680:breathVocEquivalent quantile 90.0% VOC rolling average,Id=2:BME680:breathVocEquivalent quantile 99.0% VOC rolling average,Id=0:BME680:breathVocEquivalent quantile 90.0% VOC rolling average,Id=0:BME680:breathVocEquivalent quantile 99.0% VOC rolling average,whole experiment quantile 90.0% VOC rolling average,whole experiment quantile 99.0% VOC rolling average,Id=1:BME680:breathVocEquivalent VOC mean calm period,Id=1:BME680:breathVocEquivalent VOC gradient mean calm period,Id=2:BME680:breathVocEquivalent VOC mean calm period,Id=2:BME680:breathVocEquivalent VOC gradient mean calm period,Id=0:BME680:breathVocEquivalent VOC mean calm period,Id=0:BME680:breathVocEquivalent VOC gradient mean calm period,x axis,y axis,x-y axis,position of Id=0:BME680:breathVocEquivalent-x axis,position of Id=0:BME680:breathVocEquivalent-y axis,position of Id=1:BME680:breathVocEquivalent-x axis,position of Id=1:BME680:breathVocEquivalent-y axis,position of Id=2:BME680:breathVocEquivalent-x axis,position of Id=2:BME680:breathVocEquivalent-y axis,position of Id=0:BME680:breathVocEquivalent x-y axis,position of Id=1:BME680:breathVocEquivalent x-y axis,position of Id=2:BME680:breathVocEquivalent x-y axis,Euclidian distance to Id=0:BME680:breathVocEquivalent,Euclidian distance to Id=1:BME680:breathVocEquivalent,Euclidian distance to Id=2:BME680:breathVocEquivalent
146,InsertingSourcePollutant,None,None,None,1.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-13 18:26:12,2025-10-13 18:24:06,2025-10-13 18:57:52,2025-10-13 00:00:00,2025-10-13 18:24:08,2025-10-13 18:57:50,0 days 00:33:42,0 days 00:02:05,125,0 days 00:31:37,0 days 00:02:05,125,1897,2022,270,-30,299,0.3738,251.0,0.3577,294,0.2026,224.0,Id=1:BME680:breathVocEquivalent MAX value VOC ...,Id=2:BME680:breathVocEquivalent MAX value VOC ...,0.34415,0.373413,0.33478,0.357013,0.18951,0.202442,0.32881,0.370132,0.059467,0.001485,0.068867,0.001000,0.087333,0.000453,-2.95,2.5,"(-2.95, 2.5)",-1.85,3.5,-0.5,1.7,-2.25,0.4,"[-1.85, 3.5]","[-0.5, 1.7]","[-2.25, 0.4]",1.49,2.58,2.21
147,InsertingSourcePollutant,None,None,None,0.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-13 19:13:50,2025-10-13 19:11:41,2025-10-13 19:20:00,2025-10-13 00:00:00,2025-10-13 19:11:42,2025-10-13 19:19:59,0 days 00:08:17,0 days 00:02:09,129,0 days 00:06:08,0 days 00:02:09,129,368,497,270,-30,299,0.6778,229.0,0.9853,227,0.6536,299.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.63975,0.676668,0.95069,0.984642,0.42454,0.643353,0.83994,0.982088,0.170633,0.000088,0.139667,0.001255,0.083233,0.001857,-2.95,3.5,"(-2.95, 3.5)",-1.85,3.5,-0.5,1.7,-2.25,0.4,"[-1.85, 3.5]","[-0.5, 1.7]","[-2.25, 0.4]",1.10,3.04,3.18
148,InsertingSourcePollutant,None,None,None,0.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",0.5,NaN,NaN,None,None,2025-10-13 19:44:06,2025-10-13 19:42:48,2025-10-13 19:55:25,2025-10-13 00:00:00,2025-10-13 19:42:50,2025-10-13 19:55:23,0 days 00:12:33,0 days 00:01:17,77,0 days 00:11:16,0 days 00:01:17,77,676,753,270,-30,299,0.9328,283.0,0.5129,248,2.1073,299.0,Id=0:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,0.90881,0.932126,0.44334,0.511968,1.78609,2.065092,1.24278,1.934586,0.235500,0.005980,0.107600,0.001647,0.130900,0.004138,-0.50,3.5,"(-0.5, 3.5)",-1.85,3.5,-0.5,1.7,-2.25,0.4,"[-1.85, 3.5]","[-0.5, 1.7]","[-2.25, 0.4]",1.35,1.80,3.56
149,InsertingSourcePollutant,None,None,None,1.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",0.5,NaN,NaN,None,None,2025-10-13 20:04:37,2025-10-13 20:03:23,2025-10-13 20:10:11,2025-10-13 00:00:00,2025-10-13 20:03:24,2025-10-13 20:10:09,0 days 00:06:45,0 days 00:01:14,74,0 days 00:05:31,0 days 00:01:14,74,331,405,270,-30,299,1.6777,55.0,1.1539,299,2.1168,293.0,Id=0:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,1.37377,1.664684,0.91740,1.139192,1.92633,2.115323,1.70424,2.105019,0.027300,0.000615,0.158133,0.002223,0.033467,-0.000080,-0.50,2.5,"(-0.5, 2.5)",-1.85,3.5,-0.5,1.7,-2.25,0.4,"[-1.85, 3.5]","[-0.5, 1.7]","[-2.25, 0.4]",1.68,0.80,2.73
150,InsertingSourcePollutant,None,None,None,2.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",0.5,NaN,NaN,None,None,2025-10-13 20:19:08,2025-10-13 20:17:43,2025-10-13 20:24:29,2025-10-13 00:00:00,2025-10-13 20:17:45,2025-10-13 20:24:27,0 days 00:06:42,0 days 00:01:24,84,0 days 00:05:18,0 days 00:01:24,84,318,402,270,-30,299,1001.4872,179.0,1.3343,105,2.0400,144.0,Id=1:BME680:breathVocEquivalent MAX value VOC ...,Id=0:BME680:breathVocEquivalent MAX value VOC ...,937.39420,999.237400,1.31315,1.333800,1.94077,2.038149,159.05003,998.881100,0.018600,0.000023,0.110067,0.002185,0.126767,0.001985,-0.50,1.5,"(-0.5, 1.5)",-1.85,3.5,-0.5,1.7,-2.25,0.4,"[-1.85, 3.5]","[-0.5, 1.7]","[-2.25, 0.4]",2.41,0.20,2.07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
254,InsertingSourcePollutant,None,None,None,0.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",0.5,NaN,NaN,None,None,2025-10-24 20:32:03,2025-10-24 20:29:36,2025-10-24 20:37:33,2025-10-24 00:00:00,2025-10-24 20:29:37,2025-10-24 20:37:31,0 days 00:07:54,0 days 00:02:27,147,0 days 00:05:27,0 days 00:02:27,147,327,474,270,-30,299,2.0134,131.0,4.9923,299,2.8096,286.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=0:BME680:breathVocEquivalent MAX value VOC ...,1.85013,2.010252,4.58879,4.944112,2.74257,2.806868,3.70824,4.844487,0.384700,-0.004535,0.790767,0.014290,1.095967,-0.005078,-0.50,3.5,"(-0.5, 3.5)",-1.85,3.5,-0.5,1.7,-2.25,0.4,"[-1.85, 3.5]","[-0.5, 1.7]","[-2.25, 0.4]",1.35,1.80,3.56
255,InsertingSourcePollutant,None,None,None,0.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:05:46,2025-10-24 21:03:22,2025-10-24 21:11:21,2025-10-24 00:00:00,2025-10-24 21:03:24,2025-10-24 21:11:19,0 days 00:07:55,0 days 00:02:23,143,0 days 00:05:32,0 days 00:02:23,143,332,475,270,-30,299,1.5436,269.0,6.0745,299,2.4431,236.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=0:BME680:breathVocEquivalent MAX value VOC ...,1.50536,1.541913,4.53166,5.938517,2.38429,2.439926,3.22484,5.639461,0.830100,0.003192,0.938300,0.004927,0.278667,0.009215,-2.95,3.5,"(-2.95, 3.5)",-1.85,3.5,-0.5,1.7,-2.25,0.4,"[-1.85, 3.5]","[-0.5, 1.7]","[-2.25, 0.4]",1.10,3.04,3.18
256,InsertingSourcePollutant,None,None,None,1.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:18:43,2025-10-24 21:17:10,2025-10-24 21:24:48,2025-10-24 00:00:00,2025-10-24 21:17:12,2025-10-24 21:24:46,0 days 00:07:34,0 days 00:01:32,92,0 days 00:06:02,0 days 00:01:32,92,362,454,270,-30,299,2.0029,299.0,13.3480,277,2.0105,141.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=0:BME680:breathVocEquivalent MAX value VOC ...,1.27778,1.931717,13.17579,13.337491,1.89556,2.009913,10.16265,13.288696,0.130833,0.003005,1.964067,0.021602,0.356100,0.002903,-2.95,2.5,"(-2.95, 2.5)",-1.85,3.5,-0.5,1.7,-2.25,0.4,"[-1.85, 3.5]","[-0.5, 1.7]","[-2.25, 0.4]",1.49,2.58,2.21
257,InsertingSourcePollutant,None,None,None,2.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:34:58,2025-10-24 21:33:44,2025-10-24 21:41:06,2025-10-24 00:00:00,2025-10-24 21:33:46,2025-10-24 21:41:04,0 days 00:07:18,0 days 00:01:13,73,0 days 00:06:05,0 days 00:01:13,73,365,438,270,-30,299,1.8114,299.0,7.5793,261,1.2671,299.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=1:BME680:breathVocEquivalent MAX value VOC ...,1.71769,1.786738,7.36787,7.576884,1.24307,1.262000,6.72750,7.545522,0.316533,0.002780,0.425500,0.012363,0.281700,0.004330,-2.95,1.5,"(-2.95, 1.5)",-1.85,3.5,-0.5,1.7,-2.25,0.4,"[-1.85, 3.5]","[-0.5, 1.7]","[-2.25, 0.4]",2.28,2.46,1.30
258,InsertingSourcePollutant,None,None,None,3.5,Φαρμακευτικό αλκοόλ 95%,,"Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0...",NaN,NaN,0.3,None,None,2025-10-24 21:54:05,2025-10-24 21:52:16,2025-10-24 22:01:25,2025-10-24 00:00:00,2025-10-24 21:52:18,2025-10-24 22:01:24,0 days 00:09:06,0 days 00:01:48,108,0 days 00:07:18,0 days 00:01:48,108,438,546,270,-30,299,1.6312,213.0,3.3710,287,2.1139,299.0,Id=2:BME680:breathVocEquivalent MAX value VOC ...,Id=0:BME680:breathVocEquivalent MAX value VOC ...,1.57461,1.630197,3.24331,3.369713,1.76254,2.072233,2.77298,3.363343,0.104633,-0.002098,0.727733,0.008225,0.324233,0.004552,-2.95,0.5,"(-2.95, 0.5)",-1.85,3.5,-0.5,1.7,-2.25,0.4,"[-1.85, 3.5]","[-0.5, 1.7]","[-2.25, 0.4]",3.20,2.73,0.71

In [33]:
def build_X_keys_And_Y_target_Arrays(userInputData,closeDoorTraining_openDoorTest = False)->(np.array,np.array):
  
    if closeDoorTraining_openDoorTest :
         pass

    else:
        keys = np.array(userInputData.index)
        keys_numpy = keys.reshape(-1,1)
   
    
        columns_to_pass = ["Euclidian distance to Id="+str(id)+":BME680:breathVocEquivalent"
                                   for id in range(3) ]
        column_size = len(columns_to_pass)
        target_variables = userInputData.loc[keys,columns_to_pass].to_numpy()
        target_variables_euclidian_distance_numpy = target_variables.reshape(-1,column_size)
       
    
    
        columns_to_pass = ["x-y axis"]
        target_variables = userInputData.loc[keys,columns_to_pass].to_numpy()
        target_variables_positions_numpy = np.stack(target_variables[:,0])  

        
        X_train_keys,X_test_keys,Y_train_Euclidians,Y_test_Euclidians,Y_train_Positions,Y_test_Positions = train_test_split(
            keys_numpy,target_variables_euclidian_distance_numpy,target_variables_positions_numpy,
            test_size=0.2,
            stratify=target_variables_euclidian_distance_numpy,
            random_state=42
        )
    
    return X_train_keys,X_test_keys,Y_train_Euclidians,Y_test_Euclidians,Y_train_Positions,Y_test_Positions

In [34]:


X_train_keys,X_test_keys,Y_train_Euclidians,Y_test_Euclidians,Y_train_Positions,Y_test_Positions = build_X_keys_And_Y_target_Arrays(userInputData)
print(f"X_train_keys,length:{len(X_train_keys)}:{X_train_keys}")
print(f"X_test_keys,length:{len(X_test_keys)}:{X_test_keys}")

print(f"Y_train_Euclidians,length:{len(Y_train_Euclidians)}:{Y_train_Euclidians}")
print(f"Y_test_Euclidians,length:{len(Y_test_Euclidians)}:{Y_test_Euclidians}")

print(f"Y_train_Positions,length:{len(Y_train_Positions)}:{Y_train_Positions}")
print(f"Y_test_Positions,length:{len(Y_test_Positions)}:{Y_test_Positions}")

X_train_keys,length:78:[[159]
 [196]
 [224]
 [150]
 [239]
 [176]
 [246]
 [195]
 [185]
 [228]
 [165]
 [227]
 [147]
 [235]
 [180]
 [256]
 [157]
 [225]
 [181]
 [234]
 [217]
 [184]
 [154]
 [213]
 [231]
 [175]
 [218]
 [198]
 [208]
 [206]
 [249]
 [172]
 [171]
 [252]
 [212]
 [211]
 [202]
 [210]
 [250]
 [169]
 [236]
 [177]
 [153]
 [199]
 [149]
 [151]
 [230]
 [233]
 [164]
 [192]
 [244]
 [160]
 [247]
 [254]
 [232]
 [179]
 [197]
 [237]
 [194]
 [152]
 [191]
 [216]
 [220]
 [168]
 [245]
 [209]
 [238]
 [155]
 [156]
 [201]
 [158]
 [229]
 [190]
 [243]
 [200]
 [205]
 [214]
 [163]]
X_test_keys,length:20:[[182]
 [173]
 [183]
 [255]
 [148]
 [251]
 [178]
 [226]
 [257]
 [186]
 [215]
 [146]
 [174]
 [248]
 [219]
 [207]
 [253]
 [258]
 [170]
 [193]]
Y_train_Euclidians,length:78:[[3.07 2.33 0.27]
 [2.1  2.01 1.13]
 [2.28 2.46 1.3 ]
 [2.41 0.2  2.07]
 [1.1  3.04 3.18]
 [1.49 2.58 2.21]
 [0.35 2.06 3.19]
 [2.28 2.46 1.3 ]
 [0.65 2.69 3.11]
 [1.68 0.8  2.73]
 [1.1  3.04 3.18]
 [2.41 0.2  2.07]
 [1.1  3.04 3.18]
 [3.2  2.73 0.71]
 [1.35 1.8  3.56]
 [1.49 2.58 2.21]
 [1.19 2.15 2.11]
 [2.1  2.01 1.13]
 [0.35 2.06 3.19]
 [3.07 2.33 0.27]
 [3.2  2.73 0.71]
 [1.1  3.04 3.18]
 [1.06 1.28 2.23]
 [0.65 2.69 3.11]
 [1.49 2.58 2.21]
 [3.2  2.73 0.71]
 [2.28 2.46 1.3 ]
 [2.41 0.2  2.07]
 [3.29 1.2  1.75]
 [1.68 0.8  2.73]
 [2.1  2.01 1.13]
 [3.29 1.2  1.75]
 [2.41 0.2  2.07]
 [2.41 0.2  2.07]
 [0.35 2.06 3.19]
 [1.06 1.28 2.23]
 [3.2  2.73 0.71]
 [2.03 1.02 1.33]
 [3.07 2.33 0.27]
 [2.1  2.01 1.13]
 [1.35 1.8  3.56]
 [1.19 2.15 2.11]
 [2.03 1.02 1.33]
 [3.29 1.2  1.75]
 [1.68 0.8  2.73]
 [3.29 1.2  1.75]
 [1.19 2.15 2.11]
 [3.02 1.56 0.76]
 [1.49 2.58 2.21]
 [1.06 1.28 2.23]
 [3.02 1.56 0.76]
 [3.2  2.73 0.71]
 [0.65 2.69 3.11]
 [1.35 1.8  3.56]
 [3.29 1.2  1.75]
 [1.68 0.8  2.73]
 [2.03 1.02 1.33]
 [0.35 2.06 3.19]
 [1.49 2.58 2.21]
 [3.02 1.56 0.76]
 [1.68 0.8  2.73]
 [3.07 2.33 0.27]
 [1.1  3.04 3.18]
 [2.28 2.46 1.3 ]
 [1.06 1.28 2.23]
 [3.02 1.56 0.76]
 [0.65 2.69 3.11]
 [0.35 2.06 3.19]
 [0.65 2.69 3.11]
 [3.07 2.33 0.27]
 [2.1  2.01 1.13]
 [1.06 1.28 2.23]
 [1.35 1.8  3.56]
 [2.03 1.02 1.33]
 [3.02 1.56 0.76]
 [1.35 1.8  3.56]
 [1.19 2.15 2.11]
 [2.28 2.46 1.3 ]]
Y_test_Euclidians,length:20:[[0.65 2.69 3.11]
 [3.02 1.56 0.76]
 [1.1  3.04 3.18]
 [1.1  3.04 3.18]
 [1.35 1.8  3.56]
 [3.29 1.2  1.75]
 [1.06 1.28 2.23]
 [2.03 1.02 1.33]
 [2.28 2.46 1.3 ]
 [0.35 2.06 3.19]
 [2.1  2.01 1.13]
 [1.49 2.58 2.21]
 [3.07 2.33 0.27]
 [1.19 2.15 2.11]
 [1.49 2.58 2.21]
 [2.41 0.2  2.07]
 [1.68 0.8  2.73]
 [3.2  2.73 0.71]
 [2.03 1.02 1.33]
 [1.19 2.15 2.11]]
Y_train_Positions,length:78:[[-2.5   0.5 ]
 [-2.5   1.5 ]
 [-2.95  1.5 ]
 [-0.5   1.5 ]
 [-2.95  3.5 ]
 [-2.95  2.5 ]
 [-1.5   3.5 ]
 [-2.95  1.5 ]
 [-2.5   3.5 ]
 [-0.5   2.5 ]
 [-2.95  3.5 ]
 [-0.5   1.5 ]
 [-2.95  3.5 ]
 [-2.95  0.5 ]
 [-0.5   3.5 ]
 [-2.95  2.5 ]
 [-2.5   2.5 ]
 [-2.5   1.5 ]
 [-1.5   3.5 ]
 [-2.5   0.5 ]
 [-2.95  0.5 ]
 [-2.95  3.5 ]
 [-1.5   2.5 ]
 [-2.5   3.5 ]
 [-2.95  2.5 ]
 [-2.95  0.5 ]
 [-2.95  1.5 ]
 [-0.5   1.5 ]
 [-0.5   0.5 ]
 [-0.5   2.5 ]
 [-2.5   1.5 ]
 [-0.5   0.5 ]
 [-0.5   1.5 ]
 [-0.5   1.5 ]
 [-1.5   3.5 ]
 [-1.5   2.5 ]
 [-2.95  0.5 ]
 [-1.5   1.5 ]
 [-2.5   0.5 ]
 [-2.5   1.5 ]
 [-0.5   3.5 ]
 [-2.5   2.5 ]
 [-1.5   1.5 ]
 [-0.5   0.5 ]
 [-0.5   2.5 ]
 [-0.5   0.5 ]
 [-2.5   2.5 ]
 [-1.5   0.5 ]
 [-2.95  2.5 ]
 [-1.5   2.5 ]
 [-1.5   0.5 ]
 [-2.95  0.5 ]
 [-2.5   3.5 ]
 [-0.5   3.5 ]
 [-0.5   0.5 ]
 [-0.5   2.5 ]
 [-1.5   1.5 ]
 [-1.5   3.5 ]
 [-2.95  2.5 ]
 [-1.5   0.5 ]
 [-0.5   2.5 ]
 [-2.5   0.5 ]
 [-2.95  3.5 ]
 [-2.95  1.5 ]
 [-1.5   2.5 ]
 [-1.5   0.5 ]
 [-2.5   3.5 ]
 [-1.5   3.5 ]
 [-2.5   3.5 ]
 [-2.5   0.5 ]
 [-2.5   1.5 ]
 [-1.5   2.5 ]
 [-0.5   3.5 ]
 [-1.5   1.5 ]
 [-1.5   0.5 ]
 [-0.5   3.5 ]
 [-2.5   2.5 ]
 [-2.95  1.5 ]]
Y_test_Positions,length:20:[[-2.5   3.5 ]
 [-1.5   0.5 ]
 [-2.95  3.5 ]
 [-2.95  3.5 ]
 [-0.5   3.5 ]
 [-0.5   0.5 ]
 [-1.5   2.5 ]
 [-1.5   1.5 ]
 [-2.95  1.5 ]
 [-1.5   3.5 ]
 [-2.5   1.5 ]
 [-2.95  2.5 ]
 [-2.5   0.5 ]
 [-2.5   2.5 ]
 [-2.95  2.5 ]
 [-0.5   1.5 ]
 [-0.5   2.5 ]
 [-2.95  0.5 ]
 [-1.5   1.5 ]
 [-2.5   2.5 ]]

In [35]:
def build_X_from_dataframe(keys_array, df, column_to_take):
    # flatten [[159],[196]...] → [159,196,...]
    keys = keys_array.ravel()

    # number of keys
    N = len(keys)

    # number of time steps per experiment (should be constant)
    example_key = keys[0]
    time_values = df[df["keys"] == example_key]
    T = len(time_values)

    # allocate X
    X = np.zeros((N, T))

    # fill X
    for i, key in enumerate(keys):
        rows = df[df["keys"] == key]
        X[i, :] = rows[column_to_take].values

    return X

In [36]:
def get_Data_Per_Sensor(userInputData,timeSeriesData_BIG) ->pd.DataFrame:
    df_filtered = timeSeriesData_BIG.loc[timeSeriesData_BIG["keys"].isin(userInputData.index)]
    sensors_names = np.sort(timeSeriesData_BIG["sensors"].unique())
    dfs_by_sensor = {
        sensor: df_filtered.loc[df_filtered["sensors"]==sensor]
        for sensor in sensors_names
    }
    return dfs_by_sensor

In [37]:
def build_X_train_And_X_test(userInputData,timeSeriesData_BIG,X_train_keys,X_test_keys,column_to_take ="VOC rolling average")->(np.array,np.array):
    dfs_by_sensor = get_Data_Per_Sensor(userInputData,timeSeriesData_BIG)
    column_to_take ="VOC rolling average"
    X_train = np.empty((len(dfs_by_sensor),X_train_keys.shape[0],330))
    
    for i, data_per_sensor in enumerate(dfs_by_sensor.values()):
        X_train[i,:,:]= build_X_from_dataframe(X_train_keys,data_per_sensor,column_to_take)
    
    X_test = np.empty((len(dfs_by_sensor),X_test_keys.shape[0],330))
        
    for i, data_per_sensor in enumerate(dfs_by_sensor.values()):
        X_test[i,:,:]= build_X_from_dataframe(X_test_keys,data_per_sensor,column_to_take)

    return X_train,X_test

In [41]:

def create_The_Arrays_For_The_Models(userInputData_Original,timeSeriesData_BIG_Original,apply_functions_to_X_data = [],
                                     column_to_take ="VOC rolling average",keepOpenDoorData =False,drop_other_positions =True ,closeDoorTraining_openDoorTest = False ,anyOtherMaskToBeUsed = None):
    
    userInputData,timeSeriesData_BIG = get_Data_To_Be_Used(userInputData_Original,timeSeriesData_BIG_Original,
                        )
    X_train_keys,X_test_keys,Y_train_Euclidians,Y_test_Euclidians,Y_train_Positions,Y_test_Positions = build_X_keys_And_Y_target_Arrays(userInputData)    
    X_train,X_test = build_X_train_And_X_test(userInputData,timeSeriesData_BIG,X_train_keys,X_test_keys,column_to_take)
    if apply_functions_to_X_data is not None:
       for modify_function in apply_functions_to_X_data:
           X_train,X_test =  modify_function(X_train,X_test)
    return X_train,X_test,Y_train_Euclidians,Y_test_Euclidians,Y_train_Positions,Y_test_Positions, userInputData,timeSeriesData_BIG

In [ ]:
def cutOutliers(X_train:np.array,X_test:np.array)->(np.array,np.array):

    for i in range(X_train.shape[0]):
  
        q25 = np.quantile(X_train[i,:,:], 0.25)
        print(f"q25:{q25}")
        q75 = np.quantile(X_train[i,:,:], 0.75)
        print(f"q75:{q75}")
    
        # Limit (clip) all values to the range [25% quantile, 75% quantile] for both train and test,while have learned the quantiles of train
        X_train[i,:,:] = np.clip(X_train[i,:,:], q25, q75)
        X_test[i,:,:] = np.clip(X_test[i,:,:], q25, q75)

    return X_train,X_test

In [ ]:
def cutOutliersPerColumn(X_train:np.array,X_test:np.array)->(np.array,np.array):

    for i in range(X_train.shape[0]):
        for j in range(X_train.shape[0])
            q25 = np.quantile(X_train[i,:,j], 0.25)
            print(f"q25:{q25}")
            q75 = np.quantile(X_train[i,:,j], 0.75)
            print(f"q75:{q75}")
        
            # Limit (clip) all values to the range [25% quantile, 75% quantile] for both train and test,while have learned the quantiles of train
            X_train[i,:,:] = np.clip(X_train[i,:,j], q25, q75)
            X_test[i,:,:] = np.clip(X_test[i,:,j], q25, q75)        

    return X_train,X_test

In [50]:

    
def findPCAcomponentsCovered(X_train):     
    
    for X_train_per_sensor in X_train:
        print(sensor_name)
        scaler = StandardScaler()
        X_scaled = scaler.fit_transform(X[sensor_name])
        print(scaler.get_params())
        # Step 2: Apply PCA
        pca = PCA()
        X_pca = pca.fit_transform(X_scaled)
        
        # Step 3: Explained variance
        explained_variance = pca.explained_variance_ratio_
        cumulative_variance = np.cumsum(explained_variance)
        
        # Only display first 10 components max
        max_components = min(10, len(explained_variance))
        ev_to_plot = explained_variance[:max_components]
        cum_to_plot = cumulative_variance[:max_components]
        
        # Step 4: Bar plot of cumulative explained variance
        plt.figure(figsize=(8,5))
        plt.bar(range(1, max_components + 1), cum_to_plot)
        plt.xlabel('Number of PCA components')
        plt.ylabel('Cumulative explained variance')
        plt.title('Cumulative explained variance (first 10 components)')
        plt.grid(True, axis='y')
        plt.show()
        
        # Step 5: Optimal number of components for ~90% variance
        optimal_components = np.argmax(cumulative_variance >= 0.90) + 1
        print("Optimal number of components to explain ~90% variance:", optimal_components)

In [ ]:

def run_grid_search_per_model(X_train, y_train,cv_number,verbose,name,model,params):
        PCA__n_components = [3,4,5,6,8,10]

        estimators_with_no_scaling_need = ['RandomForest','DecisionTree','GradientBoosting']

        results = {}
        if name in estimators_with_no_scaling_need:
             pipe = Pipeline([
                 ('model', model)
             ]) 
        else:
             pipe = Pipeline([
                 ('scaler', StandardScaler()),
                 ('PCA', PCA()),
                 ('model', model)
             ])
        # Build a correct param grid:
        param_grid = {
            **{'model__' + k: v for k, v in params.items()}
        }
        if name not in estimators_with_no_scaling_need:
            param_grid['PCA__n_components'] = PCA__n_components
            
        grid = GridSearchCV(
            estimator=pipe,
            param_grid=param_grid,
            cv=cv_number,
            n_jobs=-1,
            scoring='neg_mean_squared_error',
            verbose=2
        )
     
        grid.fit(X_train, y_train)
    
        results["name"]  = name
        results["model"] = grid.best_estimator_
        results["parameters"] = grid.best_params_
        results["score"] = grid.best_score_
    
        return results

def run_grid_search_find_optimal_model_per_sensor(X_train, y_train,cv_number,verbose,models):
    #put a score way worse than abest_score_nything we should have
    best_result = {
        "score" : -10,
        "model" : '',
        "parameters" : {}    
    }
    for name, (model, params) in models.items():
        print(f"Running GridSearchCV for {name}...")

        results = run_grid_search_per_model(X_train, y_train,cv_number,verbose,name,model,params,PCA__n_components)
        print(results)

        if (results["score"] >  best_result["score"]) :
            best_result["name"] = results["name"]
            print(best_result["name"])
            best_result["score"] = results["score"]
            print(best_result["score"])
            best_result["model"] = results["model"]
            print(best_result["model"])
            best_result["parameters"] = results["parameters"]
            print(best_result["parameters"])
    return best_result


def run_grid_search_find_optimal_model_per_sensor_for_all_sensors(X_train, y_train,cv_number,verbose,models):

    best_results_for_all_sensors = {}

    for i in range(X_train.shape[0]):
        best_results_for_all_sensors[i]  =run_grid_search_find_optimal_model_per_sensor(X_train[i,:,:], y_train[:,i],cv_number,verbose,models,PCA__n_components)

    return best_results_for_all_sensors

In [ ]:
#PREDICT AND SEE INDIVIDUAL RESULTS
def getPredictedValues(X_test,best_results_for_all_sensors):

   predict_Euclidians = np.empty((Y_test_Euclidians.shape))
    
    
    for i in range(X_test.shape[0]):
        
        predict_Euclidians[:,i] = best_results_for_all_sensors[i]["model"].predict(X_test[i,:,:])
    
    return predict_Euclidians

In [ ]:
def trainModels_PrintResults_AndGetPredictedValues( X_train,X_test,Y_train_Euclidians,Y_test_Euclidians,models):
    cv_number = 5
    verbose = 2
    
    best_results_for_all_sensors = run_grid_search_find_optimal_model_per_sensor_for_all_sensors(X_train, Y_train_Euclidians,cv_number,verbose,models)
    
    Y_predict_Euclidians = getPredictedValues(X_test,best_results_for_all_sensors)
    plantAllBaseSensorsData(Y_test_Euclidians, y_pred,AXIS)
    return Y_predict_Euclidians

In [ ]:
def plot_pred_vs_actual(y_test, y_pred,sensor_name,AXIS):
    # --- Plot: predicted vs actual ---
    mse = mean_squared_error(y_test, y_pred)
    
    r2  = r2_score(y_test, y_pred)
    #check if a numpy array is 1D,if yes,make it 2D with one n,1
    if y_test.ndim == 1:
       y_test =  y_test.reshape(-1,1)
    if y_pred.ndim == 1:
       y_pred =  y_pred.reshape(-1,1)   

    EucDis = np.linalg.norm(y_test - y_pred,axis=1).mean()
    print(f"MSE on test set: {mse:.4f}")
    
    print(f"R^2 on test set: {r2:.4f}")

    print(f"Euclidian distance median value {EucDis:.4f}")
  

    if (y_test.shape[1] == 1) and (y_pred.shape[1] == 1):
        plt.figure(figsize=(7,6))
        plt.scatter(y_test, y_pred, s=50)
        plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], linestyle='--')
        plt.xlabel("True target")
        plt.ylabel("Predicted target")
        plt.title(f"{sensor_name} {AXIS} predictions vs actual")
        plt.grid(True)
        plt.show()

    else:
        # --- Plot ---
        plt.scatter(y_test[:,0], y_test[:,1], label="True", alpha=0.6)
        plt.scatter(y_pred[:,0], y_pred[:,1], label="Predicted", alpha=0.6)
        plt.legend()
        plt.xlabel("X")
        plt.ylabel("Y")
        plt.title("True vs Predicted Positions")
        plt.grid(True)
        plt.show()

def plantAllBaseSensorsData(y_test, y_pred,AXIS):
    for i in range(y_test.shape[1]):
        AXIS = "Euclidian distances"
        plot_pred_vs_actual(y_test[:,i], y_pred[:,i],i,AXIS)

In [ ]:
def trilateration_least_squares(points, radii):
    def fun(p):
        x, y = p
        return [np.hypot(x - px, y - py) - r for (px, py), r in zip(points, radii)]
    res = least_squares(fun, x0=[np.mean([px for px,_ in points]), np.mean([py for _,py in points])])
    x, y = res.x
    # Check residuals
    if np.all(np.abs(fun([x, y])) < 1e-2):
        return True, (x, y)
    else:
        return False, (x, y)

In [51]:
#Take the three points of the sensors
def findIntersectionOfCircles(predict_Euclidians,userInputData):
    sensors_position_columns = ["position of Id="+str(id) + ":BME680:breathVocEquivalent x-y axis"
                                for id in range(3)]
    point_of_sensors = []
    mask = userInputData["room"] == 'Κρεβατοκάμαρα id:0 Μ:0.5 Α:1.4 ,id:1 Π:1.7 Δ:0.5  ,id:2 Π:0.4 Α:1.0'
    for sensors_position_column in sensors_position_columns:
        
        point_of_sensors.append(userInputData[mask,sensors_position_column].iloc[0]) 
        
        #get points true and false
    points = np.empty((y_dimension,2))
    bool_values =  np.empty((y_dimension,1))
    for i in range(predict_Euclidians.shape[0]):
        bool_value,point = trilateration_least_squares(point_of_sensors,predict_Euclidians[i,:])
        points[i,:] = point
        print(bool_value)
        bool_values[i] = bool_value
    
    plot_pred_vs_actual(Y_test_Positions,points,sensor_names,"Point predicted")
    return points,bool_values

SyntaxError: invalid syntax (563586925.py, line 6)

In [38]:
column_to_take ="VOC rolling average"
apply_functions_to_X_data = [cutOutliers(X_train,X_test)]

def runPipeline(userInputData_Original,timeSeriesData_BIG_Original,models):

    X_train,X_test,Y_train_Euclidians,Y_test_Euclidians,Y_train_Positions,Y_test_Positions, userInputData,timeSeriesData_BIG = create_The_Arrays_For_The_Models(userInputData_Original,timeSeriesData_BIG_Original,apply_functions_to_X_data,column_to_take)
    
    predict_Euclidians = trainModels_PrintResults_AndGetPredictedValues( X_train,X_test,Y_train_Euclidians,Y_test_Euclidians,models)

    points,bool_values = findIntersectionOfCircles(predict_Euclidians,userInputData)

data which doesn't fit our criteria of size:Index([86, 89, 104, 122, 128, 131, 139, 145, 187, 221, 242], dtype='int64')

In [ ]:
X_train,X_test,Y_train_Euclidians,Y_test_Euclidians,Y_train_Positions,Y_test_Positions, userInputData,timeSeriesData_BIG = create_The_Arrays_For_The_Models(userInputData_Original,timeSeriesData_BIG_Original)
findPCAcomponentsCovered(X_train)

best_result = run_grid_search_find_optimal_model_per_sensor(X_train, Y_train_Euclidians,cv_number,verbose,models,PCA__n_components)

### SEARCH BEST MODEL OF EACH INDIVIDUAL SENSOR'S X AND Y AXIS

## LOCATE THE PLACE OF THE SOURCE USING

In [ ]:
#rewrite it again to be sure

In [ ]:
point_of_sensors

In [ ]:
len(predict_Y)

In [ ]:
predicted_euclidian_values.shape

In [ ]:
predicted_euclidian_values

In [ ]:
point_of_sensors

In [ ]:
bool_values

In [ ]:
points